### ISSUE TITLE
Does redis-port support starting as windows service?

### ISSUE THREAD

**Issue by mstier** [microsoftarchive/redis#1]
Is it possible to install redis-server.exe as windows service? How?

**Comment by clca** [comment]
You would have to write some code in order to do it now. For the next release we plan to build a wrapper to spawn the redis-server process so it can run as Windows service.

**Comment by clca** [comment]
Redis-watcher is what you need. It is a WIndows service that can start one or more redis instances and restart the processes if they stops. you can find a readme with the instructions on how to use it under the msvs/redis-watcher directory

**Comment by tugberkugurlu** [comment]
@clca when I try to start _RedisWatcherSvc_, I am getting the following error:

> Error 1053: The service did not respond to the start or control request in a timely fashion

The service is installed properly but there is a problem when I try to start it. 

The OS I installed the service is Windows Server 2008 R2 and there is nothing else installed on this server (no role, no feature and anything else).

**Comment by tugberkugurlu** [comment]
@clca ok, I just installed [Microsoft Visual C++ 2010 Redistributable Package](http://www.microsoft.com/en-us/download/details.aspx?id=5555) and it solved the problem. I think it might be helpful if you guys can put this inside readme.

**Comment by clca** [comment]
thanks for reporting this issue, it is a bug, we forgot to set the flag in VS to include the C++ libraries in the binary. 
Fix ready, it will be checked into the repo in few hours.

**Comment by tugberkugurlu** [comment]
@clca perfect! thanks a lot.

**Comment by clca** [comment]
this seems to be resolved, feel free to reopen the issue if you find other issues with the Redis-Watcher service.
