### ISSUE TITLE
hiredis async sockets are not opened in non-blocking mode

### ISSUE THREAD

**Issue by gsomberg** [microsoftarchive/redis#10]
You can test this out by creating a Win32 project, link against hiredis, and then do the following:

w32initWinSock();
auto pRedisContext = redisAsyncConnect("127.0.0.1", 6379);
redisAsyncHandleRead(pRedisContext);

The redisAsyncHandleRead() call blocks.

To fix this, you probably need to put the following into the win32 version of redisContextConnectTcp():
    if (redisSetBlocking(c,s,blocking) != REDIS_OK)
        return REDIS_ERR;

I did that just after the redisSetTcpNoDelay() and it seems to work nicely.

**Comment by clca** [comment]
Thanks for reporting the issue and suggesting the fix, happy to accept a pull request otherwise we will take care of this with the next commit that we plan to do in the next few days.

**Comment by HenryRawas** [comment]
Should be fixed with commit 7feff64
