### ISSUE TITLE
At Win32_Interop project a file is missing

### ISSUE THREAD

**Issue by pankak** [microsoftarchive/redis#101]
Hi,

I try to compile the 2.8.4 branch in VS2013 and it looks like that a file is missing from the Win32_Interop project.

Cannot open include file: 'EventLog.h': No such file or directory   

I have search the entire solution for this file but it does not exist anywhere so i can't compile this branch.

**Comment by jepickett** [comment]
EventLog.h is built from EventLog.mc. I added the custom build step in the debug target, but I forgot to add it to the release target. Fixed in commit de0a37aa76ddc6008822cd6ddd892531cccfd49d
