### ISSUE TITLE
Sentinel - running locally is throwing errors

### ISSUE THREAD

**Issue by bapti** [microsoftarchive/redis#102]
I've tried to get a sentinel cluster running locally but I just keep getting errors

```
wait3() returned a pid (-1) we can't find in our scripts execution queue!
```

I'm running this command to run my servers with the following configurations below

Is it possible to run a sentinel cluster on windows with this version?

Thanks
Neil

```
redis-server.exe sentinel-master.conf --sentinel
redis-server.exe sentinel-slave1.conf --sentinel
```

```
sentinel-master.conf

---
maxheap 64MB
port 6379
dbfilename master.rdb

sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 900000
sentinel parallel-syncs mymaster 1

---
```

```
*sentinel-slave1.conf*

---
maxheap 64MB
port 6380
dbfilename slave.rdb

sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 900000
sentinel parallel-syncs mymaster 1

---
```

I've also posted this on stackoverflow
http://stackoverflow.com/questions/23346690/redis-sentinel-local-cluster-setup-in-windows

**Comment by jepickett** [comment]
Where are your binaries coming from? There was a fix that came from the 2.6.14 branch that never made it into 2.8.4 until commit 631e8e1afb1b28df09d29625fa374784ac59b2f0. This fix eliminates the use of wait3(). Try the most recent binaries in bin\release\redis-2.8.4.zip.

**Comment by bapti** [comment]
Those are the binaries that shipped with the nuget 2.8.4 release.  I'll try again directly from the github source though.  Thanks

**Comment by bapti** [comment]
Hi, I've put up and example if you want to have a look
https://github.com/bapti/redis-sentinel-windows/tree/master/BatchFiles

I've put in a batch which runs the binaries direct from the 2.8.4 repository which work nicely!  Thanks for that.

However the binaries from the published nuget package do throw the error I mentioned above

I hope that helps.

**Comment by jepickett** [comment]
We are getting ready to refresh the NuGet and Chocolatey binaries. Probably within a week.

**Comment by bapti** [comment]
Thanks!
