### ISSUE TITLE
2.8.4 version:info command will crash

### ISSUE THREAD

**Issue by husttb** [microsoftarchive/redis#105]
if i execute command 'info' in redis-cli.exe,the server will crash

**Comment by jepickett** [comment]
I am not seeing the problem you are having on my setup. Which binaries are you using? NuGet, Chocolatey, or the ones from GitHub? What is your system setup? What does your .conf file look like?

**Comment by husttb** [comment]
my os is win7-32bit,i use vs2013 compile a win32 binaries .

Jonathan Pickett notifications@github.com 
2014-05-06 03:26
请答复 给
MSOpenTech/redis 
reply@reply.github.com

收件人
MSOpenTech/redis redis@noreply.github.com
抄送
husttb 0049000424@zte.com.cn
主题
Re: [redis] 2.8.4 version:info command will crash (#105)

I am not seeing the problem you are having on my setup. Which binaries are 
you using? NuGet, Chocolatey, or the ones from GitHub? What is your system 
setup? What does your .conf file look like? 
—
Reply to this email directly or view it on GitHub.

---

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by jepickett** [comment]
We have chosen to not support the 32-bit version of Windows in this fork of Redis. Please try your test using a 64-bit version of Windows. You might be able to compile our source as a 32-bit binary, but I can guarantee some things will be broken. The last version that supported 32-bit was 6.2.12.

**Comment by jepickett** [comment]
rather 2.6.12

**Comment by husttb** [comment]
thanks.but our software use the 2.6.12 redis .The redis crash in our 
customers:"Error registering fd event for the new client: Result too 
large".The bug has been fixed in 2.6.14 and above. 

Jonathan Pickett notifications@github.com 
2014-05-06 09:27
请答复 给
MSOpenTech/redis 
reply@reply.github.com

收件人
MSOpenTech/redis redis@noreply.github.com
抄送
husttb 0049000424@zte.com.cn
主题
Re: [redis] 2.8.4 version:info command will crash (#105)

rather 2.6.12
—
Reply to this email directly or view it on GitHub.

---

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by jepickett** [comment]
As a temporary fix, you can try pulling a version from the 2_6_14_rebase branch at commit  "7071e9d5990933add468271a889e97030ba2298d" (October 3, 2013) and compiling. This has the fix for the file descriptor problem, and is prior to the removal of the 32-bit support. 

The problem was that the AE code was using the file descriptor as a index into an array, and we were casting SOCKET handles to FDs. Since SOCKET handles are not numbered sequentially we would end up quickly running off the end of the array. 

There are other fixes subsequently applied to the replacement code we implemented to solve this problem. So going this route is perilous. My recommendation is to upgrade your machines with the 64-bit version of Windows.

**Comment by husttb** [comment]
Thank you very much.I compile the application as your guides,but the 
application can not run on windows 2003 server.

Jonathan Pickett notifications@github.com 
2014-05-06 09:49
请答复 给
MSOpenTech/redis 
reply@reply.github.com

收件人
MSOpenTech/redis redis@noreply.github.com
抄送
husttb 0049000424@zte.com.cn
主题
Re: [redis] 2.8.4 version:info command will crash (#105)

As a temporary fix, you can try pulling a version from the 2_6_14_rebase 
branch at commit "7071e9d5990933add468271a889e97030ba2298d" (October 3, 
2013) and compiling. This has the fix for the file descriptor problem, and 
is prior to the removal of the 32-bit support. 
The problem was that the AE code was using the file descriptor as a index 
into an array, and we were casting SOCKET handles to FDs. Since SOCKET 
handles are not numbered sequentially we would end up quickly running off 
the end of the array. 
There are other fixes subsequently applied to the replacement code we 
implemented to solve this problem. So going this route is perilous. My 
recommendation is to upgrade your machines with the 64-bit version of 
Windows.
—
Reply to this email directly or view it on GitHub.

---

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by husttb** [comment]
Thanks! I have found why the application can not run on 2003. My vs 2012 
need a patch 

Jonathan Pickett notifications@github.com 
2014-05-06 09:49
请答复 给
MSOpenTech/redis 
reply@reply.github.com

收件人
MSOpenTech/redis redis@noreply.github.com
抄送
husttb 0049000424@zte.com.cn
主题
Re: [redis] 2.8.4 version:info command will crash (#105)

As a temporary fix, you can try pulling a version from the 2_6_14_rebase 
branch at commit "7071e9d5990933add468271a889e97030ba2298d" (October 3, 
2013) and compiling. This has the fix for the file descriptor problem, and 
is prior to the removal of the 32-bit support. 
The problem was that the AE code was using the file descriptor as a index 
into an array, and we were casting SOCKET handles to FDs. Since SOCKET 
handles are not numbered sequentially we would end up quickly running off 
the end of the array. 
There are other fixes subsequently applied to the replacement code we 
implemented to solve this problem. So going this route is perilous. My 
recommendation is to upgrade your machines with the 64-bit version of 
Windows.
—
Reply to this email directly or view it on GitHub.

---

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by jepickett** [comment]
Has this solved your problem on server 2003? Are you seeing any other issues on that platform?

**Comment by jepickett** [comment]
In 2.8.4 I added 32-bit support in commit f441b8d0f2f0c83fdef2874355385bc515c37734 to address issue #108. Please see my comment in that issue in order to understand the limitations that we have in in the 32-bit version of Redis.

**Comment by husttb** [comment]
Thank you very much

Jonathan Pickett notifications@github.com 
2014-05-16 09:40
请答复 给
MSOpenTech/redis 
reply@reply.github.com

收件人
MSOpenTech/redis redis@noreply.github.com
抄送
husttb 0049000424@zte.com.cn
主题
Re: [redis] 2.8.4 version:info command will crash (#105)

In 2.8.4 I added 32-bit support in commit f441b8d to address issue #108. 
Please see my comment in that issue in order to understand the limitations 
that we have in in the 32-bit version of Redis.
—
Reply to this email directly or view it on GitHub.

---

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by husttb** [comment]
i build 2.8.9 using vs2013 with platform toolset Visual Studio 2013 - 
Windows XP (v120_xp),but the exe can not run on winserver 2003,it will 
crash immediately!

Jonathan Pickett notifications@github.com 
2014-05-16 09:40
请答复 给
MSOpenTech/redis 
reply@reply.github.com

收件人
MSOpenTech/redis redis@noreply.github.com
抄送
husttb 0049000424@zte.com.cn
主题
Re: [redis] 2.8.4 version:info command will crash (#105)

In 2.8.4 I added 32-bit support in commit f441b8d to address issue #108. 
Please see my comment in that issue in order to understand the limitations 
that we have in in the 32-bit version of Redis.
—
Reply to this email directly or view it on GitHub.

---

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by husttb** [comment]
All the exes can not run on winserver 2003-32bit,including 

## redis-benchmark.exe,redis-check-aof.exe,redis-check-dump.exe,redis-cli.exe,redis-server.exe

ZTE Information Security Notice: The information contained in this mail (and any attachment transmitted herewith) is privileged and confidential and is intended for the exclusive use of the addressee(s).  If you are not an intended recipient, any disclosure, reproduction, distribution or other dissemination or use of the information contained is strictly prohibited.  If you have received this mail in error, please delete it and notify us immediately.

**Comment by jepickett** [comment]
In commit d4051d4c3820dbf0d52f1a73c9908f6bb04207c I have made API substitutions via runtime version checks that allows the code to run on Server 2003 in 32-bit mode. I do not know if it will run on Server 2003 64-bit mode, but I suspect it won't without having a separate compiler target for Server 2003. 

Performance on 32-bit Server 2003 is terrible. There have been many improvements to the Windows network stack over the last decade. I am seeing the 64-bit version on Server 2012 running about 4 times faster than the 32-bit version on Server 2003.

Let me know if this working for you as soon as you can.

**Comment by husttb** [comment]
Thanks very much.I hava tested this for two days,this works .
