### ISSUE TITLE
K32QueryWorkingSetEx call failure on Win 2008 pre-R2

### ISSUE THREAD

**Issue by coopa** [microsoftarchive/redis#106]
Hey all,
When I try to run either the latest build of redis-server, or the one from NuGet on Win Server 2008 (not R2), it throws the following exception:
"The procedure entry point K32QueryWorkingSetEx could not be located in the dynamic link library kernel32.dll."

Per http://msdn.microsoft.com/en-us/library/windows/desktop/ms684949(v=vs.85).aspx , I was able to fix this by adding 'psapi.lib' to additional dependencies and adding the '-DPSAPI_VERSION=1' to Command Line options of Win32_Interop. This allows redis to correctly function on Win2008, as well as later versions.

Regards

**Comment by jepickett** [comment]
Thanks for reporting this. Fixed in commit 01eaf183b3a9434c1d109989e36da276197fb2d4.
