### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by kellyelton** [microsoftarchive/redis#109]
I can't seem to figure out where this version is storing the data on the machine? I dug through the code for a little bit with no luck.

**Comment by jepickett** [comment]
Wikipedia has a particularly clear definition of Redis: "Redis is an open-source, networked, in-memory, key-value data store with _optional_ durability". If Redis is not specifically configured for persistence, then it is operating in in-memory-only mode. Check the **SHAPSHOTTING** section in the Redis.Windows.Conf file (in bin\release\2.8.4.zip, or msvs\setups\documentation) for information on the _save_, and _dbfilename_ settings. You may also want to look at the **APPEND ONLY MODE** section of that document to setup AOF saving. There is a good discussion on Redis persistence at http://redis.io/topics/persistence.

**Comment by kellyelton** [comment]
Hey thanks for the info
