### ISSUE TITLE
assert in hiredis after unsubscribing last pubsub channel

### ISSUE THREAD

**Issue by gsomberg** [microsoftarchive/redis#11]
In a Win32 application, linked against hiredis:

static void sRedisCommandCallbackFn2(struct redisAsyncContext_, void_, void\* pUserData)
{
    bool\* pContinue = (bool*)pUserData;
    *pContinue = true;
}

int main()
{
    w32initWinSock();

```
auto pRedisContext = redisAsyncConnect("127.0.0.1", 6379);

bool bContinue = false;
redisAsyncCommand(pRedisContext, sRedisCommandCallbackFn2, &bContinue, "SUBSCRIBE foo");
redisAsyncHandleWrite(pRedisContext);

while(!bContinue)
{
    redisAsyncHandleRead(pRedisContext);
}

redisAsyncCommand(pRedisContext, sRedisCommandCallbackFn2, &bContinue, "UNSUBSCRIBE foo");
redisAsyncHandleWrite(pRedisContext);

while(!bContinue)
{
    redisAsyncHandleRead(pRedisContext);
}

bContinue = false;
redisAsyncCommand(pRedisContext, sRedisCommandCallbackFn2, &bContinue, "PING");
redisAsyncHandleWrite(pRedisContext);

while(!bContinue)
{
    redisAsyncHandleRead(pRedisContext);
}
```

  return 0;
}

The code asserts in the last call to redisAsyncHandleRead().  The assert is async.c line 408 (or thereabouts):
assert(c->flags & REDIS_SUBSCRIBED);

At this point, the library is no longer subscribed to any pubsub channels, so it should be valid to send regular commands at this point.  It is incorrect for __redisShiftCallback() to return REDIS_ERR in this situation.

**Comment by clca** [comment]
Thanks for reporting the issue, we are investigating and we will submit a fix ASAP.

**Comment by HenryRawas** [comment]
It looks like a bug in your code. After first while (!bContinue) { ... } need to reset bContinue.
    bContinue = false;
