### ISSUE TITLE
2.8.9 redis-cli with unreadable text

### ISSUE THREAD

**Issue by longkerdandy** [microsoftarchive/redis#111]
Just update from 2.8.4 -> 2.8.9
Using latest binary release zip on Windows 8.1
Start redis-cli from cmd or powershell, when I input I got wired text pending.
For eg, when I enter 'keys *', I got these:
127.0.0.1:6379> [0G[0K127.0.0.1:6379> k[18G[0G[0K127.0.0.1:6379> ke[19G[0
G[0K127.0.0.1:6379> key[20G[0G[0K127.0.0.1:6379> keys[21G[0G[0K127.0.0.1:
6379> keys [22G[0G[0K127.0.0.1:6379> keys *[23G
(empty list or set)

**Comment by jepickett** [comment]
I have a fix that will render the ANSI escape codes, but since it borrows from another github project I have to run it up the management chain it see if anyone has a problem adding this to the project. It may be a few days before I can check this in.

**Comment by meteormatt** [comment]
I face the same problem.

![snap1](https://cloud.githubusercontent.com/assets/424475/3035959/30c76d10-e09c-11e3-8e1e-d6d4d9ab34e0.png)

**Comment by mhov** [comment]
I'm also seeing this.

**Comment by rustbomber** [comment]
I face the same problem.
![aa](https://cloud.githubusercontent.com/assets/437330/3062633/c51db184-e224-11e3-98db-bc2421dd4819.png)

How to fixed it?

**Comment by vmelamed** [comment]
Wasn't it already "few days"...? :) Please, fix this asap. The console is simply unusable...

**Comment by jahed** [comment]
Just installed this for the first time and I'm getting exactly the same problem.

Commands still work, it just shows a mess. Currently just copy and pasting commands from a text editor to bypass it.

**Comment by jepickett** [comment]
The codebase I am hoping to borrow from is ANSIcon (https://github.com/adoxa/ansicon). Getting permission to integrate this code is taking longer than I anticipated. Until I get permission you may use the ANIScon binaries to inject an ANSI interpreter into your command prompt prior to launching redis-cli:

![ansicon with redis-cli](https://cloud.githubusercontent.com/assets/5193368/3096194/32aa02ca-e5d1-11e3-9ad7-59372eefa24c.png)

**Comment by jed1978** [comment]
I also got this issue, but found another workaround before issue fixed.
You can download ConEmu instead of Windows Command Prompt.
http://sourceforge.net/projects/conemu/

![image](https://cloud.githubusercontent.com/assets/7637298/3129234/22a92b88-e7e0-11e3-997f-168163b2db22.png)

**Comment by jepickett** [comment]
This is fixed in commit 21fafdc620c9cb42c384f729c2e9ef0761139644. Output looks much better now:
![rediswithansioutput](https://cloud.githubusercontent.com/assets/5193368/3142811/e78595e0-e9d4-11e3-8125-cee0a1d74b3f.png)
