### ISSUE TITLE
Redis service failed to start

### ISSUE THREAD

**Issue by sakopov** [microsoftarchive/redis#112]
I'm following the installation guide in 2.8.9. I'm able to register the service, but can't seem to start it. Trying on multiple 64-bit machines running Windows 7 and Windows Server 2012 R2.
Running redis-server from command line results in 
"QForkMasterInit: system error caught. error code=0x000005af, message=VirtualAllo
cEx failed.: unknown error"

Nothing in the logs.

UPDATE: Looks like the error has to do with heap memory allocation which i fixed by setting maxheap option appropriately. So, while i can run the redis-server from command-line now, i still cannot run the service.

**Comment by jepickett** [comment]
The error code is ERROR_COMMITMENT_LIMIT 1455 (0x5AF): The paging file is too small for this operation to complete.

What is your system page file settings? Automatic,or have you set it to some specific value? 
How much disk space is available on the system on the drive Redis is on?
How much space is available on the drive your swap file is on? 
How much Physical RAM is on the system? 
What maxheap/maxmemory values are you passing in via the --service-install argument (directly, or .conf file)? 
What is the source of your binaries (bin\Release\redis_2.8.9.zip, NuGet, Chocolatey, built from source)?

**Comment by sakopov** [comment]
The error i posted earlier was resolved by killing a few processes. I was just running low on RAM. I also set the _maxheap_ to 1gb. I'm not setting _maxmemory_. All other settings are those that came with redis.window.config.

My system page file setting is in fact automatic. I have 8gigs of ram with 4 gigs available. Running on partition with 120gb which houses the redis installation along with the swap file.

I'm using build 2.8.9, which i didn't build... just using the binaries that came with release zip.

I don't know if this is relevant or not, but if i run

```
redis-server --service-run /path/to/config
```

from command-line after installing the service i get the following error

```
HandleServiceCommands: system error caught. error code=1063, message = StartServ
iceCtrlDispatcherA failed: unknown error
```

Not sure if this is what it's chocking on when the service fails to start.

**Comment by jepickett** [comment]
The config file should be passed with the --service-install argument rather than the --service-run argument. The path should either be path relative to the redis-server.exe file or an absolute path. 

I can replicate the error code 1063 by passing the config file with the --service-start argument. I will look at fixing that.

**Comment by sakopov** [comment]
I tried both switches w/o any luck. The redis.config file is located in the same location with all Redis executables.

```
redis-server --service-install redis.config
```

Succeeds

```
redis-server --service-start
```

Returns "Service failed to start" (with and without config specified)

If i browse the service in the Services Console I see

```
Path to Executable
"C:\Redis\redis-server.exe" --service-run redis.config
```

If i try to run that from command-line it returns previously mentioned error code 1063.

**Comment by jepickett** [comment]
To connect to the SCM (StartServiceCtrlDispatcherA in ServiceRun()) requires an elevated token. The --service-run argument is not meant to be run from from an unelevated context. It is designed to be launched by the SCM as "NT AUTHORITY\NetworkService". The token it inherits is not restricted in this scenario. 

If you launch your command prompt as administrator, the --service-run argument should work.

**Comment by sakopov** [comment]
Well, this turned out to be a stupid problem.

All binaries in the release zip along with the config file had file protection on after i unpackaged them. I unblocked the config file, re-registered the service and was able to start it this time. Looks like windows was just preventing read access to the config file.

Sorry for such a waste of time, but thank you so much for helping me out so quickly!

**Comment by jepickett** [comment]
No problem.

**Comment by azzlack** [comment]
I also has the same problem, but the fix mentioned by @sakopov above did not work for me.
But starting the server using `redis-server redis.windows.conf` works fine, so it seems to be related to the `redis-server --service-run redis.windows.conf` command.

PS, the supplied `RedisService.docx` has a type in the sample command for installing the service. It says `redis.window.conf`, when it should say `redis.windows.conf` (missing an s). I originally thought this to be the error, but fixing the config file path did not change anything.

**Comment by jepickett** [comment]
1.  Grab a copy of Process Monitor (http://technet.microsoft.com/en-us/sysinternals/bb896645)
2.  Launch ProcMon.exe
3.  In the Process Monitor Filter dialog add “Process Name” “contains” “redis-server” then “include” to the list of filters:
   ![processmonitorfilterdialog](https://cloud.githubusercontent.com/assets/5193368/3059200/ea78b42e-e1e8-11e3-8f43-4e8d74b5790b.png)
4.  Ensure the Filter-->Drop Filtered Events menu item is checked
5.  Ensure the File-->Capture Events menu item is checked
6.  Replicate your problem (messages will show up in the Process Monitor window)
7.  Use the File-->Save… menu item to save the file as a .PML file
8.  Compress the file and send it to v-jonpic@microsoft.com

**Comment by jybleau** [comment]
For me, after fixing the typo in the service install command `redis.windows.conf` and giving RW rights on redis folder to NETWORK SERVICE, it worked: service successfully started.
Windows 2008 (r1) x64.

**Comment by jepickett** [comment]
In commit e97604ce630bf8de2cf9f173b5a5dcc06ad05194 I added code to add NETWORK_SERVICE to the folder ACL during --service-install.I also fixed he documentation typo.
