### ISSUE TITLE
Issues with build

### ISSUE THREAD

**Issue by kirsn** [microsoftarchive/redis#114]
Window8.1
Followed the steps listed in the README:
- Install VS2013 express edition
- Open the msvs\redisserver.sln file
- Set the build to Release mode, and create a build

I see this output. The build states it has passed, but there is an error in there. So, not sure if this is as expected?

---

1>------ Build started: Project: hiredis, Configuration: Release Win32 ------
2>------ Build started: Project: Win32_Interop, Configuration: Release Win32 ------
3>------ Build started: Project: lua, Configuration: Release Win32 ------
1>  async.c
3>  lapi.c
2>  Performing Custom Build Tools
2>  A subdirectory or file resources already exists.
3>  lauxlib.c
2>  MC: Compiling EventLog.mc
2>  Microsoft (R) Windows (R) Resource Compiler Version 6.3.9600.16384
2>  
2>  Copyright (C) Microsoft Corporation.  All rights reserved.
2>  
2>  
3>  lbaselib.c
2>  RedisLog.c
3>  lcode.c
3>  ldblib.c
3>  ldebug.c
3>  ldo.c
3>  ldump.c
2>  win32fixes.c
1>  dict.c
3>  lfunc.c
1>  hiredis.c
3>  lgc.c
3>  linit.c
3>  liolib.c
3>  llex.c
2>  Win32_dlmalloc.c
3>  lmathlib.c
3>  lmem.c
3>  loadlib.c
2>  Win32_QFork_impl.c
1>  net.c
2>  win32_wsiocp.c
3>  lobject.c
3>  lopcodes.c
3>  loslib.c
3>  lparser.c
1>  sds.c
3>  Generating Code...
2>  Win32_EventLog.cpp
1>  hiredis.vcxproj -> D:\code\git\redis\msvs\Release\hiredis.lib
3>  Compiling...
3>  lstate.c
3>  lstring.c
3>  lstrlib.c
3>  ltable.c
3>  ltablib.c
3>  ltm.c
3>  lua.c
3>  lua_cjson.c
3>  lua_cmsgpack.c
3>  lua_struct.c
2>  Win32_FDAPI.cpp
3>  lundump.c
3>  lvm.c
3>  lzio.c
3>  print.c
3>  strbuf.c
3>  Generating Code...
2>  Win32_fdapi_crt.cpp
3>  lua.vcxproj -> D:\code\git\redis\msvs\Release\lua.lib
2>  Win32_QFork.cpp
2>Win32_QFork.cpp(145): warning C4244: 'initializing' : conversion from 'double' to 'size_t', possible loss of data
2>  win32_rfdmap.cpp
2>  Win32_service.cpp
2>  Win32_variadicFunctor.cpp
2>  Win32_Interop.vcxproj -> D:\code\git\redis\msvs\Release\Win32_Interop.lib
4>------ Build started: Project: RedisBenchmark, Configuration: Release Win32 ------
5>------ Build started: Project: RedisCheckAof, Configuration: Release Win32 ------
6>------ Build started: Project: RedisCheckDump, Configuration: Release Win32 ------
7>------ Build started: Project: RedisCli, Configuration: Release Win32 ------
4>  adlist.c
5>  redis-check-aof.c
6>  crc64.c
4>  ae.c
6>  lzf_c.c
6>  lzf_d.c
6>  redis-check-dump.c
5>....\src\redis-check-aof.c(172): warning C4013: '_setmode' undefined; assuming extern returning int
7>  linenoise.c
6>....\src\redis-check-dump.c(776): warning C4013: '_setmode' undefined; assuming extern returning int
6>....\src\redis-check-dump.c(790): warning C4244: '=' : conversion from '__int64' to 'off_t', possible loss of data
7>  adlist.c
7>  ae.c
4>  anet.c
4>  redis-benchmark.c
5>  Generating code
6>  Generating code
7>  anet.c
4>....\src\redis-benchmark.c(257): warning C4018: '<' : signed/unsigned mismatch
4>....\src\redis-benchmark.c(428): warning C4018: '<' : signed/unsigned mismatch
4>....\src\redis-benchmark.c(692): warning C4013: 'time' undefined; assuming extern returning int
4>  sds.c
7>  crc64.c
7>  redis-cli.c
4>  zmalloc.c
7>....\src\redis-cli.c(1193): warning C4244: 'function' : conversion from 'unsigned __int64' to 'size_t', possible loss of data
7>....\src\redis-cli.c(1228): warning C4244: 'function' : conversion from 'time_t' to 'unsigned int', possible loss of data
7>....\src\redis-cli.c(1418): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
7>....\src\redis-cli.c(1448): warning C4018: '<' : signed/unsigned mismatch
7>....\src\redis-cli.c(1453): warning C4018: '<' : signed/unsigned mismatch
7>....\src\redis-cli.c(1477): warning C4018: '<' : signed/unsigned mismatch
7>....\src\redis-cli.c(1487): warning C4018: '<' : signed/unsigned mismatch
7>....\src\redis-cli.c(1551): warning C4018: '>' : signed/unsigned mismatch
7>....\src\redis-cli.c(1568): warning C4018: '<' : signed/unsigned mismatch
7>....\src\redis-cli.c(1811): warning C4018: '<' : signed/unsigned mismatch
7>....\src\redis-cli.c(1925): warning C4013: '_setmode' undefined; assuming extern returning int
7>  release.c
7>  sds.c
5>  Finished generating code
6>  Finished generating code
7>  zmalloc.c
4>  Generating code
6>  RedisCheckDump.vcxproj -> D:\code\git\redis\msvs\Release\redis-check-dump.exe
5>  RedisCheckAof.vcxproj -> D:\code\git\redis\msvs\Release\redis-check-aof.exe
7>  Generating code
4>  Finished generating code
7>  Finished generating code
4>  RedisBenchmark.vcxproj -> D:\code\git\redis\msvs\Release\redis-benchmark.exe
7>  RedisCli.vcxproj -> D:\code\git\redis\msvs\Release\redis-cli.exe
8>------ Build started: Project: RedisServer, Configuration: Release Win32 ------
8>  adlist.c
8>  ae.c
8>  anet.c
8>  aof.c
8>..\src\aof.c(885): warning C4244: 'initializing' : conversion from '__int64' to 'int', possible loss of data
8>  bio.c
8>  bitops.c
8>  config.c
8>..\src\config.c(397): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(399): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(401): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(403): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(405): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(407): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(409): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(411): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(443): warning C4244: '=' : conversion from '__int64' to 'unsigned long', possible loss of data
8>..\src\config.c(604): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(626): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(648): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(652): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(656): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(687): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(711): warning C4244: '=' : conversion from '__int64' to 'long', possible loss of data
8>..\src\config.c(726): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(747): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(750): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(753): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(756): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(759): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(762): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(765): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(768): warning C4244: '=' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\config.c(816): warning C4244: '=' : conversion from '__int64' to 'long', possible loss of data
8>..\src\config.c(832): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(846): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(849): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(880): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(884): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(889): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(1658): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
8>..\src\config.c(1659): warning C4244: 'function' : conversion from '__int64' to 'size_t', possible loss of data
8>  crc64.c
8>  db.c
8>..\src\db.c(498): warning C4018: '<' : signed/unsigned mismatch
8>  debug.c
8>  dict.c
8>  endianconv.c
8>  hyperloglog.c
8>..\src\hyperloglog.c(1408): warning C4018: '<' : signed/unsigned mismatch
8>  intset.c
8>  lzf_c.c
8>  lzf_d.c
8>  memtest.c
8>  migrate.c
8>  multi.c
8>  networking.c
8>..\src\networking.c(562): warning C4018: '>' : signed/unsigned mismatch
8>..\src\networking.c(1182): warning C4244: 'function' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\networking.c(1184): warning C4244: '=' : conversion from '__int64' to 'long', possible loss of data
8>  Compiling...
8>  notify.c
8>  object.c
8>  pqsort.c
8>  pubsub.c
8>  rand.c
8>  rdb.c
8>  redis.c
8>  release.c
8>  replication.c
8>..\src\replication.c(49): warning C4244: 'function' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\replication.c(83): warning C4244: 'function' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\replication.c(109): warning C4244: 'initializing' : conversion from '__int64' to 'size_t', possible loss of data
8>..\src\replication.c(323): warning C4244: 'function' : conversion from '__int64' to 'size_t', possible loss of data
8>  rio.c
8>  scripting.c
8>  sds.c
8>  sentinel.c
8>  sha1.c
8>  slowlog.c
8>  sort.c
8>  syncio.c
8>  t_hash.c
8>  t_list.c
8>  t_set.c
8>  Compiling...
8>  t_string.c
8>  t_zset.c
8>  util.c
8>  ziplist.c
8>  zipmap.c
8>  zmalloc.c
8>  Generating code
8>d:\code\git\redis\src\redis.c(1461): warning C4723: potential divide by 0
8>d:\code\git\redis\src\redis.c(1462): warning C4723: potential divide by 0
8>d:\code\git\redis\src\redis.c(1463): warning C4723: potential divide by 0
8>  Finished generating code
8>  RedisServer.vcxproj -> D:\code\git\redis\msvs\Release\redis-server.exe
8>  compressOutputToReleaseFolder.ps1 : The term 
8>  'compressOutputToReleaseFolder.ps1' is not recognized as the name of a cmdlet, 
8>  function, script file, or operable program. Check the spelling of the name, or 
8>  if a path was included, verify that the path is correct and try again.
8>  At line:1 char:1
8>  + compressOutputToReleaseFolder.ps1
8>  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8>      + CategoryInfo          : ObjectNotFound: (compressOutputToReleaseFolder.p 
8>     s1:String) [], CommandNotFoundException
8>      + FullyQualifiedErrorId : CommandNotFoundException
8>  
8>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "powershell -executionpolicy unrestricted -command compressOutputToReleaseFolder.ps1
8>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code 1.
========== Build: 7 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by jepickett** [comment]
In commit a4dd5cba88822f0076004efa57665a766efd0def I removed the powershell script from the post build step in the 32-bit Release build. The script is only intended to work with the 64-bit Release target. It takes the output from the 64-bit build and zips it up along with the documentation and places it into the bin\Release folder.

**Comment by kirsn** [comment]
Thanks for the clarification. So, I can safely ignore that message. The built redis\* executables work as expected, on my Windows8.1 box.
