### ISSUE TITLE
Unable to execute MONITOR from redis-cli

### ISSUE THREAD

**Issue by paulbatum** [microsoftarchive/redis#115]
I cannot get the MONITOR command to work. I am using a windows build of redis-cli and I think the server I'm connecting to is Windows too (its the new Azure Redis Cache).

Steps to reproduce:
1. Clone the repo
2. Build the redis-cli
3. Confirm it works:

```
redis-cli -h pbtest.redis.cache.windows.net -a <MY PASSWORD>
keys *
1) "urn:TodoItem:IncompleteItemIds"
2) "ids:TodoItem"
3) "urn:todoitem:390ae974-56d4-4d99-9bb9-64ae11e7f4ae"
```

Attempt to use the monitor command:

```
pbtest.redis.cache.windows.net:6379> MONITOR
(error) ERR unknown command 'MONITOR'
```

**Comment by nmehlei** [comment]
Just a guess, but maybe they renamed the MONITOR command... if you find out to what it was renamed, you should be able to use it via a command map

**Comment by paulbatum** [comment]
It turns out the monitor command is disabled in Azure Redis Cache.
