### ISSUE TITLE
32 bit configuration platform removed from solution

### ISSUE THREAD

**Issue by laurencee** [microsoftarchive/redis#116]
From #108 it was mentioned that 32 bit would remain as a build it yourself option but it appears that the Win32 platform configuration has been removed from the solution.

Can this get added back so the 32 bit version can be self-compiled without having to manually set that all back up?

**Comment by laurencee** [comment]
I should add as a note the reason we can only use the 32 bit version is we have redis setup on embedded win OS systems which have custom hardware drivers that are currently 32 bit so there is no way to upgrade those systems to 64 bit OS.

**Comment by jepickett** [comment]
The 32-bit target is in the solution in the 2.8 branch.

**Comment by laurencee** [comment]
Sorry my mistake, I must have grabbed the wrong version. Git doesn't work through the proxy where I am at the moment :(
