### ISSUE TITLE
Redis 2.8.9 crushes on windows 7x64

### ISSUE THREAD

**Issue by mrniko** [microsoftarchive/redis#117]
I just run redis-server.exe and got:

QForkMasterInit: system error caught. error code=0x000005af, message=VirtualAllo
cEx failed.: unknown error

**Comment by mid787** [comment]
I have the same error

**Comment by mid787** [comment]
This is the solution : http://marcgravell.blogspot.co.il/2014/03/windows-redis-64.html. set it to 4 gb. ( in bytes)

**Comment by mrniko** [comment]
@RoyiNamir thanks for solution it works for me!
