### ISSUE TITLE
Sentinel tests error

### ISSUE THREAD

**Issue by acharyarajiv** [microsoftarchive/redis#119]
1ST when I ran tcl suite for sentinel I got an error saying “couldn't execute **"....\src\redis-sentinel": no such file or directory”**

![err](https://cloud.githubusercontent.com/assets/3601851/3171209/41c88ce8-ebc3-11e3-9011-ca31eb2e2be2.jpg)

I copied **redis-server.exe** and renamed it to **redis-sentinel.exe** after that the test started but it again threw error

![err jpg](https://cloud.githubusercontent.com/assets/3601851/3171214/61c3005a-ebc3-11e3-81fe-28de6c718656.png)

I'm using conf files that comes with this repo file

**Comment by jepickett** [comment]
I use a batch file to create a set of symbolic links to the binaries I want to test. My batch file looks like: 

```
@echo off
if exist src\redis-benchmark del src\redis-benchmark
if exist src\redis-check-aof del src\redis-check-aof
if exist src\redis-check-dump del src\redis-check-dump
if exist src\redis-cli del src\redis-cli
if exist src\redis-server del src\redis-server
if exist src\redis-sentinel del src\redis-sentinel

mklink src\redis-benchmark ..\msvs\%1\redis-benchmark.exe
mklink src\redis-check-aof ..\msvs\%1\redis-check-aof.exe
mklink src\redis-check-dump ..\msvs\%1\redis-check-dump.exe
mklink src\redis-cli ..\msvs\%1\redis-cli.exe
mklink src\redis-server ..\msvs\%1\redis-server.exe
mklink src\redis-sentinel ..\msvs\%1\redis-server.exe
```

I run the batch as:

```
MakeLinks <Directory>
```

Where Directory is relative to the msvs\ directory where the compiled binaries are contained. It may be one of:
- x64\Debug
- x64\Release
- Debug
- Release

**Comment by jepickett** [comment]
The error is expected because the connection to Redis is being broken in the test. I changed the line outputting the error message so that is would only output with loglevel=verbose. Change is in commit: c83b639b450477bfc7a95390b24aac169805088c.
