### ISSUE TITLE
When I try to store some values into redis (win-64), system throws BSoD.

### ISSUE THREAD

**Issue by rkttu** [microsoftarchive/redis#122]
When I try to store some values into redis (win-64), system throws BSoD. I analyzed my memory dump log with WinDBG(x64) and it says the BSoD caused by tcpip.sys. My environment is Windows 8 (x64) Enterprise with Hyper-V, 8GB memory.

...
DRIVER_IRQL_NOT_LESS_OR_EQUAL (d1)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: 0000000000000000, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000001, value 0 = read operation, 1 = write operation
Arg4: fffff800c854751e, address which referenced memory
...

Sure, this report is somewhat ambiguous, but I want to resolve the problem. Can I ask some hints to work around this problem?

Thank you.

**Comment by jepickett** [comment]
Likely you have some sort of hardware/driver issue. I will look at your dump if you want. Likely it will not make it through the email filters. Please compress the file and put it up some place where I can retrieve it (OneDrive, DropBox, etc.). Send me the credentials to access this to v-jonpic@microsoft.com.

**Comment by jepickett** [comment]
Are you connecting to Redis via the loopback adapter? Which port are you using? The dump is showing that the tcpip.sys driver is choking on a null-pointer access when returning data from the loopback adapter. While this may not totally rule out driver/hardware error, it does seem to lean towards a problem in the core tcpip stack. Can you reproduce the problem?
