### ISSUE TITLE
redis-cli regression: no prompt and hash values not shown

### ISSUE THREAD

**Issue by deepakverma** [microsoftarchive/redis#124]
Download latest redis-cli from http://www.nuget.org/packages/Redis-64/ (ver 2.8.4)
1. Redis prompt is not shown when connected to a Redis instance. 
2. Hash values with a hget or hvals is not shown with redis-cli 

A customer (Timbo) originally reported this here http://blogs.msdn.com/b/webdev/archive/2014/05/12/announcing-asp-net-session-state-provider-for-redis-preview-release.aspx?PageIndex=2#comments

**Comment by deepakverma** [comment]
I see the NuGet package has not been updated since March, which might be causing this. 
Can you please update it.

Thanks

**Comment by jepickett** [comment]
The binaries need to be signed. I have been promised that this will happen soon. It is out of my control.

**Comment by jepickett** [comment]
2.8.9 has been released
