### ISSUE TITLE
Sentinel mode with --sentinel parameter throw exception

### ISSUE THREAD

**Issue by BDeus** [microsoftarchive/redis#125]
To enable sentinel mode we can rename exe file in redis-sentinel (work) and set a command parameter to --sentinel (crash).
The last one throw an exception "No parameter value for argument on command line. argument = 'sentinel'".
In ParseCommandLineArguments function the n parameter seem to increment to early.

**Comment by jepickett** [comment]
fixed in commit  721a9a2467a0c86e1a960e4472115616c5afb197
