### ISSUE TITLE
After failing BgSave once, the system won't persist any changes

### ISSUE THREAD

**Issue by sigmaRetrieval** [microsoftarchive/redis#127]
If the background save fails once, the system continues to respond. However any changes are not persisted anymore by redis. This problem seem to appears randomly when under heavy load.

Log file: 
[5936] 12 Jun 15:30:09.399 # BeginForkOperation: system error caught. error code
=0x00000000, message=Forked Process did not respond in a timely manner.: unknown
 error
[5936] 12 Jun 15:30:09.399 # Can't save in background: fork: Invalid argument

Client response:
127.0.0.1:6379> bgsave
(error) ERR Background save already in progress
127.0.0.1:6379> save
(error) ERR Background save already in progress

PS. I'm using the code as of 12 june 9 GMT

**Comment by jepickett** [comment]
Likely you have 'stop-writes-on-bgsave-error' set to 'yes' in the .conf file. I will try increasing the timeout for the forked process to respond to see if that helps. How much data are you storing in Redis? How much traffic are you giving to Redis?

**Comment by sigmaRetrieval** [comment]
The load was a continuous writes sequence of a few minutes. Hopefully your fix will alleviate this issue.

**Comment by deancsmith** [comment]
I have also been experiencing this problem on 2.8.12.

It seems to occur randomly under periods with lots of writes, potentially also when the CPU for our VM is under a heavy load.

It seems like the fork timeout is occurring after around 14 seconds.
