### ISSUE TITLE
Redis error on start-up

### ISSUE THREAD

**Issue by edmenendez** [microsoftarchive/redis#128]
Downloading the latest 2.8.9 and using the binary. Confirmed the folder is not read-only. When I try to start it as a service or manually I get an error:

```
C:\Program Files\redis>redis-server --service-start
[75136] 13 Jun 11:29:07.424 # Redis service failed to start.
C:\Program Files\redis>redis-server
[159024] 13 Jun 11:29:10.767 # QForkMasterInit: system error caught. error code=0x00000070, message=CreateFileMapping failed.: no space on device
```

Here is the log file for the service install: https://dl.dropboxusercontent.com/u/579284/github/Logfile%20for%20service%20install.zip

And here is the log file for trying to start it: 
https://dl.dropboxusercontent.com/u/579284/github/Logfile2%20for%20start.zip

**Comment by coopa** [comment]
You need to set the --maxmemory setting to restrict the heap file size being created.

See here for the explanation:
https://github.com/MSOpenTech/redis/blob/2.8/src/Win32_Interop/Win32_QFork.cpp#L573

**Comment by edmenendez** [comment]
Maybe I have the syntax wrong... But that didn't help:

```
C:\Program Files\redis>redis-server --service-install redis.windows.conf --loglevel=verbose --maxmemory 2mb
[286192] 13 Jun 12:23:52.350 # Redis successfully installed as a service.
C:\Program Files\redis>redis-server --service-start
[294620] 13 Jun 12:24:09.315 # Redis service failed to start.
C:\Program Files\redis>redis-server
[287688] 13 Jun 12:24:25.265 # QForkMasterInit: system error caught. error code=0x00000070, message=CreateFileMapping failed.: no space on device
```

I also went into the conf and changed maxmemory to 2mb (it was commented out)

**Comment by jepickett** [comment]
I am not seeing a Process Exit in the PML file for the second process. It is probably still running. My timeout for querying service startup in 2 seconds. It may be that this is too short for your system. Does it launch successfully from the Services control panel? Does it launch successfully after a reboot?

**Comment by jepickett** [comment]
How much space do you have on the drive that redis is installed on? Try --maxheap instead of --maxmemory,

**Comment by RyanElfman** [comment]
I get this exact same issue

**Comment by jepickett** [comment]
How much space do you have on the drive that redis is installed on? Redis creates a memory mapped file in order to share with the forked process used for RDB and AOF persistence. By default this file is equal to the size of physical RAM. If you do not have enough disk space you will get an out of disk space error (0x70). You can limit the size of this file with the --maxheap flag.

**Comment by RyanElfman** [comment]
That would make sense, I have 16GB ram on my desktop which I was trying this on and only 5GB free (My OS is on only a 60GB SSD drive). I will try to free up that amount of space but I'm not sure I can..

Is there a way to have this file stored on another drive/partition?

**Comment by jepickett** [comment]
How much data are you going to store in Redis? You won't need your heap larger than about 1.5x your memory storage requirements. If you use the --maxmemory flag you will get this behavior, and the memory mapped file will be sized accordingly.

If you really need a heap larger than the partition Redis is installed on, you can change your directory to the location where you want the memory mapped file and from there launch Redis with a full path. Redis will use the current directory for creating the heap file.
