### ISSUE TITLE
Multiple Redis services on Windows 8.1

### ISSUE THREAD

**Issue by mrnrone** [microsoftarchive/redis#131]
Hi,

I have rebuilt the source code and now I'd like to use and run multiple Redis services on Windows 8.1. 

(Downloaded version: https://github.com/MSOpenTech/redis/archive/2.8.zip)

I have created configuration files with different "service-name" parameters and different ports of course. By default there isn't a "service-name" parameter inside configuration file but as I have seen it can work. After a successfully install I can see multiple Redis instances in Windows' services list. E.g redis6379, redis6389 etc. 

If I try the following command:

redis-server.exe --service-start --service-name redis6379
redis-server.exe --service-start --service-name redis6389

I have got the "Redis server failed to start" error messages.

If I try to start from Windows' services I have got 1067 error code.

I have tried (with default configuration file) single instance and it works perfectly. However if I set "service-name" I can't start the service! It looks like only default settings are good :(

How is it possible to use and run multiple Redis services on Windows 8.1?

Thank you!

**Comment by reddy-sabbella** [comment]
If you use the following steps, you can use multiple services. The config file is shared but the service name and port are specified in the command line arguments.

redis-server.exe --service-install redis.conf --service-name RedisService1 –port 6379
redis-server.exe --service-install redis.conf --service-name RedisService2 –port 6380
redis-server.exe --service-start --service-name RedisService1
redis-server.exe --service-start --service-name RedisService2

**Comment by mrnrone** [comment]
I've tried but I've got the same error messages. It seems if I don't use "--service-name" parameter then a single instance is runnable. The "--port" parameter works well. I don't know much about services but I think there is a problem with service naming. 
Do I have to add redis' bin directory to the PATH or set any other environment variable? Or could you check that parameter, please?

Thank you!

**Comment by jepickett** [comment]
Please read about the maxheap and maxmemory flags in msvs/setups/documentation/redis.windows.conf. Likely you are running out of either disk space for the heap memory mapped files, or you are running out of system swap file space. By default Redis tries to create a heap as large as physical memory. If you are running four instances of Redis on a single machine, you will want to limit the heap for each instance to a quarter of physical memory. Look in your application event log. For the failing instance I would expect an error of either 0x5AF(ERROR_COMMITMENT_LIMIT) or 0x70 (ERROR_DISK_FULL)

**Comment by jepickett** [comment]
In src\Win32_Interop\Win32_QFork.cpp there are comments describing how the QFork operation works. It is useful to grok this when configuring Redis in more complicated scenarios.

**Comment by mrnrone** [comment]
Hi jepickett,

you were right, first I moved binary files to a bigger partition and now I can run 2 or more instances on different ports. (I've 8GB ram and 50GB free space on disk)
1. Run from console 1: D:\Redis\redis-server.exe
2. Run from console 2: D:\Redis\redis-server.exe  --port 7777
   Works perfectly.

But as services still doesn't work :(
1. D:\Redis\redis-server.exe --service-install redis.conf --service-name Redis1 --port 6379
2. D:\Redis\redis-server.exe --service-install redis.conf --service-name Redis2 --port 7777
   [3. Two services are ready, I can see them in Window's services too.]
3. D:\Redis\redis-server.exe --service-start --service-name Redis1
4. Redis service failed to start.

I will try other memory settings in configuration file. 

Thank you!

**Comment by jepickett** [comment]
Have you been able to sort out your memory usage requirements?
