### ISSUE TITLE
Unable to disable persistence when building 2.8 from sources

### ISSUE THREAD

**Issue by paveliak** [microsoftarchive/redis#134]
I run Redis with persistence disabled, i.e. I have save "" added to the redis.conf file.
It runs fine on the redis-server.exe binary from the repo 2.8 branch (redis-2.8.9 release). However when I rebuild branch 2.8 from sources I get error "Not enough parameters available for save"

I can disable persistence by updating configuration from within Redis but I really want to do it with the configuration file.

**Comment by jmaxxz** [comment]
Similar issue. When running as a service with `save ""` set in my config file the service fails to start.

**Comment by jepickett** [comment]
Fixed in commit a14400a8583d30c1fad3275575b9a19c728af2ed
