### ISSUE TITLE
Redis does not build with VStudio 2014 CTP

### ISSUE THREAD

**Issue by paveliak** [microsoftarchive/redis#135]
Here is the error (it's being reported from multiple files).
1>------ Build started: Project: hiredis, Configuration: Release x64 ------
1>  async.c
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sys/stat.h(232): error C2365: 'fdapi_fstat64': redefinition; previous definition was 'data variable'
1>  e:\source\repos\redis\deps\hiredis....\src\win32_Interop\Win32_FDAPI.h(218): note: see declaration of 'fdapi_fstat64'

**Comment by jepickett** [comment]
The CTP no where near final. When there is a RC available I will make sure the project builds with the new tool set. Perhaps you could provide feedback to the Visual Studio team that some of their changes is breaking existing code?
