### ISSUE TITLE
Save "" causes service not to start

### ISSUE THREAD

**Issue by jmaxxz** [microsoftarchive/redis#136]
When running as a service with `save ""` set in my config file the service fails to start.

**Comment by jepickett** [comment]
fixed in commit a14400a8583d30c1fad3275575b9a19c728af2ed

**Comment by reddy-sabbella** [comment]
I got the latest Redis 2.8 and built it and running it on Windows 7 and Redis as a service has trouble starting. I had no issue with 6/10/2014 build. I can run the redis-server.exe normally. Please advise.

E:\redis>redis-server.exe --service-start --service-name RedisService1
[4528] 24 Jun 09:10:49.065 # Redis service failed to start.

**Comment by jepickett** [comment]
1.  Grab a copy of Process Monitor (http://technet.microsoft.com/en-us/sysinternals/bb896645)
2.  Launch ProcMon.exe
3.  In the Process Monitor Filter dialog add “Process Name” “contains” “redis-server” then “include” to the list of filters:
   ![processmonitorfilterdialog](https://cloud.githubusercontent.com/assets/5193368/3376865/a8e0b52e-fbd9-11e3-91ac-2413d505e8d2.png)
4.  Ensure the Filter- - >Drop Filtered Events menu item is checked
5.  Ensure the File- - >Capture Events menu item is checked
6.  Replicate your problem (lots of messages will show up in the Process Monitor window)
7.  Use the File- - >Save… menu item to save the file as a .PML file
8.  Compress the file and put it somewhere I can download it (OneDrive, DropBox, etc.), then send the instruction for accessing the file to v-jonpic@microsoft.com

Also send me a copy of your config file,

**Comment by reddy-sabbella** [comment]
Hi Jonathan,
I am attaching the compressed files that you asked.

Regards
Reddy

**Comment by jepickett** [comment]
I am not seeing the file. Email filtering usually strips the file. The most reliable method is via a cloud storage service.

**Comment by reddy-sabbella** [comment]
Here they are Jonathan.
https://drive.google.com/file/d/0B_XgvCX_16PZMFAtQUFvOVVaWm8/edit?usp=sharing
https://drive.google.com/file/d/0B_XgvCX_16PZaVRESXRCWG05YTA/edit?usp=sharing

**Comment by jepickett** [comment]
I just pushed up a fix. Let me know if this works for you.

**Comment by reddy-sabbella** [comment]
Works now Jonathan. Thanks very much for such a fast turnaround.

**Comment by reddy-sabbella** [comment]
Hi Jonathan,
It worked fine on my machine with 16 GB of RAM. Now, I installed it on a different machine that has 192 GB RAM and disk space is about 200 GB free. maxmemory in redis.conf is set to 4g. The Redis-Server.exe is not starting. Here are the ProcessMonitor logs and configuration file I am using.

Regards
Reddy

https://drive.google.com/file/d/0B4zh8i39UoaRVGI0ZmVGVmJEc2c/edit?usp=sharing

https://drive.google.com/file/d/0B4zh8i39UoaRbURsTUxnMDFtZFU/edit?usp=sharing

From: Reddy Sabbella
Sent: Wednesday, June 25, 2014 7:47 AM
To: 'MSOpenTech/redis'; MSOpenTech/redis
Subject: RE: [redis] Save "" causes service not to start (#136)

Works now Jonathan. Thanks very much for such a fast turnaround.

**Comment by reddy-sabbella** [comment]
My bad. Please ignore this. My mistake was that when I installed the service, I did not specify redis.conf. Once I specify it, it is working fine.

Regards
Reddy

From: Reddy Sabbella
Sent: Wednesday, June 25, 2014 8:36 AM
To: 'MSOpenTech/redis'; 'MSOpenTech/redis'
Subject: RE: [redis] Save "" causes service not to start (#136)

Hi Jonathan,
It worked fine on my machine with 16 GB of RAM. Now, I installed it on a different machine that has 192 GB RAM and disk space is about 200 GB free. maxmemory in redis.conf is set to 4g. The Redis-Server.exe is not starting. Here are the ProcessMonitor logs and configuration file I am using.

Regards
Reddy

https://drive.google.com/file/d/0B4zh8i39UoaRVGI0ZmVGVmJEc2c/edit?usp=sharing

https://drive.google.com/file/d/0B4zh8i39UoaRbURsTUxnMDFtZFU/edit?usp=sharing

From: Reddy Sabbella
Sent: Wednesday, June 25, 2014 7:47 AM
To: 'MSOpenTech/redis'; MSOpenTech/redis
Subject: RE: [redis] Save "" causes service not to start (#136)

Works now Jonathan. Thanks very much for such a fast turnaround.
