### ISSUE TITLE
Receiving an error when trying to set up the service from PS Command

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/redis#141]
Unable to set up the redis server with the following command from PS (.\redis-server.exe –service-install C:\RediServer\redis.default.conf –service-name Redis-Default). I have attached the error and configuration file (as jpg file) used to set up the server. Pls help

![redis default conf](https://cloud.githubusercontent.com/assets/8025468/3428575/76e67fbe-0042-11e4-818d-6d233ac7d6bd.jpg)

![error](https://cloud.githubusercontent.com/assets/8025468/3428594/be7123ac-0042-11e4-8785-7c6cdd6d8ae3.png)

**Comment by jepickett** [comment]
For a others who may see this issue in the future, the command line is lacking the leading double dash on the 'service-install' and 'service-name' arguments.
