### ISSUE TITLE
ERR wrong number of arguments for HMSET with valid command

### ISSUE THREAD

**Issue by markmcgookin** [microsoftarchive/redis#142]
I get the "ERR wrong number of arguments for HMSET" when I pass the following command (using Redis Desktop Manager)

HMSET user:1001 name "Mary Jones" password "hidden" email "mjones@example.com"

when I step through the code I can see that it is saying that c->argc is coming out at 9 (which is why it is falling over) because it needs to be divisible by 2. (See t_hash.c line 502) 

But I don't know how to get the info about what those arguments are to see what is going wrong.

**Comment by jepickett** [comment]
I ran your command through redis-cli.exe and it works (reports 'OK'). I suspect your problem has to do with the Redis client included with the Redis Desktop Manager. I would file a bug with them. My hunch is that it has something to do with parsing the "Mary Jones" argument.

**Comment by markmcgookin** [comment]
Cheers mate. Will investigate. Thanks for the input.
