### ISSUE TITLE
Redis default settings lead to crashes on windows: VirtualAllocEx failed

### ISSUE THREAD

**Issue by seansaleh** [microsoftarchive/redis#143]
## Low memory issue

As documented by others in #117, #128, #137, #79, #126, #112, and #70  there is an issue starting and running redis on windows when memory usage is above nominal. 
This issue can be easily solved with specifying `--maxheap` when starting redis, or in the configuration, but by default it leads to users experiencing crashes in redis.
##### Explanation from @jepickett

> Redis allocates a memory mapped file for sharing with the fork()ed processes used during AOF + RDB file creation. The default size of this file is equal to the size of physical memory on your system. During the forking process the system swap file is used manage Copy on Write pages created in both the master and the slave process. Thus the system swap file must be larger than size of the memory mapped file. Windows by default will create a swap file that will expand up to about 3.5 times the size of physical memory. In the worst case scenario the swap file commitment level required by Redis and its forked subprocess is 3 times the size of the memory mapped file. In the default case on a server only used for Redis, the default swap file size will be just large enough.

Leaving this issue as it is does not mean production ready software. 
This issue is also a risk to redis while its running if it forks and the machine is low on memory (potentially related to #126 and a runtime crash I had that I cannot reproduce).
## Proposed Solutions
- Document this in the readme one of these ways:
  - State that redis must be used on a dedicated machine in production environments 
  - State that the memory must be specified lower if used in development or on a shared machine
- Change default memory usage to not be maximum available RAM
- Calculate a sane default on first launch based on maximum available paged memory
- Present users with an error message clearer than `QForkMasterInit: system error caught. error code=0x000005af, message=VirtualAllocEx failed.: unknown error`

**Comment by jepickett** [comment]
1. I am working on a best practices document. An initial copy of this can be found in "msvs\setups\documentation\Redis on Windows.docx".
2. Redis is a in-memory database. While it is true that there are many scenarios where complete physical memory usage is not needed, what is an appropriate default upper limit if not max physical memory?
3. Nothing is commited until it is used, except for disk space. I could certainly add a limit based on disk space available at startup. That would at least delay some of the disk space related issues (error 0x70) until a RDB snapshot. Perhaps it is better to run into the disk space issue earlier?
4. The 0x5AF error is about not having enough contiguous paging file space available to allocate a window for our shared heap. Unfortunately the paging file is an opaque entity, without public APIs available for determining current usage. So I don't have a way to throttle heap size based on paging file availability. One way I could work around this is to break up the heap into many smaller memory mapped files and map/unmap as needed. I tested this early on and found allocation performance reduced 40%-50% with this scheme. Is this worth doing? It seems a shame to do so just for developer convenience.
5. I will put in better error messages for the 0x70 and 0x5AF errors.

**Comment by jepickett** [comment]
In commit 9613f9a2a6a51067f81b4aab6236a6ee710d8b33 I improved the error messages for the ERROR_COMMITMENT_LIMIT and ERROR_DISK_FULL errors.

**Comment by seansaleh** [comment]
1. The docs look like they describe this issue, but they could potentially make it clearer that the only stable way to run redis is on a virgin OS or with reduced memory. Are you planning on putting this information in the readme.md? 
2. Max physical is a reasonable upper limit, assuming windows can handle it. Has testing been done on low memory windows machines (such as the Azure XS instances) with redis's keyspace full? 
3. Presumably it would be better for redis to be offline rather than unable to save? I'm not sure of the best option here
4. Definitely not worth it
5. Those messages look good!

Thank you for the prompt reply. Hopefully fewer people will run into these issues now!

**Comment by jepickett** [comment]
I have updated the Readme.md file. Redis runs well on Azure XS instances.
