### ISSUE TITLE
temp aof and rdb files

### ISSUE THREAD

**Issue by lieven-m** [microsoftarchive/redis#145]
*bgrewriteaof
Temporary files created by bgrewriteaof aren't removed after completion.

*bgsave
If you trigger a bgsave, it doesn't save a temp file first.

**Comment by jepickett** [comment]
I am not seeing what you are. If I run ProcMon (http://technet.microsoft.com/en-us/sysinternals/bb896645.aspx) and trigger a bgrewriteaof and a bgsave, I am seeing the temporary files being created, accessed an deleted.  Pleas get me a copy of a ProcMon log file from your system as follows:
1.  Grab a copy of Process Monitor 
2.     Launch ProcMon.exe
3.  In the Process Monitor Filter dialog add “Process Name” “contains” “redis-server” then “include” to the list of filters:
   ![processmonitorfilterdialog](https://cloud.githubusercontent.com/assets/5193368/3502847/262a9728-0627-11e4-8b08-5d292e8d6141.png)
4.  Ensure the Filter- - >Drop Filtered Events menu item is checked
5.  Ensure the File- - >Capture Events menu item is checked
6.  Replicate your problem (lots of messages will show up in the Process Monitor window)
7.  Use the File- - >Save… menu item to save the file as a .PML file
8.  Compress the file and put it somewhere I can download it (OneDrive, DropBox, etc.), then send the instruction for accessing the file to v-jonpic@microsoft.com

**Comment by lieven-m** [comment]
The problem occurs when I'm using the redis-server with a  config file.
![redisonwindowstempfileissues](https://cloud.githubusercontent.com/assets/6168221/3506875/34624944-0677-11e4-808a-6db5a9172424.JPG)

Kind regards,
Lieven

**Comment by jepickett** [comment]
Is this fixed with 88a62862d3a2e1b7e91cd157b2267e167fffa8a8 ?

**Comment by lieven-m** [comment]
It can't be fixed with that, because I tried it from a path without spaces (c:\Redis).

**Comment by jepickett** [comment]
The PML files you sent me is showing the executable as C:\Program Files\Redis\redis-server.exe. Can you capture a new PML file with the new build of Redis? I am thinking that if our fork() simulation fails for some reason then these files will not be cleaned up.

**Comment by jepickett** [comment]
Please try the latest build. I fixed a race condition between the windows memory manager and fwrite() that may have prematurely terminated the AOF write.

**Comment by lieven-m** [comment]
I did a test with the new version and this fixed the issue.

Thanks,
Lieven
