### ISSUE TITLE
release/x64 build failed

### ISSUE THREAD

**Issue by rebornix** [microsoftarchive/redis#148]
I'm trying to build this solution using VS 2013, configuration Release and target x64. However I get this error:

```
The command "powershell -executionpolicy unrestricted -command   compressOutputToReleaseFolder.ps1
:VCEnd" exited with code 1
```

My environment path does not include my current directory, which is a common case. How about changing this script to `powershell -executionpolicy unrestricted -command .\compressOutputToReleaseFolder.ps1` to avoid this error.

**Comment by jepickett** [comment]
Fixed in commit 128f5b53deb6a65add45985cf979fab05d27ed17.
