### ISSUE TITLE
How can I use redis-sentinel to support failover?

### ISSUE THREAD

**Issue by jmpcyc** [microsoftarchive/redis#149]
In Linux version, we can use redis-sentinel or redis-server --sentinel  to monitor master server to support failover.In this version, I only have to use redis-server in sentinel mod,but  it can't connect to the master.And  when I deploy sentinel service in Linux, it can connect to the master server deployed in Windows.Anyone has depolyed sentinel service successfully in Windows ?

**Comment by jmpcyc** [comment]
I have found the problem. When I use redis-server of version2.8.9  in sentinel mod to monitor master of version 2.8.12, it workes ok.So it is a bug ?

**Comment by jepickett** [comment]
This is the same as issue 146. There was a change in the networking code from 2.8.9 to 2.8.12 that broke our IOCP implementation of the async connect code in hiredis. I have a fix for IPv4. I am working to make this also work for IPv6. I should have this checked in early next week.

**Comment by jmpcyc** [comment]
Thank you for your help.
