### ISSUE TITLE
about the maxmemory

### ISSUE THREAD

**Issue by xiexueze** [microsoftarchive/redis#15]
OS : windows server 2003 32bit
RAM: 8G (free)

But the redis-server.exe Out of memory when it's memory just to 2G.

the message is : "zmalloc: Out of memory trying to allocate 52 bytes"

**Comment by HenryRawas** [comment]
It is a 32 bit process on Windows. By default it is restricted to using 2GB. It is possible to configure Windows to allow a process to use 3GB. To go beyond that you need a 64 bit process.

**Comment by samirageb** [comment]
As a follow up, it is possible to have 32-bit processes utilizing a full 4GB of memory on a 64-bit version of windows.  Assuming that Redis is actually compatible with certain behavior that might come as a result of operating in a WOW64 environment, changing to Windows Server 2003 64-bit might give you better results.

For a better explanation and more details, see here: http://stackoverflow.com/questions/570589/can-a-32bit-process-access-more-memory-on-a-64bit-windows-os

**Comment by clca** [comment]
Memory limits will be solved soon with the 64bit version. Still working on it but almost ready :)

**Comment by trippleflux** [comment]
what is the status on x64 ?

**Comment by clca** [comment]
x64 is available now.
