### ISSUE TITLE
Support for 3.0

### ISSUE THREAD

**Issue by asilvas** [microsoftarchive/redis#151]
Even though still in beta, the sooner it's in sync the better ;-).

**Comment by jepickett** [comment]
I don't really want to be chasing breaking changes on a moving target. We have decided to wait until 3.0 is official before we put significant effort into it.

I month or two ago I did a trial run porting the 3.0 changes to a local branch. It took less than a day to get it compiling. When 3.0 drops I expect that within a couple of days I will have a (work-in-progress) Windows branch available. Formal testing will take a couple of weeks. Depending on what we find, signed releases via NuGet and Chocolatey should drop within a month of the Posix branch.
