### ISSUE TITLE
slaveof with DNS alias/Computer name

### ISSUE THREAD

**Issue by svantreeck** [microsoftarchive/redis#152]
With 2.8.9, we could set up master/slave replication via computer name, but with 2.8.12, it seems like we need to set up with IPs.  Would it be possible to add back support for computer names in the future?

In the eventlog, I get this error, and the service shuts down, but with the computer's IP runs succesfully.

```
syslog-ident = redis
Writing to socket Unknown error (10057)
```

Thanks

**Comment by jepickett** [comment]
Fixed in commit dbc7669fffc6d912c760dad77c3bed6aab958ea2.
