### ISSUE TITLE
redis-server.exe has stopped working when conf file specified

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/redis#153]
Executing "redis-server" works fine, but when specifying a config file, even the default one in the zip file, "redis-server redis.windows.conf", it does not start. Full path to config file doesn't help. This is occurring on Windows 7 and Windows Server 2012. First seen after today's commits. Using the zip package from 5 days ago works like a charm.

![image](https://cloud.githubusercontent.com/assets/2590224/3665235/f689c75a-11e3-11e4-9a7e-7d20eb2402d3.png)

**Comment by deancsmith** [comment]
Same here on 2008r2.

**Comment by jepickett** [comment]
Fixed in commit 5e05dad83a3366ff7715bb26497cf9120e80b605. Let me know if this fixes the problem on your end.

**Comment by deancsmith** [comment]
That fixed the issue for me - thanks.

Should this have been picked up by one of the integration tests?

I'm just about to start running Redis in production on a few servers, thanks for all your great work on this.

**Comment by ghost** [comment]
Agreed -- thanks for your work on this and the quick resolution.
