### ISSUE TITLE
BGREWRITEAOF is leaving temp-rewriteaof-old-XXXX.aof files behind

### ISSUE THREAD

**Issue by petedishman** [microsoftarchive/redis#155]
I'm running the latest build of redis (taken from https://github.com/MSOpenTech/redis/tree/2.8/bin/release today) and I've also done a debug build from the 2.8 branch and in both cases I'm seeing the same thing.

Whenever I run a BGREWRITEAOF a copy of the appendonly.aof file is left in my redis directory named temp-rewriteaof-old-XXXX.aof (where XXXX is the pid of the redis-server process that gets created during the rewrite)
e.g:

![image](https://cloud.githubusercontent.com/assets/3606336/3750228/99c78762-17f3-11e4-876d-324f55a6ce47.png)

I've got procmon trace of doing the bgrewriteaof available here: https://drive.google.com/file/d/0B6Q675PXCq1xSmFNSDRZdldSZDg/edit?usp=sharing

Just to confirm I tried this on the linux version of redis and there were no files left around after doing the rewrite.

I've looked through the code in aof.c backgroundRewriteDoneHandler() in particular but I can't actually see anything that would delete those files?

**Comment by petedishman** [comment]
I've seen #145 which appears to be the same issue, but I'm still getting it?
They said it went away on the latest version, but I'm not seeing that?

**Comment by jepickett** [comment]
The first two files in the screenshot above are are not present in the PML file you captured (Tools->File Summary...). The file "temp-rewriteaof-old-14992.aof" has three events that occur within 3ms at the very end of the PML file. I don't think that you have captured the file leakage here. 

Are you using a .conf file? Please send me a link to it if you are. How are you triggering a BGREWRITEAOF? redis-cli? Do you have a scenario where you can reproduce this 100% of the time?

**Comment by petedishman** [comment]
Sorry, I think the screenshot and the log may have come from different test runs.

I can reproduce it every time, just from starting redis up, connecting with the cli and running bgrewriteaof. Every call of bgrewriteaof just results in a new temp-xxx.aof file being created.

Conf file: https://drive.google.com/file/d/0B6Q675PXCq1xdWswSXkteDgxcms/edit?usp=sharing
New PML file: https://drive.google.com/file/d/0B6Q675PXCq1xRjVXanhsVXhPd1E/edit?usp=sharing

The PML starts once redis-server is up and running, nothing connected to it. It should then show me connecting with redis-cli and running bgrewriteaof.  Nothing else happens

**Comment by jepickett** [comment]
I added a fix for this issue in 8d28cf75424e223705418881ab0253d486a04034. Let me know if this works for you.

**Comment by petedishman** [comment]
Yep, that works.
Thanks
