### ISSUE TITLE
Distribute RedisWatcher through Web Platform Installer

### ISSUE THREAD

**Issue by tugberkugurlu** [microsoftarchive/redis#16]
Can u guys distribute RedisWatcher through WebPI? As you may know, there is a comman line version of the procudt (WebPICMD.exe) and this would make some much easy to automate the installation process.

**Comment by clca** [comment]
this is definitively something we can consider for the near future. Right now we are focusing on getting the 64bit version ready and more testing. NuGet, WebPI are definitively features we want to add in order to make easier for developers to deploy Redis on their machine.

**Comment by tugberkugurlu** [comment]
Thanks!

Especially now with Windows Azure VMs, [we wanna automate every installation](http://www.tugberkugurlu.com/archive/script-out-everything-initialize-your-windows-azure-vm-for-your-web-server-with-iis-web-deploy-and-other-stuff) and to be able to add the RedisWatcher to that list would be awesome.

**Comment by clca** [comment]
There are still a couple of things we want to add to Redis before we can start distributing Redis via WebPI but it won't be a long wait. We are finishing the 64bit version, after that we can focus on making easier for developer to deploy Redis (including Azure).

**Comment by nazik** [comment]
Good to know there will be a version of Redis  available for Windows Azure. I am assuming this version will run on Azure PaaS.

**Comment by tugberkugurlu** [comment]
@clca Thanks Claudio! I'm really happy that this is a continuous project. Making this available via WebPI will definitely make things easier in terms of Azure. Looking forward to it!

**Comment by oliverjanik** [comment]
+1 

"It won't be a long wait" and 11 months passed... :-D

**Comment by tugberkugurlu** [comment]
@olivierbloch yes :)

**Comment by jepickett** [comment]
The Azure team has forked our project. They will be handling support for WebPI in Azure. See: https://github.com/WindowsAzure/redis
