### ISSUE TITLE
WinXP:  hiredis.dll + sample 

### ISSUE THREAD

**Issue by 1day** [microsoftarchive/redis#164]
Hello

I tried to compile hiredis.dll + sample (https://github.com/MSOpenTech/redis/blob/2.8/deps/hiredis/examples/example.c) for WinXP x86  

Сompilation has completed successfully
Run on Win7: OK
Run on WinXP: error on redisConnectWithTimeout(hostname, port, timeout);
I found out that the reason for error here:
net.c -> if ((res = poll(wfd, 1, msec)) == -1) 
errno == 22

Do you have any ideas what is the reason? Is WinXP supported ??

**Comment by jepickett** [comment]
We are not supporting XP as a matter of policy. It seems likely that there are APIs that we are using that will not work on XP.
