### ISSUE TITLE
2.8.14

### ISSUE THREAD

**Issue by holidaycottages** [microsoftarchive/redis#165]
Hello,

When will you guys be updating to version 2.8.14?

https://groups.google.com/forum/#!msg/redis-db/b4re7Dz6xds/6aiIa8mN_zcJ

**Comment by jepickett** [comment]
I am working on it. Since there are significant changes in the networking code between 2.8.12 and 2.8.14 I suspect we will not have an official release for a few weeks.

**Comment by jepickett** [comment]
I just checked 2.8.14 in.
