### ISSUE TITLE
Binary distribution: An MSI installer as well as through the web platform

### ISSUE THREAD

**Issue by atrauzzi** [microsoftarchive/redis#168]
I'm looking to install a redis server on my PC, but can't seem to find a reliable method by which to obtain a binary distribution.

Ideally I'd either obtain an MSI that sets it up as a service and places configuration files in a sane location.  Alternatively, the web platform installer could be used to do the same.

What I don't want is to have to compile the code myself.

**Comment by jepickett** [comment]
In bin\Release there is a zip file containing the latest binaries and documentation. Our deployment model is xcopy. Please check the RedisService.docx file in the zip file for the command line arguments for installing Redis as a service.

**Comment by atrauzzi** [comment]
That's nice, but you can see why this approach is less convenient than packaging an installer that simply performs those steps for users according to conventions.

This is why I mention the web platform installer.  You're up against debian's packaging system in terms of "ease of use" here.

Consider that the bar.

**Comment by jepickett** [comment]
We use Chocolatey (https://chocolatey.org/) as our equivalent of apt-get. I think it will be possible to install Redis as a service with this mechanism in an upcoming release.

WebPI does not seem to have the facility of running binary code on install. It looks to be an xcopy deployment mechanism. I am still researching ways around this.

If the Chocolatey mechanism would work for you, is an MSI still desired? In what scenarios would an MSI work better for you?

**Comment by atrauzzi** [comment]
An officially maintained chocolatey package would be great. The most important thing is that after installation, the server is running with a default config, again, similar to apt-get.

**Comment by jepickett** [comment]
redis-64 is the official MSOpenTech package. It is currently at 2.8.12 and does not have the service install option. We are likely to release 2.8.17 soon. I will see if we can add the service install before then.

**Comment by atrauzzi** [comment]
That would be fantastic.  Default behaviours really instill confidence and allow people to get up and running very quickly, and configure "later as necessary". :)

**Comment by orangemocha** [comment]
Just added an MSI installer that installs Redis as a service, in [release 2.8.19.1](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.19.1)
