### ISSUE TITLE
Missing app.config file

### ISSUE THREAD

**Issue by wiig-with-a-k** [microsoftarchive/redis#169]
Just tried to build the solution in VS 2013 x64 release mode and I get compiler error saying the app.config is missing.

![image](https://cloud.githubusercontent.com/assets/1792167/4347625/41c7e53e-4160-11e4-86d3-ce9031525c50.png)

**Comment by jepickett** [comment]
fixed in commit 96898fa51cdb9f5fd9fd468be512ed20b09779e8
