### ISSUE TITLE
Please release downloadable binaries

### ISSUE THREAD

**Issue by ferventcoder** [microsoftarchive/redis#17]
Folks should not be required to build the solution just to use the goodness of Redis. Where the binaries go is not of my concern, just that they are the official ones with a version attached to them and that they are publicly available. :)

**Comment by ferventcoder** [comment]
Some discussion over here: https://github.com/MSOpenTech/redis/issues/14 (Issue #14)

**Comment by clca** [comment]
The binaries are already included under the msvs\bin directory. We will go with a more formal release model (with signed binaries and so on) soon when we think the code is approaching the quality bar that we consider to be suitable for production. Bear with us for a little longer, we will provide a better solution for the ready to use/no need to compile scenario.

**Comment by ferventcoder** [comment]
grats!

**Comment by HenryRawas** [comment]
Binaries were updated with a few fixes.

**Comment by clca** [comment]
now we include signed binaries (release) as well. Closing this issue for now.
