### ISSUE TITLE
Suggestion: Child Process log messages could be added to main log file

### ISSUE THREAD

**Issue by Psigio** [microsoftarchive/redis#173]
Whilst diagnosing problems reported in https://github.com/MSOpenTech/redis/issues/171 we noticed that log messages from the Redis child process launched during RDB saves are not saved to the main redis log (instead they are sent directly to stdout).  On server machines this can make diagnosis of issues more difficult as it requires checking log files in two locations (if stdout has been redirected).

If possible, could the log outputs of the child process be sent to the main log file?

**Comment by orangemocha** [comment]
Fixed in https://github.com/MSOpenTech/redis/commit/7827f41357081105c4bf5adf50344333a98cb318
