### ISSUE TITLE
Redis client @ disabled

### ISSUE THREAD

**Issue by brianlagerman** [microsoftarchive/redis#180]
The @ character is not accepted in the redis-cli Editor.  This seems to work fine the original Linux Redis Client.

I mistakenly created an issue over there;
https://github.com/antirez/redis/issues/2070

**Comment by brianlagerman** [comment]
OK, so it appears that this does have something to do with the keyboard layout.  When I use the onscreen keyboard and switch over to US or UK, the redis-cli begins accepting missing characters (I found the pipe character isn't accepted either).

**Comment by rohahn** [comment]
The same problem occurred with my german keyboard. I fixed the bug and created a pull request.

**Comment by orangemocha** [comment]
Thank you, fixed in https://github.com/MSOpenTech/redis/commit/b167e972d2ff6b5978ac59ec15db1c7444b95c52
