### ISSUE TITLE
documentation is in docx format... are there .txt or .md versions?

### ISSUE THREAD

**Issue by Pomax** [microsoftarchive/redis#182]
I need redis on a windows machine because a project uses it as a dependency, but don't have Visual studio or Office or the like. I haven't had a use for an office suite for over 5 years now and don't even have open/star/libreOffice, so I have nothing to open .docx with. Are there minimal markup equivalents somewhere to read instead, like .md files that I can load up simply by hitting the doc link on github.com on your repo?

**Comment by jepickett** [comment]
.docx files should open on a double chick on any supported version of Windows(Vista+).  The files in the binary distributions are taken from src\msvs\setups\documentation. You should be able to select the file and select 'raw view' to see the contents from GitHub. It works on my iPad.

**Comment by Pomax** [comment]
they definitely don't on windows 7. The smallest thing that will open them is MS's 25mb standalone document viewer, with then needs another 38mb to update its supported formats to office 2007 and above .docx format =(

I also don't see that dir on github? There's a plain `msvs\setups\documentation` dir (not inside `src`) but that just contains the .docx themselves, and don't render if clicked on github.com for me. It just downloads the .docx instead.

**Comment by jepickett** [comment]
Fixed in commit 47406f9591b503763290ac856e35a54a74bc053e. I am maintaining the .docx files as the source format. Pandoc (if present) is used to convert the .docx files to .md at compile time

**Comment by Pomax** [comment]
very cool, thanks a lot!
