### ISSUE TITLE
Assertion fails 'ret == DICT_OK' is not true on Redis 2.8.14

### ISSUE THREAD

**Issue by Psigio** [microsoftarchive/redis#184]
Hi,

We've seen an issue on Redis 2.8.14 on Windows Server 2008 R2 where an instance appeared to shutdown without any log lines and then failed to start repeatedly with the following messages:

```
[12184] 23 Oct 16:48:52.220 # Server started, Redis version 2.8.14
[12184] 23 Oct 16:48:55.859 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[12184] 23 Oct 16:48:55.859 # === ASSERTION FAILED ===
[12184] 23 Oct 16:48:55.859 # ==> ..\src\rdb.c:987 'ret == DICT_OK' is not true
```

After which the server shuts down and the next attempt to start raises the same error and fails.

Is our RDB corrupted due to a bad shut down perhaps?

**Comment by Psigio** [comment]
We saw an earlier assertion fail about 4 hours before this issue (see https://github.com/MSOpenTech/redis/issues/185) - not sure if this might be related (although after the earlier assertion Redis restarted ok and worked)

**Comment by Psigio** [comment]
We've done some more investigation, copying the dump file to a desktop machine and running Redis there crashes in the same way.  After seeing a similar looking issue on antirez/redis (https://github.com/antirez/redis/issues/1679) we tried runing redis-check-dump.exe on the rdb file but it appears to be ok:

```
.\redis-check-dump.exe .\dump.rdb
==== Processed 4562313 valid opcodes (in 844455664 bytes) ======================
```

**Comment by Psigio** [comment]
We done some debugging of this issue now - stepping through in the debugger we determined:
- The RDB load failed because a particular Hash has two identical keys.
- We think that the issue mentioned in https://github.com/MSOpenTech/redis/issues/185 (which appears to be during execution of HGETALL) may indicate the same "two identical keys" problem in the hash during a retrieval operation:

(Error from https://github.com/MSOpenTech/redis/issues/185)

```
[9664] 23 Oct 14:21:05.710 * Background saving terminated with success
[9664] 23 Oct 14:22:06.066 * 10000 changes in 60 seconds. Saving...
[9664] 23 Oct 14:24:03.563 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[9664] 23 Oct 14:24:03.563 # === ASSERTION FAILED ===
[9664] 23 Oct 14:24:03.563 # ==> ..\src\t_hash.c:743 'count == length' is not true
```
- Therefore, is it possible that a Hash operation (HMSET/HSET) is able to result in a duplicate key being added to a Hash in a particular situation?  This will then cause failure on the next HGETALL call to this Hash, or if Redis is shutdown & restarted it will then cause failure when attempting to restore the RDB file as this duplicate key is written out to disk.

This is a bit of an unpleasant situation as the RDB is then no longer usable (although the check-dump application didn't detect this particular problem).  We found that by commenting out the Assert statement in rdb.c and allowing the file to restore and then forcing a BGSAVE that the RDB was repaired, but this is not ideal as we are not sure about the state of the duplicated key within the Hash.

We did a very quick test to confirm that HMSET handles duplicate keys as expected and it appears to work (note we set "a" twice)

```
127.0.0.1:6379> hmset testkey a 1 b 2 a 3 c 4
OK
127.0.0.1:6379> hgetall testkey
1) "a"
2) "3"
3) "b"
4) "2"
5) "c"
6) "4"
```

Do you know if there is a bug condition during execution of HSET or HMSET that might result in duplicate keys being entered?

**Comment by jepickett** [comment]
I don't know of any specific bug that would result in a duplicate. I am trying to be as faithful to the Posix version of the code as I can be, including duplicating any existing buggy behavior. I will keep my eye out for this problem. Without a reproduction scenario there is not much I can do at this point.

**Comment by Psigio** [comment]
No worries, it's only happened once so seems a bit of a one-off.  We too have visually compared the code in the hash files against the antirez/redis code and could see that it was identical, so thought it unlikely to be a MSOT-build specific issue.  If we see it again and find a way of reproducing it we'll create a new ticket with the details.
