### ISSUE TITLE
Assertion Fails 'count == length' is not true on Redis 2.8.14

### ISSUE THREAD

**Issue by Psigio** [microsoftarchive/redis#185]
Hi,

We've seen the following assertion failure on Redis 2.8.14 on Windows Server 2008 R2

```
[9664] 23 Oct 14:21:05.710 * Background saving terminated with success
[9664] 23 Oct 14:22:06.066 * 10000 changes in 60 seconds. Saving...
[9664] 23 Oct 14:24:03.563 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[9664] 23 Oct 14:24:03.563 # === ASSERTION FAILED ===
[9664] 23 Oct 14:24:03.563 # ==> ..\src\t_hash.c:743 'count == length' is not true
```

Redis then was restarted after this and seemed to be ok.  However, about four hours later it got stuck in a different assertion failure (see https://github.com/MSOpenTech/redis/issues/184) - not sure if this is related?

**Comment by jepickett** [comment]
You seem to be having a bunch of strange issues on your machine that no one else is reporting. Have you tried a clean OS install? What else is running on that machine?

**Comment by Psigio** [comment]
We're increasingly thinking the same (see #190); that there is something unusual about this particular machine. I'll speak to our environment team to find out if we can get any specific details about the box.

The machine is a Virtual Machine, it is running Redis,  a .net service that populates Redis and also an IIS 7 instance serving some asp.net based web-services which reads from Redis.  Other than that, there are a few enterprise management type tools (virus scanner, inventory audit, update compliance etc) that's pretty much it.  Sadly we don't currently have a clean install machine to put Redis on, so we can't test to see if it's better there.

I'll update the ticket with any more specific VM parameters once we hear back from the other team.

**Comment by jepickett** [comment]
Have you been able to test this on a clean machine?

**Comment by Psigio** [comment]
Hi,

Unfortunately we don't have any other machine to test on at the moment.  We did get a little information from our environments team yesterday about the VM - it's apparently a pretty standard VMWare setup, sharing a physical machine with approximately 25 other VM images.

There was a suggestion that maybe the storage appliance used by the machine may have a particularly high latency and it's possible that writes to the Redis memory-mapped-file (MMF) aren't persisted quickly.  Not really sure if this might be the reason behind our issue; I'm no VM expert, but I wonder if because the MMF is written to intensively it might be possible for our VM image to be "swapped-in" and the file is not quite in the state it should be and then we get the assertion bugs.

We do have the option of a lower-latency storage appliance on our VMs (we have two production boxes), so we have migrated one of the VM's to use this last night.  We'll keep an eye on the log files for the next couple of days to see if it works any better.

**Comment by Psigio** [comment]
Unfortunately it seems like the lower-latency storage option made no difference:

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1564] 13 Nov 12:47:18.427 # === ASSERTION FAILED OBJECT CONTEXT ===
[1564] 13 Nov 12:47:18.427 # Object type: 0
[1564] 13 Nov 12:47:18.427 # Object encoding: 11
[1564] 13 Nov 12:47:18.427 # Object refcount: 2045
[1564] 13 Nov 12:47:18.427 # === ASSERTION FAILED ===
[1564] 13 Nov 12:47:18.427 # ==> ..\src\rdb.c:332 'obj->encoding == REDIS_ENCODING_RAW' is not true
```

Checking the source code, I think that "Object encoding" would only ever be a value up to 8, so the fact that it's 11 looks like a probable corruption issue.

We are going to try downgrading to Redis 2.6.12 (and updating our Lua scripts to not call 2.8 features) as this doesn't use the MMF to see if that helps.

**Comment by Psigio** [comment]
We've been running 2.6.12 for over a week now and it doesn't seem to exhibit any of the same behaviours that we've seen with the 2.8 branch.  Still not sure why the MMF would be a problem on our VMs, but I think we're going to have to stick with 2.6 for now.

**Comment by orangemocha** [comment]
@Psigio are you still experiencing this issue? And have you tried one of the more recent releases https://github.com/MSOpenTech/redis/releases ?

**Comment by Psigio** [comment]
Hi @orangemocha,

Unfortunately we have remained on v2.6.12 since the end of November and as it's working flawlessly there's little appetite to change back to any of the v2.8 builds, so unfortunately we're not able to test the newer versions.  It's particularly difficult to reproduce as the issues only seemed to occur on "prod" servers, so we can't really experiment with a newer build!

I'll close the ticket (sorry, probably should have remembered to do that earlier!) but at least there is a record of the issue if it crops up again for anyone else.
