### ISSUE TITLE
redis-benchmark.exe on windows doesn;t report ms numbers accurately 

### ISSUE THREAD

**Issue by deepakverma** [microsoftarchive/redis#187]
Redis-benchmark on windows seems to be not able to calculate the time granularity in micro seconds. 
Came across this article http://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx and updated the benchmark for latency measurements accordingly.
Pull request: https://github.com/MSOpenTech/redis/pull/186

Windows:
Following is output from windows for micro seconds taken for each request. Where for any request taking less than 1 ms is being calculated as 0
redis-benchmark.exe -h dfredisperf53gbstd.cache.icbbvt.windows-int.net -a WZeFtgz9jHxvWvUrgtxtelFBP1NJT8zBh3lrez8KT/c= -c 1 -d 1024 -t get -n 10
0,0,0,0,0,0,0,0

Linux:
src/redis-benchmark -h dfredisperf53gbstd.cache.icbbvt.windows-int.net -a WZeFtgz9jHxvWvUrgtxtelFBP1NJT8zBh3lrez8KT/c= -c 1 -d 1024 -t get -n 10
792,800,808,820,837,845,888,891,971,2498

After the change on windows now it shows following:
796,809,887,890,893,943,944,974

**Comment by jepickett** [comment]
Merged the pull request. Modified the include guard around the code from WIN32_IOCP to _WIN32. Updated the binaries. It looks like timing performance is more consistent run-to-run.

**Comment by deepakverma** [comment]
Thanks Jonathan.
