### ISSUE TITLE
Investigate redis-benchmark timing APIs on Windows

### ISSUE THREAD

**Issue by jepickett** [microsoftarchive/redis#188]
In issue 186, some calls to gettimeofday() were replaced with a call to QueryPerformanceCounter(), but not all of them. gettimeofday() is implemented with GetSystemTimeAsFileTime(). If this function is implemented with GetSystemTimePreciseAsFileTime(), are the calls to QueryPerformanceTimer necessary? How would this impact timing performance? Would it be better to rework all of redis-benchmark code to use the high performance timer, or some other timing mechanism like the multimedia timer?

**Comment by orangemocha** [comment]
Addressed in https://github.com/MSOpenTech/redis/commit/08e4226e596d35d3d0f3f094b4a9dd94e6f9ba99
