### ISSUE TITLE
RedisWatcher Windows Server 2003 support

### ISSUE THREAD

**Issue by roryf** [microsoftarchive/redis#19]
I'm trying to run RedisWatcher on a Windows Server 2003 box and keep getting the error:

```
The procedure entry point EventRegister could not be located in the dynamic link library ADVAPI32.dll
```

From looking at the MSDN documentation, it suggests this function was introduced in Windows Server 2008.

Should Windows Server 2003 be support with the current release? Will it be considered for the future?

**Comment by clca** [comment]
Our initial thought was to support Win2008+. We haven't spent any time testing even redis on Win2003 so there may be some hidden bugs there as well.

**Comment by roryf** [comment]
Thanks @clca. This wasn't a feature request, just curious if it had been considered and thought it would be helpful to others to have it documented. We have a migration plan to Win2008 anyway, so not a big deal IMO.

**Comment by clca** [comment]
Cool, if it is not a must-have I prefer to focus on getting Redis to run great on Win2008+ versions.
