### ISSUE TITLE
INFO command returns redis_version=2.4.6

### ISSUE THREAD

**Issue by Alex-Boo** [microsoftarchive/redis#191]
I'm a bit confused with Redis versions.
I downloaded Redis-64 2.8.17 on my computer through  nuget. 
I run redis-server.exe but when I tried SET command with NX option in redis-cli.exe I got error about wrong count of arguments. INFO command returns redis_version: 2.4.6 that as I understand doesn't support NX-option.
What is the real version of Windows fork of Redis?  

![image](https://cloud.githubusercontent.com/assets/9656679/4976514/f5263ab0-690e-11e4-9277-d718aca93e6e.png)

**Comment by jepickett** [comment]
Are you sure that you are starting the right version of Redis? Could you have an older version in your path? In powershell, 'Get-Process redis-server | Select path' will tell you where the running image is coming from. INFO is showing me 2.8.17 on my machine.

**Comment by Alex-Boo** [comment]
Thank you a lot, you was absolute right. I'm stupid.
There was old version on my computer. Looks like they both used the same port 6379.
