### ISSUE TITLE
cannot link hiredis into a dll because of main/redis_main jiggery-pokery

### ISSUE THREAD

**Issue by gaz-amoldeshpande** [microsoftarchive/redis#194]
I had to put a fake main() in my DLL that links to hiredis. Otherwise you get unresolved externals for functions that are called from the main in QForkImpl

While this is not a big deal, it should at least be documented.

If I may suggest a better way to do this:

create two files ,   winredismain.c and winredisdllmain.c   which implement custom entry points that can call the dll/maincrtstartup to invoke the normal entry point.
Applications can then include these files and use the "-entry" linker switch to invoke these custom entry points.

Thanks!

**Comment by enricogior** [comment]
From now on for hiredis and hiredis issues please visit https://github.com/Microsoft/hiredis.
Thank you.
