### ISSUE TITLE
Redis - can't [BG]SAVE after one failure

### ISSUE THREAD

**Issue by talbarda** [microsoftarchive/redis#196]
I have a message in the Redis log saying

BeginForkOperation: system error caught. error code=0x00000000, message=Forked process did not respond in a timely mannager.: unknown error Can't save in background: fork: Invalid argument

This message appeared in the log more than a week ago, and since then, each time I'm trying to run "BGSAVE" or "SAVE", it throws the "err background save already in progress" error..

I can't see another redis-server process except the main process in the task manager, nor in "client list" command.

Any ideas how to tell the Redis there's no background save process and force it to save the data into the disk, before it crashes?

**Comment by jepickett** [comment]
I believe it is "CONFIG SET stop-writes-on-bgsave-error no", and then retry the BGSAVE operation. The default policy is for failed BGSAVEs to halt persistence and warn about it, so that the admin can do something about what is likely low disk space.

**Comment by talbarda** [comment]
I think you're right..

Best,
Tal
