### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by mycall** [microsoftarchive/redis#2]
I thought I followed your directions correctly, but upon compiling, I received 10 errors.  Any ideas?

Error   4   error LNK2005: __initp_misc_invarg already defined in LIBCMTD.lib(invarg.obj)   C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   5   error LNK2005: __call_reportfault already defined in LIBCMTD.lib(invarg.obj)    C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   6   error LNK2005: __set_invalid_parameter_handler already defined in LIBCMTD.lib(invarg.obj)   C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   7   error LNK2005: __get_invalid_parameter_handler already defined in LIBCMTD.lib(invarg.obj)   C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   8   error LNK2005: __invoke_watson already defined in LIBCMTD.lib(invarg.obj)   C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   9   error LNK2005: "void __cdecl _invoke_watson(unsigned short const *,unsigned short const *,unsigned short const *,unsigned int,unsigned int)" (?_invoke_watson@@YAXPBG00II@Z) already defined in LIBCMTD.lib(invarg.obj) C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   10  error LNK2005: __invalid_parameter already defined in LIBCMTD.lib(invarg.obj)   C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   11  error LNK2005: "void __cdecl _invalid_parameter(unsigned short const *,unsigned short const *,unsigned short const *,unsigned int,unsigned int)" (?_invalid_parameter@@YAXPBG00II@Z) already defined in LIBCMTD.lib(invarg.obj) C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   12  error LNK2005: ___pInvalidArgHandler already defined in LIBCMTD.lib(invarg.obj) C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\LIBCMT.lib(invarg.obj)    RedisServer
Error   14  error LNK1169: one or more multiply defined symbols found   C:\dev\redis\Microsoft-Interop-redis-34c3eb3\msvs\Debug\redis-server.exe    1   1   RedisServer

**Comment by igorzi** [comment]
@mycall it looks like there's a mismatch between debug and release CRT.  Make sure that both pthreads-win32 and redis projects are compiled with either "Multi-threaded (/MT)" or "Multi-threaded debug (/MTd)" Runtime Library options.

**Comment by bitcrazed** [comment]
I was falling over this issue too until I noted the following industruction in the readme:

```
Under C-C++/Code Generation, change Runtime Library choice to **Multi-threaded (/MT)**
```

I had my project set to use "Multi-Threaded **DLL**" - once I changed it to "Multi-Threaded" Redis built without issue.

**Comment by clca** [comment]
this should be fixed.
