### ISSUE TITLE
redis-benchmark throwing socket error 10022

### ISSUE THREAD

**Issue by eyalpost** [microsoftarchive/redis#20]
Running redis-benchmark.exe on Windows 8 almost always fails after PING test complete. Output:
====== PING_INLINE ======
  10000 requests completed in 0.07 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

68.85% <= 1 milliseconds
100.00% <= 1 milliseconds
135135.14 requests per second

Could not connect to Redis at 127.0.0.1:6379: setsockopt(TCP_NODELAY): 10022

about once every 5 times it will continue after the PING test but will still fail later:
====== LPOP ======
  10000 requests completed in 0.07 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

68.32% <= 1 milliseconds
100.00% <= 1 milliseconds
140845.08 requests per second

Could not connect to Redis at 127.0.0.1:6379: setsockopt(TCP_NODELAY): 10022

**Comment by jiangzhuo** [comment]
I have the same response on windows7. redis built in vs2012

**Comment by clca** [comment]
We are investigating this issue

**Comment by HenryRawas** [comment]
Fix posted
