### ISSUE TITLE
redis windows error

### ISSUE THREAD

**Issue by omerdn1** [microsoftarchive/redis#200]
C:\Users\Omer\Desktop\layer1\redis>redis-server.exe redis.windows.conf
[6188] 07 Jan 15:47:20.416 #
The Windows version of Redis allocates a memory mapped heap for sharing with
the forked process used for persistence operations. In order to share this
memory, Windows allocates from the system paging file a portion equal to the
size of the Redis heap. **At this time there is insufficient contiguous free
space available in the system paging file for this operation (Windows error
0x5AF)**. To work around this you may either increase the size of the system
paging file, or decrease the size of the Redis heap with the --maxheap flag.
Sometimes a reboot will defragment the system paging file sufficiently for
this operation to complete successfully.

Please see the documentation included with the binary distributions for more
details on the --maxheap flag.

Redis can not continue. Exiting.

C:\Users\Omer\Desktop\layer1\redis>

**How do I increase the size?**

**Comment by orangemocha** [comment]
Open Control Panel -> System and Security -> System. Click on the link on the left "Advanced System Settings". Alternatively you can also type "Advanced System Settings" from the start menu.

In the dialog, under "Performance" click on "Setting":
![image](https://cloud.githubusercontent.com/assets/1625870/5650890/6d274ef8-9670-11e4-9a47-bacee7e15c59.png)

In there, go to the "Advanced" tab, and under "Virtual Memory" click on "Change":
![image](https://cloud.githubusercontent.com/assets/1625870/5650904/9b38fc38-9670-11e4-88ba-1f06c86fc439.png)

There you can choose a custom size for your paging files.

**Comment by orangemocha** [comment]
Also, note that the paging file is used in a very dynamic way by the OS, and often if you try restarting redis right away it will work (at least it does on my machine). I will investigate if there are any ways to make this more robust.

**Comment by orangemocha** [comment]
We added documentation about memory configuration in the redis.windows.conf file and the wiki : https://github.com/MSOpenTech/redis/wiki/Memory-Configuration#system-paging-file-size-requirements
