### ISSUE TITLE
Unable to run Redis Service in Sentinel mode

### ISSUE THREAD

**Issue by saluce65** [microsoftarchive/redis#201]
I'm attempting to run Redis in Sentinel mode as a Windows service.  Currently, for testing purposes, I am running 3 Redis servers on my local machine on ports 6379, 6380, and 6381.  On initial setup, 80 and 81 are slaved to 79.

My sentinel.conf configuration file looks like:

```
port 26379
dir "C:\\Code\\tmp"
sentinel monitor mymaster 127.0.0.1 6379 1
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 30000
```

When I run the Redis server in sentinel mode at the command line, everything works beautifully.

```
redis-server sentinel.conf --sentinel
```

I'm installing the server as a service using:

```
redis-server --service-install --service-name "Redis Sentinel" sentinel.conf --sentinel
```

The service installs, grants permissions, does everything it needs to.  But, when I attempt to start the service, I get:

```
Windows could not start the redis sentinel service on Local Computer.

Error 1067: The process terminated unexpectedly.
```

Looking into the event logs, I see in the Application logs with a source "redis":

```
syslog-ident = redis
Creating Server TCP listening socket *:26379: bind: No such file or directory
```

Now, whenever I attempt to install Redis in sentinel mode without specifying the service name, it seems to work.  So, there's something going on with the service naming that isn't being propagated to the creation of a listening socket.

**Comment by orangemocha** [comment]
@saluce65 I suspect you are hitting https://github.com/MSOpenTech/redis/issues/181

This has been fixed in recent releases, though they haven't been published to nuget/chocolatey yet. Could you try https://github.com/MSOpenTech/redis/releases/tag/win-2.8.17.3 ? You'll have to download the .zip file and extract the binaries.

**Comment by saluce65** [comment]
That works, thanks!

**Comment by jesuissur** [comment]
Thanks.
What about the nuget packages?  In particular the 64 bits : https://www.nuget.org/packages/Redis-64/

Phil
