### ISSUE TITLE
Update redis.windows.conf to be closer to current redis.conf

### ISSUE THREAD

**Issue by laurencee** [microsoftarchive/redis#204]
The redis.windows.conf under msvs/setups/documentation hasn't been updated for quite a while and is need of some love.

I think the major differences are 
- Diskless replication settings may need to be left out or at least commented out until implemented for the windows version 
- The windows conf needs to retain the heap configuration settings.

**Comment by orangemocha** [comment]
Fixed in https://github.com/MSOpenTech/redis/commit/c3f758c92334c2689b219b03ae5dfb932874ad09 which is included in https://github.com/MSOpenTech/redis/releases/tag/win-2.8.19-rc1
