### ISSUE TITLE
Switching maxmemory from higher to lower value causes startup failure

### ISSUE THREAD

**Issue by evillanueva045** [microsoftarchive/redis#209]
If you initially set the maxmemory to a value, let the cache populate, and then reduce the maxmemory value, when Redis attempts to start back up you encounter a VirtualAlloc/COWAlloc fail! error

**Comment by orangemocha** [comment]
Hi @evillanueva045 , 

On Windows there is another important related configuration setting, **maxheap**, which specifies the size of the memory mapped file used to implement Redis' fork operations. 

While allocations past maxmemory cause keys to be evicted (according to maxmemory-policy), allocations past maxheap will result in a hard out-of-memory error and a server abort. 

The default value for maxheap is 1.5 \* maxmemory. I suspect that once redis starts up the second time around with a smaller maxmemory, maxheap is calculated as 1.5 time this smaller value, but this is insufficient to load the original data set. I would recommend trying to set maxheap explicitly, and when you lower maxmemory, provide a value of maxheap that is large enough to hold the dataset. I'd experiment around new_max_heap = (1.2 \* previous_max_memory, 1.5 \* new_max_memory). The part to experiment about is the 1.2 factor.

Also, you might want to use https://github.com/MSOpenTech/redis/releases/tag/win-2.8.17.4. It contains a fix for a bug that might also result in VirtualAlloc/COWAlloc fail! error

**Comment by orangemocha** [comment]
Closing this issue, as I assume it has been addressed. If you are still having problems, let me know!
