### ISSUE TITLE
Assertion while reading redis.conf with UTF-8 bottom signature

### ISSUE THREAD

**Issue by JCKodel** [microsoftarchive/redis#21]
On sds.c, line 485:

```
while(1) {
    /* skip blanks */
    while(*p && isspace(*p)) p++; <-------- This line fails with an assert when redis.conf has a UTF-8 bottom signure
    if (*p) {
        /* get a token */
```

**Comment by clca** [comment]
Thanks for reporting this issue. We hit the same while working on the 64bit version. the fix will be submitted tomorrow.

**Comment by HenryRawas** [comment]
Actually this is not a bug we found. I have been trying to find out what you mean by 'UTF-8 bottom signature'. Is this a BOM, or is it something else? Can you post an example for us to test with?

**Comment by JCKodel** [comment]
Sorry... It is BOM =)

As I use brazilian portuguese Windows OS (ISO-8859-1), Visual Studio saves some files as UTF-8 with a signature (ef bb bf) at first 3-bytes of text files.

That signature is throwing the assert.

**Comment by HenryRawas** [comment]
Fix posted
