### ISSUE TITLE
redisci bug

### ISSUE THREAD

**Issue by yjjy2021** [microsoftarchive/redis#211]
hi

I do not speak English well.

redis client bug report.
ex - 1)
set key 1
dump key

client crash.

ex - 2)
setbit t1 0 1
setbit t2 0 1
bitop or res t1 t2
get res

client crash.

redis-cli.c
line 406
    case REDIS_REPLY_STRING:
        /\* If you are producing output for the standard output we want
        \* a more interesting output with quoted characters and so forth */
        out = sdscatrepr(out,r->str,r->len);
error this

**Comment by yjjy2021** [comment]
redis version redis-2.8

**Comment by orangemocha** [comment]
Fixed in https://github.com/MSOpenTech/redis/commit/fe6fff14d16a810bcddf45c3a301e646ca990687 which is included in https://github.com/MSOpenTech/redis/releases/tag/win-2.8.19-rc1
