### ISSUE TITLE
master/slave and persistence-available no.

### ISSUE THREAD

**Issue by SergeyZubatkin** [microsoftarchive/redis#212]
Hello!
I am using latest Redis port for Windows (Redis-64.2.8.17) and master/slave mechanism does not work with option persistence-available no.
I think in case of master/slave is incompatible with persistence-available no --service-start ot install should throw error..

For now I have a lot of errors in master/slave logs:
[9828] 21 Jan 11:48:48.007 # Can't save in background: fork: Invalid argument
[9828] 21 Jan 11:48:49.010 # BeginForkOperation: system error caught. error code=0x000001e7, message=BeginForkOperation: VirtualProtect failed: unknown error

Master.conf
port 6379
timeout 0
tcp-keepalive 0
loglevel warning
logfile "masterlog.txt"
databases 16
slave-serve-stale-data yes
slave-read-only no
repl-disable-tcp-nodelay no
persistence-available no
slave-priority 100
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10

Slave.conf
port 6380
timeout 0
tcp-keepalive 0
loglevel warning
logfile "slavelog.txt"
databases 16
slave-serve-stale-data yes
slave-read-only no
repl-disable-tcp-nodelay no
persistence-available no
slave-priority 100
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
slaveof <id> 6379

**Comment by orangemocha** [comment]
Thank you for reporting this issue. As you guessed master/slave replication relies on persistence to be enabled on the master. It would certainly be desirable to have a more descriptive error message. 

However, I am not sure it makes sense to throw an error on startup. A master/slave configuration is only established when a slave connects, and that's when it would seem more sensible to emit the error.

**Comment by enricogior** [comment]
This is now working on recent releases.
