### ISSUE TITLE
master and base configs include order

### ISSUE THREAD

**Issue by felickz** [microsoftarchive/redis#215]
[master.conf](https://github.com/MSOpenTech/redis/blob/2.8/msvs/Samples/MasterSlaveSentinelConf/master.conf)

```
port 6379
dbfilename master.rdb
maxheap 1GB
include base.conf
```

[base.conf](https://github.com/MSOpenTech/redis/blob/2.8/msvs/Samples/MasterSlaveSentinelConf/base.conf)

```
...
maxheap 50M
...
```

With this setup, maxheap ultimately gets configured as 50M.  

IF you truly wanted a "BASE" configuration, and "MASTER" was overriding base... wouldn't you want master.conf to include base first, then override the settings specific to master?

```
include base.conf
port 6379
dbfilename master.rdb
maxheap 1GB
```

Comments from latest [redis 2.8 redis.config](https://raw.githubusercontent.com/antirez/redis/2.8/redis.conf) (not ported to windows yet?) seem to outline this:

```
################################## INCLUDES ###################################
# Include one or more other config files here.  This is useful if you
# have a standard template that goes to all Redis servers but also need
# to customize a few per-server settings.  Include files can include
# other files, so use this wisely.
#
# Notice option "include" won't be rewritten by command "CONFIG REWRITE"
# from admin or Redis Sentinel. Since Redis always uses the last processed
# line as value of a configuration directive, you'd better put includes
# at the beginning of this file to avoid overwriting config change at runtime.
#
# If instead you are interested in using includes to override configuration
# options, it is better to use include as the last line.
#
# include /path/to/local.conf
# include /path/to/other.conf
```

**Comment by enricogior** [comment]
Hi @felickz,
I finally had time to test this issue with the latest release and it works as expected (same as Redis on Linux).
