### ISSUE TITLE
redis qfork file being created in incorrect directory despite permissions and settings in configuration file.

### ISSUE THREAD

**Issue by jimmymain** [microsoftarchive/redis#218]
The QFork file is being created in the network service directory.
C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Redis

The configuration file in c:\redis\ contains a directory entry.

```
# The Append Only File and the QFork memory mapped file will also be created 
# inside this directory.
# 
# Note that you must specify a directory here, not a file name.
dir c:\redis\
```

The directory has permissions set for NETWORK SERVICE as full control.
If I specify a log file in the configuration it is created in the correct c:\redis\ directory, so the service has permission to create files in the specified directory.

**Comment by orangemocha** [comment]
You can specify the location of the QFork file with the heapdir configuration entry (not dir). The documentation you quoted from redis.windows.conf is incorrect. 

I'll use this issue to track the documentation bug. Thanks!

**Comment by jimmymain** [comment]
Hi,
Perfect, thanks!

**Comment by orangemocha** [comment]
Fixed in https://github.com/MSOpenTech/redis/commit/b02a6d191d1774bee807cb197f4074f7be0aba08
which is included in https://github.com/MSOpenTech/redis/releases/tag/win-2.8.19-rc1
