### ISSUE TITLE
Port Redis 2.6

### ISSUE THREAD

**Issue by feklee** [microsoftarchive/redis#23]
Please port Redis 2.6 to Windows. Redis 2.6 contains critical new features, such as LUA scripting for transactions.

**Comment by clca** [comment]
We are trying to figure out what it takes to get 2.6 on Windows. The main issue is LUA, anyway I'll update this thread as soon as I have a good estimate for what it takes to align with the 2.6 release on Linux

**Comment by mei-rune** [comment]
I really want this feature, how is your progress

**Comment by clca** [comment]
Closing the 64bit for 2.4, we will push the code soon. After that 100% on 2.6. We will also use our public repo for all development so it will be easier to follow what is happening.

**Comment by trippleflux** [comment]
any news?

**Comment by clca** [comment]
Yes, making very good progress now that the 2.4 64bit is out. Fixing some issues with the code we just released and then we will get the 2.6 (pre-alpha) code on the repo.
Stay tuned :)

**Comment by clca** [comment]
We released the first version of 2.6 today, still alpha but pretty close to be a usable build for testing Redis 2.6 on Windows
