### ISSUE TITLE
beginforkoperation: virtual protect failed unkown error

### ISSUE THREAD

**Issue by MarkusMayer** [microsoftarchive/redis#232]
I am using the current binary 2.8.19 on Windows 7 Enterprise SP1. Redis is running as a service.
After using the server for a while I noticed the following error in the log.

beginforkoperation: virtual protect failed unkown error

When looking at my clients log I get exceptions on lpush commands with no apparent pattern. After some failed attemps the server continues to work normally. 

I tried to increase the swap file (15-50 GB) and to set:
maxheap to 2g
maxmemory 1g

The occasional errors are still there. Any ideas what might be the problem?

**Comment by orangemocha** [comment]
Thanks for reporting this issue. After that message in the log, there should be a warning along the lines of:

```
BeginForkOperation: system error caught. error code=
```

...with the actual error code returned by VirtualProtect. That error code might give us a better idea of what's causing this issue.

**Comment by MarkusMayer** [comment]
@orangemocha 
Hi sorry for taking so long to reply. I have been trying to reproduce the behaviour for the last couple of days without any success. Before reporting it I saw the described beahviour a couple of times on 3 days. I am pretty sure however that there wasn't any additional info in the log it just said unkown error.

If I succeed in reproducing I 'll open another issue.
