### ISSUE TITLE
Redis Fork question

### ISSUE THREAD

**Issue by Bhaal22** [microsoftarchive/redis#233]
Hi,

First thank you very much for your work to port Redis on windows.

I have a question regarding the RedisQFork.dat file.

My machine memory has 32G Ram running a 64bits version of Redis
Each time Redis dump database on disk, it takes about 1.2s to dump.

I tested on various configurations of size of memory :
 1G : 20ms
 2G : 50ms
 4G : 110ms
 16G: 350ms
 32G: 1.1sec

It seems to be an exponential time process.
I have not been able to to test on 64G or 128G

I got many execution timeout, so I had to update my connection string with a higher timeout.

I would like to know if you could maybe explain this behavior please ?
And I would like to know how are sized your machines on Windows Azure ?

Thank you,

John.

**Comment by Bhaal22** [comment]
Thank you for your investigation.
Pleas ele tme know if you need further information.

John

**Comment by orangemocha** [comment]
Hi @Bhaal22 ,
Thank you for reporting this issue.
How did you measure those times?
It should be noted that the progression of memory sizes you listed is exponential, so the progression of times is linear with the memory size.

It doesn't surprise me that writing a 32GB file could take 1 second. But if Redis was actually unavailable for that long, that would be concerning. I will investigate that part more closely to try and replicate your findings, and if that's the case, try to optimize performance.

Regarding the size of Azure machines, assuming you mean the Azure Redis Cache, you can see the configuration options on the pricing page: http://azure.microsoft.com/en-us/pricing/details/cache/

**Comment by Bhaal22** [comment]
Hi @orangemocha 

I am not quite sure this is exponential.
I measured looking at Redis logs with Time to Dump

In fact the default command timeout for StackExchange library is 1 sec. On the machine with 32GB of RAM, I had plenty of command timeout. So I guess Redis is not available during this time.

I increased StackExchange command timeout, and no more timeouts.

**Comment by Bhaal22** [comment]
Any news regarding this particular issue ?

**Comment by enricogior** [comment]
Hi @Bhaal22,
as part of the 3.0 release, we are revising the fork architecture in order to improve the performance of the database dump to disk and to make sure the redis server is available during that process.
It's still work in early stage so we don't have yet performance number to compare with the data you reported.
Thank you again for your feedback.

**Comment by Bhaal22** [comment]
Thank you for your prompt reply.
Would be glad to test it. Is it redis-3.0-winport branch ?

**Comment by enricogior** [comment]
@Bhaal22
yes, the branch is https://github.com/MSOpenTech/redis/tree/3.0-winport, I will post on https://github.com/MSOpenTech/redis/issues/231 to notify when a first testable build will be available.
Thanks for you support :)

**Comment by Bhaal22** [comment]
Super !

Thank you for your work.

**Comment by enricogior** [comment]
@Bhaal22 
in case you are interested, I pushed a single fix for the problem you were experiencing to this branch:
https://github.com/MSOpenTech/redis/tree/2.8-no-child-wait
It's not the full fork fix we will do in 3.0, this is just an optimization to make sure the server doesn't stop responding to the clients while a dump to disk is occurring.
We are not releasing this fix as a full release, so currently you need to build the binaries yourself, in case tomorrow I can share a MSI if you need it.

**Comment by Bhaal22** [comment]
Hi enrico

Thank you Very much 
No need of msi i will compile It 

I will Tell you m'y feedback early next week

**Comment by enricogior** [comment]
Hi @Bhaal22,
the official release that contains the same fix I sent you before is now available.

The new 2.8.2101 release is available [here](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101).
This is an incremental release from 2.8.21 containing only fixes for Windows-specific bugs.  

Note: we don't have yet a date for the availability of the new release through the nuget/chocolatey package managers.
