### ISSUE TITLE
Does this project have a future?

### ISSUE THREAD

**Issue by jarz** [microsoftarchive/redis#234]
Now that @MSOpenTech is ~~being assimilated by the Borg~~ rejoining Microsoft proper, will this project be maintained by Microsoft?

**Comment by orangemocha** [comment]
Please refer to https://github.com/MSOpenTech/redis/issues/231#issuecomment-95292883

**Comment by matthiasg** [comment]
@jarz what exactly does this mean ? i was under the impression msopentech was always microsoft proper as you put it
