### ISSUE TITLE
Redis 2.8.19 BGREWRITEAOF - Failure Permission Denied

### ISSUE THREAD

**Issue by chrisd88** [microsoftarchive/redis#235]
Hi,

We currently have a Redis 2.8.19 on Win 2012 STD.

The box has 256GB Mem and the DB is eating around 187GB

Due to the DB using so much memory we have opted to use AOF to store the data rather than the rdb file due to the memory requirements of doing BGSAVE on the Windows version of Redis.

Each night we run 'BGREWRITEAOF' to regenerate the aof file so its more efficient if it has to reload the dataset.

This morning the process failed in the error logs we see
"EndForkOperation: 0x00000005 - EndForkOperation: Killing forked process failed.: permission denied"

This is a bit of a mystery the new aof file has been generated but still showing the temp file name, the original aof file is still in place. Now the new aof file looks the correct size (~43GB) like its been fully generated.

I'm under the assumption that when the aof file is generated, redis tries to delete the old aof file then renames the new aof file to the correct file name. Again I'm assuming the delete option failed but I could be wrong.

I thought this might have been related to the AV software however the entire drive holding the redis data is excluded from both real-time and manual scanning (the drive holds nothing other than redis)

What doesn't make sense is why the failure killed the entire redis-server process. The idea of the BGREWRITEAOF process is that if it fails the redis-server process should not die. So in our case we had to wait 2.5hrs for the server to re-load the dataset.

Unfortunately the permission denied error doesn't explain what it couldn't do.

**Comment by orangemocha** [comment]
Thank you for reporting this issue. Two pieces of information would be helpful in determining the cause:
1) The redis log file. Could you upload it somewhere and share a link?
2) Information from Windows Error Reporting. In the Event Viewer, under Application, look for events with source "Windows Error Reporting" around the time of the crash.

**Comment by chrisd88** [comment]
Hi,

The redis event log can be grabbed from http://chrisdaley.net/redislog.zip I don't think its going to be much help to be honest

Nothing in the Application or System logs, all we get is "The Redis service terminated unexpectedly."

We had the service set to automatic recovery, 5min delay between restart however this has highlighted another weird problem. Sometimes when it loads the data into memory the logical drive where the AOF and Heap files are stored goes into meltdown essentially file browsing access in explorer is next to impossible, redis slows to a crawl when loading the data etc. Only way to recover is to manually kill the process in task manager (doesn't always kill it though). Nothing wrong with the drives, new batch of 8x Intel DC S3700 SSD's, Raid 6 array on a Dell PERC H720P Controller. 

From a normal boot you get 1-2 days where Redis works and the 'BGREWRITEAOF' process functions correctly. Then on the next day it will fail and usually loading the dataset will go badly (as described above). Reboot the box and it will function correctly for another 1-2 days.

Totally removed the AV software however the problem persists so I don't believe that is the cause.

**Comment by chrisd88** [comment]
We have managed to get a bit further with identifying the cause, redis doesn't like it when MSSQL is installed on the same box it appears. We setup a clean box just W2012R2 with Redis installed it ran 100% stable for 7 days straight, BGREWRITEAOF worked perfectly each day.

Installed SQL Server 2014 Web x64, first rewrite worked which was 24hrs after install, the second failed in the same way as it did on the original W2012 server.

Based on the logs and the source code its failing somewhere in the cleanup routine, I have added some additional logging to see if we can identify which stage it fails at.

**Comment by orangemocha** [comment]
Interesting. It's possible that SQL Server and Redis are competing for memory resources. What are your memory configuration options in SQL Server? https://msdn.microsoft.com/en-us/library/ms178067.aspx

If you have the option of running them on separate machine, I would recommend that as a workaround. 

To ensure that crash dumps are collected, please go to Control Panel\System and Security\Action Center\Problem Reporting Settings and make sure that "Automatically check for solutions and send additional report data, if needed".

I would normally recommend to also enable full memory dumps. But in your case, since Redis is using so much RAM, this might not be practcal.

> As the ultimate troubleshooting aid, you could also enable collection of full-memory dumps.The instructions are here: https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx . You can configure it for redis-server.exe only (the article explains how to do so).

**Comment by enricogior** [comment]
We have found a possible cause for this random bug, we'll release a fix asap.

**Comment by enricogior** [comment]
Hi @chrisd88,
we fixed some issues that may have caused the problem you reported.
Please upgrade to 2.8.2101.
Thank you.

The new 2.8.2101 release is available [here](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101).
This is an incremental release from 2.8.21 containing only fixes for Windows-specific bugs.  

Note: we don't have yet a date for the availability of the new release through the nuget/chocolatey package managers.
