### ISSUE TITLE
Run Redis as a Windows Service

### ISSUE THREAD

**Issue by caxelrud** [microsoftarchive/redis#24]
The project at https://github.com/kcherenkov/redis-windows-service presents a solution to run Redis as a Windows Service. 
Did you try and recommend this solution?

**Comment by eyalpost** [comment]
MSOpenTech/Redis also contains a windows service called RedisWatcher. Working fine for me.

**Comment by artiee** [comment]
I didn't get the RedisWatcher to work but I use NSSM instead.

**Comment by clca** [comment]
I'm closing this issue, feel free to re-open the bug if it is still an issue.
