### ISSUE TITLE
2.8.19.1 crashed on Windows 2012 R2

### ISSUE THREAD

**Issue by gerryhigh** [microsoftarchive/redis#240]
I've had this running for about 5 days on a production box and today it crashed for the first time.  It is running as a service and I don't see anything that was logged.

A crash was generated in \ProgramData...\WER... - memory.hdmp and triagedump.dmp in there, along with a few other files but not much else.  I've also looked in event log (this runs as a windows service) and although there is a redis log section there is nothing in it.

Any ideas on how to debug what happened?  If I can't figure this out I'm going to have to stop using REDIS on Windows.

**Comment by orangemocha** [comment]
Hi @gerryhigh. In the event viewer look under Windows Logs \ Application for events with source "Application Error" or "Windows Error Reporting". Those events should contain information that will help us investigate the failure. Can you copy & paste it in here?

If you can't find this information, you could also share those .hdmp and .dmp files.

**Comment by gerryhigh** [comment]
1 entry for Application Error, then 12 seconds later 2 entries for Windows Error Reporting at the same time, both appear to be identical.

Application Error, Event ID 1000, Task Category (100)
Faulting application name: redis-server.exe, version: 0.0.0.0, time stamp: 0x5547a2d5
Faulting module name: redis-server.exe, version: 0.0.0.0, time stamp: 0x5547a2d5
Exception code: 0xc0000005
Fault offset: 0x000000000006f750
Faulting process id: 0x7a4
Faulting application start time: 0x01d08894edae23ce
Faulting application path: C:\redis\redis-server.exe
Faulting module path: C:\redis\redis-server.exe
Report Id: 594e8705-f66e-11e4-80bf-00155d004203
Faulting package full name: 
Faulting package-relative application ID: 

# 

# Windows Error Reporting, Event ID 1001, Task Category None

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: redis-server.exe
P2: 0.0.0.0
P3: 5547a2d5
P4: redis-server.exe
P5: 0.0.0.0
P6: 5547a2d5
P7: c0000005
P8: 000000000006f750
P9: 
P10: 

Attached files:
C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\WERD0A6.tmp.appcompat.txt
C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\WERD1B1.tmp.WERInternalMetadata.xml
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_1c1d4eab3bead2a645d34d274984cbfa0742457_0627ca68_cab_4346d1af\memory.hdmp
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_1c1d4eab3bead2a645d34d274984cbfa0742457_0627ca68_cab_4346d1af\triagedump.dmp
WERGenerationLog.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_1c1d4eab3bead2a645d34d274984cbfa0742457_0627ca68_cab_4346d1af

Analysis symbol: 
Rechecking for solution: 0
Report Id: 594e8705-f66e-11e4-80bf-00155d004203
Report Status: 0
Hashed bucket:

**Comment by orangemocha** [comment]
This is most likely due to a memory corruption issue, which we have fixed in [2.8.21](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.21). Please upgrade and let us know if you are still having problems. Thanks!
