### ISSUE TITLE
MSI FatalError

### ISSUE THREAD

**Issue by guiomie** [microsoftarchive/redis#245]
Hi all,

I tried to run the 2.8.19.1 MSI (found at https://github.com/MSOpenTech/redis/releases) on a windows server 2008 enterprise, Build 6002. I've ran the msi in verbose and saw the following errors.
If I run the installer without checking "Add an exception to the Windows Firewall", the msi will install properly.

Info 2898. For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
DEBUG: Error 2858:  The data for the bitmap Bitmap is not valid
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2858. The arguments are: Bitmap, , 
...
MSI (s) (0C:F4) [16:45:32:241]: The call to SRSetRestorePoint API failed. Returned status: 0. GetLastError() returned: 127
...
SchedSecureObjectsRollback:  Failed to store ACL rollback information with error 0x80070002 - continuing
...
ExecFirewallExceptions:  Error 0x800706d9: failed trying to find existing app
ExecFirewallExceptions:  Error 0x800706d9: failed to add/update application exception for name 'Redis', file 'C:\Program Files\Redis\redis-server.exe'
...
MSI (c) (78:FC) [16:45:33:255]: Doing action: FatalError
Action 16:45:33: FatalError. 
Action start 16:45:33: FatalError.
DEBUG: Error 2858:  The data for the bitmap Bitmap is not valid
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2858. The arguments are: Bitmap, , 
Action 16:45:33: FatalError. Dialog created
Action ended 16:45:35: FatalError. Return value 2.

**Comment by guiomie** [comment]
Alright, the firewall service must run on the computer, otherwise it can't add the exception.

The wizard message is pretty generic and doesn't explain the root cause of the issue.

There is attribute IgnoreFailure | YesNoType for the element FirewallException, the exception would be silently ignored, not sure if this would be a good solution.

**Comment by orangemocha** [comment]
Thanks for reporting this issue, @guiomie !

Ideally the exception configuration would be added even if the firewall service is not running, though I am not sure if that's possible. Short of that, the option to add the exception should be disabled. And a better error should be given if this condition is encountered.

**Comment by guiomie** [comment]
Perhaps I build a wix custom action in c# that would verify if the windows firewall service is installed and running. If it is not running, we would halt the installation and tell the user to uncheck the option ... ?

**Comment by orangemocha** [comment]
I think a good solution would be to structure the firewall exception as a separate feature, then have a custom action run early to detect if the service is not running, and if so make the feature unavailable. Not sure how complicated that would be. If you would like to investigate that further, that would be great, but if not, a simple patch to set IgnoreFailure to yes would also be ok. Thanks!

By the way, is there a good reason for the firewall service being disabled in your deployment? You can turn the firewall off, but disabling the firewall service is not recommended. https://technet.microsoft.com/en-us/library/cc766337(v=ws.10).aspx

**Comment by NickMRamirez** [comment]
I can also take a stab at this. Let me know if you already have a custom action to detect the firewall. Is it to detect if it's disabled? 

Either I or someone else could add something like:

< Condition Action="disable" >
  <![CDATA[FIREWALL_ENABLED <> 1]]>
< /Condition >

inside of the checkbox Control. Also, maybe some text that shows up next to it with a message about why it's disabled. There's a Hidden attribute on the Control element. I will submit a pull request. But if you already have code for the custom action lemme know.

**Comment by guiomie** [comment]
I haven't built a custom action. My team bundled the redis executable with the project installer, so this problem won't affect our operations team. 

I still plan on contributing, but I haven't  built any custom action ever in wix before, so if this is something that would take you 1 hour to do, then go ahead, otherwise I'll take a stab at it in 7-10 days when I've got more time.

**Comment by orangemocha** [comment]
@NickMRamirez , no code yet here either, so thank you! 

Please note that the firewall is not simply disabled. This issue occurs only when the firewall service is not running.

**Comment by NickMRamirez** [comment]
Yeah, looks like it fails if the service is stopped. Setting the state of the firewall to off, via the Firewall with Advanced Security console, doesn't cause the error for me. In that case, the rule is still registered correctly.

**Comment by enricogior** [comment]
Hi @NickMRamirez, thanks for having taken the time to fix the problem, we have included your pull request into the upcoming 2.8.21 release.

**Comment by orangemocha** [comment]
Fixed in 2.8.21 https://github.com/MSOpenTech/redis/releases/tag/win-2.8.21
