### ISSUE TITLE
redis 2.8.19 - maxheap should not be set without maxmemory (AFAICT), conf description of maxheap should state that, ideally code would enforce it, or at least exception message would recommend it

### ISSUE THREAD

**Issue by jamesmanning** [microsoftarchive/redis#246]
I helped debug a situation where our redis-server.exe was crashing even though there was plenty of free memory on the machine.  The conf file had maxheap set to 500mb but had nothing set for maxmemory.

I understand that maxheap is primarily a mechanism for the control of the shared memory-mapped file for the emulation of copy-on-write, and on this particular machine, there was a low amount of disk space (a little under 4GB) so 500mb was chosen for maxheap to help limit the disk space impact of the server (RDB on with the default settings from redis.windows.conf, AOF off).

What we saw is that when total memory usage started getting near the maxheap size, we'd end up with a OOM that crashed the server

![image](https://cloud.githubusercontent.com/assets/225626/7867733/cd07cd9a-0545-11e5-94ce-cdee01babb1e.png)

Based on the comments of the maxheap setting in redis.windows.conf, it sounds like that if a maxheap is set, it should both 1) force a maxmemory value to also be set and 2) force the maxmemory value to be something under maxheap. Based on the 1.5 \* maxmemory default if maxmemory is set and maxheap if unset or is set to below 1.5 \* maxmeory, then likely maxmemory should be set to 2/3 of maxheap if maxheap is set and maxmemory isn't or it's set to a value over 2/3 of maxheap.

When maxmemory gets hit, redis acts as it does in the original *nix version where the writes fail, but read-only operations still work fine.  The server stays up, most importantly, and clients can just wait / retry / whatever as desired as they do if dealing with the original version.

If maxmemory isn't going to be forced to be set or defaulted to a value if unset, then IMHO at least the scenario where the alloc fails because we're getting close to maxheap should (if at all possible) state something in the message to help guide the user towards setting maxmemory.

Also worth noting that in the scenario of the server crashing in this situation, the event log entry doesn't help much since you get an Access Violation exception code but not much else to go on AFAICT

```
Faulting application name: redis-server.exe, version: 0.0.0.0, time stamp: 0x54edbbf6
Faulting module name: redis-server.exe, version: 0.0.0.0, time stamp: 0x54edbbf6
Exception code: 0xc0000005
Fault offset: 0x000000000008575b
Faulting process id: 0x197c
Faulting application start time: 0x01d096e9f225e363
Faulting application path: C:\Redis\redis-server.exe
Faulting module path: C:\Redis\redis-server.exe
Report Id: 622ce581-04ef-11e5-b622-005056980c7f
```

**Comment by nmehlei** [comment]
Might be related to https://github.com/MSOpenTech/redis/issues/244 , the exception code is identical to my last Windows Error Reporting output and I also set maxmemory.

**Comment by orangemocha** [comment]
Thanks for your detailed report, @jamesmanning .

I am not sure that setting maxmemory would be correct. Setting maxmemory modifies the behavior of Redis, so that when maxmemory is reached it either evicts keys or stops accepting writes. Evicting keys would be an unwanted side effect. No longer accepting writes transfers the failure condition from the server to the client. The best course of action is probably to improve the documentation, and let admins decide if to set maxmemory or not.

Regarding the logging, right now Redis should be writing some errors to the log file (though not the event log). See the example below.

```
[1992] 01 Jun 15:54:17.291 # Out Of Memory allocating 18446744073709551615 bytes
!
[1992] 01 Jun 15:54:17.291 #

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1992] 01 Jun 15:54:17.291 # ------------------------------------------------
[1992] 01 Jun 15:54:17.291 # !!! Software Failure. Press left mouse button to co
ntinue
[1992] 01 Jun 15:54:17.291 # Guru Meditation: "Redis aborting for OUT OF MEMORY"
 #..\src\redis.c:3466
[1992] 01 Jun 15:54:17.291 # ------------------------------------------------
```

**Comment by jamesmanning** [comment]
@orangemocha sounds good, as long as the docs around maxheap in the example conf files make it clear that if you set maxheap and not maxmemory, you're going to get a server crash if your memory usage starts getting close to maxheap.

Seems like it'd be better to have that failure scenario act more like maxmemory getting hit instead (disallow write or evict things with expire set), but as long as the conf and docs steer people away from the "maxheap set, maxmemory not" situation which leads to a crash, that's definitely an improvement. :smile:

**Comment by orangemocha** [comment]
We have documented the relationship between maxheap and maxmemory [in the wiki](https://github.com/MSOpenTech/redis/wiki/Memory-Configuration), and also in redis.windows.conf in [release 2.8.21](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.21).
