### ISSUE TITLE
log level in redis

### ISSUE THREAD

**Issue by baywet** [microsoftarchive/redis#249]
Hi,
We currently have a lot of entries in application logs (in message like that every 5 seconds).
syslog-ident = redis
0 clients connected (0 slaves), 4309592 bytes in use

We tried to switch the log verbosity (from the .conf file) to warning (it was on notice). We restarted the service but it didn't have any effect.
Any idea how we could reduce logs verbosity?
(running on windows server 2012 RTM)
Thanks for your help!

**Comment by enricogior** [comment]
@baywet: make sure that in the config file there is only one entry that sets the loglevel. Also make sure the configuration file is correctly passed as input argument to redis-server.exe.
To verify that the loglevel is set correctly, run redis-cli.exe and execute 'get config loglevel', it should return:
127.0.0.1:6379> config get loglevel
1) "loglevel"
2) "warning"

In case you still run into the issue, please run redis-cli.exe, execute 'config get *' and attach the output.

**Comment by baywet** [comment]
thanks @enricogior I didn't know we could do that. I got "verbose" doing that. So I issued the command set loglevel warning and got ok. will that persist or go away when the service reboots?

**Comment by enricogior** [comment]
@baywet, good question :)
I did a quick test and verified that the config values set from the client are not persisted, therefore they will go away if the service reboots.
In the comments of the official redis documentation page Pieter Noordhuis confirms it: http://redis.io/commands/config-set

**Comment by baywet** [comment]
@enricogior thanks for the information, edited the conf file again, rebooted the service, it seems to be working fine now.
