### ISSUE TITLE
Error during installing RedisWatcher - .\Users is not a valid user or group

### ISSUE THREAD

**Issue by kmmbvnr** [microsoftarchive/redis#25]
I'm using localized version of windows and i've got following error

An error occurred whilte applying security settings .\Users is not a valid user or group

I'd run `net localgroup /add Users` and group was created, but this didn't help.

**Comment by kmmbvnr** [comment]
It could be fixed by replacing permission settings to `<Permission GenericAll="yes" User="Everyone" />`

User Everyone exists on any windows installation, not depends on localization.

**Comment by HenryRawas** [comment]
Updated permission settings and rediswatcher binaries to fix this.
