### ISSUE TITLE
MSOpenTech Redis and Sentinel

### ISSUE THREAD

**Issue by sergydimitrov** [microsoftarchive/redis#250]
First of all let me clarify couple of things.

You are implementing a cache framework, utilizing the Linux version that is a definite complete catastrophic failiure study.

Current version you are publishing 2.8.19 has no high availablity framework!! 
It is a fact that prior version 2.8.12 Sentinel you can install and run. The upper versions you can not setup a sentinel. 

MSOpentech Redis is a major disaster. Let say you are implementing a high availability schenario you got Windows Server 2012 R2 systems, redis service just crashes with high availability slaves.

When we analyze the dumps we are seeing access violation exceptions while deallocating a pointer that is dereferenced already. It is very crucial that this software is very very poor QUALITY!!!

Math the symbols on the release build have a pdb to map the dump, we are seeing that freeMemoryIfNeeded method (redis.c) is getting called to dispose volatile memory locations.

This is something we can not utilize on production! It is a crashing poorly coded software.
Azure is not utilizing msopen tech redis. No one should.

Sentinel and High Availability Redis framework is NOT STABLE!!

**Comment by orangemocha** [comment]
Hello @sergydimitrov. 

> Current version you are publishing 2.8.19 has no high availablity framework!! 
> It is a fact that prior version 2.8.12 Sentinel you can install and run. The upper versions you can not setup a sentinel.

You can certainly setup a sentinel in 2.8.19. Can you please be more specific about the issues you are encountering? In order for us to investigate a specific issue, we would need to know your memory configuration, and redis configuration, and symptoms of the issue including any error messages in the Redis log and Windows event log.

**Comment by sergydimitrov** [comment]
Hello @orangemocha 

I think you are making a joke, I am not sure but can you please get the Redis 2.8.19 release package and install sentinel on Windows Server 2012 or 2012 R2. You can not start the service, you can not get any dump out of it. No event and Redis logs. 

However we are not seeing this error on 2.8.12 branch. Sentinel works fine.
This software is a joke itself. We can not rely on the stability.

**Comment by janpieterz** [comment]
@sergydimitrov  Not affiliated with MSOpenTech in any way, but saw this pop up.
I've got redis running in sentinel mode on a Windows 2012 R2 datacenter edition.
I think to be able to get this issue solved, providing @orangemocha with more details about your specific setup would help solving it a lot! 

Let's not forget that nobody forced MSOpenTech to start developing this and that their efforts should from my point of view be applauded, even though it might not always be exactly at the point where the official Redis is. These guys are working hard to make this software better, helping them along with accurate bug information will only make the product better!

**Comment by mehdyh** [comment]
I'm currently have it running in production on win28k x64, 
It crashes multiple times a day and I make it work with restart on windows service fail and retry 
on client side .
Why someone want to use redis on windows while it's unstable?
because aspnet_stateserver uses 2 gigabytes of memory and 247 threads
while Redis on windows do it with 8 megabytes of memory and 7 threads under the same workload.

**Comment by enricogior** [comment]
@sergydimitrov
I've just tested the 2.8.19 release on a clean Windows 2012 R2 machine and I was able to run redis-server in sentinel mode as a Windows service: the log file content was ok and the redis-cli was receiving the expected answer when querying the sentinel.
Can you please provide some more details regarding your server configuration? 
It would help if you can provide the sentinel.conf file you are using.
Thank you.

**Comment by sergydimitrov** [comment]
I will provide @orangemocha and @enricogior with redis and sentinel configuration. It is not that important to start sentinel on 2.8.19, There is definetely a bug introduced with 2.8.19. 

Please have a look at @mehdymohajery comments. He is comparing me the actual redis and the MSOpenTech redis by overruling the instability with the number of threads. Honestly I am only laughing at him.

Similar to him I am seeing the ultimate multiple crashes in a day. I also make it work through auto restarts and have client retry. But guys hey this is not the way we should go. I mean you can NOT use this software on production.

Their efforts will NOT be applauded. Because they are clearly stating that final stable version on their Redis Dashboard. I am seeing nothing stable. As one of my collegue agreed to me.
I will definetely help them to improve the software to make it much better as I am seeing their access violation exceptions through the crash dumps. But hey you can NOT state a fact on your dashboard that
MSOpen Tech 2.8.19 is production stable.

**Comment by cosmosgenius** [comment]
@sergydimitrov where have they mentioned its production stable?

**Comment by sergydimitrov** [comment]
On the main page of MSOpen Tech Redis.
The crash issue is directly related to the zmalloc of redisclient structure (networking.c)

We are seeing random crashes based on being unable to allocate the redisclient structure.
redisClient *createClient(int fd) {
    redisClient *c = zmalloc(sizeof(redisClient));

zmalloc goes all the way to tmalloc_large and getting access_violation exception.

Somehow questioning the stability but perhaps might be an issue related with the redis master and slave and sentinel configurations.

How can we consume all the max number of redisclient space. I am not seeing in the issues list anything related to this incident. 
Unable to allocate redisclient means server crash.

**Comment by sergydimitrov** [comment]
This scenario is not happening when redis is running in single mode, no slaves, no sentinel.
But in the production  ready architecture with a master with two slaves and three sentinels we are seing these crashes every once in a day or two.

Sentinels are configured using the 2.8.12 version. Somehow 2.8.19 version is crashing perhaps something with the configurations.
But still crashes must be related to sentinels based on the fact that every two seconds they are making the connection two master. That generates the ae event and allocates structure of redisclient.

**Comment by sergydimitrov** [comment]
Below is the sentinel configuration we are using and I am not seeing anything wrong with it.

sentinel monitor WIN-M2PCIL8HJUC 127.0.0.1 6379 1
sentinel down-after-milliseconds WIN-M2PCIL8HJUC 10000
sentinel failover-timeout WIN-M2PCIL8HJUC 120000
sentinel parallel-syncs WIN-M2PCIL8HJUC 1

**Comment by sergydimitrov** [comment]
There is an ipv6 issue sometimes sentinel using ıpv6 access, bind parameter might or might not be used I am not sure. But still the allocation of redisclient crashes in networking.c which is very wierd.
redisClient *createClient(int fd) {
redisClient *c = zmalloc(sizeof(redisClient));

System can not tolerate the sentinel connections. We should have used 2.8.19 version of the sentinel instead of 2.8.12 but this may not be the exact issue.

**Comment by enricogior** [comment]
Thanks @sergydimitrov for the information provided.
I'm currently busy finalizing the 2.8.21 release (due this week), after the release I will have time to investigate the issue you reported. I'll let you know as soon as possible.

**Comment by orangemocha** [comment]
@sergydimitrov : could you try [release 2.8.21](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.21) and see if the issues persists? We have a lot of stability fixes there.

**Comment by enricogior** [comment]
Closing the issue since it refers to an old release.
Please reopen the issue if it still applies to 2.8.2104.
Thank you.
