### ISSUE TITLE
MSOpenTech/redis & aof

### ISSUE THREAD

**Issue by MarkoRemes** [microsoftarchive/redis#253]
We are using the port for Windows based on Redis 2.6. (2.6.12) with aof file. Redis is used as temporary message storage and sometimes when the load is heavy and the messages are big the redis crashes with this message:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[10516] 17 Jun 11:59:56.027 # ------------------------------------------------
[10516] 17 Jun 11:59:56.027 # !!! Software Failure. Press left mouse button to continue
[10516] 17 Jun 11:59:56.028 # Guru Meditation: "Unknown list encoding" #..\src\t_list.c:120
[10516] 17 Jun 11:59:56.028 # ------------------------------------------------

I debugged this and the reason is that the method listTypeLength does not support the encoding type REDIS_ENCODING_LINKEDLISTARRAY. This seems to be a
windows specific type. I fixed this like this (new code is the 2nd else branch):

unsigned long listTypeLength(robj subject) {
if (subject->encoding == REDIS_ENCODING_ZIPLIST) {
return ziplistLen(subject->ptr);
}
else if (subject->encoding == REDIS_ENCODING_LINKEDLIST) {
return listLength((list)subject->ptr);
# ifdef _WIN32

}
else if (subject->encoding == REDIS_ENCODING_LINKEDLISTARRAY) {
/\* read only array */
cowListArray *ar = (cowListArray *)subject->ptr;
return (unsigned long)ar->numele;
# endif

} else {
redisPanic("Unknown list encoding");
}
}

Questions:

Is the fix valid. If not what would be?
If this is ok, could you add this to the official releases?

**Comment by enricogior** [comment]
Hi @MarkoRemes,
thank you for reporting the issue. This week we will release the 2.8.21 build that among other fixes has a fix for a problem very similar to the one you reported. Please stay tuned for the release announcement ;)

**Comment by orangemocha** [comment]
[2.8.21](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.21) has been released. Please upgrade and let us know if you are still having problems. Thanks!
