### ISSUE TITLE
Service fails to start

### ISSUE THREAD

**Issue by jkdufair** [microsoftarchive/redis#256]
I installed via the MSI but my service was failing to start. Turns out I needed to set my maxheap to 1gb. I also set my maxmemory to 768mb.

Perhaps the MSI installer could allow for setting these parameters during install? Or even something like "production" vs. "local development" mode?

Thanks to MSOpenTech for the port and continuing support.

**Comment by enricogior** [comment]
Hi @jkdufair, thank you for the feedback.
We are working to improve the documentation and the error reporting for the memory configuration issues and we will consider your suggestion as well.
For now please take a look at the new wiki page that documents the memory configuration requirements for Redis on Windows: https://github.com/MSOpenTech/redis/wiki/Memory-Configuration

**Comment by jkdufair** [comment]
I think the documentation is great. When I tried to start the server from the command line, it was very informative. The comments in the config file were great too.  My main interest is in the "out-of-the-box" experience for those inclined to use the MSI.

Again, thank you.

**Comment by orangemocha** [comment]
We are going to revisit the fork architecture to see if we can reduce the requirements on the system paging file. It will make sense to consider this change after that analysis.

**Comment by jkdufair** [comment]
Great! Thank you!

**Comment by enricogior** [comment]
@jkdufair,
the new [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) contains the fix for this issue.
The MSI now let choose a default value for `maxmemory` and `maxheap`.
If redis-server.exe fails to start, the error message is written to the Event Log.
Thank you.

**Comment by jkdufair** [comment]
Thanks for doing this!
