### ISSUE TITLE
some codes fixes for memory release problems

### ISSUE THREAD

**Issue by zeliard** [microsoftarchive/redis#258]
I found there are memory release problems from a ServiceWorkerThread() function as below:

https://github.com/MSOpenTech/redis/blob/2.8/src/Win32_Interop/Win32_service.cpp#L485-L490

I fixed this in my forked repo: 
e0024845bc130f8096a8c1d7094ba21b5a86c468

But, I couldn't PR to the original repo due to my own conflict problems.
Could you someone check these changes and apply that?

**Comment by enricogior** [comment]
Hi @zeliard, thank you very much for finding and fixing the problem, the fix will be included in the next release.
