### ISSUE TITLE
Accepting client connection: accept: Unknown error

### ISSUE THREAD

**Issue by QQ10Year** [microsoftarchive/redis#259]
OS: window7 X64
version: redis-2.8.17_x64
Redis running after a period of time, an error: “has the client connection: the accept: Unknown error. ”
Client can not connection. After the restart redis, can be connected again

**Comment by enricogior** [comment]
Hi @fglbee,
sorry for the late answer. Can you please provide some more information regarding the issue?
The client used was redis-cli.exe?
Did the problem reproduce again?
Thank you.

**Comment by enricogior** [comment]
The fix will be available in the next release 2.8.2102.

**Comment by enricogior** [comment]
Hi @fglbee,
the bug is now fixed in [v2.8.2102](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2102).
Thank you.
