### ISSUE TITLE
hiredis Visual Studio 2010

### ISSUE THREAD

**Issue by andreae75** [microsoftarchive/redis#261]
Hi, i m addictive regards redis and how i can boost my app with it.

I'm trying to support also some legacy app that use ( for compatibility reason ) old tool-set ( vs_2010 ).

But after some works on it, i give up. Seems that was not designed to compile with older version of visual studio. Or i m wrong ?

Someone have successfully build on it ?

Thanks in advance for any feedback.
\Andrea E./

**Comment by enricogior** [comment]
@andreae75 
thank you for the feedback, please check if the workaround described in the following related issue can help:
https://github.com/MSOpenTech/redis/issues/194

**Comment by andreae75** [comment]
Thanks for reply, but the issue is a linkage problem. I had to fix lot of compilation error ... seems that visual studio 2010 is not compatibly with the given solution.

**Comment by enricogior** [comment]
OK, I'll take a look.

**Comment by andreae75** [comment]
Grazie. Cheers.

----- Messaggio originale -----
Da: "Enrico Giordani" notifications@github.com
Inviato: ‎01/‎07/‎2015 17:47
A: "MSOpenTech/redis" redis@noreply.github.com
Cc: "andreae75" andrea.endrizzi@gmail.com
Oggetto: Re: [redis] hiredis Visual Studio 2010 (#261)

OK, I'll take a look.

**Comment by andreae75** [comment]
I have fixed the problem just avoid to define the getnameinfo redis\src\Win32_Interop\WS2tcpip.h: 

#if (NTDDI_VERSION >= NTDDI_WINXPSP2) || (_WIN32_WINNT >= 0x0502)
WINSOCK_API_LINKAGE
INT
WSAAPI
getnameinfo(
    _In_reads_bytes_(SockaddrLength)         const SOCKADDR \*    pSockaddr,
    _In_                                socklen_t           SockaddrLength,
    _Out_writes_opt_(NodeBufferSize)    PCHAR               pNodeBuffer,
    _In_                                DWORD               NodeBufferSize,
    _Out_writes_opt_(ServiceBufferSize) PCHAR               pServiceBuffer,
    _In_                                DWORD               ServiceBufferSize,
    _In_                                INT                 Flags
    );
#endif

**Comment by enricogior** [comment]
Thanks, good to know.

**Comment by enricogior** [comment]
From now on for hiredis and hiredis issues please visit https://github.com/Microsoft/hiredis.
Thank you.
