### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by sgoky** [microsoftarchive/redis#263]
[1836] 06 Jul 22:46:14.625 - DB 0: 225 keys (225 volatile) in 512 slots HT.
[1836] 06 Jul 22:46:14.625 - 103 clients connected (0 slaves), 12646720 bytes in use
[1836] 06 Jul 22:46:16.606 - Accepted 455f:4865:6c70:5f52:4543:5f47:696f:726e:256
[1836] 06 Jul 22:46:16.606 - Accepted 10.0.120.103:61599
[1836] 06 Jul 22:46:17.807 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1836] 06 Jul 22:46:17.807 # --- EXCEPTION_ACCESS_VIOLATION
[1836] 06 Jul 22:46:17.807 # --- INFO OUTPUT
# Server

redis_version:2.8.21
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e84b20ff4e0813fa
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:winsock_IOCP
process_id:1836
run_id:2c849a084d7539d9a9c466df9bbdb3c932e46219
tcp_port:6379
uptime_in_seconds:274353
uptime_in_days:3
hz:10
lru_clock:10152217
config_file:C:\Redis64\redis.windows.conf
# Clients

connected_clients:105
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:12683536
used_memory_human:12.10M
used_memory_rss:12748280
used_memory_peak:31397384
used_memory_peak_human:29.94M
used_memory_lua:824320
mem_fragmentation_ratio:1.01
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:340
rdb_bgsave_in_progress:0
rdb_last_save_time:1436215494
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1436215495
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:4488
total_commands_processed:1679755
instantaneous_ops_per_sec:14
total_net_input_bytes:2883742178
total_net_output_bytes:0
instantaneous_input_kbps:0.90
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:22965
evicted_keys:0
keyspace_hits:578955
keyspace_misses:96749
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:93601
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:292.42
used_cpu_user:69.98
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=205294,usec=405604,usec_per_call=1.98
cmdstat_setnx:calls=96391,usec=421202,usec_per_call=4.37
cmdstat_setex:calls=5155,usec=15600,usec_per_call=3.03
cmdstat_del:calls=103602,usec=343200,usec_per_call=3.31
cmdstat_exists:calls=27611,usec=124801,usec_per_call=4.52
cmdstat_hget:calls=97959,usec=234001,usec_per_call=2.39
cmdstat_hmset:calls=185332,usec=1809610,usec_per_call=9.76
cmdstat_hdel:calls=3618,usec=0,usec_per_call=0.00
cmdstat_hgetall:calls=92028,usec=6505239,usec_per_call=70.69
cmdstat_expire:calls=280423,usec=296400,usec_per_call=1.06
cmdstat_keys:calls=3,usec=0,usec_per_call=0.00
cmdstat_auth:calls=4488,usec=15600,usec_per_call=3.48
cmdstat_ping:calls=10233,usec=0,usec_per_call=0.00
cmdstat_echo:calls=4487,usec=0,usec_per_call=0.00
cmdstat_info:calls=127232,usec=4992021,usec_per_call=39.24
cmdstat_config:calls=6745,usec=46800,usec_per_call=6.94
cmdstat_subscribe:calls=2239,usec=0,usec_per_call=0.00
cmdstat_unsubscribe:calls=127571,usec=764407,usec_per_call=5.99
cmdstat_client:calls=4487,usec=0,usec_per_call=0.00
cmdstat_eval:calls=183089,usec=29905367,usec_per_call=163.34
cmdstat_evalsha:calls=105439,usec=13634464,usec_per_call=129.31
cmdstat_script:calls=6329,usec=31201,usec_per_call=4.93
# Keyspace

db0:keys=227,expires=227,avg_ttl=1518501
[1836] 06 Jul 22:46:17.807 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @sgoky,
this is a issue currently under investigation, we have a stable repro for it and we are working to fix it.
Thank you.

**Comment by enricogior** [comment]
Hi @sgoky,
we just released the fix for the crash you reported.

The new 2.8.2101 release is available [here](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101).
This is an incremental release from 2.8.21 containing only fixes for Windows-specific bugs.  

Note: we don't have yet a date for the availability of the new release through the nuget/chocolatey package managers.
