### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION on replication

### ISSUE THREAD

**Issue by dsevastianov** [microsoftarchive/redis#264]
This was an attempt to setup slave for Azure Redis. Target instance is about 40 GB. Memory check didn't find anything. Host machine is 112 GB of memory, maxheap is set to 50 GB, heapdir and working dir point to SSD with 700 GB of free space. It keeps failing when restarted.

[3700] 09 Jul 19:53:59.076 \* Full resync from master: c055bed1772a36afcfc1915f6962c4c41000105d:270010147828
[3700] 09 Jul 20:04:35.115 \* MASTER <-> SLAVE sync: receiving 11037471319 bytes from master
[3700] 09 Jul 20:05:52.302 \* MASTER <-> SLAVE sync: Flushing old data
[3700] 09 Jul 20:05:52.302 \* MASTER <-> SLAVE sync: Loading DB in memory
[3700] 09 Jul 20:05:52.318 #

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[3700] 09 Jul 20:05:52.318 # ------------------------------------------------
[3700] 09 Jul 20:05:52.318 # Fatal Error: "Unknown object type" #..\src\rdb.c:1123
[3700] 09 Jul 20:05:52.318 # ------------------------------------------------
[3700] 09 Jul 20:05:52.318 # --- EXCEPTION_ACCESS_VIOLATION
[3700] 09 Jul 20:05:52.318 # --- STACK TRACE
redis-server.exe!((null):0)(0x0013D980, 0x0013FF90, 0x00000001, 0x00000000)
redis-server.exe!((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x00000000, 0x055E1AD0, 0x00000000, 0x0013FF20)
ntdll.dll!memset((null):0)(0x40016BAC, 0x00000000, 0x0013E0C0, 0x4005555F)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x0013DAF0, 0x0013E5B0, 0x0013E5B0)
ntdll.dll!_chkstk((null):0)(0x00000001, 0x07FA0000, 0x00000000, 0x080D309C)
ntdll.dll!RtlRaiseException((null):0)(0x00000000, 0x00000000, 0x000000FB, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x0013E870, 0x40132548, 0x0013DE98, 0x0013E870)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x000000FB, 0x0013E940, 0x00000000, 0x0013E940)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000007)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000001, 0xFEF7DB60, 0xFEE500F0, 0x00000001)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x559ED156, 0xFEF16968, 0x00000002, 0x00227940)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x559ED155, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0xFFFFA000, 0xFFFFA000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x40033D5C, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0x05B213B0, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[3700] 09 Jul 20:05:52.334 # --- INFO OUTPUT
# Server

redis_version:2.8.21
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e84b20ff4e0813fa
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:winsock_IOCP
process_id:3700
run_id:326f229100d4b0f22c7a5c8c25d6f5d999a90ef9
tcp_port:6379
uptime_in_seconds:715
uptime_in_days:0
hz:10
lru_clock:10408992
config_file:C:\ProgramData\chocolatey\lib\redis-64\redis.windows.conf
# Clients

connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:4387824
used_memory_human:4.18M
used_memory_rss:4329560
used_memory_peak:4387824
used_memory_peak_human:4.18M
used_memory_lua:36864
mem_fragmentation_ratio:0.99
mem_allocator:dlmalloc-2.8
# Persistence

loading:1
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1436471637
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
loading_start_time:jd
loading_total_bytes:1436472352
loading_loaded_bytes:11037471319
loading_loaded_perc:0.00
loading_eta_seconds:jd
# Stats

total_connections_received:1
total_commands_processed:23
instantaneous_ops_per_sec:0
total_net_input_bytes:11037471641
total_net_output_bytes:0
instantaneous_input_kbps:147280.50
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
# Replication

role:slave
master_host:prodim.redis.cache.windows.net
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:1
slave_repl_offset:1
master_sync_left_bytes:0
master_sync_last_io_seconds_ago:0
master_link_down_since_seconds:jd
slave_priority:100
slave_read_only:1
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:24.98
used_cpu_user:5.25
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_info:calls=23,usec=2972,usec_per_call=129.22
# Keyspace

db0:keys=77,expires=0,avg_ttl=0
[3700] 09 Jul 20:05:52.365 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @dsevastianov,
Azure Redis Cache is running a porting of Redis 3.0, at the moment I don't know if a mixed 3.0/2.8 configuration is supported. Do you know if Redis for Linux supports such configuration? If the answer is yes it may be a problem specific of the Windows version that will require some investigation.

**Comment by dsevastianov** [comment]
Yes, looks like you're right, it seems to be incompatibility between 3.0 and 2.8, thanks!
