### ISSUE TITLE
Exception Access Violation

### ISSUE THREAD

**Issue by bladefist** [microsoftarchive/redis#266]
Thank you!

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[2924] 12 Jul 17:58:06.436 # --- EXCEPTION_ACCESS_VIOLATION
[2924] 12 Jul 17:58:06.436 # --- STACK TRACE
redis-server.exe!LogStackTrace(d:\redis\msot1\src\win32_interop\win32_stacktrace
.cpp:96)(0x0013ED40, 0x0013FF90, 0x00000001, 0x00000000)
redis-server.exe!UnhandledExceptiontHandler(d:\redis\msot1\src\win32_interop\win
32_stacktrace.cpp:185)(0x00000000, 0x00000000, 0x00000000, 0x4EE16535)
KERNELBASE.dll!UnhandledExceptionFilter(d:\redis\msot1\src\win32_interop\win32_s
tacktrace.cpp:185)(0x00000000, 0x51A1AD74, 0x00000000, 0x00000000)
ntdll.dll!memset(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x40
016BAC, 0x00000000, 0x0013F480, 0x4005555F)
ntdll.dll!_C_specific_handler(d:\redis\msot1\src\win32_interop\win32_stacktrace.
cpp:185)(0x00000000, 0x0013EEB0, 0x0013F970, 0x0013F970)
ntdll.dll!_chkstk(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x0
0000001, 0x51910000, 0x00000000, 0x51A41178)
ntdll.dll!RtlRaiseException(d:\redis\msot1\src\win32_interop\win32_stacktrace.cp
p:185)(0x0035B440, 0x0032F420, 0x09ACAC50, 0x0032CD00)
ntdll.dll!KiUserExceptionDispatcher(d:\redis\msot1\src\win32_interop\win32_stack
trace.cpp:185)(0xFFFFFFFE, 0x00000000, 0x00000001, 0x40059C4F)
redis-server.exe!aeGetSockState(d:\redis\msot1\src\ae_wsiocp.c:80)(0x00000007, 0
x00000007, 0x00000004, 0x00000001)
redis-server.exe!aeApiAddEvent(d:\redis\msot1\src\ae_wsiocp.c:227)(0x09ACAC50, 0
xFEE500F0, 0x00000007, 0x4EE09A9F)
redis-server.exe!createClient(d:\redis\msot1\src\networking.c:71)(0xD690DF55, 0x
00000007, 0x00000000, 0x00000007)
redis-server.exe!acceptCommonHandler(d:\redis\msot1\src\networking.c:554)(0x0000
0007, 0x000003E7, 0x0013FD10, 0x00005C22)
redis-server.exe!acceptTcpHandler(d:\redis\msot1\src\networking.c:600)(0xFEE500B
0, 0x00000001, 0x059E6EC0, 0x00000000)
redis-server.exe!aeMain(d:\redis\msot1\src\ae.c:487)(0x55A2AFAA, 0x55A2AFAA, 0x0
0000000, 0x003285B0)
redis-server.exe!redis_main(d:\redis\msot1\src\redis.c:3524)(0x00000000, 0x00000
000, 0x55A2AFAA, 0x00000000)
redis-server.exe!main(d:\redis\msot1\src\win32_interop\win32_qfork.cpp:1399)(0x0
0000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(
0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x
00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
[2924] 12 Jul 17:58:06.477 # --- INFO OUTPUT
# Server

redis_version:2.8.21
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e84b20ff4e0813fa
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:winsock_IOCP
process_id:2924
run_id:2e72e1b29eccba2628b4a8406750f0ad3893342d
tcp_port:6379
uptime_in_seconds:16713
uptime_in_days:0
hz:10
lru_clock:10678515
config_file:
# Clients

connected_clients:7
client_longest_output_list:0
client_biggest_input_buf:4258
blocked_clients:0
# Memory

used_memory:85526816
used_memory_human:81.56M
used_memory_rss:85397696
used_memory_peak:90435560
used_memory_peak_human:86.25M
used_memory_lua:36864
mem_fragmentation_ratio:1.00
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:63
rdb_bgsave_in_progress:0
rdb_last_save_time:1436741886
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1436741887
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:235
total_commands_processed:42656
instantaneous_ops_per_sec:117
total_net_input_bytes:199625417
total_net_output_bytes:0
instantaneous_input_kbps:508.68
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:5382
evicted_keys:0
keyspace_hits:10687
keyspace_misses:10439
pubsub_channels:2
pubsub_patterns:0
latest_fork_usec:1726165
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:120.33
used_cpu_user:4.14
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=67,usec=254,usec_per_call=3.79
cmdstat_del:calls=94,usec=1062,usec_per_call=11.30
cmdstat_hsetnx:calls=9813,usec=85691,usec_per_call=8.73
cmdstat_hmset:calls=8697,usec=58462,usec_per_call=6.72
cmdstat_hmget:calls=12341,usec=74940,usec_per_call=6.07
cmdstat_hgetall:calls=7,usec=139,usec_per_call=19.86
cmdstat_select:calls=41,usec=170,usec_per_call=4.15
cmdstat_expire:calls=8696,usec=50543,usec_per_call=5.81
cmdstat_keys:calls=19,usec=38352,usec_per_call=2018.53
cmdstat_ping:calls=193,usec=313,usec_per_call=1.62
cmdstat_echo:calls=234,usec=97,usec_per_call=0.41
cmdstat_type:calls=8,usec=44,usec_per_call=5.50
cmdstat_info:calls=911,usec=39791,usec_per_call=43.68
cmdstat_ttl:calls=7,usec=29,usec_per_call=4.14
cmdstat_config:calls=390,usec=4218,usec_per_call=10.82
cmdstat_subscribe:calls=148,usec=570,usec_per_call=3.85
cmdstat_unsubscribe:calls=664,usec=4557,usec_per_call=6.86
cmdstat_publish:calls=92,usec=1218,usec_per_call=13.24
cmdstat_client:calls=234,usec=478,usec_per_call=2.04
# Keyspace

db0:keys=3875,expires=3225,avg_ttl=1249712
[2924] 12 Jul 17:58:06.491 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

```
   Please report this bug by following the instructions at:

 http://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue

Suspect RAM error? Use redis-server --test-memory to verify it.
```

**Comment by enricogior** [comment]
Hi @bladefist,
that crash seems the same crash we have been investigating, the fix is currently under test and we are planning to release it tomorrow.

**Comment by bladefist** [comment]
@enricogior  Thanks for the update. I'll keep an eye out.

**Comment by enricogior** [comment]
Hi @bladefist,
we just released the fix for the crash I mentioned before.  

The new 2.8.2101 release is available [here](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101).
This is an incremental release from 2.8.21 containing only fixes for Windows-specific bugs.  

Note: we don't have yet a date for the availability of the new release through the nuget/chocolatey package managers.

**Comment by bladefist** [comment]
@enricogior Running the new version for a bit now under heavy load, everything working great. Thanks!

**Comment by enricogior** [comment]
@bladefist thank you for the feedback! :)

**Comment by orangemocha** [comment]
Very good to hear :+1:
