### ISSUE TITLE
Service fails silently, insufficient disc space is not logged or reported

### ISSUE THREAD

**Issue by cstuder** [microsoftarchive/redis#267]
After using the MSI setup (2.8.21), the Redis service failed to start on my Windows 7 instance. No error message was shown, no error logged and duplicating the launch command on the CLI did not display any error message, but immediatly returned to the shell:

```
"C:\Program Files\Redis\redis-server.exe" --service-run "C:\Program Files\Redis\redis.windows-service.conf"
```

Only after omitting the additional parameters and calling the binary directly, an error message was displayed, indicating inssufficient disc space:

```
"C:\Program Files\Redis\redis-server.exe"
```

Proposal: Log the disc space allocation failure to the log file. Don't redirect STDERR to... well I don't know where it goes actually.

**Comment by enricogior** [comment]
Hi @cstuder,
thank you for reporting the issue, we'll investigate it.

**Comment by Chaffelson** [comment]
In testing this in Win7x64 with binaries Redis-x64-2.8.2101 I think this is a spurious error.
I attempted variations using maxmemory and maxheap anywhere between 64M and 256M, and installations on both a C: with 20Gb free and a F: with 900Gb free and received identical errors with nothing meaningful logged.
The only edgecase I can think of here is that my dev box has 16Gb ram, and only 20Gb free on the C:, so if it was somehow demanding disk on the OS drive it might fail.

**Comment by enricogior** [comment]
@cstuder, @Chaffleson 
the new [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) contains the fix for this issue.
The MSI now let choose a default value for `maxmemory` and `maxheap`.
If redis-server.exe fails to start, the error message is written to the Event Log.
Thank you.
