### ISSUE TITLE
 EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by kooboo-binbin** [microsoftarchive/redis#269]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[3876] 14 Jul 13:02:45.476 # --- EXCEPTION_ACCESS_VIOLATION
[3876] 14 Jul 13:02:45.476 # --- INFO OUTPUT
# Server

redis_version:2.8.21
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e84b20ff4e0813fa
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:winsock_IOCP
process_id:3876
run_id:d7fad664e746a9d052cda58190617c1d256cb2c0
tcp_port:6379
uptime_in_seconds:900
uptime_in_days:0
hz:10
lru_clock:10815605
config_file:C:\Program Files\Redis\redis.windows-service.conf
# Clients

connected_clients:28
client_longest_output_list:320
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:10635512
used_memory_human:10.14M
used_memory_rss:10732992
used_memory_peak:11026864
used_memory_peak_human:10.52M
used_memory_lua:36864
mem_fragmentation_ratio:1.01
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:6753
rdb_bgsave_in_progress:0
rdb_last_save_time:1436878962
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1436878963
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:62
total_commands_processed:7717
instantaneous_ops_per_sec:157
total_net_input_bytes:7043987
total_net_output_bytes:0
instantaneous_input_kbps:338.91
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:8072
keyspace_misses:14262
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:2332301
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:1.11
used_cpu_user:0.31
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=3344,usec=17079,usec_per_call=5.11
cmdstat_set:calls=1990,usec=14134,usec_per_call=7.10
cmdstat_del:calls=2,usec=15,usec_per_call=7.50
cmdstat_mget:calls=299,usec=11128,usec_per_call=37.22
cmdstat_mset:calls=204,usec=14827,usec_per_call=72.68
cmdstat_select:calls=1,usec=34,usec_per_call=34.00
cmdstat_expireat:calls=1858,usec=10254,usec_per_call=5.52
cmdstat_keys:calls=1,usec=24,usec_per_call=24.00
cmdstat_ping:calls=14,usec=38,usec_per_call=2.71
cmdstat_info:calls=1,usec=146,usec_per_call=146.00
cmdstat_monitor:calls=2,usec=5,usec_per_call=2.50
cmdstat_config:calls=1,usec=82,usec_per_call=82.00
# Keyspace

db0:keys=14181,expires=1203,avg_ttl=86354309
[3876] 14 Jul 13:02:45.476 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by ScottKaiGu** [comment]
i think you can upgrade to v2.8.2101

**Comment by enricogior** [comment]
Hi #kooboo-binbin, 
as ScottKaiGu suggested, yesterday we released v2.8.2101 that has several fixes for Windows-specific bugs.
Thank you.
