### ISSUE TITLE
zadd command does not work for the following in redis 2.8.12

### ISSUE THREAD

**Issue by reddy-sabbella** [microsoftarchive/redis#277]
zadd SELECTION_LOAD_QUEUE 1.438206727564E12 "0:0:1766303:5:SCHED:2013:false:false:1766300:192.168.63.26-Tomcat"

The same command used to work with slightly different values. I got the latest 2.8.21 and it seems to work there. Is there anything specifically fixed to address this? I am afraid it may come back as this command has been working before.

**Comment by enricogior** [comment]
Hi @reddy-sabbella,
since 2.8.12 there has been hundreds of commits, I have no idea if any of those fixed that specific issue.

**Comment by enricogior** [comment]
Closing this issue since it doesn't repro with recent builds.
