### ISSUE TITLE
Cannot Install Redis 2.8 on Windows

### ISSUE THREAD

**Issue by osherdo** [microsoftarchive/redis#278]
When trying to install the version above I get the following error message:

service 'Redis'(Redis) failed to start. verify that you have sufficient proviliges to start system services.

Tried to google the problem but nothing seems to work.

How do I fix this issue?

(I am running windows 7 on VirtualBox)

**Comment by enricogior** [comment]
Hi @osherdo,
thank you for reporting the issue. I'll close this one as a duplicate of #276

**Comment by osherdo** [comment]
@enricogior thanks.
