### ISSUE TITLE
Do you have any plans to change this name of this repo?

### ISSUE THREAD

**Issue by charsyam** [microsoftarchive/redis#28]
I forked redis from antirez/redis.

and I also want to fork this project. but I failed it.

Do you have a plan to change this repo name?

**Comment by HenryRawas** [comment]
What was the failure? Why is the name a problem?

**Comment by charsyam** [comment]
I think MSOpenTech/redis is a forked project of antirez/redis.

so I can't fork this project to my github account.

when I clicked fork button, it just goes to my antirez/redis forked project.

:)

**Comment by clca** [comment]
I just tried and forked the project from MSOpenTech to my private account clca and it worked, what was forked is the MSOpenTech repo so not sure what is going on with your account :(

**Comment by charsyam** [comment]
@clca Did you fork antirez/sredis also?
becuase of this. I just make one more account :)

**Comment by strayer** [comment]
I didn't try this, but I guess this should work:
1. rename your fork of antirez/redis to redis-tmp
2. fork this repo
3. rename your newly forked repo to redis-ms (or whatever)
4. rename redis-tmp back to redis

The name of your fork is completely independent of the name of the original repo, as far as I know.

**Comment by BeatriceOltean** [comment]
There is a solution to this. Closing.
