### ISSUE TITLE
Redis starts a crash loop possibly related to failover.

### ISSUE THREAD

**Issue by ravynz** [microsoftarchive/redis#282]
Related to issue #281, Previously we were using a master slave setup, two machines both with 2.8.2101.  When a failover happened we would somtimes get one of them to enter a crash loop.  It was not always failovers, sometimes it was just a slave reconnecting. This error below would then repeat over and over, with the stack trace adding an extra line of 
redis-server.exe!UnhandledExceptiontHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:198)(0x0244E590, 0x0244E590, 0x0244E590, 0x0244FF90)
every time it repeated until pretty soon we had a 10gB log file  in under a day.

 Here is the crash log:

```
            _._                                                  
       _.-``__ ''-._                                             
  _.-``    `.  `_.  ''-._           Redis 2.8.2101 (00000000/0) 64 bit
```

  .-`.-``.``\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in stand alone mode
 |`-._`-...-` __...-.`-._|'`_.-'|     Port: 6379
 |`-._   `._    /     _.-'    |     PID: 4060
`-._    `-._`-./  _.-'    _.-'  
 |`-._`-._`-.**.-'    _.-'_.-'|  
 |    `-._`-._        _.-'_.-'    |           http://redis.io  
  `-._`-._`-.**.-'_.-'    _.-'  
 |`-._`-._`-.**.-'    _.-'_.-'|  
 |    `-._`-._        _.-'_.-'    |  
  `-._`-._`-.**.-'_.-'    _.-'  
      `-._    `-.__.-'    _.-'                                       
`-._        _.-'  
              `-.__.-'                                               

[4060] 28 Jul 15:00:19.636 # Server started, Redis version 2.8.2101
[4060] 28 Jul 15:00:20.777 \* DB loaded from disk: 1.141 seconds
[4060] 28 Jul 15:00:20.777 \* The server is now ready to accept connections on port 6379
[4060] 28 Jul 15:00:20.777 \* Connecting to MASTER 192.168.50.107:6379
[4060] 28 Jul 15:00:20.777 \* MASTER <-> SLAVE sync started
[4060] 28 Jul 15:00:20.792 \* Non blocking connect for SYNC fired the event.
[4060] 28 Jul 15:00:20.792 \* Master replied to PING, replication can continue...
[4060] 28 Jul 15:00:20.792 \* Partial resynchronization not possible (no cached master)
[4060] 28 Jul 15:00:20.792 \* Full resync from master: 5eac4da977d32c0ab944de7ffbab8e6741cdceae:1033307026
[4060] 28 Jul 15:00:29.917 \* MASTER <-> SLAVE sync: receiving 182464441 bytes from master
[4060] 28 Jul 15:00:59.183 \* MASTER <-> SLAVE sync: Flushing old data
[4060] 28 Jul 15:00:59.230 \* MASTER <-> SLAVE sync: Loading DB in memory
[4060] 28 Jul 15:01:04.667 \* MASTER <-> SLAVE sync: Finished with success
[4060] 28 Jul 15:19:30.256 # Connection with master lost.
[4060] 28 Jul 15:19:46.912 \* Caching the disconnected master state.
[4060] 28 Jul 15:19:52.568 # Accepting client connection: accept: Unknown error
[4060] 28 Jul 15:19:58.662 \* Connecting to MASTER 192.168.50.107:6379
[4060] 28 Jul 15:19:58.662 \* MASTER <-> SLAVE sync started
[4060] 28 Jul 15:20:06.881 \* Non blocking connect for SYNC fired the event.
[4060] 28 Jul 15:20:06.975 \* Master replied to PING, replication can continue...
[4060] 28 Jul 15:20:06.991 \* Trying a partial resynchronization (request 5eac4da977d32c0ab944de7ffbab8e6741cdceae:1515131860).
[4060] 28 Jul 15:20:07.006 \* Full resync from master: 5eac4da977d32c0ab944de7ffbab8e6741cdceae:1531737612
[4060] 28 Jul 15:20:07.006 \* Discarding previously cached master state.
[4060] 28 Jul 15:20:07.194 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[4060] 28 Jul 15:20:07.194 # --- EXCEPTION_ACCESS_VIOLATION
[4060] 28 Jul 15:20:07.194 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x0244E590, 0x0244FF90, 0x00000001, 0x40105AA8)
redis-server.exe!UnhandledExceptiontHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00000001, 0x00000000, 0x00000001, 0x0000F0C9)
kernel32.dll!UnhandledExceptionFilter(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x0244E590, 0x00000006, 0x00000000, 0x00000001)
ntdll.dll!EtwEventSetInformation(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x0244F1D0, 0x40016A36, 0x40108BF8, 0x00000000)
ntdll.dll!_C_specific_handler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x02450000, 0x0244FF90, 0x0244FF90, 0x77CEEA64)
ntdll.dll!RtlDecodePointer(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x02450000, 0x77B9DD94, 0x00012A08, 0x00000000)
ntdll.dll!RtlUnwindEx(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x0244F1D0, 0x0244ECE0, 0x00000000, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x04570CA0, 0x00000001, 0xFFFFFFFF, 0x04570CA0)
redis-server.exe!listAddNodeHead(c:\release\redis\src\adlist.c:96)(0x0051FA80, 0x7EF3A6C0, 0x00000000, 0x7EFEE810)
redis-server.exe!aeGetSockState(c:\release\redis\src\ae_wsiocp.c:92)(0x7EF3A6C0, 0x7E89A5C8, 0x00000000, 0x00000000)
redis-server.exe!aeWinCloseSocket(c:\release\redis\src\win32_interop\win32_wsiocp.c:477)(0x7EF3A6C0, 0x00000000, 0x7E89A5C8, 0x7EFEFE60)
redis-server.exe!freeClient(c:\release\redis\src\networking.c:718)(0x7E89A5C8, 0x7F76FFE4, 0x7F76FFD8, 0x00000014)
redis-server.exe!slaveTryPartialResynchronization(c:\release\redis\src\replication.c:1327)(0x00001229, 0x00001229, 0x4013CFC0, 0x7F2766A8)
redis-server.exe!syncWithMaster(c:\release\redis\src\replication.c:1469)(0x00000001, 0x79E1D420, 0x79E06F60, 0x000000CC)
redis-server.exe!aeMain(c:\release\redis\src\ae.c:487)(0x55B7DF54, 0x79DB6968, 0x00000002, 0x002125C0)
redis-server.exe!redis_main(c:\release\redis\src\redis.c:3524)(0x00000000, 0x002125C0, 0x55B7DF53, 0x00000002)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1349)(0x0000000A, 0xFFFFFFFF, 0xFFFFFFFF, 0x00000000)
redis-server.exe!ServiceWorkerThread(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[4060] 28 Jul 15:20:07.819 # --- INFO OUTPUT
# Server

redis_version:2.8.2101
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9d5f6488ff5c66dd
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:winsock_IOCP
process_id:4060
run_id:9c53a965b1bfab840487ab7b0d14da7e65955484
tcp_port:6379
uptime_in_seconds:1187
uptime_in_days:0
hz:10
lru_clock:12051446
config_file:C:\redis28\redis.windows.conf
# Clients

connected_clients:85
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:255704832
used_memory_human:243.86M
used_memory_rss:263847632
used_memory_peak:451215384
used_memory_peak_human:430.31M
used_memory_lua:70656
mem_fragmentation_ratio:1.03
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:153932
rdb_bgsave_in_progress:0
rdb_last_save_time:1438113619
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:4926
total_commands_processed:589917
instantaneous_ops_per_sec:536
total_net_input_bytes:679384190
total_net_output_bytes:0
instantaneous_input_kbps:23.58
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:164682
keyspace_misses:48492
pubsub_channels:2
pubsub_patterns:0
latest_fork_usec:0
# Replication

role:slave
master_host:192.168.50.107
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_repl_offset:1515131859
master_link_down_since_seconds:jd
slave_priority:25
slave_read_only:1
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:34.36
used_cpu_user:68.11
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=190549,usec=1890694,usec_per_call=9.92
cmdstat_set:calls=19910,usec=2515662,usec_per_call=126.35
cmdstat_setex:calls=43826,usec=1578195,usec_per_call=36.01
cmdstat_del:calls=15023,usec=296881,usec_per_call=19.76
cmdstat_incr:calls=22857,usec=93752,usec_per_call=4.10
cmdstat_decr:calls=228,usec=0,usec_per_call=0.00
cmdstat_sadd:calls=483,usec=15626,usec_per_call=32.35
cmdstat_srem:calls=273,usec=0,usec_per_call=0.00
cmdstat_hset:calls=18860,usec=218757,usec_per_call=11.60
cmdstat_hdel:calls=485,usec=812510,usec_per_call=1675.28
cmdstat_select:calls=1,usec=0,usec_per_call=0.00
cmdstat_expire:calls=22625,usec=15562702,usec_per_call=687.85
cmdstat_auth:calls=4925,usec=15625,usec_per_call=3.17
cmdstat_ping:calls=41065,usec=156254,usec_per_call=3.81
cmdstat_echo:calls=4689,usec=0,usec_per_call=0.00
cmdstat_multi:calls=9446,usec=0,usec_per_call=0.00
cmdstat_exec:calls=9446,usec=171878,usec_per_call=18.20
cmdstat_info:calls=52485,usec=58017154,usec_per_call=1105.40
cmdstat_config:calls=4702,usec=93750,usec_per_call=19.94
cmdstat_subscribe:calls=2443,usec=0,usec_per_call=0.00
cmdstat_unsubscribe:calls=67393,usec=640634,usec_per_call=9.51
cmdstat_publish:calls=31021,usec=234385,usec_per_call=7.56
cmdstat_client:calls=4719,usec=15625,usec_per_call=3.31
cmdstat_eval:calls=949,usec=109377,usec_per_call=115.26
cmdstat_evalsha:calls=21508,usec=5281329,usec_per_call=245.55
cmdstat_script:calls=6,usec=0,usec_per_call=0.00
# Keyspace

db0:keys=32676,expires=25819,avg_ttl=0
[4060] 28 Jul 15:20:07.850 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @ravynz,
in the latest [v2.8.2102 release](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2102) we have made a fix for the problem you reported.
Thank you.
