### ISSUE TITLE
Trying to change port on Redis for windows 8.1

### ISSUE THREAD

**Issue by osherdo** [microsoftarchive/redis#284]
Hello everyone.

Tried to change port on Redis 2.8.21.(Screenshot here:http://3.1m.yt/AGpx1ZjbQ.png)

Afterwards restarted both redis-cli and redis-server. 
Also tried to change it via redis-server with 'config set port 3001' command.

How do I do that? googled it thoroughly and could not figute out how. Or maybe it's a syntax error?

Would like to hear your opinios and suggestions. Thank you.

**Comment by enricogior** [comment]
@osherdo,
if redis-server runs as a service change the port in **redis.windows-service.conf** otherwise change it in **redis.windows.conf** and run `redis-server.exe redis.windows.conf`.
The CONFIG command doesn't support the port parameter.

**Comment by osherdo** [comment]
@enricogior thanks again for your answer.

Redis does running as a service in my OS since it appears in the services window (services.msc).

I have changed the port in redis.windows-service.conf( to 3001) :

```
# Accept connections on the specified port, default is 6379.
# If port 0 is specified Redis will not listen on a TCP socket.
port 3001
```

Yet it still comes 127.0.0.1:6379 in redis-clie.exe

One thing I should mention is that I cannot edit the file redis.windows.conf for some reason. it does not allow me to make any changes in this file.

**Comment by enricogior** [comment]
@osherdo,
copy the redis.windows-service.conf file to the desktop, edit the file and then copy it back to the c:\program files\redis folder.
From a command prompt with admin rights:
C:> net stop redis
C:> net start redis
C:> type "C:\Program Files\Redis\Logs\redis_log.txt"
the last line should contain "The server is now ready to accept connections on port 3001".

**Comment by osherdo** [comment]
@enricogior I have done cd into C:\Program Files\Redis\Logs and tried to run:

```
 The process cannot access the file because it is being used by another process.
```

I have tried to access the file again after restart but it keeps giving me the same message.

So I thought maybe port 3001 is busy ,and entered this at the command prompt (with administrative priviliges) and got this output:

```
C:\WINDOWS\system32>   netstat -aon | find ":3001"
  TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING       3180
  TCP    [::]:3001              [::]:0                 LISTENING       3180
```

the same applies for port 2999.

**Comment by enricogior** [comment]
@osherdo
"3180" is the pid of the process that is using port 3001, check in the task manager what process is.

If you are still having problems setting the Redis port I suggest to uninstall Redis and reinstall it.
During the installation you may change the default port number to 3001.
After uninstalling and before reinstalling, run again `netstat -aon | find ":3001"` to make sure the port is not already in use.

**Comment by osherdo** [comment]
@enricogior,
it is funny becuase I did anything you've said and yet it is going to port 6379.

checked to make sure that either port 3001 or 2999 for instance are not busy before reinstaliing. anything you can tell me to do next?

**Comment by osherdo** [comment]
@enricogior

**Comment by enricogior** [comment]
@osherdo
did you select port 3001 during the MSI installation and still the redis.windows-service.conf shows port 6379?
Please make sure Redis was uninstalled first verifying that the C:\Program Files\Redis folder is not present, if present delete it.
Make sure there are no other instances of Redis running.
Reinstall following the instructions I gave before and make sure the redis.windows-service.conf is updated with the correct port number.
We have never seen this problem before and I don't have a Windows 8.1 box to test it, but it seems strange that only occurs on Windows 8.1.

**Comment by osherdo** [comment]
Yes I selected port 3001 during the MSI installation and still the redis.windows-service.conf shows port 6379. 

Do you know maybe if `redis.windows-service.conf`` is set as default config file for Redis? if not, how do I change it?  because port 2999(that I chose during installation) is actually set in this file.Yet the program showing current port as 6379.

From redis.windows-service.conf:

```
# Accept connections on the specified port, default is 6379.
# If port 0 is specified Redis will not listen on a TCP socket.
port 2999
```

**Comment by enricogior** [comment]
@osherdo
you first said: "still the redis.windows-service.conf shows port 6379"
but then you pasted the  lines from redis.windows-service.conf that show that the port is set to 2999.
So too me it seems that the MSI is working as expected.

When the installation is completed, redis-server.exe is started as a service and if you check the log file it should show that Redis is using the 2999 port.
Use the command: C:> type "C:\Program Files\Redis\Logs\redis_log.txt"

If you run redis-server.exe manually, that is another instance and it will use the redis.windows.conf (not the redis.windows-service.conf) that still has the default 6379 port, that is also expected.

**Comment by osherdo** [comment]
@enricogior that's right. the config file is configured to use port 2999. Saw it on the log file (from 2 hours,though. it does not show logging for the current time.Is it okay?).

But the CLI shows port 6379 as the one being used, though.

the log says one thing and CLI is saying another, and not the same.

I do run redis-server manually. the port 6379 does appear in redis.windows.conf file and cannot be edited at all. This brings me back to ask what is the way to change configuration path file in Redis for windows? the one in the Redis website is for Mac.

This is the log file right now:

```
[7808] 04 Aug 21:50:07.833 * Redis 2.8.2101 (00000000/0) 64 bit, stand alone mode, port 2999, pid 7808 ready to start.
[7808] 04 Aug 21:50:07.834 # Server started, Redis version 2.8.2101
[7808] 04 Aug 21:50:07.834 * The server is now ready to accept connections on port 2999
```

and this is a current screenshow from redis-cli:

http://2.1m.yt/0Rlhqqdk.png

This is a current netstat screenshot. you can see actually port 6379 is being used and no trace for port 2999 being used:

http://3.1m.yt/uy9Emz01K.png

What would you suggest to do next?

**Comment by enricogior** [comment]
@osherdo
regarding: "the port 6379 does appear in redis.windows.conf file and cannot be edited at all" 

to edit redis.windows.conf copy the file to the desktop, change the port number and copy it back to C:\Program Files\Redis\

When you run redis-server.exe manually you have to pass the configuration file:
`redis-server.exe redis.windows.config`
otherwise it will use the default settings.

**Comment by osherdo** [comment]
@enricogior sorry I forgot about the port changing method. Changed it too to 2999 in `redis.windows.conf` as well.

I just don't know how to pass the configuration file manually. 
redis-cli.exe does not accept any kind of this argument.

that's the last thing I need to know in order to make it succeed, I believe.

**Comment by enricogior** [comment]
@osherdo
the configuration files is passed to the server not to the client, to pass the config file manually to the server:
 `C:\>cd \Program Files\Redis`
 `C:\Program Files\Redis>redis-server.exe redis.windows.conf`

**Comment by osherdo** [comment]
got it finally.
works just fine on redis-server.

Now how do I pass the port to the redis-cli? it still exist as 6379 there.

**Comment by enricogior** [comment]
@osherdo
to connect the client to the server that runs on port 2999:
`C:\Program Files\Redis>redis-cli.exe -p 2999`

**Comment by osherdo** [comment]
Thank you deeply @enricogior for the ongoing support . Finally!
:)

**Comment by osherdo** [comment]
just out of coriousity: do you know what that means?

I am trying `get tcp_port` and the cli returns this:

edited: cannot show it directly here- so here's a screenshot:

http://3.1m.yt/N8drp02ME.png

it shows (nil) in return.

edit: maybe I mistyped my command and there's no key named like that, therefore it's called 
(nil) (from the documenatation).

**Comment by enricogior** [comment]
@osherdo
it seems you already found the answer, anyway it's explained here: http://redis.io/commands/get
I close the issue.
