### ISSUE TITLE
Slave replication Linux to Windows does not work

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#286]
I'm trying to replicate from a Linux instance (Redislabs running 2.8.12) to my Windows 7 box running 2.8.2101. Both slaveof and masterauth are specified in the config file of the slave instance.
When I launch local Redis from console, I get this error - "Creating Server TCP listening socket *:6379: bind: No error", which is strange, considering port number I specified is obviously NOT 6379
Any ideas what I did wrong? Is this scenario even supported?

**Comment by chester89** [comment]
However, connecting from redis-cli to a Linux instance works fine

**Comment by enricogior** [comment]
Hi @chester89 
make sure you are setting the correct port number and that you pass the correct redis.config file to redis-server.exe.
Regarding the scenario: it's not explicitly supported, but it's not explicitly not supported.
Sorry that I can't help more, but please let us know if you make any progress.

**Comment by chester89** [comment]
​Will do​

2015-08-03 19:44 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89
> make sure you are setting the correct port number and that you pass the
> correct redis.config file to redis-server.exe.
> Regarding the scenario: it's not explicitly supported, but it's not
> explicitly not supported.
> Sorry that I can't help more, but please let us know if you make any
> progress.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/286#issuecomment-127327190.

## 

Yours faithfully,
Gleb

**Comment by chester89** [comment]
Ok, that was me being stupid by trying to run two local instances on a same (default) port.
Still, when my instance is trying to sync from Redislabs, it gets an error since [they disabled replication, I think](http://serverfault.com/questions/665111/redis-2-8-12-slave-sync-failing)
