### ISSUE TITLE
Redis connection fails after master failover

### ISSUE THREAD

**Issue by vlavella** [microsoftarchive/redis#290]
Hi, i'm trying to run a simple test with 3 masters and 3 slaves on a cluster. When I kill one master redis fail since the "__Booksleeve_MasterChanged" event is not being trigger so my client is not notified about the new master. 
I'm running the 3.0 alpha version.

Any idea about how to fix it? 

Thanks

**Comment by enricogior** [comment]
Hi @vlavellauruit 
was this scenario working with 2.8?

**Comment by vlavella** [comment]
Is not. In the 2.8 version I got an error on the cluster configuration so, I'm not able to run the cluster on that version... I'm missing something? 
The only thing I did is uncomment the cluster conf on the redis.windows.conf file.

**Comment by enricogior** [comment]
Hi @vlavellauruit 
I misunderstood the question, I thought the problem was specific of a master-slave switch.
If you have a client code sample to test the scenario it would help to investigate the issue.
Thank you.

**Comment by enricogior** [comment]
Hi @vlavellauruit 
early next week we will release 3.0.300-alpha2 with fixes for the cluster functionality.

**Comment by enricogior** [comment]
@vlavellauruit,
more Windows-specific fixes in the new [3.0.300-alpha3 release](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.300-alpha3).

Can you please verify if the issue is still present?
Thank you.

**Comment by vlavella** [comment]
Hi, 
I found a issue on the client made a pull request and working with my version of the client and the release that you did it seems to be working right. 
Thanks for your time. 
Regards

**Comment by enricogior** [comment]
Great, thank you for the feedback.
I'll close the issue.
