### ISSUE TITLE
redis-benchmark.exe says 'An existing connection was forcibly closed by the remote host.' or is dead silent

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#291]
Hello, I'm using 2.8.2101 build and trying to measure server performance on my Windows 7 box.
When I do `redis-benchmark.exe -h 127.0.0.1 -p 6379 -c 2 -n 10000` it shows results for some commands and then says  `Writing to socket An existing connection was forcibly closed by the remote host.`<br /> When I use `redis-benchmark.exe -h 127.0.0.1 -p 6379 -t hset,zadd,zremrangebyscore,rpush -c 2 -n 1000` it doesn't show anything at all, just prints blank line and exits.<br />
I start redis-server.exe from a console window and both AOF and RDB replication are turned on. Initially I thought loglevel is too high, so I changed it to notice only to get same results. If you need config file I used, let me know

**Comment by chester89** [comment]
It seems I fixed the first problem (connection closed by remote host) by increasing maxclients, maxmemory and maxheap config values.

**Comment by chester89** [comment]
Also, may I ask what commands are available under -t flag? it's not really clear from the source code

**Comment by enricogior** [comment]
Hi @chester89 
the "hset,zadd,zremrangebyscore,rpush" are not valid test names.
Run the default tests and the test names are shown in between "====== ":
====== LPUSH ====== 
====== LPOP ======
etc.

**Comment by chester89** [comment]
makes sense. thanks @enricogior

**Comment by enricogior** [comment]
@chester89 You are welcome ;)
