### ISSUE TITLE
Trying to pass configuration file on Redis- Failed

### ISSUE THREAD

**Issue by osherdo** [microsoftarchive/redis#292]
I am trying to Trying to pass configuration file on Redis:

```
redis-server.exe redis.windows.conf
```

Then I get one of the three results alternately:

```
[3416] 15 Aug 02:43:08.525 # Creating Server TCP listening socket *:2999: bind:
No such file or directory
```

Sometimes it says:

```
Failed to open the .conf file: redis-windows CWD=c:\Program Files\Redis
```

In CMD.

sometimes it also just shows the path again and do nothing (similarly to when you just hit 'enter' on cmd.)

I have Windows 8.1
I have uninstalled and installed again,checked I wrote everything well-still does not act well.

On the other side- `redis-cli.exe -p 2999` works well.

**Comment by enricogior** [comment]
Hi @osherdo,
the error "Creating Server TCP listening socket *:2999: bind: No such file or directory" occurs when the port is already in use, very likely you have already another redis-server.exe running that uses the 2999 port (the fact that redis-cli.exe -p 2999 works is a confirmation of that).

The error code "No such file or directory" is misleading, I'll see if I can fix it to a more meaningful one.
Thank you.

**Comment by osherdo** [comment]
@enricogior as usual thanks for the help. It did appeared in the task manager.
