### ISSUE TITLE
Connections not released when master/slave sync fails

### ISSUE THREAD

**Issue by cosborne83** [microsoftarchive/redis#294]
I'm running 2.8.2101 and have noticed that if a server is configured as a slave but initial synchronization fails repeatedly (e.g. the slave's `masterauth` is not configured but the master requires authentication), a new connection is made to the master for each synchronization attempt, but the previous connections are not cleaned up. It's therefore relatively easy to exceed the maximum number of clients on the master if inadvertently left in such a state.

**Comment by enricogior** [comment]
Hi @cosborne83,
thank you for reporting the issue.
This is definitely a bug we will try to fix in the next release.

**Comment by enricogior** [comment]
Hi @cosborne83,
the bug has been fixed in [v2.8.2102](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2102).
Thanks again for the contribution to the community.
