### ISSUE TITLE
FLUSHDB command time increases for larger key sizes when persistence-available=no

### ISSUE THREAD

**Issue by davidwestern** [microsoftarchive/redis#295]
Using REDIS 2.8.19 on Windows 2008 R2, 32GB RAM, 12 cores, dual E5645 CPUs.
We have approximately 14GB of redis memory used with 800K keys giving an average key value size of 18K. We have persistence turned off as we only need in-memory cache and want "optimal" performance without the memory-mapped file access.

When issuing a FLUSHDB this takes around 90 minutes before completing. Since this command is blocking, it stops our application from using REDIS. I have reproduced this scenario in version 2.8.2101 as well. We use FLUSHDB to periodically reset the cache for application reasons.

The long flush time appears related to the size of the key value. I wrote a test app to load certain numbers of cache entries with an 18000 byte value and then timed the FLUSHDB command. The time to flush increases at a high rate. When I reduce the key value size to 9000 bytes the times change in a manner linear to the increase in number of keys. As an example, 150K keys storing 18K values took 132 seconds to flush. 300K keys storing 9K values took only 1.46 seconds to flush. Both used 2.5GB of memory in REDIS (twice the number of 9K keys matched memory usage of the 18K key size comparison).

When I run this with persistence-available=yes then the FLUSHDB yields immediately but appears to work on a background thread. We have all "saves" turned off. We would like to avoid the memory mapped file i/o.

Here is my chart of times:

USING 18000 byte VALUES:

CacheEntries,MemUsed,FlushTimeInSeconds,RatePerSecond
100000,1.68 GB,39,2564
150000,2.5 GB,132,1136
200000,3.36 GB,344,581

So the rate goes from flushing 2564/s to 1136/s with 50000 more entries. Then from 1136/s to 581/s with 50000 more entries on top of that. So the flush rate drops by roughly half with each increase of 50000 entries in my test case.

USING 9000 byte VALUES:

CacheEntries,MemUsed,FlushTimeInSeconds,RatePerSecond
200000,1.69 GB,0.8,250000
300000,2.54 GB,1.46,205479
400000,3.39 GB,2.38,168067

The flush rate per second still drops but at a more linear rate. I'm not sure why the flush rate would not be linear, but I am more concerned with the very large flush rates when larger value sizes are used.

**Comment by enricogior** [comment]
Hi @davidwestern,
thanks for the detailed report. Your investigation is interesting and it seems like a legit perf issue that needs to be fixed. In order to speed up the repro on our side, could you send us the test app you wrote? (In case send it to --edited--)
Thank you.

**Comment by davidwestern** [comment]
I have sent the test app to winredis-bugs.microsoft.com. Let me know if you need any further input from me.

**Comment by enricogior** [comment]
Hi @davidwestern,
did you send a .exe? The mail arrived without attachment, if it was a .exe is has been removed by the mail server.
You may zip the file or just send the source code if that is ok.
Thank you.

**Comment by davidwestern** [comment]
The attachment was removed. I can share the source but it uses some
in-house libraries to simplify adding items to REDIS. Here is the link to
the download:

https://drive.google.com/file/d/0B6dRfBsKWEX1UTVtVHZTeGhNdW8/view?usp=sharing

The code is fairly straightforward as it just populates a number of cache
entries with specific sized values. Here is the .Net code if that is
helpful:

using System;
using System.Text;
using MicroD.Common;

namespace PopulateCacheValues
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args == null || args.Length < 2)
            {
                Console.WriteLine("USAGE: PopulateCacheValues <numentries>
<valuebytesize>");
                Console.WriteLine("EXAMPLE:");
                Console.WriteLine("PopulateCacheValues 150000 18000");
                return;
            }

```
        int numEntries = Conversions.ToInt(args[0], 100);
        int valueSize = Conversions.ToInt(args[1], 18000);

        AddCacheItems("testkey", numEntries, valueSize);

        Console.WriteLine(string.Format("Added {0} cache entries each
```

storing a string of {1} characters.", numEntries, valueSize));
        }

```
    protected static void AddCacheItems(string keyPrefix, int
```

numEntries, int valueByteSize)
        {
            string cacheKey;
            StringBuilder sbValue = new StringBuilder(valueByteSize);
            string toCache = string.Empty;
            for (int size = 0; size < valueByteSize; size++)
                sbValue.Append("A");

```
        toCache = sbValue.ToString();

        for (int index = 0; index < numEntries; index++)
        {
            cacheKey = keyPrefix + "_" + Convert.ToString(index);

            MicroD.Common.CacheManagement.Cache.Add(new
```

MicroD.Common.CacheKey(cacheKey), toCache);
            }

```
    }
}
```

}

**Comment by enricogior** [comment]
@davidwestern
perfect, thank you.

**Comment by enricogior** [comment]
Hi @davidwestern 
sorry for not having updated the issue, are you still looking for a solution?
I've run some tests and these are my findings:
- the problem occurs only when setting `persistence-available no`.
- the problem doesn't occur with the setting `persistence-available yes`, in this case the FLUSHDB command completes instantaneously.

When persistence is disabled, the system memory allocator is used, when persistence is enabled dlmalloc is used.
It seems the problem resides in the system allocator, but more investigation is needed in order to reach a final conclusion.
One thing worthy to be tested is to use dlmalloc even when persistence is disabled and the memory mapped file is not created.

**Comment by davidwestern** [comment]
Yes, this is still an issue. We do not need persistence. We experience a
high level of disk i/o when flushdb is issued when
persistence-available=yes, even though no persistence operation is needed.
So there still appears to be a performance impact, though it is not a
blocking operation like when persistence-available=no.

**Comment by enricogior** [comment]
@davidwestern 
you are right, the disk i/o peak is definitely significant.
As an alternative you may consider testing [v3.0-rc1](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc1) and verify if its performance is good enough for your needs (please check both persistence-available yes and no, in both cases it should take a reasonable amount of time with very low disk i/o). 
We don't have a date for the official release yet, but we are getting close and for sure we will not make changes to the memory allocation in 2.8 before the 3.0 release.

**Comment by davidwestern** [comment]
I've tested the 3.0-rc1 and it does appear to correct the issue. We are
currently operating with about 2.1M keys in a 14GB cache.
The memory mapped file appears to be completely gone with either
persistence setting.
I did not see any significant disk I/O in either case.

Flush times appeared to be relatively linear as I tested with increasing
numbers of keys (increasing in proportion to the number of keys).

We will put this RC1 version into our test instance and use it there for a
while. Once it proves stable we can then move it to production.

Thanks for getting back with me on a solution!

David

**Comment by enricogior** [comment]
@davidwestern 
I'm glad to hear that the initial testing with the 3.0 RC1 was successful.
Be aware that is still a Release Candidate and not a final release, therefore I would suggest to wait for the final 3.0 release before moving it to production.

**Comment by enricogior** [comment]
[Release v2.8.2400](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2400) fixes the issue.
