### ISSUE TITLE
Redis sentinel notification script not working in windows.

### ISSUE THREAD

**Issue by abhinashagrawal547** [microsoftarchive/redis#298]
The script is written using power shell and is called from bat file which i am providing to the redis sentinel config notification section.  Trying two different sentinel configuration as mentioned below  1. sentinel notification-script mymaster "D:\Redis-64.2.8.17\notificationScript\qwe.bat"  With this configuration redis-server running as sentinel is getting crashed as i am able to see event log but i am not getting any log in the redis stdout.log.  2. sentinel client-reconfig-script mymaster "D:\Redis-64.2.8.17\notificationScript\qwe.bat".  With this configuration , redis-server running as sentinel is getting started but the event is not firing.

**Comment by enricogior** [comment]
Hi @abhinashagrawal547 
can you please edit the title, moving the description in the comment.
Also please follow the guidelines [How to submit a generic issue](https://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue#how-to-submit-a-generic-issue).
Thank you.

**Comment by enricogior** [comment]
[Release v2.8.2400](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2400) fixes the issue.
