### ISSUE TITLE
# ==> ..\src\db.c:482 'dictFind(db->dict,key->ptr) != NULL' is not true

### ISSUE THREAD

**Issue by amaximciuc** [microsoftarchive/redis#30]
I'm running redis 64bit, 2.4, the default branch; windows 2008 r2.
save settings:
 save 900 1
 save 300 10
 save 60 10000
I keep getting
"# ==> ..\src\db.c:482 'dictFind(db->dict,key->ptr) != NULL' is not true"
in the log and redis-server.exe crashes.
I guess it happens when a bgsave is in progress, because a temp-XXXX.rdb, much smaller than dump.rdb, remains in the directory.
I have lots of expiring keys. 
thanks in advance for any help.

**Comment by HenryRawas** [comment]
Can you include a stack trace?
If you have a program that can repro this it would save a lot of time.

**Comment by amaximciuc** [comment]
thanks for quick response.
stack trace? how exactly shoud I do that so it would be perfect?
here's a perl script that reproduces the crash in about 2 minutes max (ugly, but it does it's job :) )
https://gist.github.com/4549957
to "increase" the chances, start 2 instances of the script.

**Comment by HenryRawas** [comment]
I added a stress test for background saving and expires. Fixed a couple of issues including the one reported here.

**Comment by amaximciuc** [comment]
worked for me in a 20minutes test.
from time to time(but it might be something with my machine), stress-scripts hang, redis-server's(executed with no conf) console hangs and redis-cli connects, but hangs on returning any result for commands(INFO with no reply for 14seconds.) 
When and if I'll be sure it's from redis-server, I'll open another issue.
For the moment - thanks
