### ISSUE TITLE
when redis was running bgrewriteaof cmd. it say  'Error trying to rename the existing AOF to old tempfile'

### ISSUE THREAD

**Issue by zqzjz0911** [microsoftarchive/redis#300]
What I'm seeing in the logs is:
    [16248] 27 Aug 17:54:36.424 \* Background append only file rewriting started by pid 21980
    [16248] 27 Aug 17:54:37.893 # Short write while writing to the AOF file: (nwritten=0, expected=53)
    [16248] 27 Aug 17:54:38.112 # fork operation complete
    [16248] 27 Aug 17:54:38.159 \* Background AOF rewrite terminated with success
    [16248] 27 Aug 17:54:38.159 \* Parent diff successfully flushed to the rewritten AOF (83 bytes)
    [16248] 27 Aug 17:54:38.159 # Error trying to rename the existing AOF to old tempfile: Broken pipe

please help me.

**Comment by zqzjz0911** [comment]
i built it in tag win-2.8.2102

**Comment by enricogior** [comment]
Hi @zqzjz0911 
thank you for reporting the issue.
What version of Redis are you running? What version of Windows?
Is there already an existing AOF file? If yes, how big is it?
Is the error persisting?
Thank you.

**Comment by zqzjz0911** [comment]
i built it in tag win-2.8.2102,  windows 8.1, the aof file has 9GB, it's persisting..

**Comment by enricogior** [comment]
@zqzjz0911 
how much free disk space is available?

**Comment by zqzjz0911** [comment]
there's 13GB

**Comment by zqzjz0911** [comment]
the program leave a temp file called temp-rewriteaof-bg-16248.aof (77MB)

**Comment by enricogior** [comment]
@zqzjz0911 
the temp file has always the same 77MB size or everytime there is an attempt to rewrite the AOF the size of the temp file is different?

**Comment by zqzjz0911** [comment]
always the same 77MB. but the log has changed something...

[16248] 27 Aug 18:22:11.759 \* Background append only file rewriting started by pid 14824
[16248] 27 Aug 18:22:13.493 # fork operation complete
[16248] 27 Aug 18:22:13.539 \* Background AOF rewrite terminated with success
[16248] 27 Aug 18:22:13.539 \* Parent diff successfully flushed to the rewritten AOF (0 bytes)
[16248] 27 Aug 18:22:13.539 # Error trying to rename the existing AOF to old tempfile: Broken pipe

**Comment by enricogior** [comment]
@zqzjz0911
can you delete the temp file?

**Comment by zqzjz0911** [comment]
the temp file can be deleted.

**Comment by enricogior** [comment]
@zqzjz0911 
when you started Redis, the 9BG AOF file was already there right? 
After Redis started, did the error occur at the first AOF rewrite attempt or does the log show at least one successful AOF rewrite? I mean a rewrite not followed by the "Error trying to rename the existing AOF to old tempfile".

**Comment by zqzjz0911** [comment]
yes.
the 9GB file was still 9GB, after writing these log.

**Comment by zqzjz0911** [comment]
and after running bgrewriteaof cmd, the redis process has still hold the cpu resource (2-3%)
![qq 20150827184729](https://cloud.githubusercontent.com/assets/7539663/9518750/014bf70a-4cec-11e5-8ff6-3ce20e0504ca.png)

my cpu is i7  4core 8 thread

**Comment by zqzjz0911** [comment]
i run it in two machine, there is the problem in all machine.
one is win 8.1, another is win2008 r2

**Comment by zqzjz0911** [comment]
can i send the aof file to you ?

**Comment by enricogior** [comment]
@zqzjz0911 
sure, can you zip it and upload it to a cloud service?
The Win 8.1 is a development machine? If yes, can you quit Redis, rename the AOF file, restart Redis, fill it with some data and verify if the AOF rewrite still fail?
One more question, you said you compiled Redis, did you make any change to the code? I'm wondering why you compiled it and not just downloaded the binaries.
Thank you.

**Comment by zqzjz0911** [comment]
i found that the aof file is truncated..maybe that is the reason cause this problem...

**Comment by zqzjz0911** [comment]
i have not made any change to the code..

**Comment by zqzjz0911** [comment]
please use the link to download the aof file: http://pan.baidu.com/s/1pJN2Tzt

**Comment by enricogior** [comment]
@zqzjz0911 
the site asks to use the Baidu downloader but unfortunately it fails to download it.

**Comment by zqzjz0911** [comment]
but how can i send file to you now?

**Comment by enricogior** [comment]
@zqzjz0911 
do you have an hotmail account? I can created a shared folder where you can upload the file but you will need to log in with an hotmail account.

**Comment by zqzjz0911** [comment]
--email removed-- thanks

**Comment by enricogior** [comment]
I've sent you an email, feel free to remove the email address from your previous comment.
Thank you.

**Comment by zqzjz0911** [comment]
uploadding has finished

**Comment by enricogior** [comment]
OK!

**Comment by enricogior** [comment]
@zqzjz0911 
using the AOF you sent me, I can repro the problem, I'll let you now as soon as I have a fix for it.
Thank you.

**Comment by zqzjz0911** [comment]
thx

**Comment by enricogior** [comment]
Hi @zqzjz0911,
as you already noticed, the problem was occurring because the AOF was truncated.
The fix is ready and it will be included in the next release.
For now you can workaround the problem fixing the AOF file with the redis-check-aof.exe utility:

```
c:\program files\redis\redis-check-aof --fix appenonly.aof
```

Thank you for your contribution to improve Redis on Windows!

**Comment by zqzjz0911** [comment]
but config file of redis can pass the file by using aof-load-truncated...and in that case the problem will be caused.

**Comment by zqzjz0911** [comment]
how are you fix it ? can you tell me the detail ?

**Comment by enricogior** [comment]
@zqzjz0911 
when an incomplete AOF is detected, the file is truncated at the last valid value so it won't be incomplete anymore.
The code that truncates the file wasn't releasing the file handle (that is a bug because the file remains in use).
When an AOF rewrite is executed the AOF has to be renamed but renaming was failing because the file was still in use.
There was also another bug since the temp file was not deleted after failing to rename it.

**Comment by zqzjz0911** [comment]
i see。thx。

**Comment by enricogior** [comment]
@zqzjz0911,
the new [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) contains the fix for this issue.
Thank you.

**Comment by zqzjz0911** [comment]
thx.let me build it.
