### ISSUE TITLE
Add redis install location to the path

### ISSUE THREAD

**Issue by NoNameProvided** [microsoftarchive/redis#302]
The installer should add the selected location to the system path.

**Comment by enricogior** [comment]
Hi,
thank you for your feedback, we will consider adding the location to the path in the next release.
Thanks.

**Comment by enricogior** [comment]
The new [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) contains the fix for this issue.
Thank you.
