### ISSUE TITLE
Sometimes Redis very slow to read data

### ISSUE THREAD

**Issue by noinhotnn** [microsoftarchive/redis#305]
I have setup a Redis Server and an application on a computer. But sometime it spend 4 500ms to get a key (sometime it about <10ms).
My Redis server info:
# Server

redis_version:2.8.17
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e1f61e287dff4649
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:winsock_IOCP
gcc_version:0.0.0
process_id:27168
run_id:71b50eb2c39006333a82f6316a8e53240383327f
tcp_port:6379
uptime_in_seconds:1123017
uptime_in_days:12
hz:10
lru_clock:14949456
# Clients

connected_clients:852
client_longest_output_list:41
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:100495368
used_memory_human:95.84M
used_memory_rss:99578976
used_memory_peak:111708232
used_memory_peak_human:106.53M
used_memory_lua:33792
mem_fragmentation_ratio:0.99
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:928243771
rdb_bgsave_in_progress:0
rdb_last_save_time:1439889799
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:120661111
total_commands_processed:3057391576
instantaneous_ops_per_sec:2948
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:33584
evicted_keys:0
keyspace_hits:1056976029
keyspace_misses:66292894
pubsub_channels:37651
pubsub_patterns:0
latest_fork_usec:0
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:302056.53
used_cpu_user:219502.56
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=29086285,usec=284137009,usec_per_call=9.77
cmdstat_setex:calls=36444,usec=484410,usec_per_call=13.29
cmdstat_del:calls=2,usec=0,usec_per_call=0.00
cmdstat_sadd:calls=42474,usec=359423,usec_per_call=8.46
cmdstat_smembers:calls=11,usec=46883,usec_per_call=4262.09
cmdstat_sscan:calls=4,usec=0,usec_per_call=0.00
cmdstat_zadd:calls=14,usec=0,usec_per_call=0.00
cmdstat_zrange:calls=15,usec=0,usec_per_call=0.00
cmdstat_zrangebylex:calls=9,usec=0,usec_per_call=0.00
cmdstat_hset:calls=928198056,usec=9711351759,usec_per_call=10.46
cmdstat_hget:calls=1067669643,usec=11713887079,usec_per_call=10.97
cmdstat_hmget:calls=1,usec=0,usec_per_call=0.00
cmdstat_hgetall:calls=26512784,usec=27163615893,usec_per_call=1024.55
cmdstat_select:calls=329,usec=0,usec_per_call=0.00
cmdstat_keys:calls=47,usec=46877,usec_per_call=997.38
cmdstat_scan:calls=29,usec=0,usec_per_call=0.00
cmdstat_auth:calls=120661094,usec=627342335,usec_per_call=5.20
cmdstat_ping:calls=152752,usec=171884,usec_per_call=1.13
cmdstat_echo:calls=99179,usec=15628,usec_per_call=0.16
cmdstat_type:calls=86,usec=0,usec_per_call=0.00
cmdstat_info:calls=565310,usec=246166993,usec_per_call=435.45
cmdstat_ttl:calls=86,usec=0,usec_per_call=0.00
cmdstat_config:calls=151664,usec=2515820,usec_per_call=16.59
cmdstat_subscribe:calls=44686540,usec=246239888,usec_per_call=5.51
cmdstat_unsubscribe:calls=18485,usec=31247,usec_per_call=1.69
cmdstat_publish:calls=839400014,usec=15627343967,usec_per_call=18.62
cmdstat_client:calls=104693,usec=11409149,usec_per_call=108.98
cmdstat_slowlog:calls=5526,usec=3249910,usec_per_call=588.11
# Keyspace

db0:keys=3081,expires=2744,avg_ttl=34850820
db1:keys=2,expires=0,avg_ttl=0

My config had problem?! How do I solve this problem?

**Comment by enricogior** [comment]
Hi @noinhotnn,
what client do you use to do the read?

**Comment by noinhotnn** [comment]
Hi @enricogior, 
I have a .Net application use ServiceStack.Redis to read. Here is my code:
Redis.GetValueFromHash("420", "420301228");

**Comment by enricogior** [comment]
@noinhotnn 
I was asking because there are clients such StackExchange.Redis that sometimes have issues, but ServiceStack.Redis should be ok.

I recently fixed (2.8.2101 and later) the [native latency monitor](http://redis.io/topics/latency-monitor) statistics. I don't know if on 2.8.17 the latency monitor is usable, but you may give it a try and see if it provides any insight for the problem of the slow read.

**Comment by enricogior** [comment]
@noinhotnn 
closing the issue since it refer to an old release and for lack of activity.
Please feel free to reopen it if needed.
Thank you.
