### ISSUE TITLE
Redis for Windows In production - Success story

### ISSUE THREAD

**Issue by satish860** [microsoftarchive/redis#308]
Hi All,
      We are running Redis for windows in production for large insurance company claim system with heavy load for past 6 months and I can definitely say it very reliable and fast . There are few things which feel as a community we can improve

1) Monitoring tool for windows in production. Something NewRelic addon for windowshttp://newrelic.com/plugins/vmware-29/124
2) Redis senital tool improvement.
3) Support forum for logging issues(Enterprise chores)

**Comment by orangemocha** [comment]
Thanks for sharing the good news, @satish860 ! Which version(s) of Redis have you been running in production?

1) A NewRelic addon would be great to have. It doesn't look like http://newrelic.com/plugins/vmware-29/124 is open source, so we'd probably have to develop one from scratch.
2) Which improvements would you like to see?
3) I am not sure I understand :) Could you please elaborate?
