### ISSUE TITLE
Not able to create multiple Redis windows services in a server

### ISSUE THREAD

**Issue by SwapnaliT** [microsoftarchive/redis#312]
I am trying to create a new redis windows service. There is a service that already exists in the server listening on a port. I have created the second service with the below command 
C:\Program Files\Redis>redis-server.exe --service-install --service-name redisa -port 6379 -config "C:\Program Files\Redis\redis.windowsA.conf"

I am able to see the service created. When I am trying to start the service I am getting error
C:\Program Files\Redis>redis-server.exe --service-start --service-name redisa
[4528] 09 Sep 13:11:51.291 # Redis service failed to start.

I tried creating a server instance using command prompt that uses the same config and port as the newly created service. I am able to start the server and execute commands through the client.

Are there any other steps to be performed while creating multiple redis windows services in a server. I have installed Redis-x64-2.8.2101 version of redis on Windows Server 2008 R2.

**Comment by enricogior** [comment]
Hi @SwapnaliT 
make sure the two services are using two different port numbers.
The latest [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) has a better error reporting in case of startup failure (it writes to the Event Log if there is any Windows-spefic error).

**Comment by SwapnaliT** [comment]
Hello,
Both the services are using different ports. I tried using the version 2.8.2103. No error messages are logged in the Redis view. In the System view event data logged is mentioned below from SCM.
redisa
1
60000
1
Restart the service
The handle is invalid

**Comment by SwapnaliT** [comment]
Hello,
I was able to start the service successfully by changing the sequence of parameters to the service-install command
C:\Program Files\Redis>redis-server.exe --service-install "C:\Program Files\Redi
s\redis.windowsA.conf" --service-name "RedisA"
