### ISSUE TITLE
Redis crashed after a few days

### ISSUE THREAD

**Issue by wkleu** [microsoftarchive/redis#325]
Our redis service crashed, it it is the first time this happened. The service was up for days at the time.

Our redis version: Redis server v=2.8.21 sha=00000000:0 malloc=dlmalloc-2.8 bits=64 build=e84b20ff4e0813fa

The strack trace in the logs

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[3804] 29 Sep 08:59:14.514 # === ASSERTION FAILED OBJECT CONTEXT ===
[3804] 29 Sep 08:59:14.514 # Object type: 9
[3804] 29 Sep 08:59:14.514 # Object encoding: 6
[3804] 29 Sep 08:59:14.514 # Object refcount: 537529644
[3804] 29 Sep 08:59:14.514 # === ASSERTION FAILED ===
[3804] 29 Sep 08:59:14.514 # ==> ..\src\rdb.c:336 'obj->encoding == REDIS_ENCODING_RAW' is not true
[3804] 29 Sep 08:59:14.521 # --- EXCEPTION_ACCESS_VIOLATION
[3804] 29 Sep 08:59:14.521 # --- STACK TRACE
redis-server.exe!LogStackTrace(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:96)(0x0013EA10, 0x0013FF90, 0x00000001, 0x00000000)
redis-server.exe!UnhandledExceptiontHandler(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x00000000, 0x00000000, 0x00000000, 0x00000003)
KERNELBASE.dll!UnhandledExceptionFilter(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x00000000, 0x4EE71AD0, 0x00000000, 0x0013FF20)
ntdll.dll!memset(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x40016B9D, 0x00000000, 0x0013F150, 0x4005555F)
ntdll.dll!_C_specific_handler(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x00000000, 0x0013EB80, 0x0013F640, 0x0013F640)
ntdll.dll!_chkstk(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x00000001, 0x51A00000, 0x00000000, 0x51B3309C)
ntdll.dll!RtlRaiseException(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0x0000004C, 0x00000000, 0xFFAC4160, 0xFF01B4A0)
ntdll.dll!KiUserExceptionDispatcher(d:\redis\msot1\src\win32_interop\win32_stacktrace.cpp:185)(0xCE2A683B, 0x40132308, 0x40135718, 0x00000150)
redis-server.exe!rdbSaveStringObject(d:\redis\msot1\src\rdb.c:336)(0x0013F880, 0x00000001, 0xFF01B401, 0xFFAE13C0)
redis-server.exe!rdbSaveObject(d:\redis\msot1\src\rdb.c:605)(0x0013F880, 0x00000001, 0xFEFDCF70, 0x00000001)
redis-server.exe!rdbSaveRio(d:\redis\msot1\src\rdb.c:692)(0x4012C210, 0x000000F8, 0x00000000, 0x03202764)
redis-server.exe!rdbSave(d:\redis\msot1\src\rdb.c:760)(0x000000F8, 0x55F7831A, 0x000000F8, 0x000000F8)
redis-server.exe!QForkChildInit(d:\redis\msot1\src\win32_interop\win32_qfork.cpp:311)(0xFFFFFFFF, 0x00000000, 0x02200000, 0x0000010C)
redis-server.exe!QForkStartup(d:\redis\msot1\src\win32_interop\win32_qfork.cpp:769)(0x001E7E00, 0x00000000, 0xFFFFE000, 0x00000000)
redis-server.exe!main(d:\redis\msot1\src\win32_interop\win32_qfork.cpp:1398)(0x00000000, 0x00000000, 0xFFFFE000, 0xFFFFE000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x40033D5C, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x4F2913B0, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[3804] 29 Sep 08:59:14.661 # --- INFO OUTPUT
[2588] 29 Sep 08:59:15.611 # fork operation failed
[2588] 29 Sep 08:59:16.101 # Background saving terminated by signal 1
[2588] 29 Sep 08:59:16.202 \* 10 changes in 300 seconds. Saving...
[4292] 29 Sep 08:59:16.658 #

**Comment by enricogior** [comment]
Hi @wkleu,
the log you posted looks identical to one of the problems that was fixed, so I suggest to upgrade to [v2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103).
Thank you.

**Comment by enricogior** [comment]
@wkleu 
closing the issue since it refer to an old release and for lack of activity.
Please feel free to reopen it if needed.
Thank you.
