### ISSUE TITLE
Redis service frequently crashes

### ISSUE THREAD

**Issue by russellseymour-asos** [microsoftarchive/redis#326]
I am running Redis 64 bit version 2.8.21 on the following specification of server:

OS: Windows 2012 R2
RAM: 8 GB
CPU: 4

(This is a Virtual Machine running in VMWare)

Redis has been installed using 'Chocolatey'.

Frequently the service crashes with no real information about what has happened.  The log level is set to debug.  The following shows the last x crashes:

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[4380] 28 Sep 20:43:13.186 # --- ABORT
[4380] 28 Sep 20:43:13.186 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[4184] 29 Sep 15:01:20.150 # --- EXCEPTION_ACCESS_VIOLATION
[4184] 29 Sep 15:01:20.150 # --- INFO OUTPUT

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[4352] 29 Sep 20:38:21.756 # --- EXCEPTION_ACCESS_VIOLATION
[4352] 29 Sep 20:38:21.756 # --- INFO OUTPUT

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[3100] 30 Sep 15:05:56.650 # --- ABORT
[3100] 30 Sep 15:05:56.650 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[3464] 30 Sep 18:06:12.481 # --- EXCEPTION_ACCESS_VIOLATION
[3464] 30 Sep 18:06:12.481 # --- INFO OUTPUT

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[4544] 01 Oct 07:27:53.843 # --- EXCEPTION_ACCESS_VIOLATION
[4544] 01 Oct 07:27:53.843 # --- INFO OUTPUT
```

There does not appear to be a pattern or a specific duration in which the service crashes.  Redis is used for 'Logstash' and for queuing up other tasks.

I have not modified any of the settings in the configuration file regarding memory allocation.  It is pretty much out of the box.  However as there is nothing to go on in the BUG REPORT I am not sure would need to be change anyway.

Service manager still sees the Redis service as running, although it is not possible to connect.  Restarting the service allows clients to connect again.  This is not ideal as the service is not self healing so we are missing log and monitoring alerts.

Any suggestion on how to fix this would be greatly appreciated.

Russell

**Comment by enricogior** [comment]
Hi @russellseymour-asos 
2.8.21 had several issues that have been fixed, unfortunately we haven't released the chocolatey packages yet, but you should definitely upgrade to [2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103).

**Comment by enricogior** [comment]
@russellseymour-asos 
closing this issue since it refer to an old release and for lack of activity.
Please feel free to reopen it if needed.
Thank you.
