### ISSUE TITLE
inconsistency (with Linux implementation) for float rounding

### ISSUE THREAD

**Issue by clca** [microsoftarchive/redis#33]
MS 2.6.8-pre2 / x64 on Windows 8 x64:
redis 127.0.0.1:6379> set foo 2
OK
redis 127.0.0.1:6379> incrbyfloat foo 1.1
"3.1000000000000001"
redis 127.0.0.1:6379> incrbyfloat foo 5.0
"8.0999999999999996"
redis 127.0.0.1:6379> incrbyfloat foo -2.0
"6.0999999999999996"
redis 127.0.0.1:6379> incrbyfloat foo -1.0
"5.0999999999999996"
redis 127.0.0.1:6379> incrbyfloat foo -5.0
"0.09999999999999965"
redis 127.0.0.1:6379> incrbyfloat foo 2.0
"2.0999999999999996"
redis 127.0.0.1:6379> get foo
"2.0999999999999996"
And this is the main 2.6.9 on Centos x64
redis 127.0.0.1:6379> set foo 2
OK
redis 127.0.0.1:6379> incrbyfloat foo 1.1
"3.1"
redis 127.0.0.1:6379> incrbyfloat foo 5.0
"8.1"
redis 127.0.0.1:6379> incrbyfloat foo -2.0
"6.1"
redis 127.0.0.1:6379> incrbyfloat foo -1.0
"5.1"
redis 127.0.0.1:6379> incrbyfloat foo -5.0
"0.1"
redis 127.0.0.1:6379> incrbyfloat foo 2.0
"2.1"
redis 127.0.0.1:6379> get foo
"2.1"

**Comment by HenryRawas** [comment]
Made a fix by changing the printf format from %.17Lf to %.15Lf. The above tests now produce the same results.
