### ISSUE TITLE
Sentinel announce-ip

### ISSUE THREAD

**Issue by rpannell** [microsoftarchive/redis#330]
We are trying to setup sentinel on our end and are having issues with the servers because the servers have multiple ip addresses for the specific server dns name.  I am looking at the sentinel configuration and I see "sentinel announce-ip A.B.C.D" and I am pretty sure this is the command I need to only announce to a specific ip address.  Just link the BIND configuration for Redis.

When I turn on that setting in the sentinel config file the service will not start and in the event log it states "unknown subcommand announce-ip".

Look at the sentinel.cpp it looks like the command is known, but the Win32_CommandLine doesn't have it in it's list of known commands causing the issue when starting.

Before I ask for a pull request to fix this over the weekend, is this known behavior for a reason?  Same goes for announce-port as well.

Thanks

**Comment by rpannell** [comment]
And by the way, the sentinel does work just fine.  The issue is the log getting filled very very quickly because of a "duplicate sentinel" messages that I believe would be fixed if the announced ip address is set, but I could be wrong with that belief.

Thanks

**Comment by enricogior** [comment]
Hi @rodgod20 
thank you for looking into the issue.
I don't know if there was any good reason to not support the command, I guess it was just an oversight during the porting.
Please, feel free to send a PR.
Thank you.

**Comment by enricogior** [comment]
The PR has been included in 2.8.2104. Closing the issue.
