### ISSUE TITLE
Estimating Redis memory consumption

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#334]
I've been using Redis for Windows for a couple of new features, and I noticed that the amount of memory display by info command is not the same as memory consumed by the redis-server process (I look at Working Set column in Process Explorer). I guess value shown by info command is more accurate and is the actual upper bound on the memory usage? Maybe there's some compression involved?

**Comment by enricogior** [comment]
@chester89 
the value shown by the INFO command is the actual memory used by Redis for the dataset and the internal data structures, but it's not all the actual memory used by Redis on Windows since the Windows implementation requires Windows-specific data that adds memory usage to the value returned by the INFO command.

**Comment by chester89** [comment]
so even then the numbers provided by INFO are not complete? I see

2015-10-12 21:38 GMT+03:00 Enrico Giordani notifications@github.com:

> @chester89 https://github.com/chester89
> the value shown by the INFO command is the actual memory used by Redis for
> the dataset and the internal data structures, but it's not all the actual
> memory used by Redis on Windows since the Windows implementation requires
> Windows-specific data that adds memory usage to the value returned by the
> INFO command.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/334#issuecomment-147487147.

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment]
@chester89 
INFO is still the original code from the Linux version, so it only shows the "internal" memory usage.
We would like to add the Windows-specific info as well, but it's a low priority task.
