### ISSUE TITLE
Performance at Windows 10

### ISSUE THREAD

**Issue by volodin-aa** [microsoftarchive/redis#337]
There is some performance degradation Redis-x64-3.0.300-alpha 3 in Windows 10, compared with Docker VM

![Docker Redis 2.8, Docker Redis 3.0.3 vs Windows 10 Redis 3.0](http://tweak.su/files/redis-3-at-windows/redis-3.png)

**Comment by enricogior** [comment]
Hi @volodin-aa,
thanks for reporting the issue, but since 3.0 is still in alpha the performance are not a main goal.
Also, in general matching the 2.8 performance is not a goal. The main goal of 3.0 will be clear when we will announce the beta1.
Thank you.

**Comment by enricogior** [comment]
@volodin-aa 
the [stable release](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500) has been released yesterday.
I'm closing this issue. Feel free to reopen it if needed.
Thank you.
