### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by mcandre** [microsoftarchive/redis#34]
Can developers compile redis for Windows via MinGW? It would be nice to not have to depend on Visual Studio.

**Comment by clca** [comment]
We don't have plans to support minGW. Redis can be compiled using Visual Studio Express (free download) so we don't think there is a strong need to provide the ability to compile using other toolsets.

**Comment by mcandre** [comment]
It's convenient not to depend on a particular C compiler, but instead to allow developers to use their preferred C compiler. This flexibility makes developer's lives a lot easier--setting up complicated and redundant dev environments is not fun.
