### ISSUE TITLE
Redis on Windows Setup Wizard ended prematurely 3.0.300, windows server 2008

### ISSUE THREAD

**Issue by Coop197823** [microsoftarchive/redis#341]
Unfortunately, I have run into this same issue with 3.0.300-alpha3 on windows server 2008 r2. Any workaround to get this up and running? I did have it up and running on the same machine with server 2008, but had to do a full reformat and install. Now when I try to install it, I get the Redis on Windows Setup Wizard ended prematurely error.

Here is my log:

=== Verbose logging started: 10/18/2015 19:07:57 Build type: SHIP UNICODE 5.00.7601.00 Calling process: C:\Windows\system32\msiexec.exe ===
 MSI (c) (CC:A4) [19:07:57:457]: Font created. Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (CC:A4) [19:07:57:457]: Font created. Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (CC:F4) [19:07:57:473]: Resetting cached policy values
 MSI (c) (CC:F4) [19:07:57:473]: Machine policy value 'Debug' is 0
 MSI (c) (CC:F4) [19:07:57:473]: ******\* RunEngine:
 ******\* Product: C:\Redis-x64-3.0.300-alpha3.msi
 ******\* Action: 
 ******\* CommandLine: **********
 MSI (c) (CC:F4) [19:07:57:473]: Machine policy value 'DisableUserInstalls' is 0
 MSI (c) (CC:F4) [19:07:57:473]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 3: 2 
 MSI (c) (CC:F4) [19:07:57:473]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'C:\Redis-x64-3.0.300-alpha3.msi' against software restriction policy
 MSI (c) (CC:F4) [19:07:57:473]: Note: 1: 2262 2: �DigitalSignature 3: -2147287038 
 MSI (c) (CC:F4) [19:07:57:473]: SOFTWARE RESTRICTION POLICY: C:\Redis-x64-3.0.300-alpha3.msi is not digitally signed
 MSI (c) (CC:F4) [19:07:57:473]: SOFTWARE RESTRICTION POLICY: C:\Redis-x64-3.0.300-alpha3.msi is permitted to run at the 'unrestricted' authorization level.
 MSI (c) (CC:F4) [19:07:57:473]: Cloaking enabled.
 MSI (c) (CC:F4) [19:07:57:473]: Attempting to enable all disabled privileges before calling Install on Server
 MSI (c) (CC:F4) [19:07:57:473]: End dialog not enabled
 MSI (c) (CC:F4) [19:07:57:473]: Original package ==> C:\Redis-x64-3.0.300-alpha3.msi
 MSI (c) (CC:F4) [19:07:57:473]: Package we're running from ==> C:\Redis-x64-3.0.300-alpha3.msi
 MSI (c) (CC:F4) [19:07:57:488]: APPCOMPAT: Compatibility mode property overrides found.
 MSI (c) (CC:F4) [19:07:57:488]: APPCOMPAT: looking for appcompat database entry with ProductCode '{498EE362-AF5F-4D9F-9A51-5EA4069000C7}'.
 MSI (c) (CC:F4) [19:07:57:488]: APPCOMPAT: no matching ProductCode found in database.
 MSI (c) (CC:F4) [19:07:57:488]: MSCOREE not loaded loading copy from system32
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'TransformsSecure' is 1
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'DisablePatch' is 0
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'AllowLockdownPatch' is 0
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'DisableLUAPatching' is 0
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'DisableFlyWeightPatching' is 0
 MSI (c) (CC:F4) [19:07:57:488]: APPCOMPAT: looking for appcompat database entry with ProductCode '{498EE362-AF5F-4D9F-9A51-5EA4069000C7}'.
 MSI (c) (CC:F4) [19:07:57:488]: APPCOMPAT: no matching ProductCode found in database.
 MSI (c) (CC:F4) [19:07:57:488]: Transforms are not secure.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding MsiLogFileLocation property. Its value is 'C:\Users\ccooper\Desktop\log.txt'.
 MSI (c) (CC:F4) [19:07:57:488]: Command Line: CURRENTDIRECTORY=C:\ CLIENTUILEVEL=0 CLIENTPROCESSID=1484 
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding PackageCode property. Its value is '{0F3F962B-84A8-4721-8E16-EBDBAFB2A3B6}'.
 MSI (c) (CC:F4) [19:07:57:488]: Product Code passed to Engine.Initialize: ''
 MSI (c) (CC:F4) [19:07:57:488]: Product Code from property table before transforms: '{498EE362-AF5F-4D9F-9A51-5EA4069000C7}'
 MSI (c) (CC:F4) [19:07:57:488]: Product Code from property table after transforms: '{498EE362-AF5F-4D9F-9A51-5EA4069000C7}'
 MSI (c) (CC:F4) [19:07:57:488]: Product not registered: beginning first-time install
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding ProductState property. Its value is '-1'.
 MSI (c) (CC:F4) [19:07:57:488]: Entering CMsiConfigurationManager::SetLastUsedSource.
 MSI (c) (CC:F4) [19:07:57:488]: User policy value 'SearchOrder' is 'nmu'
 MSI (c) (CC:F4) [19:07:57:488]: Adding new sources is allowed.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding PackagecodeChanging property. Its value is '1'.
 MSI (c) (CC:F4) [19:07:57:488]: Package name extracted from package path: 'Redis-x64-3.0.300-alpha3.msi'
 MSI (c) (CC:F4) [19:07:57:488]: Package to be registered: 'Redis-x64-3.0.300-alpha3.msi'
 MSI (c) (CC:F4) [19:07:57:488]: Note: 1: 2262 2: AdminProperties 3: -2147287038 
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'DisableMsi' is 1
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'AlwaysInstallElevated' is 0
 MSI (c) (CC:F4) [19:07:57:488]: User policy value 'AlwaysInstallElevated' is 0
 MSI (c) (CC:F4) [19:07:57:488]: Product installation will be elevated because user is admin and product is being installed per-machine.
 MSI (c) (CC:F4) [19:07:57:488]: Running product '{498EE362-AF5F-4D9F-9A51-5EA4069000C7}' with elevated privileges: Product is assigned.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding CURRENTDIRECTORY property. Its value is 'C:\'.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding CLIENTUILEVEL property. Its value is '0'.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding CLIENTPROCESSID property. Its value is '1484'.
 MSI (c) (CC:F4) [19:07:57:488]: TRANSFORMS property is now: 
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding VersionDatabase property. Its value is '200'.
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\Favorites
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Network Shortcuts
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\Documents
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Printer Shortcuts
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Recent
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\SendTo
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Templates
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\ProgramData
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Local
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\Pictures
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu\Programs
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Start Menu
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\Public\Desktop
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Administrative Tools
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Start Menu
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Users\ccooper\Desktop
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\ProgramData\Microsoft\Windows\Templates
 MSI (c) (CC:F4) [19:07:57:488]: SHELL32::SHGetFolderPath returned: C:\Windows\Fonts
 MSI (c) (CC:F4) [19:07:57:488]: Note: 1: 2898 2: MS Sans Serif 3: MS Sans Serif 4: 0 5: 16 
 MSI (c) (CC:F4) [19:07:57:488]: MSI_LUA: Setting AdminUser property to 1 because this is the client or the user has already permitted elevation
 MSI (c) (CC:F4) [19:07:57:488]: MSI_LUA: Setting MsiRunningElevated property to 1 because the install is already running elevated.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding MsiRunningElevated property. Its value is '1'.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding Privileged property. Its value is '1'.
 MSI (c) (CC:F4) [19:07:57:488]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\MS Setup (ACME)\User Info 3: 2 
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding USERNAME property. Its value is 'Windows User'.
 MSI (c) (CC:F4) [19:07:57:488]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\MS Setup (ACME)\User Info 3: 2 
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding DATABASE property. Its value is 'C:\Redis-x64-3.0.300-alpha3.msi'.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding OriginalDatabase property. Its value is 'C:\Redis-x64-3.0.300-alpha3.msi'.
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'MsiDisableEmbeddedUI' is 0
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding SourceDir property. Its value is 'C:\'.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding SOURCEDIR property. Its value is 'C:\'.
 MSI (c) (CC:A4) [19:07:57:488]: PROPERTY CHANGE: Adding VersionHandler property. Its value is '5.00'.
 === Logging started: 10/18/2015 19:07:57 ===
 MSI (c) (CC:F4) [19:07:57:488]: Note: 1: 2205 2: 3: PatchPackage 
 MSI (c) (CC:F4) [19:07:57:488]: Machine policy value 'DisableRollback' is 0
 MSI (c) (CC:F4) [19:07:57:488]: User policy value 'DisableRollback' is 0
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding UILevel property. Its value is '5'.
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding ACTION property. Its value is 'INSTALL'.
 MSI (c) (CC:F4) [19:07:57:488]: Doing action: INSTALL
 Action 19:07:57: INSTALL. 
 Action start 19:07:57: INSTALL.
 MSI (c) (CC:F4) [19:07:57:488]: UI Sequence table 'InstallUISequence' is present and populated.
 MSI (c) (CC:F4) [19:07:57:488]: Running UISequence
 MSI (c) (CC:F4) [19:07:57:488]: PROPERTY CHANGE: Adding EXECUTEACTION property. Its value is 'INSTALL'.
 MSI (c) (CC:F4) [19:07:57:488]: Doing action: FindRelatedProducts
 Action 19:07:57: FindRelatedProducts. Searching for related applications
 Action start 19:07:57: FindRelatedProducts.
 Action ended 19:07:57: FindRelatedProducts. Return value 1.
 MSI (c) (CC:F4) [19:07:57:488]: Doing action: PrepareDlg
 Action 19:07:57: PrepareDlg. 
 Action start 19:07:57: PrepareDlg.
 Info 2898.For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 0 character set, of 13 pixels height.
 Info 2898.For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
 Action 19:07:57: PrepareDlg. Dialog created
 Action ended 19:07:57: PrepareDlg. Return value 1.
 MSI (c) (CC:F4) [19:07:57:504]: Doing action: AppSearch
 Action 19:07:57: AppSearch. Searching for installed applications
 Action start 19:07:57: AppSearch.
 MSI (c) (CC:F4) [19:07:57:504]: Note: 1: 2205 2: 3: AppSearch 
 MSI (c) (CC:F4) [19:07:57:504]: Note: 1: 2228 2: 3: AppSearch 4: SELECT  Property ,  Signature_  FROM  AppSearch  
 Action ended 19:07:57: AppSearch. Return value 0.
 MSI (c) (CC:F4) [19:07:57:504]: Doing action: WixQueryOsWellKnownSID
 Action 19:07:57: WixQueryOsWellKnownSID. 
 Action start 19:07:57: WixQueryOsWellKnownSID.
 MSI (c) (CC:80) [19:07:57:504]: Invoking remote custom action. DLL: C:\Users\ccooper\AppData\Local\Temp\MSIDC5A.tmp, Entrypoint: WixQueryOsWellKnownSID
 MSI (c) (CC:64) [19:07:57:504]: Cloaking enabled.
 MSI (c) (CC:64) [19:07:57:504]: Attempting to enable all disabled privileges before calling Install on Server
 MSI (c) (CC:64) [19:07:57:504]: Connected to service for CA interface.
 MSI (c) (CC!C4) [19:07:57:551]: PROPERTY CHANGE: Adding WIX_ACCOUNT_LOCALSYSTEM property. Its value is 'NT AUTHORITY\SYSTEM'.
 MSI (c) (CC!C4) [19:07:57:551]: PROPERTY CHANGE: Adding WIX_ACCOUNT_LOCALSERVICE property. Its value is 'NT AUTHORITY\LOCAL SERVICE'.
 MSI (c) (CC!C4) [19:07:57:551]: PROPERTY CHANGE: Adding WIX_ACCOUNT_NETWORKSERVICE property. Its value is 'NT AUTHORITY\NETWORK SERVICE'.
 MSI (c) (CC!C4) [19:07:57:551]: PROPERTY CHANGE: Adding WIX_ACCOUNT_ADMINISTRATORS property. Its value is 'BUILTIN\Administrators'.
 MSI (c) (CC!C4) [19:07:57:566]: PROPERTY CHANGE: Adding WIX_ACCOUNT_USERS property. Its value is 'BUILTIN\Users'.
 MSI (c) (CC!C4) [19:07:57:566]: PROPERTY CHANGE: Adding WIX_ACCOUNT_GUESTS property. Its value is 'BUILTIN\Guests'.
 Action ended 19:07:57: WixQueryOsWellKnownSID. Return value 1.
 MSI (c) (CC:F4) [19:07:57:566]: Doing action: LaunchConditions
 Action 19:07:57: LaunchConditions. Evaluating launch conditions
 Action start 19:07:57: LaunchConditions.
 Action ended 19:07:57: LaunchConditions. Return value 1.
 MSI (c) (CC:F4) [19:07:57:566]: Doing action: ca_CheckIfFirewallServiceRunning
 Action 19:07:57: ca_CheckIfFirewallServiceRunning. 
 Action start 19:07:57: ca_CheckIfFirewallServiceRunning.
 MSI (c) (CC:E0) [19:07:57:566]: Invoking remote custom action. DLL: C:\Users\ccooper\AppData\Local\Temp\MSIDC9A.tmp, Entrypoint: CheckIfFirewallServiceRunning
 MSI (c) (CC:64) [19:07:57:566]: Cloaking enabled.
 MSI (c) (CC:64) [19:07:57:566]: Attempting to enable all disabled privileges before calling Install on Server
 MSI (c) (CC:64) [19:07:57:566]: Connected to service for CA interface.
 SFXCA: Extracting custom action to temporary directory: C:\Users\ccooper\AppData\Local\Temp\MSIDC9A.tmp-\
 SFXCA: Binding to CLR version v2.0.50727
 Calling custom action RedisMsi.CustomActions!RedisMsi.CustomActions.CustomActions.CheckIfFirewallServiceRunning
 Error: could not load custom action class RedisMsi.CustomActions.CustomActions from assembly: RedisMsi.CustomActions
 System.BadImageFormatException: Could not load file or assembly 'RedisMsi.CustomActions' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
 File name: 'RedisMsi.CustomActions'
 at System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
 at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
 at System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
 at System.AppDomain.Load(String assemblyString)
 at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.GetCustomActionMethod(Session session, String assemblyName, String className, String methodName)

WRN: Assembly binding logging is turned OFF.
 To enable assembly bind failure logging, set the registry value (DWORD) to 1.
 Note: There is some performance penalty associated with assembly bind failure logging.
 To turn this feature off, remove the registry value .

CustomAction ca_CheckIfFirewallServiceRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
 Action ended 19:07:57: ca_CheckIfFirewallServiceRunning. Return value 3.
 MSI (c) (CC:F4) [19:07:57:754]: Doing action: FatalError
 Action 19:07:57: FatalError. 
 Action start 19:07:57: FatalError.
 Action 19:07:57: FatalError. Dialog created
 MSI (c) (CC:BC) [19:07:57:754]: Note: 1: 2731 2: 0 
 Action ended 19:07:59: FatalError. Return value 2.
 Action ended 19:07:59: INSTALL. Return value 3.
 MSI (c) (CC:F4) [19:07:59:735]: Destroying RemoteAPI object.
 MSI (c) (CC:64) [19:07:59:735]: Custom Action Manager thread ending.
 Property(C): UpgradeCode = {05410198-7212-4FC4-B7C8-AFEFC3DA0FBC}
 Property(C): ADD_FIREWALL_RULE = 1
 Property(C): WixUIRMOption = UseRM
 Property(C): WIXUI_INSTALLDIR = INSTALLFOLDER
 Property(C): PORT = 6379
 Property(C): ALLUSERS = 1
 Property(C): ARPNOMODIFY = 1
 Property(C): ProgramFiles64Folder = C:\Program Files\
 Property(C): SourceDir = C:\
 Property(C): VersionNT = 601
 Property(C): ARPURLINFOABOUT = https://github.com/MSOpenTech/redis
 Property(C): FIREWALL_SERVICE_STOPPED = 0
 Property(C): Manufacturer = MSOpenTech
 Property(C): ProductCode = {498EE362-AF5F-4D9F-9A51-5EA4069000C7}
 Property(C): ProductLanguage = 1033
 Property(C): ProductName = Redis on Windows
 Property(C): ProductVersion = 3.0.300
 Property(C): DefaultUIFont = WixUI_Font_Normal
 Property(C): WixUI_Mode = InstallDir
 Property(C): ErrorDialog = ErrorDlg
 Property(C): SecureCustomProperties = WIX_ACCOUNT_NETWORKSERVICE;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED
 Property(C): MsiLogFileLocation = C:\Users\ccooper\Desktop\log.txt
 Property(C): PackageCode = {0F3F962B-84A8-4721-8E16-EBDBAFB2A3B6}
 Property(C): ProductState = -1
 Property(C): PackagecodeChanging = 1
 Property(C): CURRENTDIRECTORY = C:\
 Property(C): CLIENTUILEVEL = 0
 Property(C): CLIENTPROCESSID = 1484
 Property(C): VersionDatabase = 200
 Property(C): VersionMsi = 5.00
 Property(C): VersionNT64 = 601
 Property(C): WindowsBuild = 7601
 Property(C): ServicePackLevel = 1
 Property(C): ServicePackLevelMinor = 0
 Property(C): MsiNTProductType = 2
 Property(C): WindowsFolder = C:\Windows\
 Property(C): WindowsVolume = C:\
 Property(C): System64Folder = C:\Windows\system32\
 Property(C): SystemFolder = C:\Windows\SysWOW64\
 Property(C): RemoteAdminTS = 1
 Property(C): TempFolder = C:\Users\ccooper\AppData\Local\Temp\
 Property(C): ProgramFilesFolder = C:\Program Files (x86)\
 Property(C): CommonFilesFolder = C:\Program Files (x86)\Common Files\
 Property(C): CommonFiles64Folder = C:\Program Files\Common Files\
 Property(C): AppDataFolder = C:\Users\ccooper\AppData\Roaming\
 Property(C): FavoritesFolder = C:\Users\ccooper\Favorites\
 Property(C): NetHoodFolder = C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
 Property(C): PersonalFolder = C:\Users\ccooper\Documents\
 Property(C): PrintHoodFolder = C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
 Property(C): RecentFolder = C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\Recent\
 Property(C): SendToFolder = C:\Users\ccooper\AppData\Roaming\Microsoft\Windows\SendTo\
 Property(C): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
 Property(C): CommonAppDataFolder = C:\ProgramData\
 Property(C): LocalAppDataFolder = C:\Users\ccooper\AppData\Local\
 Property(C): MyPicturesFolder = C:\Users\ccooper\Pictures\
 Property(C): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
 Property(C): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
 Property(C): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
 Property(C): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
 Property(C): DesktopFolder = C:\Users\Public\Desktop\
 Property(C): FontsFolder = C:\Windows\Fonts\
 Property(C): GPTSupport = 1
 Property(C): OLEAdvtSupport = 1
 Property(C): ShellAdvtSupport = 1
 Property(C): MsiAMD64 = 16
 Property(C): Msix64 = 16
 Property(C): Intel = 16
 Property(C): PhysicalMemory = 16377
 Property(C): VirtualMemory = 31281
 Property(C): AdminUser = 1
 Property(C): MsiTrueAdminUser = 1
 Property(C): LogonUser = ccooper
 Property(C): UserSID = S-1-5-21-2976445286-4089514096-708120062-1104
 Property(C): UserLanguageID = 1033
 Property(C): ComputerName = SERVER-1
 Property(C): SystemLanguageID = 1033
 Property(C): ScreenX = 1440
 Property(C): ScreenY = 900
 Property(C): CaptionHeight = 19
 Property(C): BorderTop = 1
 Property(C): BorderSide = 1
 Property(C): TextHeight = 16
 Property(C): TextInternalLeading = 3
 Property(C): ColorBits = 32
 Property(C): TTCSupport = 1
 Property(C): Time = 19:07:59
 Property(C): Date = 10/18/2015
 Property(C): MsiNetAssemblySupport = 2.0.50727.4927
 Property(C): MsiWin32AssemblySupport = 6.1.7601.17514
 Property(C): RedirectedDllSupport = 2
 Property(C): MsiRunningElevated = 1
 Property(C): Privileged = 1
 Property(C): USERNAME = Windows User
 Property(C): DATABASE = C:\Redis-x64-3.0.300-alpha3.msi
 Property(C): OriginalDatabase = C:\Redis-x64-3.0.300-alpha3.msi
 Property(C): SOURCEDIR = C:\
 Property(C): VersionHandler = 5.00
 Property(C): UILevel = 5
 Property(C): ACTION = INSTALL
 Property(C): EXECUTEACTION = INSTALL
 Property(C): WIX_ACCOUNT_LOCALSYSTEM = NT AUTHORITY\SYSTEM
 Property(C): WIX_ACCOUNT_LOCALSERVICE = NT AUTHORITY\LOCAL SERVICE
 Property(C): WIX_ACCOUNT_NETWORKSERVICE = NT AUTHORITY\NETWORK SERVICE
 Property(C): WIX_ACCOUNT_ADMINISTRATORS = BUILTIN\Administrators
 Property(C): WIX_ACCOUNT_USERS = BUILTIN\Users
 Property(C): WIX_ACCOUNT_GUESTS = BUILTIN\Guests
 === Logging stopped: 10/18/2015 19:07:59 ===
 MSI (c) (CC:F4) [19:07:59:750]: Note: 1: 1708 
 MSI (c) (CC:F4) [19:07:59:750]: Product: Redis on Windows -- Installation failed.

MSI (c) (CC:F4) [19:07:59:750]: Windows Installer installed the product. Product Name: Redis on Windows. Product Version: 3.0.300. Product Language: 1033. Manufacturer: MSOpenTech. Installation success or error status: 1603.

MSI (c) (CC:F4) [19:07:59:750]: Grabbed execution mutex.
 MSI (c) (CC:F4) [19:07:59:750]: Cleaning up uninstalled install packages, if any exist
 MSI (c) (CC:F4) [19:07:59:750]: MainEngineThread is returning 1603
 === Verbose logging stopped: 10/18/2015 19:07:59 ===

**Comment by enricogior** [comment]
Hi @Coop197823 
what .Net versions are installed on the machine?
You can use the following command to list them all `dir %WINDIR%\Microsoft.Net\Framework\v* /O:-N /B`.
Thank you.

P.S. [v3.0.300-beta1 is available](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.300-beta1).

**Comment by Coop197823** [comment]
I was using an old version of .net, and installed the .net 4.5, and that resolved the issue.  Thanks for your help!

**Comment by mateuslacorte** [comment]
> 
> 
> I was using an old version of .net, and installed the .net 4.5, and that resolved the issue. Thanks for your help!

Thanks!
