### ISSUE TITLE
Redis Instances (Master and Slave) crahes with memory error:

### ISSUE THREAD

**Issue by tellan55** [microsoftarchive/redis#347]
Hi there,

I have a Master/Slave HA cluster both running with the latest version 2.8.21.04, running in different servers.
I am getting every certain time the following memory error bug reportin both, Master first and when migrate to the slave in the slave also.

Master memory bug report:

[1416] 24 Oct 03:06:46.194 - DB 0: 746 keys (746 volatile) in 2048 slots HT.
[1416] 24 Oct 03:06:46.194 - 208 clients connected (1 slaves), 628833184 bytes in use
[1416] 24 Oct 03:06:51.662 - DB 0: 744 keys (744 volatile) in 2048 slots HT.
[1416] 24 Oct 03:06:51.662 - 208 clients connected (1 slaves), 628850128 bytes in use
[1416] 24 Oct 03:06:57.131 - DB 0: 744 keys (744 volatile) in 2048 slots HT.
[1416] 24 Oct 03:06:57.131 - 208 clients connected (1 slaves), 628867408 bytes in use
[1416] 24 Oct 03:06:58.397 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1416] 24 Oct 03:06:58.397 # Out Of Memory allocating 179909393 bytes.
[1416] 24 Oct 03:06:58.397 # --- ABORT
[1416] 24 Oct 03:06:58.397 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00000016, 0x8AB1C2E8, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:206)(0x00000016, 0x392481AE, 0x40150880, 0x7716912A)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0x00000000, 0x0AB93311, 0x00000000)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x0AB93311, 0x4013F888, 0x0AB93311, 0x00000000)
redis-server.exe!redisOutOfMemoryHandler(c:\release\redis\src\redis.c:3397)(0xC3970010, 0x0AA92C15, 0x0AABFFD0, 0x8AB1C2E8)
redis-server.exe!zrealloc(c:\release\redis\src\zmalloc.c:183)(0x0AB93308, 0x000006F3, 0x9027D070, 0x96C9AF70)
redis-server.exe!sdscatlen(c:\release\redis\src\sds.c:246)(0x902E7FB0, 0x96C9ACC0, 0xB133CD30, 0x902E7FB0)
redis-server.exe!appendCommand(c:\release\redis\src\t_string.c:433)(0xB133CD30, 0x01E6483E, 0x00000007, 0x00000000)
redis-server.exe!call(c:\release\redis\src\redis.c:2016)(0x562B2E12, 0x4008B000, 0x00000001, 0x00000027)
redis-server.exe!processCommand(c:\release\redis\src\redis.c:2235)(0xB133CD30, 0x00000027, 0x000007F8, 0x00000001)
redis-server.exe!processInputBuffer(c:\release\redis\src\networking.c:1274)(0xB133CD30, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!readQueryFromClient(c:\release\redis\src\networking.c:1329)(0xFFF304F0, 0x00000001, 0x88C86EF0, 0x000000D8)
redis-server.exe!aeMain(c:\release\redis\src\ae.c:487)(0x5622607C, 0x4013B14C, 0x00000000, 0x00000001)
redis-server.exe!redis_main(c:\release\redis\src\redis.c:3524)(0x00265740, 0x00000004, 0x5622607C, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1363)(0x00000008, 0xFFFFFFFF, 0x00000008, 0x00265770)
redis-server.exe!ServiceWorkerThread(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[1416] 24 Oct 03:06:58.600 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

Slave memory bug report:
[904] 24 Oct 04:29:19.330 - DB 0: 1854 keys (1854 volatile) in 2048 slots HT.
[904] 24 Oct 04:29:19.330 - 202 clients connected (0 slaves), 677140984 bytes in use
[904] 24 Oct 04:29:24.814 - DB 0: 1856 keys (1856 volatile) in 2048 slots HT.
[904] 24 Oct 04:29:24.814 - 202 clients connected (0 slaves), 677428968 bytes in use
[904] 24 Oct 04:29:26.127 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[904] 24 Oct 04:29:26.127 # Out Of Memory allocating 189468974 bytes.
[904] 24 Oct 04:29:26.127 # --- ABORT
[904] 24 Oct 04:29:26.127 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00000016, 0x9A650C08, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:206)(0x00000016, 0x3CC3F3B4, 0x40150880, 0x7719912A)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0x00000000, 0x0B4B112E, 0x00000000)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x0B4B112E, 0x4013F888, 0x0B4B112E, 0x00000000)
redis-server.exe!redisOutOfMemoryHandler(c:\release\redis\src\redis.c:3397)(0xE21B0010, 0x0B3B1038, 0x0B3BFFD0, 0x9A650C08)
redis-server.exe!zrealloc(c:\release\redis\src\zmalloc.c:183)(0x0B4B1125, 0x000000ED, 0x9E696880, 0x9A6500A0)
redis-server.exe!sdscatlen(c:\release\redis\src\sds.c:246)(0x9C3B5F40, 0xB7BD4C80, 0x8AB63BC0, 0x9C3B5F40)
redis-server.exe!appendCommand(c:\release\redis\src\t_string.c:433)(0x8AB63BC0, 0x020144DF, 0x00000007, 0x00000000)
redis-server.exe!call(c:\release\redis\src\redis.c:2016)(0x562B4166, 0x4008B000, 0x00000001, 0x0000019C)
redis-server.exe!processCommand(c:\release\redis\src\redis.c:2235)(0x8AB63BC0, 0x0000019C, 0x000001F1, 0x00000001)
redis-server.exe!processInputBuffer(c:\release\redis\src\networking.c:1274)(0x8AB63BC0, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!readQueryFromClient(c:\release\redis\src\networking.c:1329)(0xFFF33390, 0x00000001, 0x88C86F10, 0x000000D8)
redis-server.exe!aeMain(c:\release\redis\src\ae.c:487)(0x562380B6, 0x4013B14C, 0x00000000, 0x00000001)
redis-server.exe!redis_main(c:\release\redis\src\redis.c:3524)(0x00385700, 0x00000004, 0x562380B2, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1363)(0x00000008, 0xFFFFFFFF, 0x00000008, 0x00385730)
redis-server.exe!ServiceWorkerThread(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:485)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[904] 24 Oct 04:29:26.533 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

Master Redis.windows.conf:

port 6379
timeout 0
bind 0.0.0.0
tcp-keepalive 0
loglevel debug
logfile "d:\ROW\STDOUT\stdout"
syslog-enabled yes
syslog-ident "redis"
databases 1
requirepass "####################"
# rename-command CONFIG EMOSEWA
###### ####################RDB

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename "dump.rdb"
dir "c:\ROW\RDB_AOF"
maxheap 2000000000
heapdir D:\ROW\HEAP\
###### ###############RDB END

maxmemory 750mb
maxmemory-policy volatile-lru
maxmemory-samples 3
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10

Slave redis.windows.conf:

port 6379
timeout 0
bind 0.0.0.0
tcp-keepalive 0
loglevel verbose
logfile "d:\ROW\STDOUT\stdout"
syslog-enabled yes
syslog-ident "redis"
databases 1
slaveof  x.x.x.x  6379
masterauth "################"
slave-serve-stale-data yes
repl-ping-slave-period 10
repl-timeout 60
slave-priority 100
requirepass "################"
# rename-command CONFIG EMOSEWA
###### ####################RDB

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename "dump.rdb"
dir "c:\ROW\RDB_AOF"
maxheap 2000000000
heapdir D:\ROW\HEAP\
###### ###############RDB END

maxmemory 750mb
maxmemory-policy volatile-lru
maxmemory-samples 3
lua-time-limit 5000
slowlog-log-slower-than 10000
slowlog-max-len 128
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-entries 512
list-max-ziplist-value 64
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10

Thanks

**Comment by enricogior** [comment]
Hi @tellan55 
the server is trying to allocate 180 MB and the memory allocator fails.
It may be caused by the heap fragmentation, something we are fixing in Redis on Windows 3.0 removing the maxheap limit and using an allocator that has a better heap fragmentation management.
The only workaround I can suggest is to increase the maxheap limit.

**Comment by tellan55** [comment]
Hi @enricogior 

In the Redis.windows.conf files for both Master and Slave the "maxheap 2000000000" should cover that memory limit since has been set for 2 GB; that value is bigger of 2.5 x "maxmemory 750mb" (2.5 x 750mb = 1.875 GB)

What value should I set for the maxheap?
Thanks,

**Comment by enricogior** [comment]
@tellan55 
there isn't a "magic" value, it depends on the type of allocation that is happening in your system.
If the individual data objects are large, it's more probable that the heap will get fragmented causing the out of memory error.
With allocation of 180MB objects, 750MB of max memory and 2GB of heap seems to be not enough to prevent the heap fragmentation.
So you should increase the maxheap as much as your system can handle.

**Comment by orangemocha** [comment]
@tellan55 you could also try the 3.0 beta, which shouldn't be affected by this problem.

**Comment by tellan55** [comment]
@orangemocha 

Great success so far (48 hours and counting with not errors) using 3.0 Beta, however I can't move it to our production environment since it is in Beta Version.

I am canceling all persistence in our production environment for now. I will report back if there are any issues in this matter with this version.

Closing the ticket

Thanks for the help!!!

**Comment by enricogior** [comment]
@tellan55 
thank you for the feedback on the 3.0 beta.
