### ISSUE TITLE
MSI install service stopped by default

### ISSUE THREAD

**Issue by baywet** [microsoftarchive/redis#349]
Hi Guys,
For security reason we'd like the service to be stopped when installing redis using the MSI.
I couldn't find any documentation on how to do that.
Is it possible?
Thanks!

**Comment by enricogior** [comment]
Hi @baywet 
the MSI setup doesn't have a flag to do what you are asking.
It is possible to add the feature but we can't provide a release date right now.
Thank you.

**Comment by baywet** [comment]
@enricogior Thanks for the fast reply. We'll surely use it when it comes out. Right not we just do a net stop be it'd be better this way.

**Comment by orangemocha** [comment]
For future reference, this could be designed as a checkbox that says "Start the service after installation", checked by default. Pull requests are welcome! :wink:

**Comment by baywet** [comment]
As we embed Redis's installation in our product, we're more looking for a option to the msi, but sure having a checkbox too would be great.

**Comment by enricogior** [comment]
@baywet 
the checkbox implies the presence of an MSI option as well.
