### ISSUE TITLE
Restore throws error "Error in payload or checksum"

### ISSUE THREAD

**Issue by acharyarajiv** [microsoftarchive/redis#35]
I'm trying to execute redis commands using nodeJs(node_redis from https://github.com/nitesh123/node_redis ) for windows

After dumping a key the encoded value returned has 10 extra bits appended to it.
On restore of dumped key with this encoded value these extra 10 bits are decoded and checked for its integrity

![5c4de344-9771-11e2-889e-b1dda04d05b7](https://f.cloud.github.com/assets/3601851/343481/4c3722e8-9de0-11e2-8ee4-a5482c2338e9.png)

In the above image what i did is 
set key value 
dump key
which returned a encoded string value

and then on restore the first 2 bits of the value of footer variable is checked against REDIS_RDB_Version (which is 6) and since the value donot match it throws the checksum error. Please refer the below image

![New](https://f.cloud.github.com/assets/3601851/343488/78be6aa6-9de0-11e2-871f-28532b5ed037.png)

**Comment by HenryRawas** [comment]
I tried to repro this using the redis-cli.exe that is part of this project.
It seems to work fine, but the way that the dumped string is deserialized by the client app is different. I think this is a bug in the node_redis client.
Here is the text version. Image below
C:\redisrun>redis-cli
redis 127.0.0.1:6379> set name ajay
OK
redis 127.0.0.1:6379> dump name
"\x00\x04ajay\x06\x00H\x17\xff\xd3-\xb9\xc9\xd9"
redis 127.0.0.1:6379> del name
(integer) 1
redis 127.0.0.1:6379>  name 0 "\x00\x04ajay\x06\x00H\x17\xff\xd3-\xb9\xc9\xd9"
OK
redis 127.0.0.1:6379> get name
"ajay"
redis 127.0.0.1:6379>

![redisdump](https://f.cloud.github.com/assets/849736/345234/e3ec4c2c-9e1b-11e2-84a9-5da433eea750.PNG)
