### ISSUE TITLE
Win32_Interop.lib unresolved external symbol listAddNodeTail, aeWait, etc.

### ISSUE THREAD

**Issue by quantjin** [microsoftarchive/redis#350]
Hello, I'm using hiredis on windows 7 32-bit, Visual Studio 2013 Express

The redis and hiredis can be build without error.

But when I tried to build hiredis/example/libuv or libevent, I'm getting 'unresolved external symbol' error message from Win32_Interop.lib, the missing functions are listAddNodeTail, aeWait, etc.

my test project link to hiredis.lib,Win32_Interop.lib,libuv.lib (or libevent.lib) 

Please help, thanks!

**Comment by enricogior** [comment]
Hi @JerryYangJin 
we are aware of the issue and we are going to fix it.
We don't have a release date yet.
We'll let you know when the fix will be available.
Thank you.

**Comment by quantjin** [comment]
@enricogior , thank you for your update!

**Comment by enricogior** [comment]
From now on for hiredis and hiredis issues please visit https://github.com/Microsoft/hiredis.
Thank you.

**Comment by dhdepddl** [comment]
@enricogior  is this bug fixed?

**Comment by enricogior** [comment]
Hi @dhdepddl 
I don't work anymore on this project.
