### ISSUE TITLE
Trouble with Keyspace Events

### ISSUE THREAD

**Issue by ghost** [microsoftarchive/redis#351]
I followed the steps listed here (http://www.yanted.com/2014/01/07/keyspace-events-in-redis-2-8/) to test keyspace events on my local machine.  From a fresh install, I did a "config set notify-keyspace-events KEA" followed by a "config get notify-keyspace-events" to make sure that everything was set properly. I then ran redis-cli --csv subscribe '**keyspace@0**:foo'.  From another command prompt, I ran SET and DEL operations on key foo.  Those operations performed as expected, but no messages were seen in my command prompt that was subscribed to the keyspace channel.

**Comment by ghost** [comment]
Disregard.

**Comment by pasteusernamehere** [comment]
So what did you do to resolve this?  I am seeing the exact same behaviour. Same test running Redis on OSX works as expected.

**Comment by pasteusernamehere** [comment]
Never mind I found it:

redis-cli --csv psubscribe '**key***:_' should be redis-cli --csv psubscribe "__key___:*"
