### ISSUE TITLE
AOF file does not get rewritten

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#352]
When I put Redis in production, I also declared I want AOF file to be rewritten when certain criterias are met:
appendonly yes
appendfilename myfilename.aof

appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes

But lately I noticed that the AOF file is 82Mb already and it doesn't get compacted. Did I misread the docs or is my configuration wrong? When I did initial tests for the system with 2101 build, AOF rewriting was working fine. Now I'm on 2103 (recently updated from 2101)

**Comment by enricogior** [comment]
Hi @chester89 
the fact that the AOF is 82MB is perfectly fine with the settings.
Redis will not compact the AOF unless it's at least 64MB and unless it has grown 100% compared to the last time the rewrite occurred.

**Comment by chester89** [comment]
oh, I see. Thanks for the clarification.

2015-11-08 15:50 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89
> the fact that the AOF is 82MB is perfectly fine with the settings.
> Redis will not compact the AOF unless it's at least 64MB and unless it has
> grown 100% compared to the last time the rewrite occurred.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/352#issuecomment-154824615.

## 

Yours faithfully,
Gleb

**Comment by chester89** [comment]
This problem just resurfaced. Is there any way I can force AOF to be rewritten?

**Comment by chester89** [comment]
Is it safe to use `BGREWRITEAOF` command on a production Redis instance? I guess I can allow about 5 minutes of downtime

**Comment by enricogior** [comment]
@chester89 
sure, it's safe to call BGREWRITEAOF and it shouldn't cause a significant downtime, since it runs on a different process (performance may vary depending on the hardware). There is only a small amount of time (in the order of milliseconds) to synchronize the two processes, but no downtime while the child process persists the AOF file to disk.

**Comment by chester89** [comment]
@enricogior ok, thanks. will try that
