### ISSUE TITLE
Some files created by Redis are taking way too much space

### ISSUE THREAD

**Issue by geoffreybauduin** [microsoftarchive/redis#353]
Alright i'm not sure it's interesting for you, or if it's something going wrong on my side, but here it goes.

I run with a Windows 10 16GB RAM computer, and I found those files while looking through my hard drive (mainly because I was lacking space...)

![image](https://cloud.githubusercontent.com/assets/1404977/11034932/64fe05c6-86ef-11e5-8f06-80cb0d247e69.png)

Here's the content of one of those files.
![image](https://cloud.githubusercontent.com/assets/1404977/11034946/7d354ee2-86ef-11e5-9e07-df5cd76a3fc7.png)

I was going crazy because it's been a real problem for me, my disk space issue, and finding that redis is causing this is somehow good news, I guess, since I was blaming Windows 10 for taking too much space all this time.

Do you guys have any idea or any workaround to avoid this kind of inconvenient ? Fyi, I'm running Redis 2.8, released 16th of July

(edit: related to #329 )

**Comment by louthy** [comment]
I had the exact same issue today.  I had a few mb left on my machine, and couldn't find where it was all going; then ran windirstat and found all these RedisQFork files.

**Comment by enricogior** [comment]
@lght @louthy 
each running instance of Redis uses one RedisQFork file.
When Redis quits the file is supposed to me deleted, if not it's safe do delete it manually.
In 3.0 we are removing the file in the first place.
