### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by cracker4o** [microsoftarchive/redis#358]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1660] 17 Nov 12:48:01.557 # --- EXCEPTION_ACCESS_VIOLATION
[1660] 17 Nov 12:48:01.557 # --- INFO OUTPUT
# Server

redis_version:2.8.21
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e84b20ff4e0813fa
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:winsock_IOCP
process_id:1660
run_id:6bfca89dd748d6de643df9a7ed61a7eabd0fa893
tcp_port:22233
uptime_in_seconds:219299
uptime_in_days:2
hz:10
lru_clock:4945505
config_file:D:\ProgramFiles\Redis\redis.windows.conf
# Clients

connected_clients:6
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:391035832
used_memory_human:372.92M
used_memory_rss:391001952
used_memory_peak:3841603048
used_memory_peak_human:3.58G
used_memory_lua:271360
mem_fragmentation_ratio:1.00
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:3931
rdb_bgsave_in_progress:0
rdb_last_save_time:1447785901
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1447785902
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:1369
total_commands_processed:93127105
instantaneous_ops_per_sec:5
total_net_input_bytes:4681738235
total_net_output_bytes:0
instantaneous_input_kbps:0.29
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:1
sync_partial_ok:1
sync_partial_err:0
expired_keys:4774
evicted_keys:0
keyspace_hits:85417380
keyspace_misses:1061887
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:93750
# Replication

role:master
connected_slaves:0
master_repl_offset:787570669
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:94747756
repl_backlog_histlen:1048576
# CPU

used_cpu_sys:5828.50
used_cpu_user:2081.38
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=71893643,usec=305556976,usec_per_call=4.25
cmdstat_set:calls=873907,usec=8968734,usec_per_call=10.26
cmdstat_del:calls=2591,usec=46875,usec_per_call=18.09
cmdstat_exists:calls=2,usec=0,usec_per_call=0.00
cmdstat_sadd:calls=809453,usec=13765613,usec_per_call=17.01
cmdstat_smembers:calls=3,usec=0,usec_per_call=0.00
cmdstat_hset:calls=1949106,usec=25563448,usec_per_call=13.12
cmdstat_hget:calls=7133251,usec=30671831,usec_per_call=4.30
cmdstat_hexists:calls=7452370,usec=46066317,usec_per_call=6.18
cmdstat_select:calls=1,usec=0,usec_per_call=0.00
cmdstat_ping:calls=633577,usec=1609370,usec_per_call=2.54
cmdstat_multi:calls=873912,usec=531249,usec_per_call=0.61
cmdstat_exec:calls=873911,usec=27468714,usec_per_call=31.43
cmdstat_psync:calls=2,usec=265635,usec_per_call=132817.50
cmdstat_replconf:calls=113897,usec=250000,usec_per_call=2.19
cmdstat_flushall:calls=4,usec=391060024,usec_per_call=97765008.00
cmdstat_info:calls=65843,usec=6156241,usec_per_call=93.50
cmdstat_slaveof:calls=1,usec=0,usec_per_call=0.00
cmdstat_role:calls=237,usec=15625,usec_per_call=65.93
cmdstat_config:calls=9,usec=281248,usec_per_call=31249.78
cmdstat_subscribe:calls=7,usec=0,usec_per_call=0.00
cmdstat_publish:calls=451366,usec=4859365,usec_per_call=10.77
cmdstat_client:calls=9,usec=0,usec_per_call=0.00
cmdstat_eval:calls=3,usec=93750,usec_per_call=31250.00
# Keyspace

db0:keys=249374,expires=107308,avg_ttl=0
[1660] 17 Nov 12:48:01.557 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @cracker4o
unfortunately the crash report is not very helpful since the stack trace is missing.
Since version 2.8.21 several major issues have been fixed (including the problem with the crash report not listing the stack trace), I suggest to upgrade to [version 2.8.2104](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2104).
Thank you.

**Comment by enricogior** [comment]
@cracker4o 
closing the issue for lack of activity.
Fell free to reopen it if needed.
Thank you.
