### ISSUE TITLE
redis-cli --bigkeys doesn't work

### ISSUE THREAD

**Issue by mehdyh** [microsoftarchive/redis#359]
redis-cli --bigkeys
returns "Couldn't determine DBSIZE!" error.
any idea why it happens?

**Comment by enricogior** [comment]
Hi @mehdymohajery 
what version of Redis are you running?
If you execute redis-cli.exe and then call the DBSIZE command what is the result?

**Comment by mehdyh** [comment]
it's OK,
if you don't pass -a password, it doesn't show authentication error.
with passing auth key it works just fine.
