### ISSUE TITLE
Is Redis 2.4 stable for production?

### ISSUE THREAD

**Issue by thierrym06** [microsoftarchive/redis#36]
Hello,

I would like to know if your Redis 2.4 version can be used in production (on a Windows 2008 Server 64 bits) or if it's only for development purpose?

Who can assist us if we have some issues using it?

Moreover, we would like to use the "Sentinel" feature with Redis 2.6. Do you known when a stable version will be available?

Thanks

**Comment by ahives** [comment]
I have the same question as I wish to use this in production within the next 2 months.

**Comment by arleyschrock** [comment]
I've been using it in production environments over the last several months without any issues. The typical platform I use it on is Windows Server 2008 R2 64 bit, with an x86 build of Redis ;)

**Comment by thierrym06** [comment]
Hi alreyschrock, thanks for your comment.

We have some questions regarding your environement, that could be useful for us:
- How many clients do you have approximately? How many MB are stored in Redis (approx.)?
- How many Redis servers do you use? Is it Redis 2.4 for Windows or other version?
- Do you use any replication system (Master / Slave)?

Thanks for your time!

**Comment by clca** [comment]
We are making progress on this front, please check the following wiki [page ](https://github.com/MSOpenTech/redis/wiki/REDIS-Stress-Test-Report-%E2%80%93-Phase-I) for an overview of the type of testing we are doing in order to make sure our code is ready for production.
