### ISSUE TITLE
Master-Master Replication

### ISSUE THREAD

**Issue by BoasE** [microsoftarchive/redis#362]
I've 2 Servers which should work independently. And important if I restart one the other should still be running and have a working Redis node.

Is there a way to mimic a Master-Master Replication ? Is there some where a tutorial for this?

**Comment by enricogior** [comment]
Hi @Gentlehag 
the issues on this github repo are dedicated to Windows-specific issues/bugs, for Redis in general a better place to ask for this type of questions would be the official Redis community on reddit https://www.reddit.com/r/redis

**Comment by BoasE** [comment]
hmm ok i just wondered wether there are redis windows specific configuration types
