### ISSUE TITLE
redis install fails with 'can not start service Redis'

### ISSUE THREAD

**Issue by HansS** [microsoftarchive/redis#363]
![redis msopen install fails](https://cloud.githubusercontent.com/assets/43744/11331975/a9615fb0-91c1-11e5-9911-19270a0bc431.PNG)

**Comment by enricogior** [comment]
Hi @HansS 
do you have .Net installed?

**Comment by HansS** [comment]
Hi Enrico,I have installed MS Visual Studio 2013 Express¨!
regardsHans

Date: Mon, 23 Nov 2015 05:26:12 -0800

**Comment by enricogior** [comment]
@HansS 
the Redis MSI installer requires the .Net framework. An alternative way to install Redis on Windows is to download the .zip folder and install the service using the command:

`redis-server --service-install redis.windows.conf`

Let me know if you still have problem installing Redis.
Thank you

**Comment by HansS** [comment]
Hi Giorgio,
i have downloaded and extracted the zip file.After running make i can not find redis-server in src directory:Hans@HP-Hans /cygdrive/c/Users/Hans/downloads/redis-2.8/src$ diradlist.c     anet.c       crc64.c       help.h         lzfP.h           object.c  redis.h             rio.c           slowlog.c       t_set.c        ziplist.cadlist.h     anet.h       crc64.h       hyperloglog.c  Makefile         pqsort.c  redisassert.h       rio.h           slowlog.h       t_string.c     ziplist.hae.c         aof.c        db.c          intset.c       Makefile.dep     pqsort.h  redis-benchmark.c   scripting.c     solarisfixes.h  t_zset.c       zipmap.cae.h         asciilogo.h  debug.c       intset.h       memtest.c        pubsub.c  redis-check-aof.c   sds.c           sort.c          testhelp.h     zipmap.hae_epoll.c   bio.c        dict.c        latency.c      migrate.c        rand.c    redis-check-dump.c  sds.h           sparkline.c     util.c         zmalloc.cae_evport.c  bio.h        dict.h        latency.h      mkreleasehdr.sh  rand.h    redis-cli.c         sentinel.c      sparkline.h     util.h         zmalloc.hae_kqueue.c  bitops.c     endianconv.c  lzf.h          multi.c          rdb.c     release.c           setproctitle.c  syncio.c        valgrind.supae_select.c  config.c     endianconv.h  lzf_c.c        networking.c     rdb.h     release.h           sha1.c          t_hash.c        version.hae_wsiocp.c  config.h     fmacros.h     lzf_d.c        notify.c         redis.c   replication.c       sha1.h          t_list.c        Win32_Interop
kind regardsHans

Date: Mon, 23 Nov 2015 11:10:43 -0800

**Comment by enricogior** [comment]
@HansS 
please download the zip folder that contains the binaries, not the zip folder with the source code.
https://github.com/MSOpenTech/redis/releases/download/win-2.8.2104/Redis-x64-2.8.2104.zip

**Comment by HansS** [comment]
ok, sorry for downloading wrong zip.It works now!
bona sera Enrico!

Date: Tue, 24 Nov 2015 07:54:18 -0800

**Comment by enricogior** [comment]
@HansS 
ok good, I close the issue.
Buona sera to you too ;)
