### ISSUE TITLE
redis 3.0 rc1 crashed

### ISSUE THREAD

**Issue by liangsuilong** [microsoftarchive/redis#366]
Here is bug report.The server is running on Windows Server 2008 R2. 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[5044] 25 Nov 14:29:08.310 # --- EXCEPTION_ACCESS_VIOLATION
[5044] 25 Nov 14:29:08.310 # --- STACK TRACE
redis-server.exe!((null):0)(0x0012E1F0, 0x0012FF90, 0x00000001, 0x40122738)
redis-server.exe!((null):0)(0x00000001, 0x00000000, 0x00000001, 0x00000001)
kernel32.dll!UnhandledExceptionFilter((null):0)(0x0012E1F0, 0x00000006, 0x00000000, 0x00000001)
ntdll.dll!MD5Final((null):0)(0x0012EE30, 0x00000000, 0x40128C38, 0x00000000)
ntdll.dll!_C_specific_handler((null):0)(0x00130000, 0x0012FF90, 0x0012FF90, 0x76EB2DE8)
ntdll.dll!RtlDecodePointer((null):0)(0x00130000, 0x76C5DF08, 0x00012F24, 0x0012E2D8)
ntdll.dll!RtlUnwindEx((null):0)(0x0012EE30, 0x0012E940, 0x00000000, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0xF4802118, 0x00000001, 0xF4805F70, 0xFFFFFFFF)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x76E85410, 0x00000000, 0xF4B56000, 0x00EC0000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xF4400250, 0x76DC3518, 0x00EC0000, 0x0000000F)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0xF4400250, 0x03000003, 0x00EC0208)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xF49740C0, 0xF4400250, 0x4016FE70, 0x00EC3C80)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000018, 0xF4811150, 0x0000000B, 0x00EC3C80)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000020, 0x00000000, 0x0000000B, 0xFCDB1710)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00EC1948, 0x00000000, 0x00000000, 0x0000000B)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00EC1910, 0x00EC1910, 0x0012F9E8, 0x00000018)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xF4942000, 0x00000001, 0xF4870160, 0x00000020)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xF48100D0, 0x00000000, 0xF48100D0, 0x40032DFB)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x001F16D0, 0x40017443, 0xF481AC40, 0xF4942000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x96E4BD94, 0x00000010, 0x0000000B)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x56555534, 0x400A4150, 0x00000000, 0x0000000B)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0000001D, 0x0000000B, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x0000000B, 0x00000032, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xF4870160, 0x00000001, 0xF4811150, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x56554CAA, 0xF4806FA8, 0x00000002, 0x001EAEE0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x56554CA9, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[5044] 25 Nov 14:29:08.322 # --- INFO OUTPUT
# Server

redis_version:3.0.500-rc1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:5e6beef03a93cf18
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:5044
run_id:5435b5d71dc725e560ae21d5dbc782dee64bff8a
tcp_port:16379
uptime_in_seconds:2187
uptime_in_days:0
hz:10
lru_clock:5592372
config_file:D:\edo6\redis\redis.conf
# Clients

connected_clients:69
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:56
# Memory

used_memory:2816936
used_memory_human:2.69M
used_memory_rss:2815944
used_memory_peak:4668600
used_memory_peak_human:4.45M
used_memory_lua:36864
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0
# Persistence

loading:0
rdb_changes_since_last_save:16
rdb_bgsave_in_progress:0
rdb_last_save_time:1448432929
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:5850787
aof_base_size:3837667
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0
# Stats

total_connections_received:69
total_commands_processed:30348
instantaneous_ops_per_sec:6
total_net_input_bytes:2997369
total_net_output_bytes:2519192
instantaneous_input_kbps:0.52
instantaneous_output_kbps:2.62
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:449
evicted_keys:0
keyspace_hits:4270
keyspace_misses:6519
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:1000
migrate_cached_sockets:0
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:1.83
used_cpu_user:1.97
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=364,usec=4000,usec_per_call=10.99
cmdstat_set:calls=883,usec=6000,usec_per_call=6.80
cmdstat_del:calls=747,usec=7002,usec_per_call=9.37
cmdstat_rpush:calls=1,usec=0,usec_per_call=0.00
cmdstat_lpush:calls=1463,usec=12000,usec_per_call=8.20
cmdstat_rpop:calls=7053,usec=27001,usec_per_call=3.83
cmdstat_brpop:calls=3890,usec=20000,usec_per_call=5.14
cmdstat_llen:calls=6644,usec=89001,usec_per_call=13.40
cmdstat_ltrim:calls=729,usec=2001,usec_per_call=2.74
cmdstat_hset:calls=737,usec=5000,usec_per_call=6.78
cmdstat_hget:calls=1269,usec=10000,usec_per_call=7.88
cmdstat_hmset:calls=498,usec=9000,usec_per_call=18.07
cmdstat_hdel:calls=730,usec=3000,usec_per_call=4.11
cmdstat_hkeys:calls=6,usec=0,usec_per_call=0.00
cmdstat_hgetall:calls=317,usec=3001,usec_per_call=9.47
cmdstat_hexists:calls=8,usec=0,usec_per_call=0.00
cmdstat_select:calls=67,usec=1000,usec_per_call=14.93
cmdstat_expire:calls=497,usec=11000,usec_per_call=22.13
cmdstat_keys:calls=552,usec=72003,usec_per_call=130.44
cmdstat_multi:calls=1788,usec=8001,usec_per_call=4.47
cmdstat_exec:calls=1788,usec=36004,usec_per_call=20.14
cmdstat_ttl:calls=317,usec=2000,usec_per_call=6.31
# Cluster

cluster_enabled:0
# Keyspace

db0:keys=12,expires=0,avg_ttl=0
db1:keys=23,expires=0,avg_ttl=0
db3:keys=138,expires=0,avg_ttl=0
db4:keys=4,expires=4,avg_ttl=82717340
db5:keys=46,expires=38,avg_ttl=60098
db6:keys=5,expires=5,avg_ttl=82028058
db8:keys=12,expires=0,avg_ttl=0
db9:keys=26,expires=0,avg_ttl=0
[5044] 25 Nov 14:29:08.322 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

```
   Please report this bug by following the instructions at:

 http://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue

Suspect RAM error? Use redis-server --test-memory to verify it.
```

**Comment by enricogior** [comment]
Hi @liangsuilong 
thank you for posting the issue.
A fix is currently under testing, we'll release a RC2 as soon as possible.
Thank you.

**Comment by liangsuilong** [comment]
@enricogior Thank you. I just hope a new version will be released as soon as possible.

**Comment by enricogior** [comment]
@liangsuilong 
the RC2 is scheduled to be released on Monday.
If you need it sooner I can send you a private build with the fix.
Let me know.

**Comment by liangsuilong** [comment]
@enricogior Thank you very much. I am quite sorry that I am too late to get your message. Now it is on Monday morning in China. Just wait a new public release. I believe you could ship it on time. No delay.

**Comment by enricogior** [comment]
@liangsuilong 
unfortunately we run into another issue that we also want to fix before releasing the RC 2.
The new ETA is Wednesday.

**Comment by liangsuilong** [comment]
@enricogior 
I read the issue. My environment does not need to setup redis cluster. The bug seems not to affect me.  

Could you send a private build to me. You could sent it to my mail as attachment. My mail address is liangsuilong@gmail.com.

**Comment by whidbey** [comment]
is that resolve? I meet this error today with RC1

**Comment by whidbey** [comment]
would you send a private fix to me?thanks whidbey@qq.com

**Comment by enricogior** [comment]
@liangsuilong, @whidbey 
the [RC2 release is available](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc2) with a fix for this issue.
Feel free to reopen the issue if needed.
Thank you.

**Comment by whidbey** [comment]
thank you
