### ISSUE TITLE
when aof file is bad, can redis-server.exe fix it automatically through some config

### ISSUE THREAD

**Issue by zqzjz0911** [microsoftarchive/redis#367]
when aof file is bad, can redis-server.exe fix it automatically through some config..

because redis-server in my system  are often make some bad aof files when it closed.is there some method that can automatically fix the aof files ???

**Comment by enricogior** [comment]
Hi @zqzjz0911 
there isn't any Windows-specific functionality for fixing the AOF, so beside using the `aof-load-truncated` configuration flag you may search to the official Redis documentation: http://redis.io/documentation.
Thank you.
