### ISSUE TITLE
3.0.5 rc master->slave replication does not work

### ISSUE THREAD

**Issue by win32nipuh** [microsoftarchive/redis#368]
I have started localhost:6379 and localhost:6380 as a slave.
On the start the slave node read some f keys from the master and not sync anymore.
Then I run 2.8 as a slave of the same mater. It works perfectly.
Is that issue  or I need to configure anything additionally for 3.0.5 rc?

**Comment by enricogior** [comment]
Hi @win32nipuh,
can you please provide the configuration files and the log files to help identify the problem?
Thank you.

**Comment by win32nipuh** [comment]
There are 2 log files from 2.8 slave and 3.0.5 slave and config files for master and 3.0.5 slave

[salve_log.txt](https://github.com/MSOpenTech/redis/files/47385/salve_log.txt)
[slave_log_2_8.txt](https://github.com/MSOpenTech/redis/files/47384/slave_log_2_8.txt)

**Comment by win32nipuh** [comment]
[redis_pwd_master.conf.txt](https://github.com/MSOpenTech/redis/files/47387/redis_pwd_master.conf.txt)
[redis_pwd_slave.conf.txt](https://github.com/MSOpenTech/redis/files/47386/redis_pwd_slave.conf.txt)

**Comment by enricogior** [comment]
@win32nipuh 
it looks like a bug in the 3.0.5 when the password is required, I'll investigate further and I'll let you know.
Thank you.

**Comment by win32nipuh** [comment]
ok, thnx.
Btw, probably it can help.
I have a SQLCLR procedure which connects to Redis (with password) and writes some data.
I use master->slave replication
It works with 2.8 ok.
Now I am testing it with 3.0.5 rc master->3.0.5 slave.
I have detected that sometimes connection can be broken by server

**Comment by win32nipuh** [comment]
Thank you, when it will be ready for a testing?

**Comment by enricogior** [comment]
@win32nipuh 
the [RC2 release is available](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc2) with a fix for this issue.
Feel free to reopen the issue if needed.
Thank you.

**Comment by win32nipuh** [comment]
Hi, 
In my environment it works:
master->slave->slave
Thank you.

**Comment by enricogior** [comment]
@win32nipuh 
thank you for the feedback :)
