### ISSUE TITLE
How to configure cluster? 

### ISSUE THREAD

**Issue by win32nipuh** [microsoftarchive/redis#369]
I read the description:
http://redis.io/topics/cluster-tutorial

How to configure a cluster in Windows?
I have created 6 nodes, edited their config files as described.
All they started in 'cluster mode'.
In the tutorial written:

To create your cluster simply type:
./redis-trib.rb create --replicas 1 127.0.0.1:7000 127.0.0.1:7001 \
127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005

How to do that in Windows?

**Comment by enricogior** [comment]
Hi @win32nipuh,
the redis-trib.rb is a Ruby script, so you need to install Ruby first http://rubyinstaller.org/

**Comment by win32nipuh** [comment]
Thank you.
This script is absent in Redis bin folder.
Is it possible to do it without Ruby?
May be using Redis any commands or manually?

**Comment by enricogior** [comment]
@win32nipuh 
I've updated the [wiki page](https://github.com/MSOpenTech/redis/wiki/Cluster-Configuration-using-the-Ruby-script) with a link to the redis-trib script, click on the "redis-trib" link and than save the page to disk with the name "redis-trib.rb".
The wiki page also explains how to install the required ruby gem.
Thank you.

**Comment by win32nipuh** [comment]
Thanks a lot

**Comment by enricogior** [comment]
@win32nipuh 
I'm closing the issue, feel free to reopen it if needed.
Thank you.
