### ISSUE TITLE
Unknown command 'flushdb' reading the append only file

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#370]
When I tried to update to 2103 build, suddenly server says "Unknown command 'flushdb' reading the append only file" and exits. I have flushdb command disabled in config. When I enable it, the problem goes away. 
What's even more weird - I tried to start 2101 build with command disabled and it didn't work either - same error.
What went wrong?

**Comment by enricogior** [comment]
@chester89 
check if the AOF file that you are trying to load contains the FLUSHDB command.

**Comment by chester89** [comment]
yes, I certainly flushed this db a couple of times. that must be it. thanks
