### ISSUE TITLE
Problem building with VS2013 as specified in the readme

### ISSUE THREAD

**Issue by gimmemoore** [microsoftarchive/redis#371]
When building branch V3.0, I get the following error building redis on windows :

1>------ Build started: Project: RedisBenchmark, Configuration: Debug x64 ------
2>------ Build started: Project: RedisCli, Configuration: Debug x64 ------
1>  ae.c
1>....\src\ae.c(169): error C2275: 'aeFileEvent' : illegal use of this type as an expression
1>          c:\tools\redis\redis-3.0\src\ae.h(67) : see declaration of 'aeFileEvent'
1>....\src\ae.c(169): error C2065: 'fe' : undeclared identifier
1>....\src\ae.c(170): error C2065: 'fe' : undeclared identifier
1>....\src\ae.c(170): error C2223: left of '->mask' must point to struct/union
1>....\src\ae.c(173): error C2065: 'fe' : undeclared identifier
1>....\src\ae.c(173): error C2223: left of '->mask' must point to struct/union
1>....\src\ae.c(174): error C2065: 'fe' : undeclared identifier
1>....\src\ae.c(174): error C2223: left of '->mask' must point to struct/union
1>....\src\ae.c(186): error C2275: 'aeFileEvent' : illegal use of this type as an expression
1>          c:\tools\redis\redis-3.0\src\ae.h(67) : see declaration of 'aeFileEvent'
1>....\src\ae.c(186): error C2065: 'fe' : undeclared identifier
1>....\src\ae.c(188): error C2065: 'fe' : undeclared identifier
1>....\src\ae.c(188): error C2223: left of '->mask' must point to struct/union
1>....\src\ae.c(188): warning C4033: 'aeGetFileEvents' must return a value
2>  ae.c
2>....\src\ae.c(169): error C2275: 'aeFileEvent' : illegal use of this type as an expression
2>          c:\tools\redis\redis-3.0\src\ae.h(67) : see declaration of 'aeFileEvent'
2>....\src\ae.c(169): error C2065: 'fe' : undeclared identifier
2>....\src\ae.c(170): error C2065: 'fe' : undeclared identifier
2>....\src\ae.c(170): error C2223: left of '->mask' must point to struct/union
2>....\src\ae.c(173): error C2065: 'fe' : undeclared identifier
2>....\src\ae.c(173): error C2223: left of '->mask' must point to struct/union
2>....\src\ae.c(174): error C2065: 'fe' : undeclared identifier
2>....\src\ae.c(174): error C2223: left of '->mask' must point to struct/union
2>....\src\ae.c(186): error C2275: 'aeFileEvent' : illegal use of this type as an expression
2>          c:\tools\redis\redis-3.0\src\ae.h(67) : see declaration of 'aeFileEvent'
2>....\src\ae.c(186): error C2065: 'fe' : undeclared identifier
2>....\src\ae.c(188): error C2065: 'fe' : undeclared identifier
2>....\src\ae.c(188): error C2223: left of '->mask' must point to struct/union
2>....\src\ae.c(188): warning C4033: 'aeGetFileEvents' must return a value
3>------ Build started: Project: RedisServer, Configuration: Debug x64 ------
3>  util.c
3>..\src\util.c(303): error C2275: 'uint32_t' : illegal use of this type as an expression
3>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdint.h(14) : see declaration of 'uint32_t'
3>..\src\util.c(303): error C2146: syntax error : missing ';' before identifier 'next'
3>..\src\util.c(303): error C2065: 'next' : undeclared identifier
3>..\src\util.c(304): error C2065: 'next' : undeclared identifier
3>..\src\util.c(305): error C2065: 'next' : undeclared identifier
3>..\src\util.c(309): error C2065: 'next' : undeclared identifier
3>..\src\util.c(310): error C2065: 'next' : undeclared identifier
3>..\src\util.c(311): error C2065: 'next' : undeclared identifier
3>..\src\util.c(316): error C2065: 'next' : undeclared identifier
3>..\src\util.c(319): error C2065: 'next' : undeclared identifier
3>..\src\util.c(320): error C2065: 'next' : undeclared identifier
3>  t_list.c
3>..\src\t_list.c(415): error C2275: 'PORT_LONG' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\win32_interop\win32_types_hiredis.h(41) : see declaration of 'PORT_LONG'
3>..\src\t_list.c(415): error C2146: syntax error : missing ';' before identifier 'index'
3>..\src\t_list.c(415): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(418): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(418): warning C4133: 'function' : incompatible types - from 'int *' to 'PORT_LONG *'
3>..\src\t_list.c(426): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(439): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(454): error C2275: 'PORT_LONG' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\win32_interop\win32_types_hiredis.h(41) : see declaration of 'PORT_LONG'
3>..\src\t_list.c(454): error C2146: syntax error : missing ';' before identifier 'index'
3>..\src\t_list.c(454): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(457): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(457): warning C4133: 'function' : incompatible types - from 'int *' to 'PORT_LONG *'
3>..\src\t_list.c(463): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(477): error C2065: 'index' : undeclared identifier
3>..\src\t_list.c(498): error C2275: 'robj' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\redis.h(443) : see declaration of 'robj'
3>..\src\t_list.c(498): error C2065: 'value' : undeclared identifier
3>..\src\t_list.c(499): error C2065: 'value' : undeclared identifier
3>..\src\t_list.c(499): warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
3>..\src\t_list.c(504): error C2065: 'value' : undeclared identifier
3>..\src\t_list.c(504): warning C4047: 'function' : 'robj *' differs in levels of indirection from 'int'
3>..\src\t_list.c(504): warning C4024: 'addReplyBulk' : different types for formal and actual parameter 2
3>..\src\t_list.c(505): error C2065: 'value' : undeclared identifier
3>..\src\t_list.c(505): warning C4047: 'function' : 'robj *' differs in levels of indirection from 'int'
3>..\src\t_list.c(505): warning C4024: 'decrRefCount' : different types for formal and actual parameter 1
3>..\src\t_list.c(659): error C2275: 'listTypeIterator' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\redis.h(987) : see declaration of 'listTypeIterator'
3>..\src\t_list.c(659): error C2065: 'li' : undeclared identifier
3>..\src\t_list.c(662): error C2065: 'li' : undeclared identifier
3>..\src\t_list.c(662): warning C4047: '=' : 'int' differs in levels of indirection from 'listTypeIterator *'
3>..\src\t_list.c(664): error C2065: 'li' : undeclared identifier
3>..\src\t_list.c(664): warning C4047: '=' : 'int' differs in levels of indirection from 'listTypeIterator *'
3>..\src\t_list.c(667): error C2065: 'li' : undeclared identifier
3>..\src\t_list.c(667): warning C4047: 'function' : 'listTypeIterator *' differs in levels of indirection from 'int'
3>..\src\t_list.c(667): warning C4024: 'listTypeNext' : different types for formal and actual parameter 1
3>..\src\t_list.c(675): error C2065: 'li' : undeclared identifier
3>..\src\t_list.c(675): warning C4047: 'function' : 'listTypeIterator *' differs in levels of indirection from 'int'
3>..\src\t_list.c(675): warning C4024: 'listTypeReleaseIterator' : different types for formal and actual parameter 1
3>..\src\t_list.c(1098): error C2275: 'robj' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\redis.h(443) : see declaration of 'robj'
3>..\src\t_list.c(1098): error C2065: 'key' : undeclared identifier
3>..\src\t_list.c(1100): error C2065: 'key' : undeclared identifier
3>..\src\t_list.c(1100): warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
3>..\src\t_list.c(1110): error C2065: 'key' : undeclared identifier
3>..\src\t_list.c(1110): error C2223: left of '->type' must point to struct/union
3>..\src\t_list.c(1115): error C2065: 'key' : undeclared identifier
3>..\src\t_list.c(1115): warning C4047: 'function' : 'robj *' differs in levels of indirection from 'int'
3>..\src\t_list.c(1115): warning C4024: 'listTypeLength' : different types for formal and actual parameter 1
3>..\src\t_list.c(1115): warning C4024: '_redisAssertWithInfo' : different types for formal and actual parameter 2
3>  sentinel.c
3>..\src\sentinel.c(3016): error C2275: 'sds' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\sds.h(43) : see declaration of 'sds'
3>..\src\sentinel.c(3016): error C2146: syntax error : missing ';' before identifier 'serversection'
3>..\src\sentinel.c(3016): error C2065: 'serversection' : undeclared identifier
3>..\src\sentinel.c(3016): warning C4047: '=' : 'int' differs in levels of indirection from 'sds'
3>..\src\sentinel.c(3017): error C2065: 'serversection' : undeclared identifier
3>..\src\sentinel.c(3017): warning C4022: 'sdscatlen' : pointer mismatch for actual parameter 2
3>..\src\sentinel.c(3017): warning C4047: 'function' : 'const sds' differs in levels of indirection from 'int'
3>..\src\sentinel.c(3017): warning C4024: 'sdslen' : different types for formal and actual parameter 1
3>..\src\sentinel.c(3018): error C2065: 'serversection' : undeclared identifier
3>..\src\sentinel.c(3018): warning C4047: 'function' : 'sds' differs in levels of indirection from 'int'
3>..\src\sentinel.c(3018): warning C4024: 'sdsfree' : different types for formal and actual parameter 1
3>  replication.c
3>..\src\replication.c(2374): error C2275: 'listIter' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\adlist.h(48) : see declaration of 'listIter'
3>..\src\replication.c(2374): error C2146: syntax error : missing ';' before identifier 'li'
3>..\src\replication.c(2374): error C2065: 'li' : undeclared identifier
3>..\src\replication.c(2392): error C2065: 'li' : undeclared identifier
3>..\src\replication.c(2392): warning C4133: 'function' : incompatible types - from 'int *' to 'listIter *'
3>..\src\replication.c(2393): error C2065: 'li' : undeclared identifier
3>..\src\replication.c(2393): warning C4133: 'function' : incompatible types - from 'int *' to 'listIter *'
3>  hyperloglog.c
3>..\src\hyperloglog.c(1495): error C2275: 'uint8_t' : illegal use of this type as an expression
3>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdint.h(12) : see declaration of 'uint8_t'
3>..\src\hyperloglog.c(1495): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1495): error C2065: 'end' : undeclared identifier
3>..\src\hyperloglog.c(1495): error C2100: illegal indirection
3>..\src\hyperloglog.c(1495): warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
3>..\src\hyperloglog.c(1503): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1504): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1504): error C2065: 'end' : undeclared identifier
3>..\src\hyperloglog.c(1507): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1507): error C2100: illegal indirection
3>..\src\hyperloglog.c(1508): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1508): error C2100: illegal indirection
3>..\src\hyperloglog.c(1509): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1511): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1511): error C2100: illegal indirection
3>..\src\hyperloglog.c(1512): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1512): error C2100: illegal indirection
3>..\src\hyperloglog.c(1513): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1516): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1516): error C2100: illegal indirection
3>..\src\hyperloglog.c(1517): error C2065: 'p' : undeclared identifier
3>..\src\hyperloglog.c(1517): error C2100: illegal indirection
3>..\src\hyperloglog.c(1518): error C2065: 'p' : undeclared identifier
3>  ae.c
3>..\src\ae.c(169): error C2275: 'aeFileEvent' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\ae.h(67) : see declaration of 'aeFileEvent'
3>..\src\ae.c(169): error C2065: 'fe' : undeclared identifier
3>..\src\ae.c(170): error C2065: 'fe' : undeclared identifier
3>..\src\ae.c(170): error C2223: left of '->mask' must point to struct/union
3>..\src\ae.c(173): error C2065: 'fe' : undeclared identifier
3>..\src\ae.c(173): error C2223: left of '->mask' must point to struct/union
3>..\src\ae.c(174): error C2065: 'fe' : undeclared identifier
3>..\src\ae.c(174): error C2223: left of '->mask' must point to struct/union
3>..\src\ae.c(186): error C2275: 'aeFileEvent' : illegal use of this type as an expression
3>          c:\tools\redis\redis-3.0\src\ae.h(67) : see declaration of 'aeFileEvent'
3>..\src\ae.c(186): error C2065: 'fe' : undeclared identifier
3>..\src\ae.c(188): error C2065: 'fe' : undeclared identifier
3>..\src\ae.c(188): error C2223: left of '->mask' must point to struct/union
3>..\src\ae.c(188): warning C4033: 'aeGetFileEvents' must return a value
========== Build: 0 succeeded, 3 failed, 6 up-to-date, 0 skipped ==========

**Comment by enricogior** [comment]
Hi @gimmemoore 
are you using Visual Studio 2013 update 5?

**Comment by gimmemoore** [comment]
Hi @enricogior 

With Visual Studio 2013 Update 5, all is good, I'll make a pull request on the README.md to add this particularity for those who wants to build it themselves.

Thanks!
Kevin
