### ISSUE TITLE
Inconsistent memory consumption with redis-cli

### ISSUE THREAD

**Issue by StefanPlizga** [microsoftarchive/redis#372]
Hello,
My redis instance, 2.8.2104, is configured with maxmemory 3584MB.

When I run command info with redis-cli,I get:
# Memory

used_memory:3357075808
used_memory_human:3.13G
used_memory_rss:3357074904
used_memory_peak:3365150808
used_memory_peak_human:3.13G
used_memory_lua:2209792
mem_fragmentation_ratio:1.00
mem_allocator:dlmalloc-2.8

However, when I run redis-cli --stat, I get 2.00G for mem:
------- data ------
keys       mem
2846       2.00G

On another Redis instance, used_memory_human from Info and mem from --stat reports the same value, the only difference is that used_memory_human on the other instance is about 500MB, and not a number about 2GB.

Is there a specific behavior/bug that would explain why redis-cli --stat does reports 2.00GB for memory usage if used_memory_human is greated than 2GB?

Thanks
Stefan

**Comment by enricogior** [comment]
Hi @StefanPlizga
good catch ;)
This is a bug in the Windows version of redis-cli, the fix is ready and it will be included in the next release.
Thank you for reporting the bug.

**Comment by StefanPlizga** [comment]
Hi @enricogior 
Thank you for your prompt answer! Good to know.

**Comment by enricogior** [comment]
@StefanPlizga 
we can leave the issue open until the fix is released, I'll take care to close it.
Thanks.

**Comment by enricogior** [comment]
[Release v2.8.2400](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2400) fixes the issue.
