### ISSUE TITLE
Testing Redis Cluster 3.0.300 and having issues

### ISSUE THREAD

**Issue by undecided2013** [microsoftarchive/redis#375]
First of all I had a cluster with 3 masters. I wanted to make one of them a slave so I used the CLUSTER REPLICATE command but it kept telling me I could not do it because there were keys in there.

I eventually got frustrated and did a bunch of CLUSTER RESET and CLUSTER MEET and eventually I ended up with 1 master and 2 Slaves but I can't get the cluster to not be in failed mode. This is the CLUSTER INFO now:

cluster_state:fail cluster_slots_assigned:0 cluster_slots_ok:0 cluster_slots_pfail:0 cluster_slots_fail:0 cluster_known_nodes:3 cluster_size:0 cluster_current_epoch:3 cluster_my_epoch:1 cluster_stats_messages_sent:1139804 cluster_stats_messages_received:1139804

What should be my next step?

Thx

**Comment by enricogior** [comment]
Closing this issue since 3.0.300 is not supported anymore (latest release is 3.0.501).
Thank you.
