### ISSUE TITLE
5 errors when building msvs\redisserver.sln 

### ISSUE THREAD

**Issue by myusrn** [microsoftarchive/redis#382]
I cloned this repo and opened msvs\redisserver.sln in my win10 x64 + vs15upd1 enterprise environment.   

When i then try and build just the RedisCli.vcxproj i get the 5 errors shown in the attached image and log file.  If i try and build the entire solution i get the 19 errors shown in attached log file.  

Might these errors be due to a known issue/oversight on my part, e.g. something i need to install or change on my dev wks setup to get build working?   

I'm trying to acquire a win10 command line usable redis-cli.exe for use carrying out the learning examples found in http://redis.io/topics/data-types-intro. 

<img width="516" alt="redisclivcxprjbuilderrors" src="https://cloud.githubusercontent.com/assets/3043446/12075191/d51a9024-b12c-11e5-9e31-aa3246bb6082.png">
[RedisCliVcxprjBuildErrors.txt](https://github.com/MSOpenTech/redis/files/76313/RedisCliVcxprjBuildErrors.txt)
[RedisServerSlnBuildErrors.txt](https://github.com/MSOpenTech/redis/files/76315/RedisServerSlnBuildErrors.txt)

**Comment by enricogior** [comment]
@myusrn 
VS 2015 is not supported yet, you should use VS 2013 update 5.
Thank you.

**Comment by enricogior** [comment]
@myusrn 
if you only need redis-cli.exe, just download the .zip binaries from the release page.

**Comment by myusrn** [comment]
thanks i'll setup a vs13upd5 environment and give that a try.  

in the mean time could i ask where is the release page you are referring to with a zip containing pre-built redis-cli.exe?  

i ask because i found http://redis.io/ | downloads | stable | download 3.0.6 -> redis-3.0.6.tar.gz contained what appears to be another way to get a sources drop.

**Comment by enricogior** [comment]
@myusrn 
redis.io has Linux releases only, the Windows releases can be found here: https://github.com/MSOpenTech/redis/releases
For each release there is a Download section: the first entry is the MSI installer the second entry is  the zip folder containing the binaries.

**Comment by myusrn** [comment]
thanks for pointer to redis for windows client build download, that does the trick.

**Comment by rebulanyum** [comment]
According to [this link](http://stackoverflow.com/questions/19914828/microsoft-build-tools-2013-missing-v120-directory), it seems to me that the only way to compile this is by using Visual Studio 2013. Nothing else works; especially if you're using Visual Studio 2015, it's a problem Maybe you should support on compiling this on VS 2015...

**Comment by enricogior** [comment]
@rebulanyum 
community contributions are welcome, we would for sure accept a PR to support VS 2015.
Thank you.

**Comment by enricogior** [comment]
Thanks to @CAIQT the 3.0 branch is now compatible with VS 2015, you only need to update the projects files.
