### ISSUE TITLE
108 errors in building redis

### ISSUE THREAD

**Issue by KevinBurton** [microsoftarchive/redis#383]
I downloaded the zip file. Extracted all of the files and using VS 2013 I tried to compile the sources but I was met with 108 errors. A sample of some of the errors is include below. Ideas?

Warning 1   warning LNK4068: /MACHINE not specified; defaulting to X86  C:\Users\RKevi\Projects\redis-3.0\src\Win32_Interop\LINK    Win32_Interop
Error   2   error C2275: 'aeFileEvent' : illegal use of this type as an expression  C:\Users\RKevi\Projects\redis-3.0\src\ae.c  169 1   RedisBenchmark
Error   3   error C2065: 'fe' : undeclared identifier   C:\Users\RKevi\Projects\redis-3.0\src\ae.c  169 1   RedisBenchmark
Error   4   error C2065: 'fe' : undeclared identifier   C:\Users\RKevi\Projects\redis-3.0\src\ae.c  170 1   RedisBenchmark
Error   5   error C2223: left of '->mask' must point to struct/union    C:\Users\RKevi\Projects\redis-3.0\src\ae.c  170 1   RedisBenchmark
Error   6   error C2065: 'fe' : undeclared identifier   C:\Users\RKevi\Projects\redis-3.0\src\ae.c  173 1   RedisBenchmark
Error   7   error C2223: left of '->mask' must point to struct/union    C:\Users\RKevi\Projects\redis-3.0\src\ae.c  173 1   RedisBenchmark
Error   8   error C2065: 'fe' : undeclared identifier   C:\Users\RKevi\Projects\redis-3.0\src\ae.c  174 1   RedisBenchmark
Error   9   error C2223: left of '->mask' must point to struct/union    C:\Users\RKevi\Projects\redis-3.0\src\ae.c  174 1   RedisBenchmark
Error   10  error C2275: 'aeFileEvent' : illegal use of this type as an expression  C:\Users\RKevi\Projects\redis-3.0\src\ae.c  186 1   RedisBenchmark
Error   11  error C2065: 'fe' : undeclared identifier   C:\Users\RKevi\Projects\redis-3.0\src\ae.c  186 1   RedisBenchmark
Error   12  error C2065: 'fe' : undeclared identifier   C:\Users\RKevi\Projects\redis-3.0\src\ae.c  188 1   RedisBenchmark
Error   13  error C2223: left of '->mask' must point to struct/union    C:\Users\RKevi\Projects\redis-3.0\src\ae.c  188 1   RedisBenchmark

**Comment by enricogior** [comment]
Hi @KevinBurton 
make sure you have updated VS to Update 5.

**Comment by verylot** [comment]
understand
