### ISSUE TITLE
Using example for hiredis.lib

### ISSUE THREAD

**Issue by fborot** [microsoftarchive/redis#384]
I downloaded the sources/project and built the hiredis.lib successfully , I then tried to build the example on this link

http://blog.sriharsha.net/post/56940106721/hiredis-windows-example

I understand that with that lib only one can build its own client in c/c++. When building the example I get the following errors:

1>main.obj : error LNK2019: unresolved external symbol _freeReplyObject referenced in function _main
1>main.obj : error LNK2019: unresolved external symbol _redisConnect referenced in function _main
1>main.obj : error LNK2019: unresolved external symbol _redisFree referenced in function _main
1>main.obj : error LNK2019: unresolved external symbol _redisCommand referenced in function _main

I linked hiredis.lib and ws2_32.lib also, but I can't find the problem, please see my code below.
Any ideas are greatly appreciated !!
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include "deps\hiredis\hiredis.h"
# include "src\Win32_Interop\win32fixes.h"
# include <winsock2.h>

int main(int argc, char **argv) {
    unsigned int j;
    redisContext *c = NULL;
    redisReply *reply = NULL;
    const char *hostname = (argc > 1) ? argv[1] : "127.0.0.1";
    int port = (argc > 2) ? atoi(argv[2]) : 6379;
    int tries = 0;

```
//if (!w32initWinSock()) {
//  printf("Winsock init error %d", WSAGetLastError());
//  exit(1);
//};

//atexit((void(*)(void)) WSACleanup);

while (reply == NULL) {
    do {
        printf("Reconnecting (%d)...\r", ++tries);
        fflush(stdout);
        if (c != NULL)
            redisFree(c);
        c = redisConnect(hostname, port);
        Sleep(1000);
    } while (c->err & (REDIS_ERR_IO | REDIS_ERR_EOF));

    reply = (redisReply *)redisCommand(c, "INFO");
    if (c->err && !(c->err & (REDIS_ERR_IO | REDIS_ERR_EOF))) {
        fprintf(stderr, "Error: %s\n", c->errstr);
        exit(1);
    }
    else if (tries > 0) {
        printf("\n");
    };
};

/* Set a key */
reply = (redisReply *)redisCommand(c, "SET %s %s", "foo", "hello world");
printf("SET: %s\n", reply->str);
freeReplyObject(reply);

/* GET */
reply = (redisReply *)redisCommand(c, "GET foo");
printf("GET foo: %s\n", reply->str);
freeReplyObject(reply);

/* Disconnects and frees the context */
redisFree(c);

return 0;
```

}

**Comment by enricogior** [comment]
Hi @fborot 
we will soon release a Windows version of the minimalistic hiredis that will make easier to link the lib.
Keep an eye on https://github.com/microsoft/hiredis, we hope to release the Windows version by the end of the month. It will also include a working hiredis example.
Thank you.

**Comment by enricogior** [comment]
From now on for hiredis and hiredis issues please visit https://github.com/Microsoft/hiredis.
Thank you.
