### ISSUE TITLE
What is the meaning of server_load?

### ISSUE THREAD

**Issue by snobu** [microsoftarchive/redis#385]
Executing `info cpu` in Azure Redis returns

```
>info cpu
# CPU

used_cpu_sys:45.08

used_cpu_user:16.09

used_cpu_avg_ms_per_sec:37

server_load:10.36

event_wait:1566

event_no_wait:847
```

What is the meaning of `server_load` and what is the measurement unit there?

From https://azure.microsoft.com/en-gb/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/

> "Is there a high Redis-server server load ? Using the Redis-cli client tool, you can connect to your Redis endpoint and run "INFO CPU" to check the value of server_load. A server load of 100 (maximum value) signifies that the redis server has been busy all the time (has not been idle) processing the requests.Run Slowlog from redis-cli to see if there are any requests that are taking more time to process causing server load to max out."

it looks like it's an aggregate over multiple performance metrics.

It's clearly not just CPU, because during the exact time that i'm getting `10.36` from server_load, i'm getting 40% CPU usage in the Azure Portal graph.

Can we have a bit more detail here please?

**Comment by rustd** [comment]
From https://azure.microsoft.com/en-us/documentation/articles/cache-how-to-monitor/ 

Redis Server Load   The percentage of cycles in which the Redis server is busy processing and not waiting idle for messages. If this counter reaches 100 it means the Redis server has hit a performance ceiling and the CPU can't process work any faster. If you are seeing high Redis Server Load then you will see timeout exceptions in the client. In this case you should consider scaling up or partitioning your data into multiple caches.
