### ISSUE TITLE
Avoid creation of large Swap file (redisqfork_2100.dat)

### ISSUE THREAD

**Issue by prashant4github** [microsoftarchive/redis#387]
Hi Team,
We have installed Redis 2.8 on windows server with 32GB RAM, without setting any value for maxmemory and maxheap flags (which are the default options). With this configuration, we observed that a swap file (redisqfork_2100.dat) of size 32GB is created by Redis on server hard-disk. I don't want Redis to create such a large swap file. While looking for solution to this problem, I found that setting a maximum value  to maxmemory flag will solve this issue as size for 'Redis heap' and 'Redis swap file created on disk' are dependent on size of maxmemory. Based on my usage, I think setting value of 1GB to maxmemory flag should be ok for me. But I am not sure if that will have an adverse impact on Redis functionality as that will also reduce size of 'Redis heap' and 'Redis Swap file'. Please suggest if 1GB value for maxmemory flag is practical for Redis 2.8.
Thanks.

**Comment by enricogior** [comment]
Hi @prashant4github 
for Redis 2.8: https://github.com/MSOpenTech/redis/wiki/Memory-Configuration
for Redis 3.0: https://github.com/MSOpenTech/redis/wiki/Memory-Configuration-For-Redis-3.0
as you can see, in 3.0 we removed the creation of the swap file, the only requirements is to have the system paging file enabled with enough space (the default settings are good enough).

**Comment by prashant4github** [comment]
Hi @enricogior 
Thanks for providing required details. This clarifies my doubt.
Thanks.
