### ISSUE TITLE
Building Win32_Intertop

### ISSUE THREAD

**Issue by sromovskypeter** [microsoftarchive/redis#388]
Hello, 
I wanted to use hiredis client on Windows machine, so I cloned repository, opened MSVS solution and built hiredis project. Everything went well and I end up with hiredis.lib (debug and release versions).

When I linked the library to my project, included hiredis.h and tried to compile I end up with errors:

```
1>hiredis.lib(hiredis.obj) : error LNK2019: unresolved external symbol strerror_r referenced in function __redisSetError
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol strerror_r
1>hiredis.lib(hiredis.obj) : error LNK2019: unresolved external symbol FDAPI_close referenced in function redisFree
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol FDAPI_close
1>hiredis.lib(net.obj) : error LNK2019: unresolved external symbol FDAPI_WSAIoctl referenced in function redisKeepAlive
1>hiredis.lib(net.obj) : error LNK2019: unresolved external symbol ParseStorageAddress referenced in function redisContextPreConnectTcp
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol bind
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol connect
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol fcntl
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol freeaddrinfo
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol getaddrinfo
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol getsockopt
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol poll
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol setsockopt
1>hiredis.lib(net.obj) : error LNK2001: unresolved external symbol socket
```

I was reading somewhere that I also need Win32_Interop.lib linked to project. 
So I tried to build it same way as hiredis, but I end up with errors:

```
win32_time.h(35): error C2061: syntax error: identifier 'gettimeofdaysecs'
win32_time.h(35): error C2059: syntax error: ';'
win32_time.h(35): error C2059: syntax error: '<parameter-list>'
win32_time.h(37): error C2143: syntax error: missing ')' before '*'
win32_time.h(37): error C2143: syntax error: missing '{' before '*'
win32_time.h(37): error C2059: syntax error: 'type'
win32_time.h(37): error C2059: syntax error: ')'
```

I was able to get rid of these errors by moving #include <time.h> from Win32_Time.c file to Win32_Time.h file.
But that way build proccess ends up with error:

```
c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\sys\stat.h(237): error C2365: 'fdapi_fstat64': redefinition; previous definition was 'data variable'
c:\users\psromov\downloads\redis-3.0\src\win32_interop\win32_fdapi.h(161): note: see declaration of 'fdapi_fstat64'
```

What am I doing wrong? How can I get hiredis client working? 

I am using Microsoft Visual C++ 2015 and building for x64 platform.

Thank You,

Peter

**Comment by enricogior** [comment]
Hi @sromovskypeter 
we will soon release a Windows version of the minimalistic hiredis that will make easier to link the lib.
Keep an eye on https://github.com/microsoft/hiredis, we hope to release the Windows version by the end of the month.
Thank you.

**Comment by sromovskypeter** [comment]
Hi,
thank you @enricogior, by making some changes in win32_interop sources I was able to build win32_interop. 
Then, when I linked it to my project, hiredis starts working. I was also able to run example.c
But when I tried build ae example I went into errors similiar to ones mentioned in #350.

So I will probably wait for Windows version release.

Thank you

**Comment by enricogior** [comment]
From now on for hiredis and hiredis issues please visit https://github.com/Microsoft/hiredis.
Thank you.
