### ISSUE TITLE
--pipe  PipeMode error

### ISSUE THREAD

**Issue by llb0536** [microsoftarchive/redis#39]
can't use pipe Mode

**Comment by HenryRawas** [comment]
Pipe mode is not supported for Windows.

**Comment by ivanjh** [comment]
Is there a particular reason behind that?

**Comment by BeatriceOltean** [comment]
Trying to understand the priority. Could sockets solve this scenario?

**Comment by ivanjh** [comment]
Pipe mode is a client feature that "solves" the high latency/mass operation scenario - http://redis.io/topics/mass-insert
It's quite a niche use case - since the input file has to be created in Redis Protocol raw format (not text commands).
Anyone with the skills to produce such a format, is not far from creating the a pipe mode client themselves.

**Comment by jepickett** [comment]
In Linux, named pipes are implemented as a separate kernel object with a chunk of system memory acting as a shared buffer for IPC communication. On Windows, named pipes are implemented on top of the network stack as essentially a socket based service. Thus the performance characteristics and use cases for each are radically different. In my testing of named pipes on Windows vs. sockets, socket communication is more than ten times faster than named pipe communication. While the raw Redis protocol format is more compact than the text format, it is not compact enough to overcome the low performance characteristics of Windows named pipes. Thus our decision is to not implement named pipe communication in the Windows version of Redis at this time.

**Comment by ivanjh** [comment]
@jepickett, You'll probably have to forgive my ignorance here (assume incompetence over malice in what I say). 

I'm not sure how redis-cli's "pipe mode" (http://redis.io/topics/mass-insert), that takes advantage of Redis server's pipelined nature (http://redis.io/topics/pipelining) to help speed bulk operations over latent links (all using the standard TCP transport), relates to named pipes.

Your comment (and @BeatriceOltean's before it) leads me to wonder if the unfortunate naming of this feature has led project owners & collaborators astray. (Also, the initial report also lacked any detail to help)

The issue appears to be that pipe mode doesn't recognise stdin input:

> redis-cli.exe --pipe < redispipe.txt
> All data transferred. Waiting for the last reply...
> Last reply received from server.
> errors: 0, replies: 0

I believe, standard interactive operation uses linenoise() to read from stdin, but in "pipe mode" stdin is read with read() aka redis_read_impl() which maps handles thru RFDMap.

Unfortunately, lookupPosixFD() doesn't appear to deal with the reserved handles for stdin/stdout/stderr (0,1,2), returning -1 and causing redis_read_impl() to return 0 (nothing read).

I tested a rough hack into win32_rfdmap.cpp:

``` c
int RFDMap::lookupPosixFD(RFD rfd) {
//BEGIN - ROUGH HACK FOR STDIN/OUT/ERR
    if (rfd == 0 || rfd == 1 || rfd == 2)
        return rfd; 
//END - ROUGH HACK FOR STDIN/OUT/ERR
    if (RFDToPosixFDMap.find(rfd)  != RFDToPosixFDMap.end()) {
```

And everything looks like it runs ok.

> redis-cli.exe --pipe < redispipe.txt
> All data transferred. Waiting for the last reply...
> Last reply received from server.
> errors: 0, replies: 1000

NOTE: "redispipe.txt" is, as mentioned at http://redis.io/topics/mass-insert - "a text file containing the Redis protocol, in raw format".
Something like:

> *3\r\n$3\r\nSET\r\n$3\r\nkey\r\n$5\r\nvalue\r\n

I hope this helps.

(Can we re-open? Or does this deserve a new issue?)

**Comment by jepickett** [comment]
Thank you for clarifying the issue. I have checked in the change required to make it work. Let me know if you encounter any problems with this.

**Comment by ivanjh** [comment]
Looks good and works for me.
I'm not sure there's a reason to keep this issue open any longer.

@jepickett - Thanks for your efforts. :-)
