### ISSUE TITLE
The disk is in use or locked by another process

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#391]
Hello.
I've been running 2.8.2103 version for more than a month without any problems, then I had a problem and the machine rebooted for some reason. I started Redis again, but when I connect to it it says 'the disk is in use or locked by another process'. Any ideas how I can repair the situation?

**Comment by enricogior** [comment]
Hi @chester89 
the error comes from redis-cli?

**Comment by chester89** [comment]
It does.
I solved it - appears that my pagefile was too small (saw the error when
calling redis-server --help) for a given configuration

2016-01-15 10:54 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89
> the error comes from redis-cli?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/391#issuecomment-171895665.

## 

Yours faithfully,
Gleb
