### ISSUE TITLE
Fail to save data to harddisk by config

### ISSUE THREAD

**Issue by jackyjqzhang** [microsoftarchive/redis#392]
In line 1533 of redis.c 
   appendServerSaveParams(60_60,1);  /_ save after 1 hour and 1 change _/
    appendServerSaveParams(300,100);  /_ save after 5 minutes and 100 changes _/
    appendServerSaveParams(60,10000); /_ save after 1 minute and 10000 changes */

These hard code bypassed the config file for saving data to hard disk from memory and supposed to be be commented out to enable the config settings.

**Comment by enricogior** [comment]
Hi @jackyjqzhang 
those are just default values that are overwritten later when the configuration file is loaded.
