### ISSUE TITLE
Installation fails on starting services

### ISSUE THREAD

**Issue by joelviel** [microsoftarchive/redis#393]
Hi,

I am trying to install Redis-x64-3.0.501.msi on my Win10 laptop
The process is stucked on status: starting services
Error is Service Redis failed to start. Verify that you have  sufficient privileges to start system services.

I am admin on my workstation. Do you know how I can fix this?

Thank you for your help

**Comment by enricogior** [comment]
Hi @viellepeau 
what version of Windows 10 are you using?
Have you made any changes to the MSI setup options?

**Comment by joelviel** [comment]
Microsoft Windows 10 Home
Version 10.0.10586 Build 10586
I chose all default options in the installer except add to PATH env var

**Comment by enricogior** [comment]
@viellepeau 
we never tested the Home version, I don't know if that may be the problem.
Try creating the install log running the following command from a command windows that has admin privilegies: `msiexec /i Redis-x64-3.0.501.msi /l*v redis-msi.log`

**Comment by joelviel** [comment]
[redis-msi.log.txt](https://github.com/MSOpenTech/redis/files/93972/redis-msi.log.txt)
Please find attached the log

**Comment by enricogior** [comment]
@viellepeau 
the MSI log shows the error but without adding more info to the already known problem.
Check the application event log to see if there is any Redis entry.
You may also uninstall the current installation and try using the binaries from the .zip file https://github.com/MSOpenTech/redis/releases/download/win-3.0.501/Redis-x64-3.0.501.zip
and see if the Redis starts when running as an app and then try to install it using the command line command: `redis-server --service-install redis.windows.conf --loglevel verbose`

**Comment by joelviel** [comment]
It works :) Thank you
![sucess](https://cloud.githubusercontent.com/assets/2602237/12389918/97c95c5c-be0e-11e5-8d1a-73aa1fd190e2.PNG)
