### ISSUE TITLE
redis-cli.exe and redisServer.exe of 3.0 are getting compilation errors

### ISSUE THREAD

**Issue by reddy-sabbella** [microsoftarchive/redis#394]
I was trying to build the latest 3.0 source code with VS 2013 and get compilation errors for redis-cli.exe as wee as for redisServer.exe. Here are some sample errors:

Error   1   error C2275: 'aeFileEvent' : illegal use of this type as an expression  E:\redis-3.0\src\ae.c   169 1   RedisCli
Error   2   error C2065: 'fe' : undeclared identifier   E:\redis-3.0\src\ae.c   169 1   RedisCli

**Comment by enricogior** [comment]
Hi @reddy-sabbella 
as stated in the [README](https://github.com/MSOpenTech/redis/blob/3.0/README.md) in the "How to build Redis using Visual Studio" paragraph:

> Regardless which Visual Studio edition you use, make sure you have updated to Update 5, otherwise you will get a "illegal use of this type as an expression" error.

**Comment by reddy-sabbella** [comment]
Thank you. It works with update 5.
