### ISSUE TITLE
Redis 3.0.501 Cluster Performance.

### ISSUE THREAD

**Issue by sreefubs** [microsoftarchive/redis#401]
**Environment Details:**
Redis Version : 3.0.501
Redis Client : StackExchange.Redis
Redis Cluster Size : 6 (3Master & 3 Slaves)

On testing Redis cluster with my use case, I see Redis Master-Salve(Active Passive setup) is performing way better than Redis Cluster setup.

Is this expected behavior ? Or do I need to tweak?

**Comment by enricogior** [comment]
Hi @sreefubs 
can you provide some numbers to have a better idea of the difference in performance?
Thank you.

**Comment by sreefubs** [comment]
I'm doing 50000 HGET Iterations. 
**Time taken/HGET:**
Active-Passive Setup : 0.4milliseconds
Cluster Setup : 0.7 milliseconds

**Comment by enricogior** [comment]
@sreefubs 
from a Salvatore Sanfilippo [comment](https://groups.google.com/forum/#!topic/redis-db/UHfT5dBPh54) about the cluster performance:

> With a pipeline of 32 operations the cluster node handles 250k 
> ops/sec, while the non-cluster version 500 ops/sec.

So I don't see any performance degradation for the Windows version compared to the Linux version.

**Comment by sreefubs** [comment]
Thanks a lot for your quick reply. Have I understood properly,

Cluster node handles **250k ops/sec**
non-cluster handles **500k ops/sec**

Having said that, non-cluster is performing is 2x faster right ?

**Comment by enricogior** [comment]
@sreefubs 
those numbers are a general indication, they aren't absolute values but relative to the machine configuration used, on different machines/environments there might be slight different results. 
Given the cluster has more operations to carry on for each query, the numbers you are seeing in your test are consistent with the expected behavior.

**Comment by sreefubs** [comment]
Thanks E.G. :) 
I was in a assumption that Cluster setup will provide Higher or atleast the equal performance in comparing with Active Passive setup.

**Comment by enricogior** [comment]
@sreefubs 
Redis cluster is designed to scale up to 1000 nodes, I guess that as soon as the nodes count grows up to a certain value the performance gain of the cluster solution is significant.
To determine when the cluster is a better choice it depends on the user-case.
