### ISSUE TITLE
redis got crash in window server 2012 standard

### ISSUE THREAD

**Issue by badpaybad** [microsoftarchive/redis#406]
info redis server
# Server

redis_version:2.8.2101
# Replication

role:master
# The bug begin

[8452] 12 Feb 03:01:07.947 \* Background saving terminated with success
[8452] 12 Feb 03:02:08.002 \* 10000 changes in 60 seconds. Saving...
[8452] 12 Feb 03:02:09.017 # BeginForkOperation: system error caught. error code
=0x000005af, message=BeginForkOperation: VirtualProtect failed for the heap: unk
nown error

[8452] 12 Feb 03:02:09.017 # Can't save in background: fork: Invalid argument
[8452] 12 Feb 03:02:14.051 \* 10000 changes in 60 seconds. Saving...
[8452] 12 Feb 03:02:15.457 \* Background saving started by pid 12384
[12384] 12 Feb 03:02:15.520 #

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[12384] 12 Feb 03:02:15.520 # --- ABORT
[12384] 12 Feb 03:02:15.520 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktra
ce.cpp:95)(0x00000016, 0x40149A50, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrac
e.cpp:206)(0x00000001, 0x087E866F, 0x4012C210, 0x6142C6FB)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0
x00000000, 0x00000040, 0x00000030)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x4012C210, 0x4
00382F6, 0x00000001, 0x0013F810)
redis-server.exe!dlmalloc(c:\release\redis\src\win32_interop\win32_dlmalloc.c:46
38)(0x00000030, 0x00000009, 0x00000001, 0x4012C210)
redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:143)(0x0013F8A0, 0x00000
009, 0x40135918, 0x00000006)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:681)(0x4012C210, 0x000000
D8, 0x00000000, 0x04BA275C)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0x000000D8, 0x00000000,
 0x000000D8, 0x000000D8)
redis-server.exe!QForkChildInit(c:\release\redis\src\win32_interop\win32_qfork.c
pp:305)(0xFFFFFFFF, 0x00000000, 0x03BA0000, 0x000000E8)
redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp
:747)(0x003184D0, 0x00000000, 0x00000000, 0x00000006)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1348)(0
x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(
0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x
00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
[12384] 12 Feb 03:02:15.520 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

```
   Please report this bug by following the instructions at:

 http://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue

Suspect RAM error? Use redis-server --test-memory to verify it.
```

**Comment by enricogior** [comment]
Hi @badpaybad 
2.8.2101 is an old version, we have released several fixes since then, including the fix for the crash you reported, so please update to the [latest version](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2400).
Thank you.

**Comment by badpaybad** [comment]
thanks you very much
