### ISSUE TITLE
Service crash on Redis 3.0.500

### ISSUE THREAD

**Issue by lei13720831568** [microsoftarchive/redis#408]
Service crash on Redis 3.0.500

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[9452] 15 Feb 15:00:28.056 # Redis version: 3.0.500
[9452] 15 Feb 15:00:28.056 # --- EXCEPTION_ACCESS_VIOLATION
[9452] 15 Feb 15:00:28.057 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x01BFE750, 0x01BFFF90, 0x01BFE750, 0x40123730)
redis-server.exe!UnhandledExceptiontHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x01BFE750, 0x76ED9E3C, 0x00000030, 0xFFFFFFFF)
kernel32.dll!UnhandledExceptionFilter(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x01BFE750, 0x938B54EA, 0x00000000, 0x00000001)
ntdll.dll!RtlInitializeAtomPackage(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x01BFF330, 0x00000001, 0x401297C8, 0x00000000)
ntdll.dll!_C_specific_handler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x01BFFF90, 0x01BFFF90, 0x01C00000, 0x76DF6461)
ntdll.dll!RtlIntegerToChar(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x00000001, 0x00000000, 0x01BFFF90, 0x01C00000)
ntdll.dll!_C_specific_handler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x01BFF330, 0xFFFFFFFE, 0x00000000, 0x76DD0000)
ntdll.dll!KiUserExceptionDispatcher(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x40032F9B, 0xFFFFFFDF, 0x64D99000, 0x00000000)
redis-server.exe!je_bitmap_set(c:\release\redis\deps\jemalloc-win\include\jemalloc\internal\bitmap.h:101)(0xFFFFFFDF, 0x64D99000, 0x00000000, 0x76E19335)
redis-server.exe!arena_run_reg_alloc(c:\release\redis\deps\jemalloc-win\src\arena.c:289)(0x00000000, 0x64D99000, 0x00000020, 0x40170F10)
redis-server.exe!arena_bin_malloc_hard(c:\release\redis\deps\jemalloc-win\src\arena.c:1449)(0x400DCA90, 0xE2400250, 0x40170F10, 0x00CC1CA0)
redis-server.exe!je_arena_malloc_small(c:\release\redis\deps\jemalloc-win\src\arena.c:1609)(0x00000018, 0xE280F150, 0x00000011, 0x00CC1CA0)
redis-server.exe!je_malloc(c:\release\redis\deps\jemalloc-win\src\jemalloc.c:956)(0x00000020, 0x00000000, 0x00000011, 0x76BDD020)
redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:142)(0x00CC1A48, 0xE280F150, 0x00000000, 0x00000000)
redis-server.exe!listAddNodeTail(c:\release\redis\src\adlist.c:113)(0x00CC1A10, 0x00CC1A10, 0xE280F150, 0x00000011)
redis-server.exe!aeApiAddEvent(c:\release\redis\src\ae_wsiocp.c:153)(0x285BC000, 0x285BC000, 0xE286F220, 0x00000009)
redis-server.exe!prepareClientToWrite(c:\release\redis\src\networking.c:184)(0x40124C80, 0x0037ABD0, 0x00000009, 0x00000009)
redis-server.exe!addDeferredMultiBulkLength(c:\release\redis\src\networking.c:438)(0xFFFFFFFF, 0x285BC000, 0x40124C80, 0x0037ABD0)
redis-server.exe!luaReplyToRedisReply(c:\release\redis\src\scripting.c:849)(0xFFFFFFFF, 0x01BFF670, 0x285BC000, 0x285BC000)
redis-server.exe!evalGenericCommand(c:\release\redis\src\scripting.c:1070)(0x00000000, 0x00000000, 0x00000000, 0x008DA938)
redis-server.exe!call(c:\release\redis\src\redis.c:2122)(0x56C1778C, 0x400A4CF0, 0x00000000, 0x00000011)
redis-server.exe!processCommand(c:\release\redis\src\redis.c:2368)(0x00000005, 0x00000011, 0x00000000, 0x00000000)
redis-server.exe!processInputBuffer(c:\release\redis\src\networking.c:1291)(0x00000000, 0x00000011, 0x00000009, 0x00000001)
redis-server.exe!readQueryFromClient(c:\release\redis\src\networking.c:1344)(0xE286F220, 0x00000001, 0xE280F150, 0x000000AC)
redis-server.exe!aeMain(c:\release\redis\src\ae.c:481)(0x56C16FED, 0xE2806FA8, 0x00000002, 0x0036ED10)
redis-server.exe!redis_main(c:\release\redis\src\redis.c:3765)(0x00000000, 0x0036FD20, 0x56C16FE5, 0x0036ED10)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1241)(0x0000001A, 0x0036FD20, 0x0000001A, 0x00000000)
redis-server.exe!ServiceWorkerThread(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(c:\release\redis\src\win32_interop\win32_service.cpp:484)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[9452] 15 Feb 15:00:28.103 # --- INFO OUTPUT
# Server

redis_version:3.0.500
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:e18d443f4404273c
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:9452
run_id:1b63a77dc06e463eef10003b572af57a8b9b0753
tcp_port:12379
uptime_in_seconds:1959
uptime_in_days:0
hz:10
lru_clock:12679052
config_file:D:\Redis-x64-3.0.500\redis.windows.conf
# Clients

connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:2141557800
used_memory_human:1.99G
used_memory_rss:2141527336
used_memory_peak:2141557800
used_memory_peak_human:1.99G
used_memory_lua:90112
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-3.6.0
# Persistence

loading:0
rdb_changes_since_last_save:9283903
rdb_bgsave_in_progress:0
rdb_last_save_time:1455517669
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:13
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:1994093424
aof_base_size:1032252266
aof_pending_rewrite:0
aof_buffer_length:8210
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0
# Stats

total_connections_received:9
total_commands_processed:13039938
instantaneous_ops_per_sec:9150
total_net_input_bytes:3843126793
total_net_output_bytes:1457530776
instantaneous_input_kbps:3668.04
instantaneous_output_kbps:24.13
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:3235090
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:28003
migrate_cached_sockets:0
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:44.94
used_cpu_user:122.73
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=325719,usec=620000,usec_per_call=1.90
cmdstat_setex:calls=325719,usec=382000,usec_per_call=1.17
cmdstat_del:calls=325719,usec=217000,usec_per_call=0.67
cmdstat_incr:calls=682867,usec=389046,usec_per_call=0.57
cmdstat_lpush:calls=682867,usec=454040,usec_per_call=0.66
cmdstat_rpop:calls=325719,usec=1853000,usec_per_call=5.69
cmdstat_brpop:calls=6,usec=0,usec_per_call=0.00
cmdstat_zadd:calls=682867,usec=6160620,usec_per_call=9.02
cmdstat_zrem:calls=325719,usec=1163000,usec_per_call=3.57
cmdstat_zrange:calls=325723,usec=968000,usec_per_call=2.97
cmdstat_zcard:calls=7,usec=0,usec_per_call=0.00
cmdstat_hset:calls=2374323,usec=4048356,usec_per_call=1.71
cmdstat_hget:calls=2342903,usec=3357173,usec_per_call=1.43
cmdstat_hincrby:calls=1008586,usec=2356184,usec_per_call=2.34
cmdstat_hdel:calls=1302876,usec=1957000,usec_per_call=1.50
cmdstat_hlen:calls=11,usec=0,usec_per_call=0.00
cmdstat_hscan:calls=8,usec=1000,usec_per_call=125.00
cmdstat_select:calls=9,usec=0,usec_per_call=0.00
cmdstat_scan:calls=1,usec=0,usec_per_call=0.00
cmdstat_auth:calls=9,usec=0,usec_per_call=0.00
cmdstat_ping:calls=1,usec=0,usec_per_call=0.00
cmdstat_type:calls=12,usec=0,usec_per_call=0.00
cmdstat_info:calls=2,usec=1000,usec_per_call=500.00
cmdstat_ttl:calls=12,usec=0,usec_per_call=0.00
cmdstat_eval:calls=1334307,usec=72081786,usec_per_call=54.02
# Cluster

cluster_enabled:0
# Keyspace

db10:keys=10,expires=0,avg_ttl=0
[9452] 15 Feb 15:00:28.104 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @lei13720831568 
this problem has been fixed in [release 3.0.501](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.501), please upgrade.
Thank you.
