### ISSUE TITLE
wsarecvflags not initialized

### ISSUE THREAD

**Issue by minatl** [microsoftarchive/redis#41]
when I run client applicationusing hiredis and AE module in a windows 2003 server（x86），the  
app crashed at aeWinReceiveDone：WSARecv， i fixed it，by add one line before the call WSARecv， wsarecvflags = 0.
I seek all the source file， I  can't see a wsarecvflags init code。Why？

**Comment by HenryRawas** [comment]
Add code to initialize wsarecvflags.
