### ISSUE TITLE
Can't start the redis 3.0.501

### ISSUE THREAD

**Issue by huhm** [microsoftarchive/redis#417]
The redis server--Redis-x64-2.8.2103  crashed every several days  because of the  memory management architecture.
I‘m considering to switch to 3.0.501 to avoid the crashing.But there're some problem to install the redis service.
I download the Redis-x64-3.0.501 and edit the redis.windows-service.conf with the following setting(other setting I use the default)

```
bind 127.0.0.1
timeout 60
dbfilename "dump_main.rdb"
dir "D:\\XXX\Redis-x64-3.0.501"
maxmemory 150MB
```

Then Excute the cmd "redis-server redis.windows-service.config". No error throws and the redis service did't started.
My system is Win7-x64. The 'dump_main.rdb' is a rdbfile from the redis 2.8.

**Comment by enricogior** [comment]
Hi @huhm 
the .zip folder contains two different configuration file examples:
- redis.windows.conf
- redis.windows-service.conf

The first one is used when running Redis as an application.
The second one is used when Redis is installed as a service.
In you case you are running Redis as an application passing the configuration file that should be only used when running it as a service.
Thank you.

**Comment by huhm** [comment]
I change the cmd to "redis-server redis.windows.conf" ,but still can't connect the server(use the redis-cli.exe).

**Comment by huhm** [comment]
It's ok now after I changed the dir setting and the config file.Thank you . I need test this version for several days before apply.
