### ISSUE TITLE
[2.8.2104] Redis not connectable till service restart - Windows Server 2008 R2

### ISSUE THREAD

**Issue by BoasE** [microsoftarchive/redis#418]
We have one server with redis running and two production server connecting to it.

Yesterdasy evening (about 23:00h) I had to restart redis and everything. Then 2 hours later our web sites using redis were having trouble the whole night long.

When I look into the logs I can see that the clients were not able to connect to redis.
I restarted the redis service and after some seconds every thing works fine. So I feel quite sure the problem is related to redis

in the redis server log I can't see any error for the whole time.

> [16264] 02 Mar 22:56:01.968 \* Redis 2.8.2104 (00000000/0) 64 bit, stand alone mode, port 6379, pid 16264 ready to start.
> [16264] 02 Mar 22:56:01.969 # Server started, Redis version 2.8.2104
> [16264] 02 Mar 22:56:08.198 \* DB loaded from disk: 6.229 seconds
> [16264] 02 Mar 22:56:08.198 \* The server is now ready to accept connections on port 6379
> [21252] 03 Mar 06:04:14.279 \* Redis 2.8.2104 (00000000/0) 64 bit, stand alone mode, port 6379, pid 21252 ready to start.
> [21252] 03 Mar 06:04:14.279 # Server started, Redis version 2.8.2104

Here the windows log with the exception it is repeated in the log for the whole night

Would this maybe fixed with the current 2.8 Redis version?

 The following stacktrace is the one failing it is placed the site startup  as you can see it can not connected to the redis server

> Exception information: 
>     Exception type: TargetInvocationException 
>     Exception message: Exception has been thrown by the target of an invocation.
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Owin.Loader.DefaultLoader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder)
>    at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
>    at Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup)
>    at Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup)
>    at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint()
>    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
>    at Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context)
>    at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
>    at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
>    at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
>    at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
> 
> srv01:6379
>    at ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
>    at ServiceStack.Redis.RedisNativeClient.AssertServerVersionNumber()
>    at ServiceStack.Redis.RedisClient.GetServerRole()
>    at ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
>    at ServiceStack.Redis.PooledRedisClientManager.GetClient()
>    at SR.BusPortal.Search.Redis.RedisGlobalLock..ctor(IRedisClientsManager redis) in D:\Continua\Agent\Ws\37324\Source\WEB\src\SR.BusPortal.Search\SR.BusPortal.Search.Redis\RedisGlobalLock.cs:line 26
> 
> No connection could be made because the target machine actively refused it 79.133.49.2:6379
>    at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
>    at System.Net.Sockets.Socket.Connect(String host, Int32 port)
>    at ServiceStack.Redis.RedisNativeClient.Connect()
>    at ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded()
>    at ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()

Not sure if it might be related to my the other problem on this server: https://github.com/MSOpenTech/redis/issues/414

**Comment by enricogior** [comment]
Hi @Gentlehag 
since 2.8.2104 we have made several fixes and improvements, you should definitely upgrade to 2.8.2400.
Regarding the specific issue you have seen, I would need more information in order to understand if is a known issue already fixed in 2.8.2400.
My suggestion is to start using 2.8.2400 and verify if the problem still persist.
Thank you.

**Comment by BoasE** [comment]
ok I did the update now I let you know if it happens agian ;-)

**Comment by BoasE** [comment]
since updating to 2.8.2400 i'vent expecirended this problem again
