### ISSUE TITLE
Install Redis as a Windows service?

### ISSUE THREAD

**Issue by thierrym06** [microsoftarchive/redis#42]
Hi,

By default, we apparently cannot install Redis Server 2.4/2.6 as a Windows service.

So, we would like to know if there is a way to install it as a Windows service?

Moreover, in a previous "issue", you were talking about RedisWatcherSvc as a solution:
https://github.com/MSOpenTech/redis/issues/1

Our understanding is that RedisWatcherSvc is basically a watchdog that will restart Redis instance(s) if necessary.

When RedisWatcherSvc starts a Redis Instance, is it the Redis console application launched or Redis is running in background?

Thanks,

Thierry

**Comment by HenryRawas** [comment]
The watcher will run Redis as a background process. It sets the file 'stdout.log' as the output for the console messages, and 'stderr.log' as the output for error messages.

You cannot run Redis as a service without making some changes to the code. If you are willing to do some coding, there is documentation in MSDN for how to convert a console application to a service. Also the RedisWatcher can be used as an example. RedisWatcher can be run as a service or as a console application. Look at the code in RedisWatcher.c and service.c. The wmain() proc uses the command line parameters to decide if it will start as a console app or as a service. Of course you have to think about how to configure the service as well.

**Comment by thierrym06** [comment]
Thanks!
