### ISSUE TITLE
Redis version: 3.0.500-rc2 crash

### ISSUE THREAD

**Issue by haptear** [microsoftarchive/redis#423]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[2816] 08 Mar 23:05:24.109 # Redis version: 3.0.500-rc2
[2816] 08 Mar 23:05:24.109 # --- EXCEPTION_ACCESS_VIOLATION
[2816] 08 Mar 23:05:24.109 # --- STACK TRACE
redis-server.exe!((null):0)(0x0013EA80, 0x0013FF90, 0x00000001, 0x40123730)
redis-server.exe!((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x00000003, 0xB11B1AD0, 0x00000000, 0xB3C58736)
ntdll.dll!memset((null):0)(0x0013F6B0, 0x0013F310, 0x40129C28, 0x00000000)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x0013EBF0, 0x0013F6B0, 0x0013F6B0)
ntdll.dll!_chkstk((null):0)(0x00000001, 0xB3C20000, 0x00000000, 0xB3D56204)
ntdll.dll!RtlRaiseException((null):0)(0x004001F0, 0x00000001, 0xFFFFFFFF, 0x00000001)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x40032F9B, 0xFFFFFFE0, 0x009C1000, 0x00000072)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xFFFFFFE0, 0x009C1000, 0x00000072, 0x00000018)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00400250, 0x00000020, 0x40170F30)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000018, 0x00000017, 0x0080FA58, 0x00809B20)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000020, 0x00000042, 0x00000000, 0x00809B20)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00809B20, 0x00000042, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00809B20, 0x00000000, 0x00995CA0, 0x00000042)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00995CA0, 0x0081AD40, 0x00000004, 0x00000042)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x009C0400, 0x00995CA0, 0x0081AD40, 0x00995CA0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00A84000, 0x00000007, 0x001DC780, 0x40040201)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0xF0DEB6CC, 0x008090A0, 0x4008DB5C)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x56DEEA34, 0x400A4CF0, 0x00000000, 0x00000042)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0000000E, 0x00000042, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000042, 0x00000153, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00870840, 0x00000001, 0x00811150, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x56DEA4ED, 0x00806FA8, 0x00000002, 0x001D66A0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0xFFFFE000, 0x56DEA4EC, 0x001D66A0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0xFFFFE000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x4004382C, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0xB1F913B0, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[2816] 08 Mar 23:05:24.114 # --- INFO OUTPUT
# Server

redis_version:3.0.500-rc2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b2f2fd931fa31053
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:2816
run_id:7232b6b4db6bc0be3c99d934ed57462be5a7af26
tcp_port:16379
uptime_in_seconds:17736
uptime_in_days:0
hz:10
lru_clock:14608948
config_file:D:\edo6\redis\redis.conf
# Clients

connected_clients:69
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:56
# Memory

used_memory:3095880
used_memory_human:2.95M
used_memory_rss:3058232
used_memory_peak:4306600
used_memory_peak_human:4.11M
used_memory_lua:36864
mem_fragmentation_ratio:0.99
mem_allocator:jemalloc-3.6.0
# Persistence

loading:0
rdb_changes_since_last_save:86
rdb_bgsave_in_progress:0
rdb_last_save_time:1457449307
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_current_size:10419017
aof_base_size:7976690
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0
# Stats

total_connections_received:70
total_commands_processed:154022
instantaneous_ops_per_sec:7
total_net_input_bytes:9394205
total_net_output_bytes:12105493
instantaneous_input_kbps:0.37
instantaneous_output_kbps:0.03
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:3675
evicted_keys:0
keyspace_hits:15025
keyspace_misses:53101
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:1332
migrate_cached_sockets:0
# Replication

role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:4.17
used_cpu_user:1.98
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats

cmdstat_get:calls=93,usec=276,usec_per_call=2.97
cmdstat_set:calls=80,usec=324,usec_per_call=4.05
cmdstat_del:calls=40,usec=168,usec_per_call=4.20
cmdstat_exists:calls=61,usec=111,usec_per_call=1.82
cmdstat_lpush:calls=72,usec=286,usec_per_call=3.97
cmdstat_rpop:calls=53100,usec=116209,usec_per_call=2.19
cmdstat_brpop:calls=31283,usec=104272,usec_per_call=3.33
cmdstat_llen:calls=53091,usec=206161,usec_per_call=3.88
cmdstat_ltrim:calls=37,usec=86,usec_per_call=2.32
cmdstat_smembers:calls=978,usec=32015,usec_per_call=32.74
cmdstat_hset:calls=36,usec=241,usec_per_call=6.69
cmdstat_hget:calls=3704,usec=22614,usec_per_call=6.11
cmdstat_hmset:calls=3669,usec=29805,usec_per_call=8.12
cmdstat_hdel:calls=35,usec=96,usec_per_call=2.74
cmdstat_hkeys:calls=1,usec=5,usec_per_call=5.00
cmdstat_hgetall:calls=42,usec=280,usec_per_call=6.67
cmdstat_hexists:calls=3,usec=8,usec_per_call=2.67
cmdstat_select:calls=68,usec=163,usec_per_call=2.40
cmdstat_expire:calls=3673,usec=17619,usec_per_call=4.80
cmdstat_keys:calls=3664,usec=226420,usec_per_call=61.80
cmdstat_multi:calls=122,usec=333,usec_per_call=2.73
cmdstat_exec:calls=122,usec=1390,usec_per_call=11.39
cmdstat_ttl:calls=48,usec=56,usec_per_call=1.17
# Cluster

cluster_enabled:0
# Keyspace

db0:keys=36,expires=0,avg_ttl=0
db1:keys=21,expires=0,avg_ttl=0
db3:keys=73,expires=0,avg_ttl=0
db4:keys=10,expires=10,avg_ttl=66409748
db5:keys=24,expires=23,avg_ttl=57118
db6:keys=15,expires=15,avg_ttl=175645257
db8:keys=12,expires=0,avg_ttl=0
db9:keys=36,expires=0,avg_ttl=0
[2816] 08 Mar 23:05:24.114 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @haptear 
the RC2 release is not supported anymore, please upgrade to the [current release](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.501).
Thank you.
