### ISSUE TITLE
2.8.2400 Sudden high Ram then dump gone

### ISSUE THREAD

**Issue by BoasE** [microsoftarchive/redis#427]
This morning redis suddenly had 50GB ofRAM (maxmemroy is only set to 10000mb and maxheab to 30000mb)

As this slowed down the whole server . then I restarted redis, as a result the dump file was gone !
There were no errors in redis logs.

Any explenations  on this?

Can the redis dump get lost if the service restart is triggerd while redis is saving?

Is there a way to configure redis du have a backup dump is the current one "gets lost" ?

Any advice what to do to avoid this?

**Comment by BoasE** [comment]
now dump gone one more time :-/ I don't understand why t his happens :-/

**Comment by enricogior** [comment]
@Gentlehag 
the RDB rewrite process is:
- create a new temp file where the new RDB is first saved
- if the temp file has been saved successfully close the original RDB and rename the temp file to the new file.

Give the previously described algorithm, killing the Redis process is a safe thing by the RDB point of view, even if the killing occurs while Redis is saving to disk. The only problem that may happen is that the temp file is left behind along with the original RDB.
The problem you described is new to me since I've never heard of such a problem.
Are you sure that the RDB file is not deleted externally (i.e. antivirus or any other third party software)?

**Comment by BoasE** [comment]
yes i'm sure that it is not deleted. this time i didn't event restart redis.
Maybe it reached the maxmemory limitiation, but i'm not sure with that

**Comment by enricogior** [comment]
@Gentlehag 
everytime you shutdown Redis the RDB file is deleted?

**Comment by BoasE** [comment]
nope can't tell when.

The problem half an hour ago happend in the running evironment without any administrative interaction with redis.

I didn't had a look at the memory but maybe it was at the maxmemory limit

**Comment by enricogior** [comment]
@Gentlehag 
Redis doesn't have any code that executes a "delete", it only renames the RDB and given the renaming is done by Windows it's an atomic operation that doesn't and up deleting the original file and the destination.
Is there any temp-dump.rdb file left over?

**Comment by BoasE** [comment]
no there was no empty tmp-dump.rdp
but i'm not sure wether it there were one. because after some  minutes when i looked at it it the database started to have keys again (with 12MB data) 

what would happen if the target is locked?

Also not sure wether it has something to do with it, since this morning i've pending (not installed) windows updates on this machine

is there a way to log the size the new database would have? e.g. is ome one is emptying the redis db with commands

**Comment by enricogior** [comment]
@Gentlehag 
if the target is locked the Windows rename command would fail leaving both the RDB and the temp file behind.
There isn't a command to explicitly delete the RDB file, there is a command to remove all the keys from the in-memory data-set that in turn may cause the RDB file to be empty, but not to delete it.
If both the RDB and the temp files are gone, I suspect something external.

**Comment by BoasE** [comment]
to be exactly i don't know wether it is gone or just completly empty.

Is there  a way to log if that command occured? or even better to prevent this command? we have no use case for it.

**Comment by enricogior** [comment]
@Gentlehag 
you may rename or disable the FLUSHALL command using the general command-disable mechanism as described in the config file.

**Comment by enricogior** [comment]
@Gentlehag 
btw, last time we had a reported issue similar to yours, it was a compromised server, make sure it's not your case.

**Comment by BoasE** [comment]
can you provide me an example for the command-disable ?
in my confdig the command disbale isn't described.

am I right that I should add this at the end of the config? 

`rename-command FLUSHALL ""`

**Comment by BoasE** [comment]
i found a possible issue with one redis instance which may led to that someone could have sent commands (like flushall) to this instance.

After solving this issue and also blocking critical commands it didn't happened again. so I close this case.
