### ISSUE TITLE
Failed to install Redis 2.8.2103 as a service

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#429]
Hello.
I've been trying to launch Redis as a service with a custom name and I got some problems - although I used [this guide](https://github.com/ServiceStack/redis-windows).
My two attempts were this:
- redis-server.exe --service-install --service-name custom_service_name my_conf_file.conf -> claimed in the log it successfully registered (but in reality it used standard name, 'Redis'), but won't start with 1067 error 'process terminated unexpectedly'. I tried to launch it from Services using UI, but I don't think that's wrong;
- redis-server.exe --service-install my_conf_file.conf --service-name custom_service_name -> failed with a message 'Invalid argument during startup - failed to open .conf file ....'

I use Windows Server 2008 R2
Did I miss something here?

**Comment by enricogior** [comment]
Hi @chester89 
you shouldn't be using 2.8.2103 since it's an old release, you should at least upgrade to 2.8.2104.

This is the result of registering the service using a custom name and then starting and stopping the service using the custom name on a Windows Server 2008 R2 machine:

```
C:\Redis-x64-2.8.2104>redis-server --service-install --service-name myredis redis.windows.conf
[3048] 21 Mar 10:49:57.129 # Granting read/write access to 'NT AUTHORITY\NetworkService' on: "C:\Redis-x64-2.8.2104" "C:\Redis-x64-2.8.2104\"
[3048] 21 Mar 10:49:57.129 # Redis successfully installed as a service.

C:\Redis-x64-2.8.2104>net start myredis
The myredis service was started successfully.

C:\Redis-x64-2.8.2104>net stop myredis
The myredis service is stopping.
The myredis service was stopped successfully.
```

Make sure you are using a command prompt with admin privilegies.

**Comment by chester89** [comment]
I'll try 2104 build today. I was very surprised it didn't work, because
earlier I used default service name on Windows 7 box and it worked OK

2016-03-21 12:56 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89
> you shouldn't be using 2.8.2103 since it's an old release, you should at
> least upgrade to 2.8.2104.
> 
> This is the result of registering the service using a custom name and then
> starting and stopping the service using the custom name on a Windows Server
> 2008 R2 machine:
> 
> C:\Redis-x64-2.8.2104>redis-server --service-install --service-name myredis redis.windows.conf
> [3048] 21 Mar 10:49:57.129 # Granting read/write access to 'NT AUTHORITY\NetworkService' on: "C:\Redis-x64-2.8.2104" "C:\Redis-x64-2.8.2104\"
> [3048] 21 Mar 10:49:57.129 # Redis successfully installed as a service.
> 
> C:\Redis-x64-2.8.2104>net start myredis
> The myredis service was started successfully.
> 
> C:\Redis-x64-2.8.2104>net stop myredis
> The myredis service is stopping.
> The myredis service was stopped successfully.
> 
> Make sure you are using a command prompt with admin privilegies.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/429#issuecomment-199201770

## 

Yours faithfully,
Gleb

**Comment by chester89** [comment]
Actually, I just checked - I successfully registered Redis 2103 build as a
service with custom name on Windows 7 box

2016-03-21 13:16 GMT+03:00 Gleb Chermennov thebitterend77@gmail.com:

> I'll try 2104 build today. I was very surprised it didn't work, because
> earlier I used default service name on Windows 7 box and it worked OK
> 
> 2016-03-21 12:56 GMT+03:00 Enrico Giordani notifications@github.com:
> 
> > Hi @chester89 https://github.com/chester89
> > you shouldn't be using 2.8.2103 since it's an old release, you should at
> > least upgrade to 2.8.2104.
> > 
> > This is the result of registering the service using a custom name and
> > then starting and stopping the service using the custom name on a Windows
> > Server 2008 R2 machine:
> > 
> > C:\Redis-x64-2.8.2104>redis-server --service-install --service-name myredis redis.windows.conf
> > [3048] 21 Mar 10:49:57.129 # Granting read/write access to 'NT AUTHORITY\NetworkService' on: "C:\Redis-x64-2.8.2104" "C:\Redis-x64-2.8.2104\"
> > [3048] 21 Mar 10:49:57.129 # Redis successfully installed as a service.
> > 
> > C:\Redis-x64-2.8.2104>net start myredis
> > The myredis service was started successfully.
> > 
> > C:\Redis-x64-2.8.2104>net stop myredis
> > The myredis service is stopping.
> > The myredis service was stopped successfully.
> > 
> > Make sure you are using a command prompt with admin privilegies.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/MSOpenTech/redis/issues/429#issuecomment-199201770
> 
> ## 
> 
> Yours faithfully,
> Gleb

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment]
@chester89 
ok, so I'm going to close the issue.

**Comment by chester89** [comment]
Also, is there a list of components that should be installed before/along with Redis? I happen to have this VERY old image of Windows Server (that is installed), and I think there's something missing on my system. I have .NET 4.5 installed

**Comment by enricogior** [comment]
@chester89 
the only component that is required for the MSI installation is .Net 2.0, while for Redis itself there aren't specific components required. If you use the binaries from the .zip folder provided with the Release, it should be possible to install it as a service without problems even if you don't have .Net 2.0.

**Comment by chester89** [comment]
@enricogior I downloaded zip from Github and tried to install it via calling `redis-server.exe --service-install ...` last time. will try to use MSI

**Comment by enricogior** [comment]
@chester89 
sure, I meant that the .Net 2.0 dependency is not for Redis itself but only for the MSI.

**Comment by chester89** [comment]
@enricogior yes, I understand that

2016-04-15 17:23 GMT+03:00 Enrico Giordani notifications@github.com:

> @chester89 https://github.com/chester89
> sure, I meant that the .Net 2.0 dependency is not for Redis itself but
> only for the MSI.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/429#issuecomment-210481242

## 

Yours faithfully,
Gleb
