### ISSUE TITLE
ERR wrong number of arguments for 'spop' command

### ISSUE THREAD

**Issue by chuanqi** [microsoftarchive/redis#433]
when use the command  `spop foo 3`

response :ERR wrong number of arguments for 'spop' command

why?

**Comment by enricogior** [comment]
Hi @chuanqi 
I tested the command on a Linux machine to verify if this is a Windows-specific issue or not.
On Linux it also returns the "wrong number of arguments" error.
Since we don't make fixes/changes in the original Redis code, you should ask in the official Redis forum.
Thank you.

**Comment by BridgeAR** [comment]
[Cite](http://redis.io/commands/spop): `The count argument will be available in a later version and is not available in 2.6, 2.8, 3.0`

**Comment by enricogior** [comment]
Thanks @BridgeAR, I'm closing the issue.

**Comment by chuanqi** [comment]
@BridgeAR thanks.
