### ISSUE TITLE
Compatibility to linux distribution

### ISSUE THREAD

**Issue by BoasE** [microsoftarchive/redis#445]
Hi

is it possible to load the windows dump in the linux redis version?

and furthermore would it be possible to have a cluster with a windows host and linux primary or vice versa?

**Comment by enricogior** [comment]
Hi @Gentlehag 
loading a Windows dump in  Linux Redis version should work, but it's not a scenario we officially test and support.
For sure you cannot mix different cluster versions regardless of the platform, so for sure you cannot use 3.0.501 on Windows with 3.0.7 on Linux. Mixing 3.0.501 on Windows with 3.0.5 on Linux may work but again it's not officially tested and supported.

**Comment by BoasE** [comment]
Thanks for your information. my scenario is that i would like to checkout the linux version with havin a fallback to the windows version. is there any better solution ? Like an export and import or so ?

**Comment by enricogior** [comment]
@Gentlehag 
not that I'm aware of.

**Comment by BoasE** [comment]
ok thx for info ill give it a shot wether i can onetime load the given rdb and post here if it worked
