### ISSUE TITLE
why syntax to execute Lua script is not as per redis document

### ISSUE THREAD

**Issue by sriharshav** [microsoftarchive/redis#45]
redis-cli eval test.lua 1 2 fails to execute.

however redis-cli --eval test.lua woks.

why this part is not as per standard redis documentation?

**Comment by HenryRawas** [comment]
I think this does conform to the documentation.
The eval command does not take a file name as parameters - it takes the actual script as a string.
So for example the following works:

> redis-cli eval "return redis.call('set','foo','bar')" 0
> OK
> redis-cli eval "return redis.call('get','foo')" 0
> "bar"

The --eval option is handled by redis-cli application. It reads the file content into a string, and then sends a eval command with the string.

**Comment by sriharshav** [comment]
@HenryRawas, thanks for reply and sorry, I misinterpreted it.
