### ISSUE TITLE
Redis sentinel binaries

### ISSUE THREAD

**Issue by effyteva** [microsoftarchive/redis#462]
Hi,

Could you please publish Redis Sentinel binaries in the release file as well?
This could save some users from compiling it using VS2013.
I just tried to compile using VS2015 and ran into multiple issues.

Thanks.

**Comment by enricogior** [comment]
Hi @effyteva 
the sentinel binaries are just the redis-server binaries renamed to redis-sentinel.
You can make a copy of redis-server.exe and rename it redis-sentinel.exe or simply run:
`redis-server.exe sentinel.conf --sentinel`.

**Comment by effyteva** [comment]
Thank you, I didn't know that.
I'd recommend adding this to the docs.
:+1:
