### ISSUE TITLE
can't start redis service on windows (error 5: can't access)

### ISSUE THREAD

**Issue by tian-junwei** [microsoftarchive/redis#465]
when I start a redis service but it fail and return the error (error 5 : can't access)，I found if  the windows has Everyone group or NETWORK SERIVCE the redis  service will be started successfully but if not it return error. How shoud I set the redis if I want to start redis service with system group ?

**Comment by enricogior** [comment]
Hi @tiantianjunwei 
by default the MSI installs the Redis service using the Network Service account that will also need to have read/write access to the installation folder.
If you change the account, make sure it can access the installation folder.

**Comment by tian-junwei** [comment]
how can I change the redis configs to use SYSTEM not Network Service when redis starts

**Comment by enricogior** [comment]
@tiantianjunwei 
follow the Microsoft documentation for general Windows services account management, the only Redis-specific is that the account requires read/write access to the installation folder and it's subfolders.
