### ISSUE TITLE
In redisAsyncHandleWrite,When redisBufferWrite not done, new WRITE_EVENT  couldn't be register。

### ISSUE THREAD

**Issue by minatl** [microsoftarchive/redis#47]
In redisAsyncHandleWrite,When redisBufferWrite not done, new WRITE_EVENT  couldn't be register。
because hiredis thank here is an other write_event already registered.

I fix it by add one line "_EL_DEL_WRITE(ac);" before _EL_ADD_WRITE(ac); 

Redis-sentinel seems has the same problem。

**Comment by clca** [comment]
Looking into this, we will get it fixed with the next release

**Comment by jepickett** [comment]
I am closing this issue because asyncAsyncHandleWrite is not being called anywhere in the current code base.
