### ISSUE TITLE
Redis Bug Report

### ISSUE THREAD

**Issue by Aaron-2016** [microsoftarchive/redis#471]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[6388] 17 Jun 14:13:19.539 # Redis version: 3.0.501
[6388] 17 Jun 14:13:19.539 # === ASSERTION FAILED ===
[6388] 17 Jun 14:13:19.539 # ==> ..\src\ziplist.c:405 'NULL' is not true
[6388] 17 Jun 14:13:19.539 # --- EXCEPTION_ACCESS_VIOLATION
[6388] 17 Jun 14:13:19.539 # --- STACK TRACE
redis-server.exe!((null):0)(0x01AFE520, 0x01AFFF90, 0x01AFE520, 0x40124730)
redis-server.exe!((null):0)(0x01AFE520, 0x77008E94, 0x00000030, 0x09000009)
kernel32.dll!UnhandledExceptionFilter((null):0)(0x01AFE520, 0x263EB791, 0x00000000, 0x00000001)
ntdll.dll!RtlInitializeAtomPackage((null):0)(0x01AFF100, 0x00000000, 0x4012A7C8, 0x00000000)
ntdll.dll!_C_specific_handler((null):0)(0x01AFFF90, 0x01AFFF90, 0x01B00000, 0x76F26861)
ntdll.dll!RtlIntegerToChar((null):0)(0x00000001, 0x00000000, 0x01AFFF90, 0x01B00000)
ntdll.dll!_C_specific_handler((null):0)(0x01AFF100, 0xEAEE8092, 0x00000000, 0x76F00000)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0xFFFFFFFF, 0x40158FD0, 0x401690F0, 0x00000195)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000007, 0x40035BBE, 0xEA0001B8, 0xEA000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0xEAEE8092, 0x01AFF350, 0xEAEE8094, 0x01AFF350)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0000000C, 0x01AFF420, 0x00000000, 0xEA46D290)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x006305DA, 0x00252A40, 0x00000000, 0x0024E8B0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x576378DF, 0x4015F4E8, 0x01AFEF40, 0x01AFEF60)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000004, 0x576378DF, 0x00252A20)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000029, 0x0024E950, 0x00000029, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[6388] 17 Jun 14:13:19.554 # --- INFO OUTPUT
# Server

redis_version:3.0.501
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ba05b51e58eb9205
redis_mode:standalone
os:Windows  
arch_bits:64
multiplexing_api:WinSock_IOCP
process_id:6388
run_id:916494c2bfee90f9ad2854bf56107846e34bb13a
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
lru_clock:6519007
config_file:C:\Redis\redis.windows-service.conf
# Clients

connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:22391536
used_memory_human:21.35M
used_memory_rss:0
used_memory_peak:22391536
used_memory_peak_human:21.35M
used_memory_lua:36864
mem_fragmentation_ratio:0.00
mem_allocator:jemalloc-3.6.0
# Persistence

loading:1
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1466136799
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
loading_start_time:jd
loading_total_bytes:1466136799
loading_loaded_bytes:36431885
loading_loaded_perc:0.00
loading_eta_seconds:jd
# Stats

total_connections_received:1
total_commands_processed:0
instantaneous_ops_per_sec:0
total_net_input_bytes:6
total_net_output_bytes:49
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
# Replication

role:slave
master_host:100.138.101.122
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_repl_offset:1
master_link_down_since_seconds:jd
slave_priority:100
slave_read_only:1
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
# CPU

used_cpu_sys:0.06
used_cpu_user:0.23
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Commandstats
# Cluster

cluster_enabled:0
# Keyspace

db0:keys=10944,expires=0,avg_ttl=0
[6388] 17 Jun 14:13:19.554 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment]
Hi @aaron1235 
the bug you reported is similar to a bug that has just been fixed.
Please upgrade to [3.0.502](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.502).
If the problem persists, please reopen the issue.
Thank you.

**Comment by enricogior** [comment]
@aaron1235 
update: the latest release is [3.0.503](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.503).
Sorry about the double release in one day.
Thank you.
