### ISSUE TITLE
Unable to remote connect in v3.2.100

### ISSUE THREAD

**Issue by ulimetic** [microsoftarchive/redis#485]
Since the latest upgrade, I can't connect to Redis from a computer from my LAN, only locally. Used to be ok right before the latest upgrade (was already running v3.x). Not a firewall issue cause I tried without it. I usually use Redis Desktop Manager to admin it from my station to my server and I can't have it connect anymore. Local connections are fine.

**Comment by djeeg** [comment]
Had the same trouble with an upgrade
Then saw there were security changes from redis v3.0 -> v3.2, see this page about "protected mode" http://redis.io/topics/security
To enable remote connections:
- I found my redis config file and looked for the NETWORK section
- Then added a "bind" directive for a single IP address

**Comment by eparlier** [comment]
Thank you djeeg, I will try it out asap

**Comment by ulimetic** [comment]
Thanks djeeg, 
I read again the comments in the service.conf and what worked for me is binding to the local ipv4 address.
bind 1270.0.1 192.168.1.5
