### ISSUE TITLE
GUI wrapper for RedisInstWA.exe

### ISSUE THREAD

**Issue by jphellemons** [microsoftarchive/redis#50]
Hi, can you make a small gui (wpf or something) for redisinstwa.exe? 
so that you have a small wizard. it makes it more open to other people

http://ossonazure.interoperabilitybridges.com/articles/how-to-deploy-redis-to-windows-azure-using-the-command-line-tool#h2Section4

**Comment by clca** [comment]
Thanks for the suggestion, we will consider building a UI on top the Azure installer after we have released the next version 2.6.14

**Comment by jepickett** [comment]
The Azure team has forked our code. They will be providing Redis for Azure. See https://github.com/WindowsAzure/redis
