### ISSUE TITLE
Error running RedisInstWA.exe

### ISSUE THREAD

**Issue by acharyarajiv** [microsoftarchive/redis#51]
Hi 
When i tried running RedisInstWA.exe with source as redis-server physical path it threw an error saying "Path not found"
this is what i tried 

<pre><code>  RedisInstWA.exe -source samples/redis-server.exe  -config samples -redisconfig samples -emu </code></pre>

Then i tried giving url instead of source path and i threw an error saying "Did not find redisbin64.zip"
This is what i tried 

<pre><code>  RedisInstWA.exe -source https://github.com/MSOpenTech/redis/archive/2.6.zip -x64  -config samples -redisconfig samples -emu </code></pre>

 and this is the error 
![error_redis_2 6_zip](https://f.cloud.github.com/assets/3601851/707646/c3ccdd34-de27-11e2-89f8-1e0961b7dc9a.jpg)

**Comment by HenryRawas** [comment]
The -source value for a local path should just be the folder path. In other words, remove the /redis-server.exe (assuming the exe files are in samples.

There is a problem right now in specifying a URL. We moved the location of the zip files. I will update the RedisWAInst to fix this.
