### ISSUE TITLE
How to download releases? S3 links not working

### ISSUE THREAD

**Issue by oaprograms** [microsoftarchive/redis#535]
I tried downloading .msi, but all the links are dead here: https://github.com/MSOpenTech/redis/releases
Is there any other place to download them?

thanks

**Comment by orangemocha** [comment]
It's possible that this may be caused by AWS: http://venturebeat.com/2017/02/28/aws-is-investigating-s3-issues-affecting-quora-slack-trello/

**Comment by oaprograms** [comment]
That was it probably, it's working again.
