### ISSUE TITLE
redis-server.exe - not reading port from standard input configuration

### ISSUE THREAD

**Issue by pythonmobile** [microsoftarchive/redis#54]
Can you please check what is wrong? I am supplying the configuration for my redis server from standard input ("-"), and it seems to be executing at the default port instead of the the one given in the config.

**Comment by clca** [comment]
are you using the --port option? redis-server.exe --port 2121 for instance works for me. 
You should use the latest version of the code (2.6 branch) that you can install using nuget or by copying the files from the bin directory of the github repo.

**Comment by jepickett** [comment]
Has the --port option fixed your problem?

**Comment by BeatriceOltean** [comment]
Configuration would fix this issue
