### ISSUE TITLE
Bug, redis server cannot accept enough client.

### ISSUE THREAD

**Issue by triStone** [microsoftarchive/redis#59]
The redis server will return error if fd is large than eventLoop->setsize (in ae.c aeCreateFileEvent function), and the fd is returned by aeWinAccept function in anet.c, which instead the accept function of raw redis server code.
This code will cause problem, in my test, accept in linux will return a value increase 1 every time, but aeWinAccept which call socket function will return a value increase 4 or 12 every time, so if eventLoop->setsize is set to 11024, the redis server will only accept about 11024/12 client connection concurrently. Then the redis server will refuse the new connection and shows ERANGE error.
My test environment is 64bits windows7 and 64bits windows 2003.

My solution is add a array in aeEventLoop to map real fd to events index, and change the access of eventLoop->events[fd] to eventLoop->events[getEventIndex(fd)]

**Comment by clca** [comment]
Thanks for reporting the issue. We are investigating the issue, we will post an update soon.

**Comment by jepickett** [comment]
I am nearly finished testing the fix. The code we share in common with the Linux version of Redis will now use simulated file descriptors. These are mapped to SOCKET handles in the IOCP code. Previously we would not be able to create more than about 2,000 connections to Redis. With this fix I can connect more than 60,000 clients on my local machine. The fix should be available soon in the 6.2.14 release.

**Comment by jepickett** [comment]
Each version of Windows will have a maximum number of TCP ports available for a given address bound to an adapter. I believe the default value on Server 2003 is 5000. HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\MaxUserPort will allow you to configure this value up to 65534.  If you need more than this it might be possible with NIC teaming.

**Comment by BeatriceOltean** [comment]
This issue is being built into 2.6.14 release. Test sign off in process.

**Comment by jepickett** [comment]
2.6.14 and 2.8.4 are available. Signed binaries are available from NuGet and Chocolatey.
