### ISSUE TITLE
I need "ioctl.h" and "unistd.h";

### ISSUE THREAD

**Issue by jstzwhc** [microsoftarchive/redis#591]
When I build the task, I need "ioctl.h" and "unistd.h".

**Comment by tporadowski** [comment]
Please provide some more details on what you are doing and what happens - only then someone might be able to help.

**Comment by jstzwhc** [comment]
In Branch 3.2:

**Comment by jstzwhc** [comment]
linenoise.c  "#include <sys/ioctl.h>
#include <unistd.h>
"

**Comment by jstzwhc** [comment]
#include <sys/ioctl.h>
#include <unistd.h>
error code: c1083 No such file or directory

**Comment by jstzwhc** [comment]
In Branch 3.2:
**RedisCli:**
linenoise.c
#include <sys/ioctl.h>
#include <unistd.h>
error code: c1083 No such file or directory

**Comment by tporadowski** [comment]
Looks like you don't have ```_WIN32``` defined as this part should be normally skipped:
```c
#ifdef _WIN32
#include "../../src/Win32_Interop/Win32_Portability.h"
#include "../../src/Win32_Interop/win32fixes.h"
#define UNUSED(V) ((void) V)
#include "../../src/Win32_Interop/win32_ANSI.h"
#else
#include <termios.h>
#include <unistd.h>
#include <sys/ioctl.h>
#endif
```
https://github.com/MicrosoftArchive/redis/blob/3.2/deps/linenoise/linenoise.c#L106-L115

**Comment by jstzwhc** [comment]
**I tried, but the problem remains.**
#ifdef _WIN32
#include "../../src/Win32_Interop/Win32_Portability.h"
#include "../../src/Win32_Interop/win32fixes.h"
#define UNUSED(V) ((void) V)
#include "../../src/Win32_Interop/win32_ANSI.h"
#else
#include <termios.h>
#include <unistd.h>
#include <sys/ioctl.h>
#endif
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <sys/stat.h>
#include <sys/types.h>
**#include <sys/ioctl.h>
#include <unistd.h>**
#include "linenoise.h"

**Comment by tporadowski** [comment]
@jstzwhc just remove those 2 includes you marked in bold - they are already part of ```#if ... #else ... #endif```

**Comment by jstzwhc** [comment]
I tried, but the problem remains.

**Comment by jstzwhc** [comment]
I tried, but the problem remains.
**mode_t old_umask = umask(S_IXUSR|S_IRWXG|S_IRWXO);**
Error Reports:
"umask" **undefinition**;
"S_IXUSR and S_IRWXG and S_IRWXO" **Undeclared identifier**

**Comment by tporadowski** [comment]
Looks like ```3.2``` branch here is not completely ported to Windows, so please better switch to ```win-3.2.100``` as this part of Redis code that uses __umask__ is different there (uses ```_WIN32``` preprocessor directive): https://github.com/MicrosoftArchive/redis/blob/win-3.2.100/deps/linenoise/linenoise.c#L1335-L1340

Depending on what you are doing with this Redis port - you might also want to check my fork of this archived repo - where I updated Redis port for Windows to Redis 4.0.2 (without modules support yet): https://github.com/tporadowski/redis

**Comment by jstzwhc** [comment]
Fine,I  swith to 3.2.100 branch.
Please release 3.2.100, not only 3.2.100-preview!

**Comment by LihtPro** [comment]
very helpful, thanks!
