### ISSUE TITLE
Assertion failure on SHUTDOWN

### ISSUE THREAD

**Issue by nguillaumin** [microsoftarchive/redis#6]
Hi,

When I issue a `SHUTDOWN` command to the server I get the following assertion failure:

![](http://oi45.tinypic.com/2ukci.jpg)

```
crt\src\close.c Line:46
(fh >= 0 && (unsigned)fh < (unsigned)_nhandle
```

To reproduce:
- Run `redis-server.exe`
- Run `redis-cli.exe`
- Enter `SHUTDOWN` in the client

**Comment by clca** [comment]
Thanks for reporting this issue. I repro-ed it on my machine, it won't take long to get it fixed.
