### ISSUE TITLE
AbortForkOperation: 0x00000005 - EndForkOperation: Killing forked process failed.: permission denied

### ISSUE THREAD

**Issue by FrancisFYK** [microsoftarchive/redis#616]
version 3.0.504 was used

**Comment by enricogior** [comment]
Hi @FrancisFYK , this repository hasn't been updated in almost 3 years. But finally there is a new software that provides Redis compatibility on Windows, and is currently up-to-date with the Redis 5 API. See https://github.com/MicrosoftArchive/redis/issues/620.

**Comment by FrancisFYK** [comment]
thank you
