### ISSUE TITLE
Windows link of new redis verison 5.0 is not available anymore on redis.io

### ISSUE THREAD

**Issue by alesshosry** [microsoftarchive/redis#635]
After watching some online tutorials I have navigated to https://redis.io/download but I realized that they removed Windows section which was redirecting users to this project. Any clarifications about that? Aren't you supporting new version of redis anymore? If no, then how we can use new redis versions on windows?

**Comment by enricogior** [comment]
Hi @AlessHo 
as mentioned in the official [README](https://github.com/microsoftarchive/redis/blob/3.0/README.md) this project is no longer being actively maintained.
If you are looking for an up-to-date alternative, you may want to check out [Memurai](https://www.memurai.com/).

**Comment by alesshosry** [comment]
I prefer to use another cashing tool that runs on Windows, since redis is not, and some people are saying to use docker, others are suggesting your compiled solution for windows that is not supported anymore by redis, and now someone told me to use [memurai](https://www.memurai.com/); well this is frustrating!

**Comment by tporadowski** [comment]
@AlessHo creator of Redis has never supported Windows version and indeed - it used to be available for download on [redis.io downloads page](https://redis.io/download) (in "Other versions" section), but that was at the time this version was maintained by MS Open Tech team. If I manage to keep [my Redis for Windows fork](https://github.com/tporadowski/redis) up-to-date with original Redis - perhaps _antirez_ agrees to bring it back there, but for now it is like it is.

**Comment by alesshosry** [comment]
I understand, thanks
