### ISSUE TITLE
redis server stooped  EndForkOperation: 0x00000005 - EndForkOperation: Killing forked process failed.: 拒绝访问

### ISSUE THREAD

**Issue by zjl767864079zjl** [microsoftarchive/redis#642]
The redis version is 5.0.9.  The PC system version is Server2016
before,I used redis version is 3.0.504, also exist the problem. So I change the redis version, but the problem remains.
Who can help me? 
Thanks!

**Comment by tporadowski** [comment]
If you are using my fork of this repository from [tporadowski/redis](https://github.com/tporadowski/redis) - please [report your issue](https://github.com/tporadowski/redis/issues) there.

**Comment by rushvel** [comment]
Can you please run your test scenario against Memurai Developer from www.memurai.com? Let us know please if this happens, we would like to know about this issue and if it reproduces to fix it. Thank you.

**Comment by bettojanea** [comment]
Hi @zjl767864079zjl 
as mentioned in the official https://github.com/microsoftarchive/redis/blob/3.0/README.md
this project is no longer being actively maintained. If you are looking for an up-to-date alternative, you may want to check out Memurai.

**Comment by zjl767864079zjl** [comment]
Modify configuration stop-writes-on-bgsave-error no,the error not repeated.
