### ISSUE TITLE
An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by rulloa** [microsoftarchive/redis#68]
Hi.
I am testing Redis server using a ServiceStack client.

I am using a BasicRedisClientManager to get client connections, and because of the load, the server frequently throws the message "An established connection was aborted by the software in your host machine."

Is that a problem?

Best regards.

**Comment by jepickett** [comment]
The error occurs when redis-server forcibly closes a socket. We have identified scenarios where this can happen regularly. We are currently working on stability fixes for 2.6.14.

**Comment by rulloa** [comment]
Thanks!!!

**Comment by glikoz** [comment]
What is the last situation of this item. Is this really closed in 2.6.14?

**Comment by rulloa** [comment]
Yes sr. Thank you very much!!!
