### ISSUE TITLE
TTL: overriten after bgsave

### ISSUE THREAD

**Issue by wchible** [microsoftarchive/redis#69]
Hi,
the TTL are change (not the same) when the BGFsave is executed,!
when the server store the data in the Database, the TTL (expiration time) for my keys are changed

verison 2.6.12

thanks.

**Comment by jepickett** [comment]
Likely this is fixed in the 2.6.14_rebase branch. We have moved to a new fork() implementation that has fixed a bunch of problems with the background AOF and RDB saving mechanisms.

**Comment by jepickett** [comment]
2.6.14 and 2.8.4 have been released. The signed binaries are available from NuGet and Chocolatey. Let us know if this fixes your issue.

**Comment by jepickett** [comment]
I am going to close this since we are no longer going to be updating 2.6.12. If you see this issue with 2.8.4+ please open a new issue. Thanks.
