### ISSUE TITLE
Binary version

### ISSUE THREAD

**Issue by thmarx** [microsoftarchive/redis#7]
Hello,

it would be very helpfull if someone can provide a binary download of the redis windows version. 
I, and I think a lot of others too, do not have visual studio installed.

**Comment by clca** [comment]
we are working on it. We plan to release binaries for redis-server and redis-cli soon. In the meantime you can still use Visual Studio Express (it is free) to compile the code, it should not take more and a couple of minutes to have the whole VS solution compiled.

**Comment by thmarx** [comment]
i will give it a try

**Comment by thmarx** [comment]
Building was realy easy, thanks for the hint to use visual studio express.

**Comment by AllYouCanAlex** [comment]
Any news on binary downloads?

**Comment by clca** [comment]
with the version we released today you can find all binaries (release and debug versions) under the msvs\bin
