### ISSUE TITLE
Redis On Widows Not Woking with IPv6 address 

### ISSUE THREAD

**Issue by edamtrong1178** [microsoftarchive/redis#71]
Now, I use redis with version 2.6.12 on Windows,
I want to connect redis server by Ipv6 address - > It is not support.

I known Redis 2.8.2 on Linux actually support with IPv6 address.
I hope that we will support IPv6 address for Redis on Windows. 
I think we will use much IPv6 address in future.

**Comment by jepickett** [comment]
We have rebased the code in the 2.8.4_msopen branch. It has the changes for IPv6, though it has not been extensively tested at the moment.

**Comment by edamtrong1178** [comment]
When I try using redis 2.8.4_msopen . I have some issues with redis:
- I still not start redis server with error: "The program can't start because msvcr110.dll is missing from your computer...."
  -  It also not working with window 32-bit.
    Please help to check this issues.

**Comment by jepickett** [comment]
1. We have dropped support for the 32-bit version starting with 2.6.14. 
2. I have just eliminated the dependency on the c++ runtime DLLs. 
3. 2.8.4 has been released and supports IPv6

**Comment by jepickett** [comment]
Are you still having problems with the 2.8.4 version?

**Comment by edamtrong1178** [comment]
Yes. I try download redis 2.8.4_msopen. So I cannot run redis-server on window 7 64bit. The error is missing DLL file.
Please help me to check it!

**Comment by jepickett** [comment]
I have opened the latest binaries in the bin\Release\redis-2.8.4.zip with Depends(http://www.dependencywalker.com/). The only binary dependencies I am seeing are Kernel32.dll and Advapi32.dll: 
![redisdependencies](https://cloud.githubusercontent.com/assets/5193368/2724810/afe44058-c5a5-11e3-9107-5f4601290dfe.png)

Where are your binaries coming from? GitHub, Chocolatey, or NuGet?
