### ISSUE TITLE
Hang during AOF rewrite in Redis 2.6.12

### ISSUE THREAD

**Issue by tekr** [microsoftarchive/redis#72]
Redis hung during AOF rewriting, with the following log lines:

[9708] 28 Jan 09:27:55.711 \* Starting automatic rewriting of AOF on 100% growth
[9708] 28 Jan 09:27:55.711 \* cowBkgdSaveReset deleting 0 SDS and 0 obj items
[9708] 28 Jan 09:27:56.012 \* SYNC append only file rewrite performed

Nothing further was logged, and the process writing to Redis has hung waiting on a response to a call to EXECUTE a transaction (using the BookSleeve C# library). Additional client connections via the command-line utility hang when a command is issued, indicating that Redis itself has hung.

A single process was writing to Redis at a moderate rate (~20 adds/sets per sec) as well as publishing messages over the pub/sub mechanism. Note that for each add/set, a message was simultaneously published using pub/sub within a transaction.

There was a single reader client pulling values out and subscribed to the published channels.

Redis configuration:

Snapshot save disabled
appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

The appendonly.aof file is approx. 80MB and temp-rewriteaof-bg-9708.aof is about 4MB. A quick look at the temp rewrite file shows it ends at about half way through the full appendonly.aof, suggesting the rewrite hadn't completed at the point of hanging.

**Comment by tekr** [comment]
The same thing just happened again, meaning it's hung on both attempts to rewrite the AOF file in my dev setup.

**Comment by tekr** [comment]
This may be related to #65 though no BGREWRITEAOF command was issued to the server.

**Comment by jepickett** [comment]
This is likely fixed in 2,6.14. We have moved to a new fork() mechanism that has eliminated all of the background AOF and RDB crashes that we were able to replicate. 2.6.14 is going through a test pass at the moment. We should have an official announcement of its availability soon.

**Comment by jepickett** [comment]
2.6.14 and 2.8.4 have been released. The signed binaries are available from NuGet and Chocolatey.
