### ISSUE TITLE
Errors in RedisWAInst of 2_6_14_rebase

### ISSUE THREAD

**Issue by acharyarajiv** [microsoftarchive/redis#73]
Hi

I was trying to deploy redis in azure and there were a couple of tweaks and fixes i had make, to fix errors
Here is the description

> Error 1: AzureSdkForNodeJs was always installed and exited with an error **installation failed. Please try installing the SDK separately and retry**

i had changed to change the way `XmlConfig.xml` was built in so that it checks if Azure Sdk For NodeJs was installed and if not then install

> Error 2: could not locate "Microsoft.WindowsAzure.Management.CloudService.dll"

I noticed in recent version of azure sdk **CloudService.dll** is changed to **Microsoft.WindowsAzure.ManagementLibraries.Private.dll**. So i fixed that error

> Error 3: RedisInstWA.exe crashed with error msg 'Unhandled Exception: System.InvalidCastException: Unable to cast COM object of t
> ype 'System.__ComObject' to interface type 'Shell32.Shell'. This operation faile
> d because the QueryInterface call on the COM component for the interface with II
> D '{286E6F1B-7113-4355-9562-96B7E9D64C54}' failed due to the following error: No
>  such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
>    at RedisInstWA.Program.PrepareBinaries(String workPath)
>    at RedisInstWA.Program.Main(String[] args)'

This is caused while creating shell32.shell object
I use win 8.1 and this occurs only in my machine
I added `[STAThread]` above `main()` in program.cs of RedisInstWA solution (refered from this [msdn forums](http://social.msdn.microsoft.com/Forums/vstudio/en-US/b25e2b8f-141a-4a1c-a73c-1cb92f953b2b/instantiate-shell32shell-object-in-windows-8?forum=clr#de21c00b-b417-44f5-87b6-dd6b26ba8240))

Inst4WA was able to deploy the solution however redis was not running. It threw config errors and i had to comment the below parameters from redis.conf
- tcp-keepalive 0
- repl-disable-tcp-nodelay no
- hz 10
- aof-rewrite-incremental-fsync yes 

and **hash-max-zipmap-entries 512** and **hash-max-zipmap-value 64** had to be changed to **hash-max-ziplist-entries 512** and **hash-max-ziplist-value 64**

After this, on deployment initially it threw these errors 

> `[MonAgentHost] Error:     Insufficient system resources exist to complete the requested service.
> [MonAgentHost] Error:     ERROR:EnableTraceEx() to enable provider failed
> [MonAgentHost] Error:     Failed to start the etw real time user session
> [MonAgentHost] Error:     Failed to start event tracing
> [MonAgentHost] Error:     Error: Failed to start ETW providers
> [MonAgentHost] Error:     Failed to start the ETW providers
> [MonAgentHost] Error:     Failed initialize agent sub-components`

and the role constantly switches between `Busy, unknown and destroy` state.

The commits for bug fixes are here
d74d22620b1d320d846a996c678c27db1ba2f9ab and e1dcba82578d933eef0c8bca75ee5993d4088406 

Any solution or suggestions on how to make redis 2_6_14_rebase run on azure?
Is there something in the configuration that i'm missing?

**Comment by jepickett** [comment]
The Azure folks have forked our repository. Azure support will come from them. See https://github.com/WindowsAzure/redis
