### ISSUE TITLE
redis-cli doesn't show a prompt to me

### ISSUE THREAD

**Issue by deepakverma** [microsoftarchive/redis#75]
downloaded redis-cli from https://github.com/MSOpenTech/redis/tree/2_6_14_rebase/bin/release
on two different machines I am not seeing any prompt after getting connected.

expected : something like:
redis 127.0.0.1:6379>

**Comment by tekr** [comment]
I'm seeing the same problem. redis-cli in 2.6.12 works (even seemingly with a 2.6.14 server), however the client in 2.6.14 hangs on startup.

**Comment by jepickett** [comment]
fixed in 2.8.4 in commit 8b9a8a0a419f00bc5e69dc7d1536379a745c4728
