### ISSUE TITLE
Are 2.6.14 or 2.8.5 production ready? Exception:Problem mapping heap. Error ocurred initializing Redis. GetLastError() returns 0x00000070

### ISSUE THREAD

**Issue by glikoz** [microsoftarchive/redis#76]
I've downloaded https://github.com/MSOpenTech/redis/tree/2_6_14_rebase/bin/release/redis_2.6.14.zip
But when I tried to execute redis-server.exe I got this exception:

Problem mapping heap. Error ocurred initializing Redis. GetLastError() returns 0x00000070

We are using 2.6.12 and there are so many improvements from 2.6.12 to now.
We want to use faster and more stable version of redis. 

Could someone update release folders of 2.6.14 or 2.8.5 if one of them is production ready.
Thx.

**Comment by jepickett** [comment]
In 2.6.14 we have moved to a new implementation of fork() for the background AOF and RDB code. In order for this implementation to provide the point-in-time-snapshot behavior that redis expects, we had to move the heap into a memory mapped file. In 2.6.14 the default size of this file is equal to [the size of physical memory - 3GB]. Windows system error 0x70 is ERROR_DISK_FULL. There is new flag '--maxheapgb [heap size in GB]' that can be used to limit the size of this file (and the redis heap).

The binaries in the 2.6.14_rebase branch are up to date. 

The 2.8.4_msopen branch is not quite ready for production use yet,

**Comment by glikoz** [comment]
There is not configuration file in the release folder. Could you upload sample of it? I've added https://github.com/MSOpenTech/redis/blob/2_6_14_rebase/redis.conf to the same folder. Also I've added 
maxheapgb 1 row to file.. Also I've 16GB RAM (physical) and 6GB available. So what is wrong?

**Comment by jepickett** [comment]
The --maxheapgb flag was initially added to the 2.8.4 branch. I have back ported the change to 2.6.14 and updated the binaries. Try again. 

The way the qfork code is implemented is as a wrapper around the redis main(). This means that the --maxheapgb flag is intercepted and handled before any of the Redis code is run.So the handling of this flag does not go through the normal config.c file processing. At the moment this flag can only be used from the Redis command line. Putting this flag into a .conf file will not produce the behavior you are hoping for.

**Comment by glikoz** [comment]
Win 7 Ultimate 64 SP 1 
6 GB Free memory
Now exception is: QForkMasterInit: system error caught. error code=0x00000070, message=QForkMasterInit: CreateFileMapping failed.

**Comment by glikoz** [comment]
Could you update 2.8.4's bin folder? I can test it also.

**Comment by jepickett** [comment]
How much disk space is available on the drive where you have the Redis binary? It might be worth getting a ProcMon(http://technet.microsoft.com/en-us/sysinternals/bb896645.aspx) capture of the redis startup events in order to understand why you are seeing the failure.

I updated the binaries last night.

**Comment by jepickett** [comment]
Only the 2.6.14 binaries were updated last night. The 2.8.4 binaries are there now.

**Comment by glikoz** [comment]
It was C disk.2Gb free space.. I moved it to D (10GB free space). I got same exception. I've tried 2.8.4  also. And same exception.Altough  I've logged with administrator account, I've tried Run As Administrator. And same exception.

**Comment by glikoz** [comment]
I've tried on w2008R2 machine also. I got "The program can't start because MSVCR110.dll missing.." message with popup.. So i googled..  Than http://www.microsoft.com/en-us/download/details.aspx?id=30679# .. And yes it works on this configuration.. 2.8.4 also works with this configuration.. BUT there was 630 GB free space..
When I moved redis to disk that has 2.88 GB free space I got same exception.. So what is the required freespace for Redis 2.6.14.. It is bigger than 10GB?

**Comment by jepickett** [comment]
Grab a ProcMon dump for me. Add [Process Name] [contains] [redis-server] to your filer set. Check the [Filter]-->[Drop Filter Events] menu item and start Redis. You should bet a bunch of events in the procmon window. Select the [Fiile]-->[Save] menu item and save the file as a .PML file. Put this file up someplace where I can grab it (dropbox or whatever). And send me the link and login info to v-jonpic@microsoft.com.

We are now dependent on the DLL version of the MSCRT library. You can grab this at http://www.microsoft.com/en-us/download/details.aspx?id=30679. We are discussing options for bundling this dependency with the Redis binaries. For now it is a manual install.

**Comment by glikoz** [comment]
I've sent pml file as attachment.. It seems redis-server try to use ~13GB from disk.

**Comment by jepickett** [comment]
Thanks for the file. 

The first event shows that you are launching Redis without any command line arguments. If you add the ‘--maxheapgb [size of heap in GB]’ flag to the redis command line, the size of the ‘RedisQFork_[processID].dat’ file will be constrained to the heap size you specify. This should allow you to launch on your machine with 2GB of disk available. Without this flag we create a file that is 80% of the size of physical ram (16GB \* 0.8 = 12.8 GB)

I am thinking of eliminating this flag in favor of using the existing --maxmemory flag. The QFork file must have a size that is a multiple of the memory allocator granularity. Currently this is 64MB. If I do this the resulting file will likely be larger than the --maxmemory specified, but should be smaller than the 1GB minimum required at the moment.

**Comment by glikoz** [comment]
Thanks for the solution. It works.

Summary:

1- Download latest binary from https://github.com/MSOpenTech/redis/tree/2_6_14_rebase/bin/release
2- Download and install http://www.microsoft.com/en-us/download/details.aspx?id=30679
3- Execute redis-server with <b>--maxheapgb 2</b> parameter  (It means use 2GB from disk (not memory))
4- You can use old redis.conf configuration file (copy to same folder with redis)
5- You can use old dump.rdb (db file).
6- You can use 2.6.14 for production environment.

Notes:

There is no major speed improvement between 2.6.12 and 2.6.14 (to redis-benchmark.exe)
But as i know  there are solved stability and consistency issues between two releases
( ex: https://github.com/MSOpenTech/redis/issues/59)

Thanks for this great work.

**Comment by jepickett** [comment]
FYI, I just pushed a change that removes the maxheapgb flag and instead utilizes the existing maxmemory flag. I have pushed this change in both the 2.6.14 and 2.8.4 branches. I have also made the the qfork code recognize the maxmemory flag if present in a .conf file. The binaries have been updated.

**Comment by glikoz** [comment]
Thanks jepickett,

I want to say "could you add sample .conf file to zip with info for maxheapgb" . Because when  newbie wants to try this great work he/she will see blinking command prompt and newbie has to find necessary information from issues. But reading .conf file is better startup for newbies. Also defensive .conf (setting maxheapgb to 1GB or 2GB) is better option. We have to encourage people involving.  But decision is yours. Thanks again.
