### ISSUE TITLE
2.8.4_msopen: setting maxmemory crashes process on initialization

### ISSUE THREAD

**Issue by nayato** [microsoftarchive/redis#78]
Starting Redis with following command:
redis-server.exe --maxmemory 200m
Fails with the following message:
VirtualAlloc/COWAlloc fail!
[16424] 10 Mar 15:48:42.189 # Out Of Memory allocating 16 bytes!

Error is the same with any maxmemory value. If maxmemory isn't present process starts fine.

**Comment by jepickett** [comment]
I just pushed up a change on the 2.6.14 and 2.8.4 branches that fixes this. Binaries are updated as well.

**Comment by jepickett** [comment]
Also Redis seems to need at least 60m to startup successfuly

**Comment by nayato** [comment]
Confirmed, many thanks!
