### ISSUE TITLE
After a few process restarts it is impossible to start Redis anymore

### ISSUE THREAD

**Issue by nayato** [microsoftarchive/redis#79]
After a few times of the sequence of actions as follows from cmd:
redis-server.exe
pause for 10-20 seconds
Ctrl-C

Redis starts failing with the following error message:
QForkMasterInit: system error caught. error code=0x000005af, message=VirtualAllocEx failed.: unknown error

Only OS restart seems to fix it.

**Comment by jepickett** [comment]
I am not able to reproduce this. What does your repro environment look like? (machine/VM,OS flavor,physical RAM, free HDD space)

**Comment by jepickett** [comment]
Does the problem go away if you raise the paging file reserve (System control panel->Advanced->Performance Settings->Advanced->Virtual Memory Change...)?

**Comment by nayato** [comment]
It's a workstation type laptop, Win 2012 R2, 16 GB RAM, 480 GB free disk space. Virtual memory was set to 10000 - which is less than amount of RAM - probably that might have to do with it.
It's quite random per my observations over a few days. Right now (with the latest build) I'm not able to repro that either. I will close the issue if it doesn't come back in 24h.

**Comment by nayato** [comment]
Did not repro after last changes and switching to system managed virtual memory settings
