### ISSUE TITLE
Redis 2.8.4

### ISSUE THREAD

**Issue by vv3d0x** [microsoftarchive/redis#82]
Redis-server does not save db to disk
http://screencast.com/t/jdFIzeDKZR

**Comment by jepickett** [comment]
What are the specifications of the system you are running this on? Is there sufficient disk space for the RDB file?

**Comment by vv3d0x** [comment]
1. Windows 7 Ultimate x64
2. Free space on disk more than 100Gb

**Comment by jepickett** [comment]
I fixed a bug introduced a couple of days ago that could prevent saving. Try the new binaries.

**Comment by vv3d0x** [comment]
Data store/restore to rdb file, but I steel see the same errror

**Comment by jepickett** [comment]
I am not seeing the error you are. Let’s take a procmon trace. Do the following:
1.  Get a copy of procmon on your system (http://technet.microsoft.com/en-us/sysinternals/bb896645.aspx)
2.  Launch ProcMon
a.  In the Process Monitor Filter window add the following filter: ‘Process Name’ ‘contains’ ‘redis-server’ then ‘Include’
b.  Ensure the Filter->Drop Filtered Events menu items is checked
c.  Ensure the File->Capture Events menu item is checked
3.  Replicate the problem you are seeing
4.  Use the File->SaveAs menu item to save the procmon log as a .PML file
5.  Send the resulting file to v-jonpic@microsoft.com

**Comment by jepickett** [comment]
Have you been able to capture the procmon trace for me? Is this still a problem?

**Comment by vv3d0x** [comment]
I switched to linux on virtualbox.
But last build works perfect with next config:
maxheap 1gb
maxmemory 512mb
