### ISSUE TITLE
When starting Redis 2.8.4 with a config file, no verbose output is shown.

### ISSUE THREAD

**Issue by dionoid** [microsoftarchive/redis#84]
If I start redis-server with a config file (e.g. `redis-server redis.conf`) I don't see any verbose output (i.e. ascii art Redis logo). When starting without config file, I do see the verbose output. Looks like a bug.

**Comment by jepickett** [comment]
what is loglevel set to in your conf file?

**Comment by dionoid** [comment]
The problem seems to be the line "logfile stdout" in the default conf file.
This doesn't output to the console, but creates a file named "stdout" and logs all output to this file.
So the line "logfile stdout" isn't working like it's documented.

**Comment by jepickett** [comment]
Fixed in commit 3cd77a5cb5dbcd1a945b08bb3ae89fc2154de25e. Let me know if this works for you.
