### ISSUE TITLE
Redis 2.8.4 needs MS VC++ 2013 Redist Package, not MS VC++ 2012 Redist Package

### ISSUE THREAD

**Issue by dionoid** [microsoftarchive/redis#85]
The 2.8.4 release notes (redis/tree/2.8.4_msopen/msvs/setups/documentation/Redis Release Notes.docx) states that Redis 2.8.4 depends on Microsoft Visual C++ 2012 Redistributable Package. However, it depends on the Microsoft Visual C++ 2013 Redistributable Package.
I think this should be fixed in the release notes (and also provide the correct link to VC++ 2013 redist package).

**Comment by jepickett** [comment]
We have just eliminated the need for the redistributable. The Chocolatey and NuGet distributions will be updated soon.

**Comment by dionoid** [comment]
The latest binaries (in the /bin folder) still need the MS VC++ 2013 redistributable; I'm not using the Chocolatey and NuGet distibutions.

**Comment by jepickett** [comment]
The release version was still linking with the DLL version of the CRT. New binaries + project files have been pushed up.
