### ISSUE TITLE
'wait3() returned a pid (-1)

### ISSUE THREAD

**Issue by Quantumplation** [microsoftarchive/redis#89]
Hello!

Great to see a MS port of Redis!  We're looking to use it in production, in an environment with 3 replicated servers in a server farm.

I can't seem to get the sentinel monitoring working, however.

The three servers start up and replicate correctly.  However, when I start a sentinel process, they sit there looping and outputting the following message over and over:

[10420] 10 Apr 15:58:12.722 . -script-child -1 0 16
[10420] 10 Apr 15:58:12.722 # wait3() returned a pid (-1) we can't find in our s
cripts execution queue!
[10420] 10 Apr 15:58:12.722 . -script-child -1 0 16
[10420] 10 Apr 15:58:12.722 # wait3() returned a pid (-1) we can't find in our s
cripts execution queue!
...

The sentinel config is as follows:
port 26379
loglevel debug
maxmemory 100mb

sentinel monitor mymaster 127.0.0.1 6379 3
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 900000
sentinel parallel-syncs mymaster 1

Any idea of what could be causing this?

**Comment by jepickett** [comment]
This was fixed in 2.6.14 in commit 99e01c7e6bfd84ad852f2775400c4e0f24f9e8e5, but not brought forward to 2.8.4. I have done so in commit 631e8e1afb1b28df09d29625fa374784ac59b2f0

**Comment by Quantumplation** [comment]
Oh wonderful! Thank you for the quick response!

**Comment by jepickett** [comment]
Has the change fixed the issue you were experiencing?

**Comment by Quantumplation** [comment]
Yes, I was able to test this yesterday, I no longer get the error described here, but now I'm having another issue.  I'll have a more detailed writeup tomorrow.  Should I post it here, or create a separate issue?

**Comment by jepickett** [comment]
If the issue has significantly different characteristics, then I would file a new issue.

**Comment by jepickett** [comment]
I am closing this issue. I look forward to seeing additional problems you have to report.
