### ISSUE TITLE
The rediswatcher installer does not allow you to choose a install location

### ISSUE THREAD

**Issue by dmeierotto** [microsoftarchive/redis#9]
Currently the MSI installer just defaults to c:\program files.... with no option to change the path.  Please give an option to select the path.

**Comment by clca** [comment]
We will include path selection in the MSI with the next commit (or we are happy to accept pull requests :)).

**Comment by dmeierotto** [comment]
Great! For now I found an acceptable work around which is to install the service from the command line like this:

`sc create RedisWatcher binPath= e:\services\redis\bin\rediswatcher.exe DisplayName= "Redis Watcher"`

**Comment by clca** [comment]
Nice workaround, selection of install path for redis-watcher is something we plan to check in with the next larget commit we are planning (for now working on few bugs we want to get fixed ASAP).

**Comment by bvakili-evault** [comment]
Please also note that the default 'exepath' (c:\redis\bin) in watcher.conf will not match what the user selected for the redis-server.exe installation folder (typically C:\Program Files\redis).

Is the administrator expected to always manually edit this file during a deployment?  Can this property in 'watcher.conf' be automatically set to the correct default value?

**Comment by BeatriceOltean** [comment]
Will be available in 2.6.14

**Comment by jepickett** [comment]
We have made the latest versions of Redis available via NuGet and Chocolatey. Unless there is a good reason to do so, we will probably not be supporting a separate MSI installation.

**Comment by jepickett** [comment]
Redis now supports running as a service directly, and monitoring should be done via sentinel, therefore I have eliminated the RedisWatcher project.
