### ISSUE TITLE
2.8.4 BGSAVE not reset rdb_changed_since_last_save

### ISSUE THREAD

**Issue by BDeus** [microsoftarchive/redis#90]
Since 2.8.4 version and new fork implementation when a bgsave is complete the rdb_changed_since_last_save is not reset.
The bgsave will launch every x minutes since the config file threshold reached and not reset.

**Comment by jepickett** [comment]
Fixed in commit bcfdbf7bcc7d07983fa75a9ebdb29b0f237eae3a. Let me know if this solves your problem. Thanks,

**Comment by BDeus** [comment]
the fix correct the issue thanks
