### ISSUE TITLE
using last dll (redis 2.8.4) After restart computer a new fork file created and the old file not deleted

### ISSUE THREAD

**Issue by Ahmad-Hassan1511** [microsoftarchive/redis#91]
Using redis watcher : 
- A new fork file created and the old file not deleted when restart the windows.
- But if (shutdown) redis using redis-cli.exe before restart, the file removed.

Using the redis-server.exe directly : 
- It remove the fork file after i close the redis-server.exe file.

**Comment by jepickett** [comment]
Can you give me the step-by-step instructions for replicating the behavior you are seeing?

**Comment by Ahmad-Hassan1511** [comment]
Dear Sir,

My Computer is Dell (Windows 7 ultimate 64) and RAM is 6 GB 

The steps from the beginning :
- I opened this link : https://github.com/MSOpenTech/redis/tree/2.8.4_msopen
- and clicked ((download zip))
- then opened the project in visual studio 2013 and build 
- then i took the files in that path (C:\Users\ahmad\Downloads\redis-2.8.4_msopen\msvs\x64\Debug)
- files (redis-benchmark.exe,redis-check-aof.exe,redis-check-dump.exe,redis-cli.exe,redis-server.exe)  (((Copied)))
- (((Past))) in  a new folder in c drive : C:\redis

Then i build the watcher install project in visual studio 2013 and open its exe installer  and its path :  C:\Users\ahmad\Downloads\redis-2.8.4_msopen\msvs\RedisWatcher\Install\bin\Debug
- then i open (InstallWatcher.msi) and installed with the defaults ...
- then open that path : C:\Program Files (x86)\RedisWatcher and open file (watcher.conf)
- then update the following to the right paths : 

exepath c:\redis

{
 workingdir c:\redis
 runmode hidden
 saveout 1
 cmdparms redis.conf
}
- then i opened that path : C:\Users\ahmad\Downloads\redis-2.8.4_msopen
  (((copy))) file named (redis.conf)
- then (((Past))) it in the following path :C:\redis
- then i modify the redis.conf file and add that line :

maxheap 100000000 
- then start the watcher service (to start redis) 
- then a new file created in that path : C:\redis, its name like (RedisQFork_2572.dat) and its name is random.

=>>   that file when restart computer not removed by itself, i do not know why that happene, and a new file with a different name created.

**Comment by jepickett** [comment]
We have retired the RedisWatcher project. Redis is now installable as a service directly. By 
handling the pre-shutdown notification in Redis, we are able to more cleanly shut down Redis when the system is shutting down. This eliminates the problem of not cleaning up the Redis heap file on system restart. Please see the RedisService.docx file included with the latest binary package in bin\release\redis-2.8.4.zip for instructions on installing and running Redis as a service. 

When running as a service, Redis will output its log events to the Windows EventLog. Once Redis is installed as a service, you will be able to open EventViewer and find the Redis log under [Application and Services Logs\Redis]:

![redisineventviewer](https://cloud.githubusercontent.com/assets/5193368/2724520/728c9ad2-c5a2-11e3-874d-9b5ad2bd7c8a.png)
