### ISSUE TITLE
QForkMasterInit: system error caught. error code=0x00000070, message=CreateFileMapping failed.: no space on device

### ISSUE THREAD

**Issue by JCMais** [microsoftarchive/redis#92]
I get this error message when I try to execute any command.

![redis-error](https://cloud.githubusercontent.com/assets/1041647/2710957/090a8f04-c4c8-11e3-864f-fa1badfefdbd.PNG)

Running on Windows 7 64bits, using the last binaries from the release folder for branch 2.8.4_msopen.

**Comment by jepickett** [comment]
Please see the release documentation in msvs\setups\documentation. You will need disk space on the drive where Redis is running for the memory mapped file. You can control the size of this file  with the--maxheap flag, as documented in redis.windows.conf.

**Comment by JCMais** [comment]
Hm, my fault not reading the docs, I was updating directly from 2.6 to 2.8, and didn't know about these new configuration keys. And as the default is the current system memory \* 1.5, it was trying to allocate 12GB, which I don't have on the current drive.

Everything working now.

There is any way to specify the location to create the heap file?

**Comment by jepickett** [comment]
Not directly. The file will be written to the current working directory. Usually this is the same as the directory Redis is in. You could setup a batch file to 'cd' the directory you want Redis to write data files into and then launch Redis specifying a full path name.
