### ISSUE TITLE
custom service name

### ISSUE THREAD

**Issue by jepickett** [microsoftarchive/redis#95]
"Is it possible to use a custom service name ? I's useful when we have multiple Redis instances" - Tortue Torche 

Add the ability to set a custom service name  with the --service-xxxxxx commands

**Comment by tortuetorche** [comment]
:+1:

**Comment by jepickett** [comment]
Functionality added in commit 9f871c4ec5255f9e38d1f01466deb8b95de34a89. Please see RedisService.docx for a discussion about how to use the --service-name argument.
