### ISSUE TITLE
Async Example Subscribe

### ISSUE THREAD

**Issue by alexanf** [microsoftarchive/redis#96]
The example given as a resolution to issue 86, however async subscription does not work.

Example:
# ifdef _WIN32
# include "....\src\Win32_Interop\win32fixes.h"
# endif
# include <stdio.h>
# include <time.h>
# include <stdlib.h>
# include <string.h>
# include <signal.h>
# include "hiredis.h"
# include "async.h"
# include "adapters\ae.h"

/\* Put event loop in the global scope, so it can be explicitly stopped */
static aeEventLoop *loop;

void getCallback(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    printf("Callback called\n");
    if (reply == NULL) return;
    if (reply->type == REDIS_REPLY_ARRAY && reply->elements == 3){
        if (strcmp(reply->element[0]->str, "subscribe") != 0){
            printf("Channel %s: %s\n", reply->element[1]->str, reply->element[2]->str);
        }
        else {
            printf("%s\n", reply->element[0]->str);
        }
    }

}

void connectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("Connected...\n");
}

void disconnectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("Disconnected...\n");

```
/* Stop event loop to exit program */
aeStop(loop);
```

}

int main (int argc, char **argv) {
# ifndef _WIN32

```
signal(SIGPIPE, SIG_IGN);
```
# endif
# ifdef _WIN32

```
/* For Win32_IOCP the event loop must be created before the async connect */
loop = aeCreateEventLoop(1024 * 10);
```
# endif

```
redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 6379);
if (c->err) {
    /* Let *c leak for now... */
    printf("Error: %s\n", c->errstr);
    return 1;
}
```
# ifndef _WIN32

```
loop = aeCreateEventLoop(1024*10);
```
# endif

```
redisAeAttach(loop, c);
redisAsyncSetConnectCallback(c,connectCallback);
redisAsyncSetDisconnectCallback(c,disconnectCallback);
redisAsyncCommand(c, getCallback, NULL, "subscribe foo");
aeMain(loop);
return 0;
```

}

After execution, the following appears:
![image](https://cloud.githubusercontent.com/assets/5544091/2750431/90c5aede-c878-11e3-8462-9ef0785d7271.png)

After publishing with redis-cli publish foo bar
![image](https://cloud.githubusercontent.com/assets/5544091/2750434/e117a9e6-c878-11e3-88ee-00884e78076a.png)
appears, indicating the message was published to one client. However, nothing appears in the program window.

**Comment by jepickett** [comment]
With the following code I am seeing this work:

My subscriptions:

``` C
    redisAsyncCommand(c, subscribeCallback, NULL, "subscribe foo");
    redisAsyncCommand(c, subscribeCallback, NULL, "subscribe bar");
    redisAsyncCommand(c, subscribeCallback, NULL, "subscribe foobar");
```

My subscription callback:

``` C
void subscribeCallback(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = (redisReply *)r;
    printf("entered subscribeCallback()\n");
    if (reply == NULL) return;
    if (reply->type == REDIS_REPLY_ARRAY && reply->elements == 3) {
        if (strcmp(reply->element[0]->str, "message") == 0) {
            printf("Channel %s = %s\n", reply->element[1]->str, reply->element[2]->str);
            // exit if some client sends a "PUBLISH <channel> EXIT"
            if (_stricmp(reply->element[2]->str, "exit") == 0)  {
                redisAsyncFree(c);
            }
        } else if (strcmp(reply->element[0]->str, "subscribe") == 0) {
            printf("%s %s : %d\n", reply->element[0]->str, reply->element[1]->str, reply->element[2]->integer);
        } else {
            printf("other message\n");
        }
    } else {
        printf("other message\n");
    }
}
```

Let me know if this works for you.

**Comment by alexanf** [comment]
Jonathan,

it works. I also tried psubscribe and no problems so far. Also the
performance is pretty good.

Thanks,
Alex

2014-05-10 1:29 GMT+02:00 Jonathan Pickett notifications@github.com:
