### ISSUE TITLE
Async Example Get

### ISSUE THREAD

**Issue by alexanf** [microsoftarchive/redis#97]
The callback is called a random number above 32 times, however almost always below the requested. Here is the code I changed and the output file running the programm. the
# ifdef _WIN32
# include "....\src\Win32_Interop\win32fixes.h"
# endif
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <signal.h>
# include "hiredis.h"
# include "async.h"
# include "adapters\ae.h"

static int numReads = 0;

/\* Put event loop in the global scope, so it can be explicitly stopped */
static aeEventLoop *loop;

void getCallback(redisAsyncContext _c, void *r, void *privdata) {
    redisReply *reply = r;
    if (reply == NULL) return;
    printf("argv[%s]: %s, read[%i]\n", (char_)privdata, reply->str,numReads);
    numReads++;
    /\* Disconnect after receiving the reply to GET */
    //redisAsyncDisconnect(c);
}

void connectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("Connected...\n");
}

void disconnectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("Disconnected...\n");

```
/* Stop event loop to exit program */
aeStop(loop);
```

}

int main (int argc, char **argv) {
# ifndef _WIN32

```
signal(SIGPIPE, SIG_IGN);
```
# endif
# ifdef _WIN32

```
/* For Win32_IOCP the event loop must be created before the async connect */
loop = aeCreateEventLoop(1024 * 10);
```
# endif

```
redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 6379);
if (c->err) {
    /* Let *c leak for now... */
    printf("Error: %s\n", c->errstr);
    return 1;
}
```
# ifndef _WIN32

```
loop = aeCreateEventLoop(1024*10);
```
# endif

```
redisAeAttach(loop, c);
redisAsyncSetConnectCallback(c,connectCallback);
redisAsyncSetDisconnectCallback(c,disconnectCallback);
redisAsyncCommand(c, NULL, NULL, "SET key %b", argv[argc-1], strlen(argv[argc-1]));
for (int i = 0; i < 500; i++){
    printf("calling get %i times\n", i);
    redisAsyncCommand(c, getCallback, (char*)"end-1", "GET key");

}
aeMain(loop);
return 0;
```

}

calling get 0 times
calling get 1 times
calling get 2 times
calling get 3 times
calling get 4 times
calling get 5 times
calling get 6 times
calling get 7 times
calling get 8 times
calling get 9 times
calling get 10 times
calling get 11 times
calling get 12 times
calling get 13 times
calling get 14 times
calling get 15 times
calling get 16 times
calling get 17 times
calling get 18 times
calling get 19 times
calling get 20 times
calling get 21 times
calling get 22 times
calling get 23 times
calling get 24 times
calling get 25 times
calling get 26 times
calling get 27 times
calling get 28 times
calling get 29 times
calling get 30 times
calling get 31 times
calling get 32 times
calling get 33 times
calling get 34 times
calling get 35 times
calling get 36 times
calling get 37 times
calling get 38 times
calling get 39 times
calling get 40 times
calling get 41 times
calling get 42 times
calling get 43 times
calling get 44 times
calling get 45 times
calling get 46 times
calling get 47 times
calling get 48 times
calling get 49 times
calling get 50 times
calling get 51 times
calling get 52 times
calling get 53 times
calling get 54 times
calling get 55 times
calling get 56 times
calling get 57 times
calling get 58 times
calling get 59 times
calling get 60 times
calling get 61 times
calling get 62 times
calling get 63 times
calling get 64 times
calling get 65 times
calling get 66 times
calling get 67 times
calling get 68 times
calling get 69 times
calling get 70 times
calling get 71 times
calling get 72 times
calling get 73 times
calling get 74 times
calling get 75 times
calling get 76 times
calling get 77 times
calling get 78 times
calling get 79 times
calling get 80 times
calling get 81 times
calling get 82 times
calling get 83 times
calling get 84 times
calling get 85 times
calling get 86 times
calling get 87 times
calling get 88 times
calling get 89 times
calling get 90 times
calling get 91 times
calling get 92 times
calling get 93 times
calling get 94 times
calling get 95 times
calling get 96 times
calling get 97 times
calling get 98 times
calling get 99 times
calling get 100 times
calling get 101 times
calling get 102 times
calling get 103 times
calling get 104 times
calling get 105 times
calling get 106 times
calling get 107 times
calling get 108 times
calling get 109 times
calling get 110 times
calling get 111 times
calling get 112 times
calling get 113 times
calling get 114 times
calling get 115 times
calling get 116 times
calling get 117 times
calling get 118 times
calling get 119 times
calling get 120 times
calling get 121 times
calling get 122 times
calling get 123 times
calling get 124 times
calling get 125 times
calling get 126 times
calling get 127 times
calling get 128 times
calling get 129 times
calling get 130 times
calling get 131 times
calling get 132 times
calling get 133 times
calling get 134 times
calling get 135 times
calling get 136 times
calling get 137 times
calling get 138 times
calling get 139 times
calling get 140 times
calling get 141 times
calling get 142 times
calling get 143 times
calling get 144 times
calling get 145 times
calling get 146 times
calling get 147 times
calling get 148 times
calling get 149 times
calling get 150 times
calling get 151 times
calling get 152 times
calling get 153 times
calling get 154 times
calling get 155 times
calling get 156 times
calling get 157 times
calling get 158 times
calling get 159 times
calling get 160 times
calling get 161 times
calling get 162 times
calling get 163 times
calling get 164 times
calling get 165 times
calling get 166 times
calling get 167 times
calling get 168 times
calling get 169 times
calling get 170 times
calling get 171 times
calling get 172 times
calling get 173 times
calling get 174 times
calling get 175 times
calling get 176 times
calling get 177 times
calling get 178 times
calling get 179 times
calling get 180 times
calling get 181 times
calling get 182 times
calling get 183 times
calling get 184 times
calling get 185 times
calling get 186 times
calling get 187 times
calling get 188 times
calling get 189 times
calling get 190 times
calling get 191 times
calling get 192 times
calling get 193 times
calling get 194 times
calling get 195 times
calling get 196 times
calling get 197 times
calling get 198 times
calling get 199 times
Connected...
argv[end-1]: HiredisExample.exe, read[0]
argv[end-1]: HiredisExample.exe, read[1]
argv[end-1]: HiredisExample.exe, read[2]
argv[end-1]: HiredisExample.exe, read[3]
argv[end-1]: HiredisExample.exe, read[4]
argv[end-1]: HiredisExample.exe, read[5]
argv[end-1]: HiredisExample.exe, read[6]
argv[end-1]: HiredisExample.exe, read[7]
argv[end-1]: HiredisExample.exe, read[8]
argv[end-1]: HiredisExample.exe, read[9]
argv[end-1]: HiredisExample.exe, read[10]
argv[end-1]: HiredisExample.exe, read[11]
argv[end-1]: HiredisExample.exe, read[12]
argv[end-1]: HiredisExample.exe, read[13]
argv[end-1]: HiredisExample.exe, read[14]
argv[end-1]: HiredisExample.exe, read[15]
argv[end-1]: HiredisExample.exe, read[16]
argv[end-1]: HiredisExample.exe, read[17]
argv[end-1]: HiredisExample.exe, read[18]
argv[end-1]: HiredisExample.exe, read[19]
argv[end-1]: HiredisExample.exe, read[20]
argv[end-1]: HiredisExample.exe, read[21]
argv[end-1]: HiredisExample.exe, read[22]
argv[end-1]: HiredisExample.exe, read[23]
argv[end-1]: HiredisExample.exe, read[24]
argv[end-1]: HiredisExample.exe, read[25]
argv[end-1]: HiredisExample.exe, read[26]
argv[end-1]: HiredisExample.exe, read[27]
argv[end-1]: HiredisExample.exe, read[28]
argv[end-1]: HiredisExample.exe, read[29]
argv[end-1]: HiredisExample.exe, read[30]
argv[end-1]: HiredisExample.exe, read[31]
argv[end-1]: HiredisExample.exe, read[32]
argv[end-1]: HiredisExample.exe, read[33]
argv[end-1]: HiredisExample.exe, read[34]
argv[end-1]: HiredisExample.exe, read[35]
argv[end-1]: HiredisExample.exe, read[36]
argv[end-1]: HiredisExample.exe, read[37]
argv[end-1]: HiredisExample.exe, read[38]
argv[end-1]: HiredisExample.exe, read[39]
argv[end-1]: HiredisExample.exe, read[40]
argv[end-1]: HiredisExample.exe, read[41]
argv[end-1]: HiredisExample.exe, read[42]
argv[end-1]: HiredisExample.exe, read[43]
argv[end-1]: HiredisExample.exe, read[44]
argv[end-1]: HiredisExample.exe, read[45]
argv[end-1]: HiredisExample.exe, read[46]
argv[end-1]: HiredisExample.exe, read[47]
argv[end-1]: HiredisExample.exe, read[48]
argv[end-1]: HiredisExample.exe, read[49]
argv[end-1]: HiredisExample.exe, read[50]
argv[end-1]: HiredisExample.exe, read[51]
argv[end-1]: HiredisExample.exe, read[52]
argv[end-1]: HiredisExample.exe, read[53]
argv[end-1]: HiredisExample.exe, read[54]
argv[end-1]: HiredisExample.exe, read[55]
argv[end-1]: HiredisExample.exe, read[56]
argv[end-1]: HiredisExample.exe, read[57]
argv[end-1]: HiredisExample.exe, read[58]
argv[end-1]: HiredisExample.exe, read[59]
argv[end-1]: HiredisExample.exe, read[60]
argv[end-1]: HiredisExample.exe, read[61]
argv[end-1]: HiredisExample.exe, read[62]
argv[end-1]: HiredisExample.exe, read[63]
argv[end-1]: HiredisExample.exe, read[64]
argv[end-1]: HiredisExample.exe, read[65]
argv[end-1]: HiredisExample.exe, read[66]
argv[end-1]: HiredisExample.exe, read[67]
argv[end-1]: HiredisExample.exe, read[68]
argv[end-1]: HiredisExample.exe, read[69]
argv[end-1]: HiredisExample.exe, read[70]
argv[end-1]: HiredisExample.exe, read[71]
argv[end-1]: HiredisExample.exe, read[72]
argv[end-1]: HiredisExample.exe, read[73]
argv[end-1]: HiredisExample.exe, read[74]
argv[end-1]: HiredisExample.exe, read[75]
argv[end-1]: HiredisExample.exe, read[76]
argv[end-1]: HiredisExample.exe, read[77]
argv[end-1]: HiredisExample.exe, read[78]
argv[end-1]: HiredisExample.exe, read[79]
argv[end-1]: HiredisExample.exe, read[80]
argv[end-1]: HiredisExample.exe, read[81]
argv[end-1]: HiredisExample.exe, read[82]
argv[end-1]: HiredisExample.exe, read[83]
argv[end-1]: HiredisExample.exe, read[84]
argv[end-1]: HiredisExample.exe, read[85]
argv[end-1]: HiredisExample.exe, read[86]
argv[end-1]: HiredisExample.exe, read[87]
argv[end-1]: HiredisExample.exe, read[88]
argv[end-1]: HiredisExample.exe, read[89]
argv[end-1]: HiredisExample.exe, read[90]
argv[end-1]: HiredisExample.exe, read[91]

**Comment by jepickett** [comment]
The problem was that the GET results exceeded the read buffer length. The async code tried to reschedule the read operation, but function that was called to do so would not reschedule if already read mode. Likely this is a problem with the Linux version of Redis as well. I have added a workaround for this issue. I also modified the example code to demonstrate that this now works.

**Comment by alexanf** [comment]
Thanks a lot. Any news on the async subscribe?

2014-05-08 2:39 GMT+02:00 Jonathan Pickett notifications@github.com:
