### ISSUE TITLE
setting maxheap via .conf is failed  with m and g suffixes (512m,1g )

### ISSUE THREAD

**Issue by glikoz** [microsoftarchive/redis#98]
Interestingly ,

maxheap 512m (FAIL)
maxheap 1g (FAIL)
maxheap 1gb (SUCCESS)

There is a problem with m and g suffixes.

windows 7 64bit

**Comment by jepickett** [comment]
Do you have a dump.rdb file in the same directory as redis? Redis will fail if there is not enough heap space to load the last snapshot. The memory is calculated in util.c/memtoll(). 1gb=1_1024_1024 bytes. 1g=1_1000_1000 bytes. Without the lat snapshot, I am able to start redis on maxheap=5m, though that leaves essentially nothing left for data. In the scenario that works, what does the info command in redis-cli show under the memory section?

**Comment by glikoz** [comment]
FAIL means "server could not start". So "info" is meaningless. But now I could not reproduce the problem. I can see RedisQFork_52128.dat files for all configurations. So I have to close issue. 
PS: redis.windows.conf file is excellent. Thanks for good work.
